part of 'story.dart';

const chapterFourBeats = <String, StoryBeat>{
  'ch4_daybreak': StoryBeat(
    id: 'ch4_daybreak',
    label: '静默病房',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    timelineMinute: 3280,
    text:
        '第三日六点四十分，集合厅没有人真正醒来。灯早已按时亮起，却只照出几张贴在椅背上的脸，水杯和PDA被每个人放在能同时碰到的位置。\n我们已经知道外表完整的记录会撒谎，也知道一个人交出权限后，系统仍可以把别人的动作写在他名下。睡眠因此变得像另一种托管：闭上眼时，你只能希望醒着的人没有替你做决定。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_daybreak_roll_call',
  ),
  'ch4_daybreak_roll_call': StoryBeat(
    id: 'ch4_daybreak_roll_call',
    label: '空椅子也参加点名',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '林澄照着昨晚抄下的名单点名。念到已经死亡的人时，她停了半秒，仍把编号完整念完，再在纸上画一道横线。\n“为什么还要念？”唐弈问。\n“因为系统只会把他们从在线列表里删掉。”林澄握紧记号笔，“我们至少要知道少的是哪一把椅子，不是只知道总数变了。”\n没有人接着催她。那几道没有回应的停顿，比任何悼词都更适合这个房间。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch4_breakfast_distribution',
  ),
  'ch4_breakfast_distribution': StoryBeat(
    id: 'ch4_breakfast_distribution',
    label: '密封餐盒也需要见证人',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚把早餐箱搬到长桌中央，要求每个人自己挑选未开封的餐盒。昨天还会有人顺手替同伴递水，今天连拉开罐装饮料的声音都要在两双眼睛下完成。\n“再这样下去，我们会把吃饭变成审讯。”周叙说。\n“不是审讯，是让怀疑有明确的终点。”叶岚把自己的餐盒留到最后，“封膜完整、选择随机、离桌后不交换。做完这三步，至少不要再用一句‘可能被下药’把所有人困一上午。”\n苏弥没有反驳。她把星遥那份温水放在桌上，没有碰杯口，只低声提醒：“先喝两口。你昨晚只睡了一个小时。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.zhouXu,
      Speaker.yeLan,
      Speaker.suMi,
    ],
    next: 'ch4_xingyao_hides_tinnitus',
  ),
  'ch4_xingyao_hides_tinnitus': StoryBeat(
    id: 'ch4_xingyao_hides_tinnitus',
    label: '她把不适藏进一次调音',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'vertigo',
    text:
        '星遥没有去碰温水。她把耳机摘下来又戴回去，像在确认接触不良，右手却在桌沿下按住耳后。\n“从什么时候开始响的？”我问。\n“没有响。”她回答得太快，随后避开我的视线，“只是左声道比右声道响，我在校准。”\n她向来会先说设备，再说自己。可这一次，她连设备读数也没有给我看。我伸手碰到耳机外壳时，她下意识向后躲了一下，那不是嫌我碍事，而是整个房间在她眼里短暂地偏向了右侧。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch4_xingyao_small_promise',
  ),
  'ch4_xingyao_small_promise': StoryBeat(
    id: 'ch4_xingyao_small_promise',
    label: '不是只有故障才值得报错',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'vertigo',
    text:
        '我没有当众叫苏弥，只把温水推近一点。\n“如果下一次还响，先告诉我，再保存波形。”\n“顺序反了。”星遥扯了一下嘴角，“不保存就只有我的话。”\n“你的话也是记录源。”我说，“至少对我来说，不需要等设备替你作证。”\n她看了我几秒，终于喝下第一口水。“那你也答应。听见我说停，就别逞强继续往前。”\n这算不上告白，甚至不是一个足够浪漫的约定。可在这里，把下一次不适交给另一个人知道，已经比牵手更接近信任。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch4_tone_returns',
  ),
  'ch4_tone_returns': StoryBeat(
    id: 'ch4_tone_returns',
    label: '那道声音又来了',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'vertigo',
    text:
        '公共频道再次掠过一道细得几乎听不见的尖声。扬声器里只剩下轻微电流声，戴着耳机的星遥却立刻摘下右侧耳罩，手掌撑住桌沿。\n“不是音量大。”她闭了一下眼，“像有什么东西直接在右耳里晃。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch4_xingyao_first_symptom',
  ),
  'ch4_xingyao_first_symptom': StoryBeat(
    id: 'ch4_xingyao_first_symptom',
    label: '她不想成为第一个病人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'vertigo',
    text:
        '苏弥让星遥坐下，星遥却先去摸桌上的频谱记录。\n“我没有失去行动能力。”她说，语速比平时更快，“先把波形存下来。”\n“你现在看不清屏幕。”苏弥把她的手从PDA上移开，“症状也是记录。别为了保住技术员的位置，把病人的位置删掉。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.suMi],
    next: 'ch4_sumi_examines',
  ),
  'ch4_sumi_examines': StoryBeat(
    id: 'ch4_sumi_examines',
    label: '眼震与耳鸣',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '苏弥用手指引导星遥的视线左右移动。星遥的瞳孔等大，呼吸没有受抑制，眼球却在看向右侧时出现细小的往返摆动。\n“恶心、耳鸣、定向障碍，没有明显药物抑制。”苏弥记下时间，“但现在还不能排除吸入物或延迟反应。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi],
    next: 'ch4_lincheng_silent_cards',
  ),
  'ch4_lincheng_silent_cards': StoryBeat(
    id: 'ch4_lincheng_silent_cards',
    label: '不使用公共频道的路线',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '林澄撕下三张废弃盘点表，分别写上“前进”“撤回”和“需要支援”，又用不同颜色画出集合厅到C-02的三段路线。\n“如果干扰来自频道，就先不用耳机。”她把纸卡分给每一组，“走廊转角看不见对方时，用手电光闪两次确认。谁都不要因为没听到命令就自己追上去。”',
    passageSpeakers: [Speaker.narration, Speaker.linCheng],
    next: 'ch4_medical_candidate',
  ),
  'ch4_medical_candidate': StoryBeat(
    id: 'ch4_medical_candidate',
    label: 'C-02仍在闪烁',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        'PDA地图上，C-02的黄色候选框已持续了五小时。那里有唯一张可以固定伤员的病床、仅剩的无菌器械，也有苏弥昨夜盘点时发现的镇静剂缺口。\n如果不进去，我们无法知道药是什么时候丢的；如果现在进去，每一个不适的人都会自然地成为“苏弥正在救治的患者”。而她的条款，正需要更多人活下来。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_walk_to_c02',
  ),
  'ch4_walk_to_c02': StoryBeat(
    id: 'ch4_walk_to_c02',
    label: '无声行进',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text:
        '我们关掉公共频道，沿林澄画出的绿色路线前往医疗区。没有耳机里的呼吸和报点，走廊突然显得异常宽阔。\n星遥走在我右后方，一只手始终按着耳廓。她每次绕过转角都会先举起“前进”纸卡，仿佛只要动作准确，身体的晃动就不会被别人看见。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_corridor_echo',
  ),
  'ch4_corridor_echo': StoryBeat(
    id: 'ch4_corridor_echo',
    label: '声音没有穿过空气',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'vertigo',
    text:
        '经过C区配电箱时，星遥突然停下。她没有再听到尖声，手指却清楚地感到PDA耳机接口在震动。\n“断开耳机后，空气里没有对应的声音。”她把线缆绕在手指上，“它可能不是广播，而是沿着特定输出线送进某一副耳机。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch4_corridor_stop_test',
  ),
  'ch4_corridor_stop_test': StoryBeat(
    id: 'ch4_corridor_stop_test',
    label: '在走廊中央停下三十秒',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'vertigo',
    text:
        '星遥要求所有人原地停下，关闭PDA音频输出三十秒。韩骐看了一眼前方的气密门，显然不愿把时间花在一次没有保证的测试上。\n“如果有人正赶去拿药，我们停在这里就是让路。”他说。\n“如果输出线才是暴露源，我们继续戴着耳机走，就是自己把它带进病房。”星遥靠着墙，却把计时器举得很稳，“你可以不信我头晕的原因，但不能假装这个变量不存在。”\n三十秒里没有第二个人出现症状。她的耳鸣也没有完全消失，却不再继续加重。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch4_medical_entry_protocol',
  ),
  'ch4_medical_entry_protocol': StoryBeat(
    id: 'ch4_medical_entry_protocol',
    label: '谁先进入隔离区',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'concerned',
    text:
        'C-02门前，苏弥让星遥和我留在前室，其他人先隔着观察窗确认空气监测与药柜状态。\n“你把自己留在最里面，门一关我们怎么知道你做了什么？”陈默问。\n“所以叶岚和高原跟我进去，韩骐守外门，所有动作使用房间固定摄像。”苏弥把医疗钥匙放在透明托盘上，“隔离不是把嫌疑人关进一个看不见的地方。恰好相反，每一次开柜都要比外面更容易被复核。”\n陈默没有点头，只把固定摄像的指示灯拍进自己的PDA。门锁释放时，所有人都听见了那声短促的机械咬合。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch4_c02_entry',
  ),
  'ch4_c02_entry': StoryBeat(
    id: 'ch4_c02_entry',
    label: '隔离病房',
    speaker: Speaker.narration,
    scene: SceneKey.medicalIsolation,
    text:
        'C-02比旧医务室更小，却被两道气密门分成前室和病房。观察窗占了半面墙，窗下有一条可以双向传递药品的狭槽。\n床边输液架还挂着半袋电解质溶液，医疗推车上摊着拆开的注射器外包装。那个空位太整齐了，像有人特意把“镇静剂在这里被使用”摆成一句完整的话。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_missing_ampoule',
  ),
  'ch4_missing_ampoule': StoryBeat(
    id: 'ch4_missing_ampoule',
    label: '少掉的不只是一支药',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '苏弥打开双重锁药柜。第二排左端少了一支镇静剂，软塑固定槽内却没有玻璃粉末或漏液。它不是在柜内破损，而是被完整取走。\n“昨晚二十三点四十七分，它还在。”她把自己和我的签字指给众人，“今天一点零七分，系统首次报告缺口。我无法证明这八十分钟里没有人拿过我的门禁。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi],
    next: 'ch4_sumi_accused',
  ),
  'ch4_sumi_accused': StoryBeat(
    id: 'ch4_sumi_accused',
    label: '第一个被写上的名字',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'protective',
    text:
        '“柜子归你管，剂量也只有你会用。”韩骐没有提高声音，只向前走了半步，“现在有人头晕，药又少了。你至少要先交出医疗区的钥匙。”\n他的推理省略了过程，却正好贴合每个人最容易理解的句子：药在医生手里，病人出现了，所以医生需要被控制。',
    passageSpeakers: [Speaker.hanQi, Speaker.narration],
    next: 'ch4_sumi_answers',
  ),
  'ch4_sumi_answers': StoryBeat(
    id: 'ch4_sumi_answers',
    label: '可以监督，不能先定罪',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '苏弥把钥匙放到推车中央，却没有推向韩骐。\n“可以增加一名保管人，可以每次开柜都录像，也可以先停止我单独用药。”她说，“但在没有确认星遥是否中毒之前，交出钥匙只会让一个未经证实的结论先变成权力。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi],
    next: 'ch4_tangyi_counts',
  ),
  'ch4_tangyi_counts': StoryBeat(
    id: 'ch4_tangyi_counts',
    label: '救治也会改变条款距离',
    speaker: Speaker.tangYi,
    scene: SceneKey.medicalIsolation,
    text:
        '唐弈倚在观察窗边，用硬币轻敲玻璃。\n“苏弥多救一个人，就离她的条件更近；我们多保留一个伤员，就多一个要分药和食物的人。”他看向苏弥，“这不证明你下药。它只证明，‘救人’在这里也不是没有利益的动词。”',
    passageSpeakers: [Speaker.narration, Speaker.tangYi],
    next: 'ch4_xingyao_collapses',
  ),
  'ch4_xingyao_collapses': StoryBeat(
    id: 'ch4_xingyao_collapses',
    label: '她先抓住了耳机',
    speaker: Speaker.narration,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'vertigo',
    cgId: 'cg_medical_isolation',
    text:
        '星遥想把刚才存下的波形投到墙上。屏幕才亮起，她的右手便忽然抓空，肩膀撞上输液架。\n金属架倒下的声音与耳机里的尖声同时响起。她试图说“右边”，只发出半个音，膝盖就失去支撑。我接住她时，她的手指仍死死勾着那根耳机线。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_immediate_response',
  ),
  'ch4_immediate_response': StoryBeat(
    id: 'ch4_immediate_response',
    label: '先移除正在作用的东西',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    cgId: 'cg_medical_isolation',
    cgFrame: 1,
    text:
        '“拔掉耳机，不要喂水。”苏弥跪到星遥身边，一手托住后脑，一手检查颈动脉，“林澄，把前室换气开到最大。高原，看风管压差。”\n星遥的呼吸快而浅，对疼痛有反应，却无法稳定地睁开眼。苏弥没有立即去拿药。她先让所有可能继续作用的暴露来源停下。',
    passageSpeakers: [Speaker.suMi, Speaker.narration],
    next: 'ch4_no_depression_signs',
  ),
  'ch4_no_depression_signs': StoryBeat(
    id: 'ch4_no_depression_signs',
    label: '不像镇静剂过量',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '两分钟后，星遥可以按指令握手，眼震却仍然存在。她的瞳孔、呼吸和血压都不符合常用镇静剂过量的模式。\n“这不能证明药没有被偷，只能证明不该用一支丢失的药解释眼前所有症状。”苏弥把用过的手套单独封存，“现在把现场和病人分开记录。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi],
    next: 'ch4_xingyao_partial_recovery',
  ),
  'ch4_xingyao_partial_recovery': StoryBeat(
    id: 'ch4_xingyao_partial_recovery',
    label: '醒来以后先确认少了什么',
    speaker: Speaker.liXingyao,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'vertigo',
    text:
        '星遥再次睁眼时，先摸耳机，再摸PDA，最后才像突然想起什么似的看向我。\n“我断了多久？”\n“一分四十七秒。”我说。\n“有没有人碰过我的端口？”\n她没有问自己会不会留下后遗症，也没有问是谁接住了她。确认意识缺失期间的设备状态，是她能抓住的第一根绳子。\n“我拔了耳机，苏弥检查你，林澄一直录像。”我把每个人的动作逐项说完，“没有空白。”\n她缓慢呼出一口气，手指却仍扣着我的袖口，没有松开。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch4_accusation_round',
  ),
  'ch4_accusation_round': StoryBeat(
    id: 'ch4_accusation_round',
    label: '每个人都能说出一个凶手',
    speaker: Speaker.zhouXu,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'defensive',
    text:
        '周叙最先打破沉默：“耳机是星遥自己改的，谁知道是不是线路接错？”\n“她在集合厅就出现症状，错误接线解释不了为什么脉冲只在特定时段出现。”陈默说。\n韩骐看向苏弥：“药仍然少了一支。不是这次，不代表不会是下一次。”\n“而你从进门开始就在要求拿钥匙。”唐弈笑得很淡，“要列动机，谁都别漏。”\n几句话把房间切成了四个方向。每个人都挑选了最能威胁自己的那一种解释，再把它说成最需要优先处理的事实。',
    passageSpeakers: [
      Speaker.zhouXu,
      Speaker.chenMo,
      Speaker.hanQi,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch4_sumi_search_request',
  ),
  'ch4_sumi_search_request': StoryBeat(
    id: 'ch4_sumi_search_request',
    label: '先让可检验的问题排队',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '“都停一下。”苏弥没有喊得很响，却把记录板拍在金属推车上，“现在有三个问题：星遥为什么晕倒、镇静剂去了哪里、谁能接触耳机输出。它们可以有关，也可以没有关系。”\n她在玻璃上画出三列，要求每个人只能把观察写进对应位置，不得在证据后直接补上人名。\n“先救人不是暂停调查。”她说，“是把调查从谁最像凶手，改成哪一种伤害正在发生。”\n叶岚接过笔，在三列最下方又加了一行：什么事实能使我们撤回当前判断。直到那一行出现，房间里的声音才真正低下来。',
    passageSpeakers: [
      Speaker.suMi,
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch4_support_choice',
  ),
  'ch4_support_choice': StoryBeat(
    id: 'ch4_support_choice',
    label: '无声调查中的位置',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text: '星遥需要有人与她一起复原暴露时间，苏弥需要第二个人复核体征，林澄则要在禁用公共频道的情况下维持内外联系。我只能先占据其中一个位置。',
    next: null,
    choices: [
      StoryChoice(
        label: '陪星遥重建耳机时间线',
        caption: '不让她在症状中独自证明自己的判断',
        next: 'ch4_support_xingyao',
        effect: ChoiceEffect(xingyao: 1, logic: 1, flag: 'ch4_support_xingyao'),
      ),
      StoryChoice(
        label: '替苏弥复核体征与用药',
        caption: '让医疗结论可以被第二个人重复',
        next: 'ch4_support_sumi',
        effect: ChoiceEffect(sumi: 1, cooperation: 1, flag: 'ch4_support_sumi'),
      ),
      StoryChoice(
        label: '按林澄的纸卡守住内外路线',
        caption: '不把年龄最小的人留在隔离门外独自报点',
        next: 'ch4_support_lincheng',
        effect: ChoiceEffect(
          lincheng: 1,
          cooperation: 1,
          flag: 'ch4_support_lincheng',
        ),
      ),
    ],
  ),
  'ch4_support_xingyao': StoryBeat(
    id: 'ch4_support_xingyao',
    label: '先承认自己是受影响的人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'alarm',
    text:
        '星遥把右耳机交给我，开口时仍不习惯使用“我感到”而不是“设备显示”。\n“第一次是恶心，第二次是右侧耳鸣，进病房后开始觉得墙在向左倾。”她停了一下，“我之前没说第三个。因为那听起来不像可重复的数据。”\n我把三次感受和PDA时间戳并排写下。主观不等于无效；它只需要更谨慎地标明来源。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch4_investigation_setup',
  ),
  'ch4_support_sumi': StoryBeat(
    id: 'ch4_support_sumi',
    label: '医生也要把判断交出去',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '苏弥让我重新测量星遥的呼吸频率，再照她的方法检查瞳孔与疼痛反应。两组记录的差值被原样保留，没有被她修正成更整齐的数字。\n“如果我被当作嫌疑人，那么我说‘不像药物过量’就不能成为唯一依据。”她把听诊器交给我，“你不需要变成医生。你只需要证明，一个外行按同样步骤也能看到同一组事实。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi],
    next: 'ch4_investigation_setup',
  ),
  'ch4_support_lincheng': StoryBeat(
    id: 'ch4_support_lincheng',
    label: '没有声音时也能互相确认',
    speaker: Speaker.linCheng,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'determined',
    text:
        '我和林澄分站气密门内外。她把每一次传递物品的时间写在纸卡背面，收到后必须隔着玻璃举起相同编号。\n“大人经常觉得不说话就是失去联系。”她把“已收到”的卡片贴到玻璃上，“其实最可怕的是说了很多，却没有人确认对方真的收到。”\n她设计的不是替代语言的暗号，而是一条每一步都必须得到回应的路线。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch4_investigation_setup',
  ),
  'ch4_investigation_setup': StoryBeat(
    id: 'ch4_investigation_setup',
    label: '把三个问题分开',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '叶岚在观察窗上贴了三条纸：星遥体内是否有镇静剂；输液液是否被污染；耳机是否收到了其他人没有收到的信号。\n“药物失踪、病人昏厥和高频干扰同时发生，不代表它们必须共享一个原因。”她说，“先让每一条因果都自己站稳。”',
    passageSpeakers: [Speaker.narration, Speaker.yeLan],
    next: 'ch4_medical_investigation',
  ),
  'ch4_medical_investigation': StoryBeat(
    id: 'ch4_medical_investigation',
    label: '隔离病房现场调查',
    text: '',
    scene: SceneKey.medicalIsolation,
    phase: StoryPhase.investigation,
    next: 'ch4_investigation_review',
  ),
  'ch4_investigation_review': StoryBeat(
    id: 'ch4_investigation_review',
    label: '现场没有给出一个方便的凶手',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '注射器的无菌内封没有被针帽穿过，输液残液中也没有检出相应药物。星遥的失衡发生在右侧耳机收到18.6kHz脉冲之后，体征变化则更接近前庭刺激后的晕厥。\n这些记录能排除“苏弥用丢失的镇静剂放倒星遥”，却无法解释药到底去了哪里。一个无法定罪的结论，没有让房间里的怀疑减少；它只让怀疑失去了最简单的对象。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_sumi_body_fact',
  ),
  'ch4_sumi_body_fact': StoryBeat(
    id: 'ch4_sumi_body_fact',
    label: '身体事实',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '“药物过量不会只在朝右看时加重眼震，也不会在拔掉耳机后迅速减轻。”苏弥把两份独立测量并排，“我能说的是，星遥经历了短暂晕厥，诱因更像强烈的定向感觉冲突。”\n她没有说“我是清白的”。医疗结论只负责描述身体，不负责替她审判药物失窃。',
    passageSpeakers: [Speaker.suMi, Speaker.narration],
    next: 'ch4_xingyao_frequency_fact',
  ),
  'ch4_xingyao_frequency_fact': StoryBeat(
    id: 'ch4_xingyao_frequency_fact',
    label: '只进入一侧耳机的脉冲',
    speaker: Speaker.liXingyao,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'alarm',
    text:
        '星遥醒来后没有立即拿回设备。她让我把离线频谱夹分别接到左、右声道，右侧每隔七秒便出现一组18.6kHz的窄脉冲，左侧和空气麦克风都没有。\n“它利用的是PDA输出链，不是病房扬声器。”她低声说，“所以大家在同一个房间，只有我持续受到刺激。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch4_gaoyuan_airflow_fact',
  ),
  'ch4_gaoyuan_airflow_fact': StoryBeat(
    id: 'ch4_gaoyuan_airflow_fact',
    label: '换气不是主因',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'injured',
    text:
        '高原拄着夹板检查了前室与病房压差。滤网有积灰，换气量仍在安全范围；门外三人与室内其他人也没有同步症状。\n“通风差会让恶心更难受，但不能解释为什么只有一副耳机记下脉冲。”他用扳手敲了敲风管，“这次别把一个真实的小问题，当成解释一切的大答案。”',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan],
    next: 'ch4_case03_question',
  ),
  'ch4_case03_question': StoryBeat(
    id: 'ch4_case03_question',
    label: 'CASE 03：谁把病人写进了药柜',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '现在需要判断的不是镇静剂最后在谁手里，而是星遥的昏厥是否由那支药造成。如果两件事只因同时发生就被绑在一起，苏弥会立刻失去药品与救治权。\n我必须用身体表现、暴露媒介和排除性检查组成同一条因果链，再决定哪一种解释值得改变所有人的权限。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_case03_deduction',
  ),
  'ch4_case03_deduction': StoryBeat(
    id: 'ch4_case03_deduction',
    label: '谁把病人写进了药柜',
    text: '',
    scene: SceneKey.medicalIsolation,
    phase: StoryPhase.deduction,
    next: 'ch4_case03_resolved',
  ),
  'ch4_case03_sedative_error': StoryBeat(
    id: 'ch4_case03_sedative_error',
    label: '缺失的药不是体内的药',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '我一度把药柜缺口当成已经进入星遥体内的证据。苏弥把未穿刺的无菌封和阴性残液检测推回我面前。\n“药确实丢了，但我们没有找到进入她身体的路径。”她说，“你正在用需要另行调查的缺口，替代眼前已经检查的症状。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi],
    next: 'ch4_case03_deduction',
  ),
  'ch4_case03_contamination_error': StoryBeat(
    id: 'ch4_case03_contamination_error',
    label: '真实的积灰不等于致昏迷毒物',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'injured',
    text:
        '我把换气量下降与昏厥直接连在一起。高原用扳手点着压差记录，提醒我风量仍在安全范围，房间里也没有出现多人同步症状。\n“积灰是真的，恶心会因闷热加重也是真的。”他说，“但它们没法解释右声道的七秒脉冲。别因为一条线索看得见，就让它遮住更精确的记录。”',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan],
    next: 'ch4_case03_deduction',
  ),
  'ch4_case03_resolved': StoryBeat(
    id: 'ch4_case03_resolved',
    label: '被定向制造的晕厥',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '体征记录证明星遥经历的是以眼震、定向障碍和短暂意识丧失为主的晕厥；耳机记录证明右声道在症状加重前持续收到定向脉冲；无菌封与残液检测则排除了现场注射和输液投药。\n“有人或某个程序把干扰送进特定耳机，制造出一名需要立即救治的病人。”我说，“镇静剂的失踪是另一个真问题，但它没有造成这次昏厥。”',
    passageSpeakers: [Speaker.narration, Speaker.shenYan],
    flagsOnEnter: {'case03_solved'},
    next: 'ch4_case03_limits',
  ),
  'ch4_case03_limits': StoryBeat(
    id: 'ch4_case03_limits',
    label: '正确答案只覆盖它能够证明的范围',
    speaker: Speaker.liXingyao,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'vertigo',
    text:
        '星遥靠在病床边，把“定向音频刺激”写进结论栏，又在后面加上一个醒目的问号。\n“我们证明了作用路径，没证明发送者。”她说，“公共频道日志可能被改写，耳机也可能在我们拿到以前就写入了触发程序。”\n“所以你还是不能说是谁害你。”韩骐说。\n“不能。”她抬起眼，“这正是结论，不是缺陷。一个答案如果顺手把没有证明的部分也包进去，就和主办方给我们的假记录没区别。”\n她说得冷静，攥着笔的指节却没有恢复血色。知道自己被准确地选作目标，并不会因为尚未找到凶手而减轻半分。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.hanQi,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch4_sumi_inventory_testimony',
  ),
  'ch4_sumi_inventory_testimony': StoryBeat(
    id: 'ch4_sumi_inventory_testimony',
    label: '苏弥交出自己的八十分钟',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '苏弥主动打开个人活动记录，把镇静剂最后确认到缺失报警之间的八十分钟逐段投上墙面。她去过宿舍、集合厅和旧医务室，中间有十一分钟留在无摄像覆盖的盥洗区。\n“你完全可以在那时把药交给别人。”周叙说。\n“是。”苏弥回答，“也可能有人趁我洗脸时复制门禁。现在没有证据区分这两种情况。”\n“你为什么要把对自己最不利的空白说出来？”我问。\n“因为等别人发现，它就会从一段未知时间变成我刻意隐藏的时间。”她看着我，眼底有连续失眠留下的淡青色，“我需要你们相信我的检查，不代表我有权要求你们忽略我的漏洞。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.zhouXu,
      Speaker.suMi,
      Speaker.shenYan,
      Speaker.suMi,
    ],
    next: 'ch4_chenmo_log_boundary',
  ),
  'ch4_chenmo_log_boundary': StoryBeat(
    id: 'ch4_chenmo_log_boundary',
    label: '日志能证明门开过，不能证明是谁',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'discovery',
    text:
        '陈默把药柜底层的离线触点记录导出。凌晨零点三十二分，柜门曾离开闭合位置不到两毫米，持续四秒，却没有产生正式开柜事件。\n“有人用薄片试过锁舌。”他说，“没打开，或者只是在测试报警阈值。”\n韩骐问：“能查指纹吗？”\n“边缘全是清洁剂残留，昨天盘点的人也都碰过。”陈默放大锁舌上的浅痕，“这条记录只能证明缺失前有人对柜子做过准备。拿它去指认最会开锁的人，和拿药柜归属指认医生没有区别。”\n他说这句话时没有看苏弥。那更像是说给未来可能被技术能力定罪的自己。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.hanQi,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch4_missing_drug_separate',
  ),
  'ch4_missing_drug_separate': StoryBeat(
    id: 'ch4_missing_drug_separate',
    label: '清白不会让镇静剂回来',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '叶岚撤下“星遥体内是否有镇静剂”的纸条，却把“药物去向”留在玻璃上。\n“我们只撤回了一项指控：没有证据表明苏弥用这支药放倒星遥。”她说，“这不等于药没有被偷，也不等于偷药的人没有计划在别的人身上使用。”\n指控被纠正后，风险反而有了更清晰的形状：某处有一支能让人失去反抗能力的药，当前没有持有记录。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch4_lincheng_headset_memory',
  ),
  'ch4_lincheng_headset_memory': StoryBeat(
    id: 'ch4_lincheng_headset_memory',
    label: '最不起眼的一次借用',
    speaker: Speaker.linCheng,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'anxious',
    text:
        '林澄忽然记起，昨晚轮值时有人以“右耳接触不良”为由借过备用耳机。她只看见对方戴着工作手套的手，没有看清编号。\n“我当时觉得耳机不算重要物资。”她的声音发紧，“就没有要求签字。”\n星遥没有责怪她，只让她把能记住的手套颜色、借还时间和对方说话习惯分别记录。\n“你没有制造脉冲。”星遥说，“别让对方借走一副耳机以后，还顺便借走你判断自己有没有资格继续做事的权利。”\n林澄点头，却写了三遍才把时间写对。主办方不只利用恶意，也利用那些在正常生活里根本不需要提防的小小善意。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch4_high_risk_announcement',
  ),
  'ch4_high_risk_announcement': StoryBeat(
    id: 'ch4_high_risk_announcement',
    label: '高危应急物资索引',
    speaker: Speaker.administrator,
    scene: SceneKey.medicalIsolation,
    timelineMinute: 3450,
    text:
        '所有PDA在同一刻震动。原本只有审计界面保留的索引页被系统主动推送给每一名幸存者。\n“第三日应急权限已开放。高危物资可用于破拆、防卫、医疗与区域控制。本系统仅公布初始封存位置，不保证当前状态。”\n镇静剂箱、破拆斧、高压控制棒、工业紧固器、强腐蚀清洗剂和门禁强制控制器依次亮起。第一项已经显示“当前状态：去向不明”。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    highRiskItemsOnEnter: {
      'sedative_case',
      'rescue_axe',
      'stun_controller',
      'industrial_driver',
      'corrosive_cleaner',
      'door_override',
    },
    highRiskItemsMissingOnEnter: {'sedative_case'},
    next: 'ch4_index_locations',
  ),
  'ch4_index_locations': StoryBeat(
    id: 'ch4_index_locations',
    label: '六个位置在地图上同时变红',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'inspecting',
    text:
        '高原把六个封存点标上最短步行时间：旧安保器材室两分四十秒，维修间三分十秒，清洁库四分二十秒，D区破拆柜五分以上。\n“这不是六件东西，是六场赛跑。”他说，“离门最近的人现在出发，其他人连他有没有打开柜子都来不及确认。”\n地图没有显示体力差异。韩骐跑完两分四十秒仍能压制一个人，陈默带着工具走同样距离却需要停下来换气。相同的公开坐标，让所有人看见目标，也让少数人拥有了更快把目标变成权力的身体。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch4_distance_to_weapons',
  ),
  'ch4_distance_to_weapons': StoryBeat(
    id: 'ch4_distance_to_weapons',
    label: '人开始计算彼此到武器的距离',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'guarded',
    text:
        '陈默悄悄移动到内门控制面板旁。韩骐也离开药柜，把自己放在通往走廊的最短直线上。两个人都没有奔跑，房间里的其他人却已经跟着改变站位。\n“谁先出去，谁就是准备抢东西？”唐弈问。\n“谁拦住门，谁也可能是在替自己争取时间。”陈默回答。\n主办方甚至不需要下达“争夺开始”。当每个人都知道别人知道武器在哪里，任何移动都会获得第二种解释。星遥把我的袖口抓得更紧，低声说：“别站在韩骐和门之间。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch4_no_safe_keeper',
  ),
  'ch4_no_safe_keeper': StoryBeat(
    id: 'ch4_no_safe_keeper',
    label: '没有一个天然中立的保管人',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '叶岚逐一否决“交给最强的人”“交给医生”“交给01”和“按原位置不管”这四个看似简单的答案。每种方法都能减少一种风险，也会把另一种风险集中到具体的人手里。\n“所以别再问谁最值得信任。”她说，“问一件东西离开柜子后，谁能看见、谁能叫停、谁能把它放回去。”\n“你可以一直设计程序。”韩骐说，“但有人正在去拿它时，程序不会替你追人。”\n“力量能追上一个人，也能成为其他人需要逃跑的原因。”陈默说。\n他们第一次把矛盾说得如此完整，也因此再没有一句容易让所有人同时接受的折中。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.hanQi,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch4_index_panic',
  ),
  'ch4_index_panic': StoryBeat(
    id: 'ch4_index_panic',
    label: '索引不是保管方案',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'guarded',
    text:
        '陈默快速翻过六件物资的门禁要求，脸色比看到镇静剂缺口时更难看。\n“公布位置会让每个柜子立刻变成目标。”他说，“而且旧安保柜和维修间不在同一条路上。我们不可能同时守住所有位置。”\n索引使每个人都拥有同样的知识，却没有给出同样的距离、门禁或身体能力。信息平等的一秒之后，力量差开始决定谁能最先到达。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch4_weapon_terms',
  ),
  'ch4_weapon_terms': StoryBeat(
    id: 'ch4_weapon_terms',
    label: '工具从被公布的一刻起成为武器',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '叶岚要求所有人暂时不离开C-02，先将位置、原用途、可能伤害方式和所需门禁写成公共表。\n“破拆斧可以救人，也可以伤人；镇静剂可以防止患者伤害自己，也可以剥夺拒绝能力。”她说，“主办方只提供了物件和冲突。我们不能因为它期待某种用法，就把实际使用者的决定一起抹掉。”',
    passageSpeakers: [Speaker.narration, Speaker.yeLan],
    next: 'ch4_hanqi_security',
  ),
  'ch4_hanqi_security': StoryBeat(
    id: 'ch4_hanqi_security',
    label: '强者提出最快的方案',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'protective',
    text:
        '韩骐提议先取得旧安保柜的高压控制棒和总钥匙，由他保管，其他人再依次去确认剩余封存。\n“这里只有我能在不拿破拆工具的情况下压住一个抢柜子的人。”他直接说，“如果你们觉得这是集中权力，就安排两个人跟着我。但别用讨论把离柜子更近的人送到我们前面。”',
    passageSpeakers: [Speaker.narration, Speaker.hanQi],
    next: 'ch4_chenmo_access',
  ),
  'ch4_chenmo_access': StoryBeat(
    id: 'ch4_chenmo_access',
    label: '弱者要求控制门的方法',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'guarded',
    text:
        '陈默要求先复制每个柜子的访问日志，再由不同人分持物理钥匙和电子门禁。\n“身体上能守住柜子，不等于有权单独决定什么时候开。”他看着韩骐，“如果你同时拿着工具、钥匙和01，见证人就只能记录你已经做完的事。”\n他没有与韩骐比较谁更能打。他要的是一道让力量无法直接跨过的程序。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch4_protocol_memory',
  ),
  'ch4_protocol_memory': StoryBeat(
    id: 'ch4_protocol_memory',
    label: '昨夜的制度今天开始承重',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '托管制度写在纸上时，我们争论的是权限如何被撤销；现在柜子里放着能让人失去反抗能力或直接受伤的物品，同一套制度开始决定谁能拿到它们。\n我们不是在三个全新方案中作选择。昨夜已经通过的规则，正在把每个人推向不同的起点。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_shared_precedent',
    nextByFlag: {
      'ch3_central_custody': 'ch4_central_precedent',
      'ch3_clause_market': 'ch4_market_precedent',
      'ch3_shared_revocation': 'ch4_shared_precedent',
    },
    auditNext: 'ch4_audit_projection',
    auditRequiredFlags: {'audit_weapon_manifest_found', 'case03_solved'},
  ),
  'ch4_central_precedent': StoryBeat(
    id: 'ch4_central_precedent',
    label: '中央保管人已经有了名字',
    speaker: Speaker.tangYi,
    scene: SceneKey.medicalIsolation,
    text:
        '昨夜的中央保管制让韩骐拥有第一顺位的门禁处置权，叶岚保留副本，陈默负责技术审计。在没有武器时，三人互相限制；现在韩骐却是最可能先拿到安保器材的人。\n“制度没有突然变坏。”唐弈说，“只是它昨晚保管的是按钮，今天保管的是能让别人不再按按钮的东西。”',
    passageSpeakers: [Speaker.narration, Speaker.tangYi],
    next: 'ch4_key_custody_choice',
  ),
  'ch4_market_precedent': StoryBeat(
    id: 'ch4_market_precedent',
    label: '价格表上出现了新的筹码',
    speaker: Speaker.tangYi,
    scene: SceneKey.medicalIsolation,
    text:
        '昨夜通过的公开交换规则禁止把饮水、急救和解除即时死亡当作对价，却没有规定高危物资的门禁能否被交换。\n“当一件工具可以阻止别人伤害你，它就不只是物品。”唐弈转动硬币，“它也是一段暂时不受威胁的时间。如果我们不公开分配，这段时间一样会在私下被交换。”',
    passageSpeakers: [Speaker.narration, Speaker.tangYi],
    next: 'ch4_key_custody_choice',
  ),
  'ch4_shared_precedent': StoryBeat(
    id: 'ch4_shared_precedent',
    label: '两名见证人能否跑得过一个人',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '昨夜的共同撤销规则能阻止一段托管权限继续生效，却不能让两名见证人同时出现在六个不同柜子旁边。\n“我们可以要求每次开柜都由两人确认。”叶岚说，“但如果有人先拿到工具再去寻找第二个人，规则只能在他愿意等待时生效。”\n制度需要人到场才能运作，而地图已经开始用距离替主办方选择谁能先到。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch4_key_custody_choice',
  ),
  'ch4_key_custody_choice': StoryBeat(
    id: 'ch4_key_custody_choice',
    label: '高危物资开放后的第一次分配',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '封存位置已经公开，C-02的候选框也从黄色转为橙色。我们必须在离开病房前决定第一组门禁和钥匙如何分配。每个方案都有目前能被说清的理由，也都会让某些人先于其他人拿到实物。',
    next: null,
    choices: [
      StoryChoice(
        label: '由韩骐保管安保柜与总钥匙',
        caption: '优先确保有人能制止抢夺，两名见证人同行',
        next: 'ch4_strong_custody',
        effect: ChoiceEffect(
          cooperation: -1,
          flag: 'ch4_security_hanqi',
          highRiskItemId: 'stun_controller',
          highRiskHolderId: '04',
        ),
      ),
      StoryChoice(
        label: '由陈默与唐弈拆分维修门禁',
        caption: '用技术权限和公开交换阻止强者独占入口',
        next: 'ch4_alliance_custody',
        effect: ChoiceEffect(
          logic: 1,
          flag: 'ch4_security_alliance',
          highRiskItemId: 'industrial_driver',
          highRiskHolderId: '08',
        ),
      ),
      StoryChoice(
        label: '每次取用都交由现场多数决',
        caption: '没有人预先持有完整钥匙，紧急情况也需要表决',
        next: 'ch4_majority_custody',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch4_security_majority'),
      ),
    ],
  ),

  // Standard run: physical control escalates into a direct killing.
  'ch4_strong_custody': StoryBeat(
    id: 'ch4_strong_custody',
    label: '钥匙和控制棒落在同一只手里',
    speaker: Speaker.hanQi,
    scene: SceneKey.securityRoom,
    portraitMood: 'armed',
    text:
        '集中保管方案通过后，韩骐指定叶岚和我作为见证人，一同前往A-03领取高压控制棒。我们把三台PDA的录像同步到公共记录，约定任何一人提出异议都要暂停开柜。\n方案写在屏幕上时，每个人似乎都拥有叫停权。可走进安保器材室后，这项权利是否还能执行，取决于持械者愿不愿意停下。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_security_room_entry',
  ),
  'ch4_security_room_entry': StoryBeat(
    id: 'ch4_security_room_entry',
    label: '安保器材室只容得下三个人',
    speaker: Speaker.narration,
    scene: SceneKey.securityRoom,
    text:
        'A-03安保器材室比地图上更狭窄。三排铁柜挤在一起，墙上仍贴着褪色的防暴器材领用流程，最后一栏写着“归还时由值班主管确认”。这里没有主管，也没有一扇能让见证人与持械者保持安全距离的第二道门。\n叶岚站在门口录像，我负责读取封条。韩骐进入最里面那排柜子后，我们若要离开，只能从他身边经过。直到门在背后合拢，我才意识到所谓“两名见证人同行”只保证有两双眼睛，不保证那两个人仍能叫停持有者。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_security_seal_audit',
  ),
  'ch4_security_seal_audit': StoryBeat(
    id: 'ch4_security_seal_audit',
    label: '封条完整不代表领取合理',
    speaker: Speaker.yeLan,
    scene: SceneKey.securityRoom,
    portraitMood: 'intervening',
    text:
        '控制棒柜的纸质封条与电子序列完全一致，电池仓也没有提前开启的痕迹。\n“记录没问题。”韩骐说。\n“记录只能证明你是按我们刚通过的方案拿到它。”叶岚没有停止录像，“如果方案本身把过多权力给了一个人，完整记录不会把方案变正确。”\n韩骐拉开绝缘套上的固定扣。“所以你跟着我。我要做什么，你都能看见。”\n“看见和阻止不是同一个能力。”叶岚说。房间太窄，她说完这句话时，仍不得不侧身让韩骐从面前通过。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.hanQi,
      Speaker.yeLan,
    ],
    next: 'ch4_hanqi_tests_baton',
  ),
  'ch4_hanqi_tests_baton': StoryBeat(
    id: 'ch4_hanqi_tests_baton',
    label: '一次符合流程的试放电',
    speaker: Speaker.hanQi,
    scene: SceneKey.securityRoom,
    portraitMood: 'armed',
    text:
        '韩骐将控制棒抵在墙边测试板上，按规程进行半秒试放电。蓝白电弧在金属触点间一闪，爆响撞回狭窄房间，空气里立刻多出一股焦涩气味。\n我明知这是正常测试，肩膀仍然本能地绷紧。叶岚的镜头也向下偏了一瞬。\n“有效距离不到一米，只有贴身时能用。”韩骐关掉保险，“它不是枪。”\n“对必须靠近你才能阻止你的人来说，这个距离已经够了。”我说。\n韩骐看了看我，没有反驳，只把控制棒扣到右侧腰带。那是最方便拔出的方向。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch4_security_witness_break',
  ),
  'ch4_security_witness_break': StoryBeat(
    id: 'ch4_security_witness_break',
    label: '见证人第一次要求返还',
    speaker: Speaker.yeLan,
    scene: SceneKey.securityRoom,
    portraitMood: 'intervening',
    text:
        '离开前，叶岚要求把控制棒重新装入绝缘袋，由三人共同携带到C-02后再决定是否启用。\n“柜子已经打开，危险位置也确认了。没有正在发生的抢夺。”她说，“继续贴身携带不属于最低必要措施。”\n“走廊上才最可能有人截我们。”韩骐拒绝卸下，“你可以记录我不同意。”\n“记录不是许可。”\n“但你也没有能力执行返还。”\n两个人都没有再提高声音。就是从这句平静的事实开始，见证制度失去了撤销能力，只剩下替之后发生的事提供时间戳。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch4_hanqi_private_reason',
  ),
  'ch4_hanqi_private_reason': StoryBeat(
    id: 'ch4_hanqi_private_reason',
    label: '他说自己不想再晚一步',
    speaker: Speaker.hanQi,
    scene: SceneKey.securityRoom,
    portraitMood: 'armed',
    text:
        '叶岚先去开外门时，韩骐忽然低声对我说：“项圈爆炸的时候，我就在两米外。”\n我知道他说的是最初那个试图破坏项圈的人。\n“我能把他按住。”韩骐盯着控制棒的保险灯，“可我先等规则讲完，等别人同意。等我过去，他已经把工具插进去了。”\n“那不是你的错。”\n“这里不在乎谁有没有错，只在乎谁来得及。”他抬头看我，“我不想再看着一个本来能按住的人，把所有人拖进下一次爆炸。”\n他的恐惧是真的，保护欲也是真的。正因如此，他比一个单纯贪恋武器的人更难被说服放手。',
    passageSpeakers: [
      Speaker.hanQi,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.shenYan,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch4_hanqi_requests_01',
  ),
  'ch4_hanqi_requests_01': StoryBeat(
    id: 'ch4_hanqi_requests_01',
    label: '保管人要求同时保管01',
    speaker: Speaker.hanQi,
    scene: SceneKey.corridor,
    portraitMood: 'armed',
    text:
        '返回C-02前室时，韩骐要求我把01交给他，直到六个柜子都完成盘点。\n“高危门禁可以通过你的终端转授。”他说，“我不会让你离开两米，也不会查看你的私密字段。但我要确保没有人用你的终端越过我。”\n他把“保护”与“控制”摆在同一个句子里，而他的条款仍要求他在终局亲自持有01。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch4_chenmo_objects',
  ),
  'ch4_chenmo_objects': StoryBeat(
    id: 'ch4_chenmo_objects',
    label: '审计人拒绝承认无法撤销的保管',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'desperate',
    text:
        '陈默拦在前室第二道门旁，要求韩骐先把控制棒放回绝缘包，再讨论01托管。\n“持有武器的人不能同时成为唯一门禁保管人。”他的声音发紧，却没有退开，“这不是对你品德的判断，是最低限度的权限隔离。”',
    passageSpeakers: [Speaker.narration, Speaker.chenMo],
    next: 'ch4_chenmo_copy_attempt',
  ),
  'ch4_chenmo_copy_attempt': StoryBeat(
    id: 'ch4_chenmo_copy_attempt',
    label: '他想在被拿走之前留下副本',
    speaker: Speaker.narration,
    scene: SceneKey.medicalIsolation,
    text:
        '韩骐向前时，陈默没有与他推挤。他转身将离线读取器插进门禁维护口，试图在总钥匙被集中保管前复制一份撤销凭证。\n维护口亮起警告灯。韩骐伸手抓住他的手腕，陈默另一只手仍然按住读取器。两个人都清楚，这不再只是一场口头争论：副本再过五秒就会完成，而韩骐可以在一秒内让他离开终端。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_strong_intervention',
  ),
  'ch4_strong_intervention': StoryBeat(
    id: 'ch4_strong_intervention',
    label: '还有几秒可以说话',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '读取器的进度灯从一格跳到两格。我可以先要求韩骐放手，可以要求陈默中止复制，也可以立即启动昨夜制定的公共撤销。三种说法都无法代替他们已经作出的动作，却会决定之后记录如何描述我的位置。',
    next: null,
    choices: [
      StoryChoice(
        label: '要求韩骐先放开陈默',
        caption: '武器持有者必须先停止身体强制',
        next: 'ch4_strong_plea_release',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch4_opposed_hanqi_force'),
      ),
      StoryChoice(
        label: '要求陈默中止未授权复制',
        caption: '先阻止一次不可追回的权限复制',
        next: 'ch4_strong_plea_stop',
        effect: ChoiceEffect(logic: 1, flag: 'ch4_opposed_chenmo_copy'),
      ),
      StoryChoice(
        label: '呼叫两名见证人启动撤销',
        caption: '用昨夜的公共程序冻结门禁',
        next: 'ch4_strong_plea_revoke',
        effect: ChoiceEffect(
          logic: 1,
          cooperation: 1,
          flag: 'ch4_called_revocation',
        ),
      ),
    ],
  ),
  'ch4_strong_plea_release': StoryBeat(
    id: 'ch4_strong_plea_release',
    label: '放手没有发生',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'conflicted',
    text:
        '“韩骐，你先放手。”我说，“复制可以稍后追责，身体伤害不能。”\n“他正在复制所有高危门禁。”韩骐的手指没有松开，“等他做完，你所说的稍后就没有意义。”\n他听见了我的要求，也理解了伤害可能。他仍然选择优先中止复制。',
    passageSpeakers: [Speaker.shenYan, Speaker.hanQi, Speaker.narration],
    next: 'ch4_strong_stun',
  ),
  'ch4_strong_plea_stop': StoryBeat(
    id: 'ch4_strong_plea_stop',
    label: '中止指令来得太晚',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'desperate',
    text:
        '“陈默，中止复制。”我说，“把已经完成的部分封存，先离开维护口。”\n“现在中止，副本会被控制器删除。”他咬紧牙，“他不会再给第二次机会。”\n他知道韩骐的力量足以使他受伤，却把这几秒当成唯一能够留下反制权的窗口。',
    passageSpeakers: [Speaker.shenYan, Speaker.chenMo, Speaker.narration],
    next: 'ch4_strong_stun',
  ),
  'ch4_strong_plea_revoke': StoryBeat(
    id: 'ch4_strong_plea_revoke',
    label: '制度没能跑过手指',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '我呼叫叶岚与苏弥执行紧急撤销。叶岚立即确认武器持有者与门禁复制者正在发生身体冲突，苏弥在病房内提交第二份确认。\n系统进入三秒冻结倒计。第一秒结束前，韩骐已经拔出控制棒。\n“规则有用。”叶岚后来在记录里写道，“但它没有快到可以替人在一秒内放开手。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.yeLan],
    next: 'ch4_strong_stun',
  ),
  'ch4_strong_stun': StoryBeat(
    id: 'ch4_strong_stun',
    label: '第一次放电后他还活着',
    speaker: Speaker.narration,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'armed',
    text:
        '控制棒碰到陈默前臂时发出短促爆响。他的手指立刻失去力量，离线读取器掉在地上，进度灯停在最后一格。\n陈默向后撞上门框，膝盖跪下，仍然保持意识。他没有试图反击，只伸手去够地上的读取器。第一次放电已经让复制中止，之后的动作不再是为了阻止正在发生的危险。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_strong_restraint',
  ),
  'ch4_strong_restraint': StoryBeat(
    id: 'ch4_strong_restraint',
    label: '他知道继续压制会发生什么',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'armed',
    text:
        '韩骐用膝盖压住陈默肩背，将他的脸转向一侧。苏弥隔着气密门大声告诉他，陈默的呼吸位置受限，继续压制可能导致缺氧。\n“他还在抢设备。”韩骐说。\n陈默的手指已经离读取器有半米，只在地面无意识地弯曲。韩骐看见了这个距离，仍然没有立刻移开重心。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch4_strong_death_confirmed',
  ),
  'ch4_strong_death_confirmed': StoryBeat(
    id: 'ch4_strong_death_confirmed',
    label: '不是意外结束的压制',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'shaken',
    timelineMinute: 3582,
    text:
        '气密门解锁后，苏弥把韩骐推开，对陈默进行心肺复苏。她连续报出时间、呼吸、脉搏与每一次操作，声音没有停，仿佛只要记录还在延续，人就没有离开。\n十二分钟后，她停下。“八号陈默，呼吸心跳停止。”\n控制棒让他失去反抗能力，持续压制在明确警告后仍未停止。这不是一次无法预见的失手，而是一个人在知道死亡风险后仍然选择继续的动作。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    flagsOnEnter: {'ch4_first_killer_hanqi', 'ch4_active_killing_started'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '08',
        cause: '高压放电后持续压制导致窒息',
        timelineMinute: 3582,
        responsibleParticipantIds: ['04'],
        sourceItemId: 'stun_controller',
      ),
    ],
    next: 'ch4_strong_after_death',
  ),
  'ch4_strong_after_death': StoryBeat(
    id: 'ch4_strong_after_death',
    label: '保护不能抹掉杀人的主语',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '“我是在阻止他拿走所有人的门禁。”韩骐仍站在原地，控制棒已经被放进绝缘袋，“副本一旦完成，谁也不知道他会打开哪一扇柜门。”\n“那就按时间说，不要用一个目的盖住全部动作。”叶岚把记录板转向他，“陈默未经授权复制；你使用控制棒；复制中断；陈默失去反抗能力；苏弥发出医疗警告；你继续压制。”\n韩骐盯着那六行字，没有否认其中任何一行。他只是反复看第一行，像只要起点有错，终点就能不属于自己。\n“主办方公布了武器，我们通过了集中保管，陈默也作出了违规复制。”叶岚说，“这些都是原因，但没有一个原因可以替你承担最后那段时间。”',
    passageSpeakers: [
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.narration,
      Speaker.yeLan,
    ],
    next: 'ch4_hanqi_surrenders_baton',
  ),
  'ch4_hanqi_surrenders_baton': StoryBeat(
    id: 'ch4_hanqi_surrenders_baton',
    label: '他终于松手时已经没有人来抢',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'conflicted',
    text:
        '韩骐把绝缘袋推到地面中央，解下总钥匙，再退到墙边。他做完了叶岚在安保器材室就要求的全部动作，现在却没有人靠近。\n“拿走。”他说。\n叶岚让高原用绝缘钩把袋子拖过来，没有允许任何人直接进入韩骐伸手可及的位置。\n韩骐望着那段刻意空出的距离，像第一次真正看见别人眼中的自己。“我停下以后，他已经没有呼吸了。”\n“你现在停下，仍然比继续好。”苏弥说，“但停止不能倒流。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.suMi,
    ],
    next: 'ch4_chenmo_belongings',
  ),
  'ch4_chenmo_belongings': StoryBeat(
    id: 'ch4_chenmo_belongings',
    label: '未完成的副本只剩百分之九十七',
    speaker: Speaker.liXingyao,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'vertigo',
    text:
        '星遥捡起离线读取器。屏幕停在百分之九十七，缓存因中断已经自动清除，只留下陈默最后输入的文件名：PUBLIC-REVOKE。\n“他不是在给自己复制完整钥匙。”她检查残余索引后说，“目标目录只包含公共撤销凭证。方法未经授权，但用途不是打开所有柜子。”\n韩骐的呼吸顿了一下。\n这项发现没有把陈默的违规变成正确，也没有让韩骐在当时必然知道读取内容。它只是残忍地证明，如果双方再多给彼此三秒说明，最初那个必须立即阻止的威胁也许根本不是他们想象的样子。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch4_strong_group_split',
  ),
  'ch4_strong_group_split': StoryBeat(
    id: 'ch4_strong_group_split',
    label: '同一条走廊出现两条队伍',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'anxious',
    text:
        '撤离C-02时，没有人愿意让韩骐走在队伍中间。高原在前方开路，韩骐独自走最后，叶岚要求他与前一人保持四米距离。\n林澄原本负责用纸卡确认队尾，举起“前进”时手却一直发抖。\n“我来回头看。”我说。\n“不要。”她摇头，“如果连这个也交给你，我以后只会更不敢看他。”\n她每过一个转角都停下，等韩骐独自出现在视野里，再把纸卡举高。韩骐一次也没有催她。队伍仍然一起移动，却已经不再是同一群人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch4_standard_seal_notice',
  ),

  // Standard run: a weaker alliance uses preparation and the seal itself.
  'ch4_alliance_custody': StoryBeat(
    id: 'ch4_alliance_custody',
    label: '门禁被拆成两半',
    speaker: Speaker.chenMo,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'guarded',
    text:
        '陈默保管维修间的电子凭证，唐弈保管机械钥匙。两人只有同时到场才能打开工业紧固器的柜子。\n“这不是因为我信任他。”陈默说，“是因为我打不过韩骐，他也打不过。如果一个人可以抢走完整钥匙，程序就没有意义。”\n他们没有变得更强。他们只是把一道门变成必须同时控制两个人才能跨过的障碍。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch4_maintenance_room_entry',
  ),
  'ch4_maintenance_room_entry': StoryBeat(
    id: 'ch4_maintenance_room_entry',
    label: '维修间里没有适合防身的东西',
    speaker: Speaker.chenMo,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'guarded',
    text:
        'F-02维修间的墙面挂满扳手、切割片和备用导轨。地图只把工业紧固器标为高危物资，可一旦门关上，房间里几乎每件东西都能伤人。\n陈默没有先去柜子。他逐个拍下工具挂架，确认哪一个空位是早已缺失，哪一个是在索引公布后才被取走。\n“你在找韩骐有没有先来过？”唐弈问。\n“我在找任何人有没有先来过。”陈默说，“如果只盯着最能打的那一个，我们会看不见更耐心的人。”\n他说得公正，视线却仍在听见走廊脚步时第一时间转向门锁。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch4_two_key_opening',
  ),
  'ch4_two_key_opening': StoryBeat(
    id: 'ch4_two_key_opening',
    label: '两把钥匙没有创造两份信任',
    speaker: Speaker.tangYi,
    scene: SceneKey.maintenanceRoom,
    text:
        '唐弈先插入机械钥匙，陈默的电子凭证必须在五秒内完成确认。第一次配合时，唐弈故意慢了半拍，柜锁自动复位。\n“你在测试我会不会先把凭证贴上去。”陈默说。\n“你也在等我先转钥匙。”唐弈笑了笑，“这说明制度有效。我们都不能单独开门。”\n“也说明只要你拒绝配合，我就什么都做不了。”\n两人第二次同时动作，柜门终于弹开。相互制约让背叛变难，也让他们开始计算谁更需要对方先履行承诺。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.tangYi,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch4_driver_weight',
  ),
  'ch4_driver_weight': StoryBeat(
    id: 'ch4_driver_weight',
    label: '十二公斤的防御计划',
    speaker: Speaker.chenMo,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'desperate',
    text:
        '工业紧固器连同电池重十二公斤。陈默双手把它移到工作台时，手臂已经明显发抖；韩骐若在场，大概可以单手提起。\n“这东西不会让你打赢他。”我说。\n“我没想和他打。”陈默检查远程触发片，“力量只在接触范围内有用。门、距离和准备时间才是我的体力。”\n他把一枚锚钉压进弹仓，动作熟练得不像第一次读说明书。\n“你以前用过？”\n“做数据中心机柜固定时见过。”他顿了顿，“我以前从没想过它能把人关在哪里。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.chenMo,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.chenMo,
    ],
    next: 'ch4_chenmo_fear_admission',
  ),
  'ch4_chenmo_fear_admission': StoryBeat(
    id: 'ch4_chenmo_fear_admission',
    label: '他承认自己不是在设计公平',
    speaker: Speaker.chenMo,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'desperate',
    text:
        '陈默忽然问我，韩骐拿到控制棒后会先找谁。\n“也许先保护药品。”我说。\n“你也不敢说他不会找我。”\n他把远程触发片攥在掌心。“我知道分持门禁听起来像公平。其实不是。我只是在设计一个他不能一秒结束谈判的地方。”\n“让谈判继续，和让对方永远出不来，不是同一件事。”\n“我知道。”陈默看向墙上的封锁地图，“可门一旦打开，我还能决定的时间可能只有那一秒。”\n恐惧没有让他的推理失效，却把所有方案都推向不可撤销的方向。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.chenMo,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch4_tangyi_reframes_defense',
  ),
  'ch4_tangyi_reframes_defense': StoryBeat(
    id: 'ch4_tangyi_reframes_defense',
    label: '唐弈把恐惧改写成先手',
    speaker: Speaker.tangYi,
    scene: SceneKey.maintenanceRoom,
    text:
        '唐弈一直等到陈默说完，才把机械钥匙从锁孔里拔出。\n“你总想设计一条谁都能撤回的路。”他说，“可韩骐只需要赢一次，你需要每次都不输。”\n“所以呢？”\n“别把门当警告。警告会让他下次绕开。”唐弈看了一眼尚未击发的锚钉，“要么不用；要用，就让第一次也是最后一次。”\n陈默没有回答，也没有把锚钉退出弹仓。两人的联盟从这一刻不再只是互相制约：一个人提供方法，另一个人开始替方法消除道德上的回头路。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.chenMo,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch4_alliance_private_terms',
  ),
  'ch4_alliance_private_terms': StoryBeat(
    id: 'ch4_alliance_private_terms',
    label: '公开分配后的私下协议',
    speaker: Speaker.tangYi,
    scene: SceneKey.maintenanceRoom,
    text:
        '前往维修间途中，唐弈告诉陈默，韩骐迟早会尝试把01与安保门禁同时纳入保管。\n“他不需要杀你才能赢。”唐弈说，“只要让你永远接触不到维护口，你的技术就不再是筹码。所以你要留下一个他无法靠力量直接拿走的出口。”\n这句话没有提到杀人，却已经将韩骐写成了必然会来的敌人。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch4_alliance_driver',
  ),
  'ch4_alliance_driver': StoryBeat(
    id: 'ch4_alliance_driver',
    label: '工业紧固器的另一种用法',
    speaker: Speaker.chenMo,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'desperate',
    text:
        '紧固器原本用于将导轨锚钉打入混凝土。陈默没有将它带回C-02，而是在医疗区前室的隔离门轨道旁留下一枚尚未击发的锚钉。\n“如果有人强行通过第二道门，锚钉可以把导轨卡在半闭位置。”他向唐弈解释，“里面的人无法追出来，外面的人也无法单独进去。”\n他说的是防御距离。他没有说，如果永久封锁在此时开始，卡死的门会把哪一侧变成陷阱。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch4_hanqi_moves_for_01',
  ),
  'ch4_hanqi_moves_for_01': StoryBeat(
    id: 'ch4_hanqi_moves_for_01',
    label: '韩骐来到隔离门前',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'protective',
    text:
        '当C-02的倒计时跳到十五分钟，韩骐来到前室，要求取得01门禁以撤出病床和药品。他没有携带武器，却拒绝让陈默继续保留维修凭证。\n“把凭证放进传递槽，你可以在外面看着我完成转移。”他说，“我不需要进入你的系统，只需要你不再控制这道门。”\n对陈默而言，“暂时交出”与“以后再也无法拿回”之间，已经没有可信的边界。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch4_alliance_intervention',
  ),
  'ch4_alliance_intervention': StoryBeat(
    id: 'ch4_alliance_intervention',
    label: '是否把门轨旁的锚钉告诉他',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text: '我已经看见门轨旁的锚钉，也知道C-02的封锁倒计正在继续。把陷阱告诉韩骐可能让他立即强行夺门；保持沉默则会让我成为一名知情者。',
    next: null,
    choices: [
      StoryChoice(
        label: '告诉韩骐门轨已被改造',
        caption: '公开陷阱，要求三方同时退离门口',
        next: 'ch4_alliance_warning',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch4_warned_hanqi'),
      ),
      StoryChoice(
        label: '只要求陈默交出凭证',
        caption: '优先结束对峙，不公开已经发现的装置',
        next: 'ch4_alliance_order',
        effect: ChoiceEffect(logic: 1, flag: 'ch4_ordered_handover'),
      ),
      StoryChoice(
        label: '保持沉默并让病床先通过',
        caption: '把救援通道放在权限争夺之前',
        next: 'ch4_alliance_silence',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch4_silent_about_trap'),
      ),
    ],
  ),
  'ch4_alliance_warning': StoryBeat(
    id: 'ch4_alliance_warning',
    label: '警告没有让轨道恢复',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '“门轨旁有一枚待击发锚钉。”我抬高双手，让三个人都看见我没有碰门禁，“韩骐退到黄线外，陈默解除装置，唐弈把电源放下。三件事同时做。”\n“装置是我装的。”陈默没有再否认，“可他还站在内门边。我蹲下拆锚钉时，他一步就能拿走凭证。”\n“你预先布置了一道能把人锁进封锁区的门。”韩骐说，“从这一刻起，你没有资格继续控制它。”\n信息被公开了，但两人都将它当成对方必须先退让的新证据。',
    passageSpeakers: [
      Speaker.shenYan,
      Speaker.chenMo,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch4_alliance_door_trigger',
  ),
  'ch4_alliance_order': StoryBeat(
    id: 'ch4_alliance_order',
    label: '交出凭证的要求被听见',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'desperate',
    text:
        '“陈默，先把凭证放进传递槽。”我说，“韩骐不进内门，由叶岚保管。”\n“叶岚拿不走他手里的东西。”陈默说，“只要我把凭证放下，他就没有理由再与我谈条件。”\n他不是没有听懂妥协。他是已经不相信交出唯一筹码后，程序还会保护他。',
    passageSpeakers: [Speaker.shenYan, Speaker.chenMo, Speaker.narration],
    next: 'ch4_alliance_door_trigger',
  ),
  'ch4_alliance_silence': StoryBeat(
    id: 'ch4_alliance_silence',
    label: '沉默让病床先通过',
    speaker: Speaker.narration,
    scene: SceneKey.medicalIsolation,
    text:
        '我没有公开锚钉，只要求所有人向两侧让开，先把星遥所在的移动病床推过前室。\n病床通过时，韩骐与陈默分站两侧，谁都没有伸手。当最后一只轮子越过安全线，唐弈才向陈默轻轻点头。\n我保住了救援通道，也因此成为知道陷阱却没有立即公开的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch4_alliance_door_trigger',
  ),
  'ch4_alliance_door_trigger': StoryBeat(
    id: 'ch4_alliance_door_trigger',
    label: '锚钉打进了门轨',
    speaker: Speaker.narration,
    scene: SceneKey.medicalIsolation,
    text:
        '韩骐越过第一道门，伸手去抓陈默胸前的凭证袋。陈默没有与他拉扯，而是按下紧固器的远程触发片。\n锚钉击穿薄钢盖，将隔离门导轨固定在半闭位置。韩骐被留在病房一侧，陈默和唐弈退到走廊一侧。\n这个装置精确利用了空间、时间和韩骐必须靠近才能抢夺的身体优势。弱者没有在力量上赢过他，只是提前决定了他发力时会站在哪里。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch4_alliance_release_window',
  ),
  'ch4_alliance_release_window': StoryBeat(
    id: 'ch4_alliance_release_window',
    label: '他们有时间把门打开',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'injured',
    text:
        '高原检查门轨图纸后确认，只要将紧固器调到反转模式，三分钟内就能拔出锚钉。C-02的封锁倒计还剩八分钟。\n“把工具接回去，门能开。”他说，“不要再讨论谁先交出什么，先把人弄出来。”\n陈默拿着反转控制片，唐弈则站在紧固器电源旁。两人都听见了解锁方法和剩余时间。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch4_alliance_refusal',
  ),
  'ch4_alliance_refusal': StoryBeat(
    id: 'ch4_alliance_refusal',
    label: '他们把开门变成了条件',
    speaker: Speaker.tangYi,
    scene: SceneKey.medicalIsolation,
    text:
        '唐弈要求韩骐先将所有门禁权限转交给公共组，并书面放弃01终端持有要求，才会接通反转电源。\n“你现在没有讨价还价的位置。”他隔着半闭门说，“我们放你出来，你就会继续拿走所有人的选择。”\n救人被写成了一笔交易，而倒计时让拒绝交易的代价由被困者独自支付。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch4_alliance_last_request',
  ),
  'ch4_alliance_last_request': StoryBeat(
    id: 'ch4_alliance_last_request',
    label: '他最后一次要求开门',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'conflicted',
    text:
        '韩骐把所有可转交门禁都发到公共组，却拒绝删除自己对01的持有条款记录。那不是他能删除的条款，也不是一句承诺就会消失的冲突。\n“门禁给你们了。”他说，“先开门。我出去以后不碰陈默，不碰唐弈，由叶岚记录。”\n这一次，他给出了可执行的退让。陈默的手指停在反转控制片上，没有按下去。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch4_alliance_death',
  ),
  'ch4_alliance_death': StoryBeat(
    id: 'ch4_alliance_death',
    label: '被预谋固定在封锁线内',
    speaker: Speaker.administrator,
    scene: SceneKey.medicalIsolation,
    timelineMinute: 3600,
    text:
        '倒计归零时，隔离门没有因锚钉停止封锁。两侧液压杆同时加压，变形的门框连同锚钉一起被压进墙体。\n“C-02永久封锁完成。”\n韩骐在最后时刻仍站在观察窗后。他没有死于比自己更强的人，而是死于两名无法正面阻止他的人提前安装的门轨、分持的权限，以及在仍有救援时间时不再开门的决定。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch4_first_killer_alliance', 'ch4_active_killing_started'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '04',
        cause: '工业紧固器卡死隔离门后被永久封锁',
        timelineMinute: 3600,
        responsibleParticipantIds: ['08', '06'],
        sourceItemId: 'industrial_driver',
      ),
    ],
    next: 'ch4_alliance_after_death',
  ),
  'ch4_alliance_after_death': StoryBeat(
    id: 'ch4_alliance_after_death',
    label: '反杀仍然是杀人',
    speaker: Speaker.yeLan,
    scene: SceneKey.corridor,
    portraitMood: 'intervening',
    text:
        '“开门以后，他迟早会拿走陈默的权限，也会继续追索01。”唐弈把反转电源留在脚边，“我们只是没有把威胁重新放回走廊。”\n“这个风险是真的。”叶岚没有替韩骐否认，“门在倒计结束前可以打开，也是真的。你们听见了高原给出的方法，收到韩骐转交的门禁，仍然决定不接电。”\n陈默没有反驳。他的拇指还压在已经失效的反转片上，那里没有血，却留下了一道被汗泡白的圆印。\n“你们不是因为没有办法而活下来。”叶岚说，“可以叫反击，可以叫自保，但不能叫系统自己杀了他。”',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.narration,
      Speaker.yeLan,
    ],
    next: 'ch4_chenmo_after_lock',
  ),
  'ch4_chenmo_after_lock': StoryBeat(
    id: 'ch4_chenmo_after_lock',
    label: '控制片失效以后他还按了两次',
    speaker: Speaker.chenMo,
    scene: SceneKey.corridor,
    portraitMood: 'desperate',
    text:
        '封锁完成后，陈默又按了两次反转控制片。指示灯已经熄灭，紧固器电源也被墙体切断，任何指令都不可能再抵达门轨。\n“刚才它有延迟。”他说，“也许第一次没收到。”\n没有人提醒他，最后一次可逆时间早已过去。\n他把控制片拆开，检查电池、触点和焊点，仿佛只要找到一处硬件故障，就能证明自己不是在清醒状态下选择了不接电。拆到最后，里面所有零件都完好。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch4_tangyi_washes_hands',
  ),
  'ch4_tangyi_washes_hands': StoryBeat(
    id: 'ch4_tangyi_washes_hands',
    label: '唐弈洗掉了紧固器留下的黑灰',
    speaker: Speaker.tangYi,
    scene: SceneKey.corridor,
    text:
        '唐弈在医疗区洗手池前反复搓洗指缝。紧固器电源线留下的黑灰很快就被水冲掉，他却仍没有关掉水龙头。\n“你后悔吗？”叶岚问。\n“后悔没有意义。”\n“我问的不是意义。”\n唐弈抬头看着镜子里的自己。“开门，他会继续赢。不开门，我们至少活过今天。我只是讨厌答案真的这么有效。”\n他没有崩溃，也没有为自己辩称无辜。那份近乎清醒的厌恶，比一句冲动更清楚地说明他知道自己做了什么。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch4_alliance_group_split',
  ),
  'ch4_alliance_group_split': StoryBeat(
    id: 'ch4_alliance_group_split',
    label: '弱者联盟不再等于安全一侧',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'shaken',
    text:
        '苏弥要求陈默和唐弈暂时分开行动，也要求剩余的人不得以报复为由私自拘禁他们。\n“他们刚杀了韩骐。”周叙说，“你还担心我们伤害他们？”\n“正因为已经有人用‘他以后会伤害我’解释一次死亡，我不允许同一句话立刻开始下一轮。”苏弥关掉水龙头，“观察、限制接触高危物资、所有行动双人记录。不是围殴，也不是放任。”\n陈默第一次主动交出电子凭证。可当高原伸手去接时，仍然犹豫了一瞬。能够杀死最强者的弱者，已经不再被任何人看作单纯需要保护的一方。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.zhouXu,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch4_standard_postseal',
  ),

  // Standard run: procedure turns a rescue decision into collective killing.
  'ch4_majority_custody': StoryBeat(
    id: 'ch4_majority_custody',
    label: '没有人预先拿走完整钥匙',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '机械钥匙被放进观察窗下的透明盒，电子门禁则需要现场超过半数的存活终端同时确认。\n“任何人都不能单独取用。”叶岚说，“但请把另一面也写下：任何人在紧急情况下也不能单独取用。”\n没有人持有武器，屋里的紧张暂时下降。我们把“没有人可以独自伤害别人”与“没有人可以独自开始救人”写进了同一个按钮。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch4_gaoyuan_declines',
  ),
  'ch4_gaoyuan_declines': StoryBeat(
    id: 'ch4_gaoyuan_declines',
    label: '高原的呼吸开始变浅',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'injured',
    text:
        '大多数人准备撤离时，高原忽然坐到前室地上。他的伤腿在连续行动后肿胀加重，呼吸频率也明显加快。\n“可能是疼痛和脱水。”他试图扶墙起身，“给我五分钟，不要因为我一个人把所有器材都搬回来。”\n苏弥却发现他的指尖发凉，伤腿夹板边缘有新的渗血。他需要病床转运和氧气，不能只在地上等待。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch4_contamination_doubt',
  ),
  'ch4_contamination_doubt': StoryBeat(
    id: 'ch4_contamination_doubt',
    label: '没有被排除的另一种风险',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'guarded',
    text:
        '陈默指出，星遥的昏厥虽然不是镇静剂造成，但C-02的公共频道已被定向污染，还无法确认高原的异常是否与另一组输出有关。\n“如果现在把他带回集合厅，而他身上的PDA仍在发送干扰，我们会把未知暴露源一起带回去。”\n这个风险不是虚构的：星遥的耳机确实收到了定向脉冲。但它正被用来支持另一个尚未被证明的推论：高原本人也是暴露源。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch4_seal_countdown',
  ),
  'ch4_seal_countdown': StoryBeat(
    id: 'ch4_seal_countdown',
    label: '八分钟的封锁通知',
    speaker: Speaker.administrator,
    scene: SceneKey.medicalIsolation,
    timelineMinute: 3592,
    text:
        '扬声器在公共频道关闭的情况下独立亮起。\n“C-02永久封锁将于八分钟后执行。未确认的医疗暴露对象建议保留在隔离区。高危物资取用权限已开放。”\n“建议”不是强制规则。我们可以使用多数确认打开氧气柜，将高原转移出去；也可以在无法排除暴露风险时，让他留在封锁区。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch4_majority_debate',
  ),
  'ch4_majority_debate': StoryBeat(
    id: 'ch4_majority_debate',
    label: '每一票都有可以被理解的理由',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '苏弥主张立即转移：高原的循环状态正在恶化，而PDA可以单独封存。韩骐支持她，认为至少可以用人力将他抬出去。\n陈默主张留观：公共频道污染机制尚未解除，且转移需要打开氧气柜和两道门，可能将暴露扩散到主走廊。唐弈支持留观，认为不该用全体人员的未知风险为一名伤员买单。\n叶岚和林澄要求先拆除PDA再转移，却被倒计时逼着在完成检查前投票。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch4_vote_interest_screen',
  ),
  'ch4_vote_interest_screen': StoryBeat(
    id: 'ch4_vote_interest_screen',
    label: '投票前先公开谁会从结果获利',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '叶岚要求所有投票人先公开与两种结果的直接利益。苏弥需要更多人存活；韩骐希望维持可行动人员；陈默担心暴露扩散；唐弈的资源条款会因需要救治的人减少而更容易完成。\n“有利益不等于失去投票权。”叶岚说，“但每个人必须让别人知道，他说的公共安全里混着哪一部分自己的生存条件。”\n“那01呢？”周叙问。\n所有人看向我。我的终局条款仍有空白字段，我甚至无法完整说明自己会从哪种结果获利。最关键的一票，恰好来自利益最不透明的人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.zhouXu,
      Speaker.narration,
    ],
    next: 'ch4_vote_hanqi_position',
  ),
  'ch4_vote_hanqi_position': StoryBeat(
    id: 'ch4_vote_hanqi_position',
    label: '韩骐不愿把谨慎用在正在恶化的人身上',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'protective',
    text:
        '“先把人抬出去，PDA留在传递槽。”韩骐指着高原逐渐变慢的呼吸，“如果终端有问题，终端隔离；如果人有问题，走廊里还有六个人能控制他。”\n陈默问：“如果干扰不靠终端呢？”\n“那也要等它发生。不能因为可能发生的伤害，先执行一个正在发生的死亡。”\n“你拿自己能压住他当作全体人的保险。”陈默说，“如果先倒下的是你呢？”\n韩骐没有回答。他的方案并非没有程序，只是程序的最后一道防线始终是他自己的身体。',
    passageSpeakers: [
      Speaker.hanQi,
      Speaker.chenMo,
      Speaker.hanQi,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch4_vote_sumi_position',
  ),
  'ch4_vote_sumi_position': StoryBeat(
    id: 'ch4_vote_sumi_position',
    label: '苏弥把最坏结果写给所有人看',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'concerned',
    text:
        '苏弥没有保证转移一定安全。她在玻璃上写下最坏情况：未知干扰进入主走廊，增加一到多人短暂失能；另一侧则是高原在缺氧和循环恶化中死亡。\n“概率我给不出来。”她说，“严重程度可以。前者有监测、断开终端和二次隔离的补救；封锁完成后，后者没有。”\n唐弈问：“如果前者让所有人都失去行动能力呢？”\n“那是你提出的情形，你也要给出它成立的依据。”苏弥的声音第一次带上明显怒意，“不能只因为一个想象足够可怕，就让它自动大过眼前这个人。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.tangYi,
      Speaker.suMi,
    ],
    next: 'ch4_vote_chenmo_position',
  ),
  'ch4_vote_chenmo_position': StoryBeat(
    id: 'ch4_vote_chenmo_position',
    label: '陈默要求证明撤离仍可撤回',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'guarded',
    text:
        '陈默提出一个折中：先将高原移到前室，拆除PDA音频模块，再决定是否打开外门。\n“前室也会永久封锁。”高原隔着观察窗说。\n“至少可以增加检查时间。”\n“增加给谁？”高原抬起手腕，指尖已经发青，“你们在门外多得到三分钟，我在里面就少三分钟。”\n陈默移开视线。他的程序确实保留了集体撤回转移的机会，却没有给被转移的人保留同样的撤回权。所谓中间位置，仍然要由某个人的身体来支付时间。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.chenMo,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch4_gaoyuan_asks_to_speak',
  ),
  'ch4_gaoyuan_asks_to_speak': StoryBeat(
    id: 'ch4_gaoyuan_asks_to_speak',
    label: '被投票的人要求保留一句话',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'injured',
    text:
        '高原按下床边对讲器，第一次没有讨论设备。\n“我知道把我带出去可能有风险。”他说，“如果你们找到我在发送干扰的证据，就把我单独关进旧医务室，我接受。可现在你们是在用星遥身上发生过的事，证明同样的事可能从我身上发生。”\n他停下来换了两次气。\n“别把我算成一票。我现在连终端都按不稳。但也别在表决时说‘九号同意留观’。我没有同意。”\n系统把他的终端标成无法提交，却没有提供“被决定者陈述”这一栏。叶岚只能把这段话录在计票画面旁边。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch4_majority_vote',
  ),
  'ch4_majority_vote': StoryBeat(
    id: 'ch4_majority_vote',
    label: '我的终端也必须选一边',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '当前确认为四票转移、四票留观。高原因身体状态无法提交，我的01成为决定性一票。系统没有要求我判断谁是好人，只要求我在不完整的证据与不可逆的封锁之间决定，哪一种风险由谁承担。',
    next: null,
    choices: [
      StoryChoice(
        label: '投票立即转移高原',
        caption: '已知的循环恶化优先于未证实的扩散风险',
        next: 'ch4_majority_rescue_vote',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch4_voted_rescue'),
      ),
      StoryChoice(
        label: '投票将高原留在隔离区',
        caption: '在没有排除PDA暴露前不打开主走廊通道',
        next: 'ch4_majority_delay_vote',
        effect: ChoiceEffect(
          logic: 1,
          cooperation: -1,
          flag: 'ch4_voted_delay',
        ),
      ),
    ],
  ),
  'ch4_majority_rescue_vote': StoryBeat(
    id: 'ch4_majority_rescue_vote',
    label: '我投了转移，表决却没有结束',
    speaker: Speaker.administrator,
    scene: SceneKey.medicalIsolation,
    text:
        '我提交转移，计票短暂变成五比四。然而系统在执行前弹出“高危医疗转移需要两名无利益见证人”的附加确认。\n“03号的存活人数条款构成直接利益，04号持有安保优先权。两人均不具备见证资格。”系统逐项熄灭他们的确认框。\n“我不签。”唐弈说，“五票可以决定开门，不能决定让我为一个我反对的转移负责。”\n陈默把自己的确认框也切成灰色。“如果PDA暴露还没排除，打开主走廊就是拿其他人作赌注。”\n“多数决已经通过。”我说。\n“执行条件未满足。”系统回答。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.tangYi,
      Speaker.chenMo,
      Speaker.shenYan,
      Speaker.administrator,
    ],
    next: 'ch4_majority_last_contact_rescue',
  ),
  'ch4_majority_delay_vote': StoryBeat(
    id: 'ch4_majority_delay_vote',
    label: '五比四的留观决定',
    speaker: Speaker.narration,
    scene: SceneKey.medicalIsolation,
    text:
        '我提交留观。透明钥匙盒立刻锁死，氧气柜和病床制动器不再接受个人请求。\n“重新表决。”苏弥将高原刚刚的血压和意识评分推上公共屏，“他的状态比一分钟前更差，原判断已经过期。”\n“医疗隔离决定已执行。”系统回答，“需要两名原支持者主动撤回，才可重新开放请求。”\n九个终端的确认框同时亮起。没有人立即动。我没有亲手关门，却用自己的终端让门失去了被一个人打开的可能。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch4_majority_last_contact_delay',
  ),
  'ch4_majority_last_contact_rescue': StoryBeat(
    id: 'ch4_majority_last_contact_rescue',
    label: '支持救援不等于救援已经发生',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'injured',
    text:
        '我试图以01的紧急门禁越过见证条件，系统只重复显示“执行条件未满足”。多数表决保护了所有人不被一次个人冲动强制改变，也保护了少数人不必为不赞成的救援提供执行条件。\n高原隔着观察窗向我举起手，手掌只抬到一半。\n“别说你们已经选了救我。”他的声音通过门边对讲器断断续续，“门还在这里。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.gaoYuan],
    next: 'ch4_majority_death_rescue',
  ),
  'ch4_majority_last_contact_delay': StoryBeat(
    id: 'ch4_majority_last_contact_delay',
    label: '被表决的人仍然在说话',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'injured',
    text:
        '高原隔着观察窗看见了五比四的数字。他没有说自己没有风险，也没有说众人必须为他承担一切。\n“把我的PDA从传递槽送出去，可以单独封存。”他说，“再把氧气瓶从外侧接入，不用打开内门。还有时间。”\n这个方案需要打开已被多数决锁死的氧气柜。两名支持留观的人只要同时撤回，门就会重新接受请求。倒计还有九十秒，没有人按下撤回。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch4_majority_death_delay',
  ),
  'ch4_majority_death_rescue': StoryBeat(
    id: 'ch4_majority_death_rescue',
    label: '通过了的救援没有被执行',
    speaker: Speaker.administrator,
    scene: SceneKey.medicalIsolation,
    timelineMinute: 3600,
    text:
        '封锁执行前十二秒，高原失去意识。苏弥用拳头砸向观察窗，转身要去取破拆斧，但斧头所在的D-01距离这里超过五分钟。\n“C-02永久封锁完成。”\n我投了转移，却没有让转移成为一个能被执行的动作。拒绝提供见证条件的人明知门会因此保持关闭，仍然选择等待倒计结束。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch4_first_killer_majority', 'ch4_active_killing_started'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '09',
        cause: '多数转移缺少执行见证，被留在永久封锁区',
        timelineMinute: 3600,
        responsibleParticipantIds: ['06', '08'],
      ),
    ],
    next: 'ch4_majority_after_death',
  ),
  'ch4_majority_death_delay': StoryBeat(
    id: 'ch4_majority_death_delay',
    label: '五票不会让死亡变成无主语动作',
    speaker: Speaker.administrator,
    scene: SceneKey.medicalIsolation,
    timelineMinute: 3600,
    text:
        '封锁执行前十二秒，高原失去意识。苏弥请求最后一次撤回，系统在屏幕上列出五名支持留观者，没有人在倒计结束前同时完成撤回。\n“C-02永久封锁完成。”\n我没有亲手使他受伤，却在明知当前状态可能致死、明知还存在一个可执行的转移方案时，用01使留观成为多数决。系统执行了封锁，却没有替五张选票承担决定。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch4_first_killer_majority', 'ch4_active_killing_started'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '09',
        cause: '多数表决拒绝转移，被留在永久封锁区',
        timelineMinute: 3600,
        responsibleParticipantIds: ['01', '06', '08', '11'],
      ),
    ],
    next: 'ch4_majority_after_death',
  ),
  'ch4_majority_after_death': StoryBeat(
    id: 'ch4_majority_after_death',
    label: '多数人不能共同稀释责任',
    speaker: Speaker.yeLan,
    scene: SceneKey.corridor,
    portraitMood: 'intervening',
    text:
        '“少我这一票，结果也未必会变。”唐弈说。\n“我只是拒绝见证，不是投他去死。”陈默把终端扣在桌上，“执行条件是系统后来加出来的。”\n叶岚将票数、撤回条件和高原最后提出的氧气方案并列，没有把所有责任涂成同一种颜色。\n“多数决的意义是让一个决定可以被共同执行，不是让责任被除以投票人数。”她说，“支持留观者知道封锁的结果，拒绝见证者知道救援会因他的拒绝而停止。每个人承担的不一样，但不是零。”',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.chenMo,
      Speaker.narration,
      Speaker.yeLan,
    ],
    next: 'ch4_vote_log_signatures',
  ),
  'ch4_vote_log_signatures': StoryBeat(
    id: 'ch4_vote_log_signatures',
    label: '系统要求确认结果，没有人愿意先签名',
    speaker: Speaker.administrator,
    scene: SceneKey.corridor,
    text:
        '封锁后，系统自动生成“多数程序已正确执行”的报告，要求所有参与者确认。报告里没有高原的最后陈述，没有不断恶化的体征，也没有两名见证人拒绝执行通过方案的时间。\n“请确认程序记录完整。”\n唐弈最先把终端锁屏。陈默说系统只问记录是否完整，不是在问谁该负责。\n“恰好相反。”叶岚把缺失字段逐项写进异议栏，“一份只保留票数的记录，会让以后的人以为死亡是在五比四出现的瞬间自动发生。门为什么没开，仍然有动作和名字。”\n最终没有一人按下无异议确认。高原已经死去，却第一次迫使所有人的终端共同留下一个未完成状态。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch4_majority_group_split',
  ),
  'ch4_majority_group_split': StoryBeat(
    id: 'ch4_majority_group_split',
    label: '数字结束后立场仍留在每个人身上',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'shaken',
    text:
        '回集合厅的路上，支持转移的人走在苏弥身边，支持留观的人彼此也没有靠近。投出同一选项并没有让他们成为同伴，只让每个人知道了别人愿意把哪种风险交给谁。\n“下一次还投票吗？”林澄问。\n“要。”叶岚说，“但不能只投结论。执行人、撤回条件、倒计时里谁有权改变决定，都必须一起写。”\n苏弥抱着高原未用完的急救包，没有回头。“还要写被投票的人怎么说。否则我们只是在给活着的人设计更整齐的表格。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.yeLan,
      Speaker.suMi,
    ],
    next: 'ch4_standard_postseal',
  ),

  // Audit run: the forecast can be used, ignored, or mishandled.
  'ch4_audit_projection': StoryBeat(
    id: 'ch4_audit_projection',
    label: '三种死亡形状早于我们的争论',
    speaker: Speaker.liXingyao,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'vertigo',
    text:
        '星遥将第二日恢复的高危目录与刚公布的索引叠在一起。六件物资的初始封条编号完全一致，但审计缓存里还有三列没有公开的模拟结果。\n第一列写着“安保保管：技术审计者失效”；第二列是“拆分门禁：安保持有者封锁”；第三列是“多数执行：伤员留置”。\n“这些记录生成在我们今天讨论之前。”她说，“ZERO没有预知我们会选哪一个，它只提前准备了三种都能产生死亡的制度形状。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.liXingyao],
    next: 'ch4_audit_forecast_limits',
  ),
  'ch4_audit_forecast_limits': StoryBeat(
    id: 'ch4_audit_forecast_limits',
    label: '预演省略了所有人的犹豫',
    speaker: Speaker.liXingyao,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'vertigo',
    text:
        '星遥继续展开模拟详情。三条路径都只有物资、权限和最终失效对象，没有记录争吵、警告、退让或任何一次本可以停止的时刻。\n“它把人压缩成了条件。”她说，“韩骐等于力量，陈默等于门禁，高原等于需要转移的伤员。只要条件相遇，死亡就像计算结果一样出现。”\n“主办方就是这么看我们的。”我说。\n“那我们不能照着它的眼睛看。”她把三条结果缩到屏幕角落，“预演只能告诉我们哪里要设置刹车，不能告诉我们谁天生就是会撞上去的人。”\n她说完后闭眼缓了几秒。我扶住她肩膀，她没有像早晨那样躲开。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch4_audit_verify_source',
  ),
  'ch4_audit_verify_source': StoryBeat(
    id: 'ch4_audit_verify_source',
    label: '预演不是让人盲信的神谕',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '“三行预演不能让我们提前给三个人定罪。”叶岚挡住了韩骐伸向公共屏的手，“先验证封条编号、生成时间和当前柜体状态。预测必须与现实交叉，不能反过来命令现实服从它。”\n我们调出医疗区摄像回放，确认镇静剂在高频干扰出现前已被移出；旧门禁记录则显示其余五件物资仍在封存位置。\n“表头与现实匹配，所以这份记录值得公开审查。”叶岚说，“它证明三种制度都存在风险，不证明站在制度里的人已经实施了风险。”',
    passageSpeakers: [Speaker.yeLan, Speaker.narration, Speaker.yeLan],
    next: 'ch4_audit_pair_assignments',
  ),
  'ch4_audit_pair_assignments': StoryBeat(
    id: 'ch4_audit_pair_assignments',
    label: '核验人不得靠近自己最想控制的物件',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '叶岚没有按体力或专业分配核验，而是先列出利益冲突：韩骐不靠近控制棒，苏弥不单独核对镇静剂，陈默不接触工业紧固器，我不持有门禁强制控制器。\n“让不懂的人去看，能看出什么？”韩骐问。\n“专业人员通过固定摄像指导，现场的人只读取封条，不开柜。”叶岚回答，“你能指出检查方法，但不能同时成为方法、执行者和最终保管人。”\n苏弥把医疗柜封条格式写给林澄，陈默则画出紧固器柜的外部触点位置。每个人仍然贡献能力，却第一次不能借能力自然地取得物件。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch4_audit_decision',
  ),
  'ch4_audit_decision': StoryBeat(
    id: 'ch4_audit_decision',
    label: '如何使用一份会预演死亡的记录',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalIsolation,
    text:
        '我们可以公开预演、逐件核对封条并让所有人看见三种制度如何被利用；也可以担心预演刺激潜在行为人，只由少数人秘密转移物资。新证据不会自动生成新制度，它只让我们知道旧制度会把人带到哪里。',
    next: null,
    choices: [
      StoryChoice(
        label: '公开预演并原地核验六件封条',
        caption: '不移动物资，让每个人都能重复验证风险',
        next: 'ch4_audit_public_seal',
        effect: ChoiceEffect(
          logic: 2,
          cooperation: 2,
          flag: 'ch4_audit_chain_blocked',
        ),
      ),
      StoryChoice(
        label: '不公开预演，按旧制度分配钥匙',
        caption: '避免告诉潜在行为人系统预期的手段',
        next: 'ch4_key_custody_choice',
        effect: ChoiceEffect(cooperation: -1, flag: 'ch4_audit_withheld'),
      ),
    ],
  ),
  'ch4_audit_public_seal': StoryBeat(
    id: 'ch4_audit_public_seal',
    label: '不把武器搬到另一个人身边',
    speaker: Speaker.yeLan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'intervening',
    text:
        '我们将三列预演与封条核验步骤同时投到公共屏。每个柜子由距离最近的两人在不开门的情况下读取外部封条，第三人在集合厅交叉核对。\n送风口外侧的空导管反射出一小段玻璃轮廓。林澄从固定摄像下确认位置，所有人先记录发现过程，没有让苏弥独自伸手取药。\n其余五件物资的封条均与审计目录一致。没有人因“为了更好保管”而先拿到它们。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    highRiskItemsResealedOnEnter: {
      'sedative_case',
      'rescue_axe',
      'stun_controller',
      'industrial_driver',
      'corrosive_cleaner',
      'door_override',
    },
    next: 'ch4_audit_sedative_recovery',
  ),
  'ch4_audit_sedative_recovery': StoryBeat(
    id: 'ch4_audit_sedative_recovery',
    label: '失踪的药被当众放回原位',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'relieved',
    text:
        '林澄用长柄夹从空导管里取出镇静剂，先把安瓿举到固定摄像前，再从传递槽送给苏弥。苏弥没有直接接触，而是让周叙隔着透明袋核对批号和封口。\n“是原来缺失的那一支。”周叙说完，像不习惯自己会成为替医生作证的人。\n苏弥重新盘点药柜，把八十分钟的个人空白、锁舌试探记录和药物发现位置一并留在报告里。\n“找回来不等于我的嫌疑从未存在。”她说，“只意味着现在没有人能用它伤害下一个人。”\n她的肩膀终于放松一点，却仍没有删除针对自己的审计记录。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.zhouXu,
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch4_audit_weapon_distance',
  ),
  'ch4_audit_weapon_distance': StoryBeat(
    id: 'ch4_audit_weapon_distance',
    label: '封条之外还要封存到达路线',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'inspecting',
    text:
        '高原提出，仅仅确认柜门关闭仍然不够。六个位置已经公开，任何人都能在下一次争执中重新发起赛跑。\n我们把高危柜所在区域改成双人进入，门口设置机械签到板；若一人独自刷卡，区域门只记录请求，不实际开启。01也不能越过这层限制。\n“这会让紧急取用变慢。”韩骐说。\n“是。”高原回答，“所以破拆、医疗和安保各留一套不具致命能力的普通工具在公共区。我们牺牲最快的武器，换取一条所有人都看得见的到达路线。”\n制度并没有消灭物件的危险，只把最容易被力量差吞掉的两分四十秒拉长到足够让别人介入。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch4_audit_hanqi_reacts',
  ),
  'ch4_audit_hanqi_reacts': StoryBeat(
    id: 'ch4_audit_hanqi_reacts',
    label: '预演里的杀人者仍然是一个未行动的人',
    speaker: Speaker.hanQi,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'conflicted',
    text:
        '韩骐在公共屏前看了很久。第一列的“技术审计者失效”没有写死因，却与他刚才提出的集中保管完全匹配。\n“你们要因为一台机器觉得我可能杀人，就先把我当成凶手？”他问。\n“不。”叶岚回答，“所以我们没有夺走你的PDA，也没有限制你离开。我们只是不再把你与一件可以放电的工具放进同一个无法撤销的位置。”',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.yeLan],
    next: 'ch4_audit_chenmo_reacts',
  ),
  'ch4_audit_chenmo_reacts': StoryBeat(
    id: 'ch4_audit_chenmo_reacts',
    label: '防卫计划在实施前被说出',
    speaker: Speaker.chenMo,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'guarded',
    text:
        '陈默承认，他在看见索引后第一个想到的办法，就是用工业紧固器把隔离门卡在韩骐无法直接追上的位置。\n“我没有准备杀他。”他说。\n“我相信你现在没有。”星遥说，“预演的价值不是证明你已经犯罪，而是让我们在你还能放弃这个方法时，看见它会把人送到哪里。”\n陈默交出了他已经画了一半的门轨改造图。纸上没有尸体，只有一道无法从内侧打开的门。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch4_audit_rescue_plan',
  ),
  'ch4_audit_rescue_plan': StoryBeat(
    id: 'ch4_audit_rescue_plan',
    label: '在倒计前把执行条件写完',
    speaker: Speaker.linCheng,
    scene: SceneKey.medicalIsolation,
    portraitMood: 'determined',
    text:
        '林澄将转移步骤写成六张纸卡：切断所有PDA音频输出；将病人和终端分别封存；氧气柜二人开启；病床三人接力；内门关闭后核对人数；最后由第六人带走公共记录。\n“不等有人倒下再表决。”她说，“现在就确认每一步由谁做。中途有人无法继续，就按名单换下一个，不再重新讨论要不要救。”\n我们不是在封锁前找到了一个没有风险的方案。我们只是把还有时间完成的决定，从倒计最后一分钟移到了现在。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch4_audit_seal',
  ),
  'ch4_audit_seal': StoryBeat(
    id: 'ch4_audit_seal',
    label: '隔离病房里没有被留下的人',
    speaker: Speaker.administrator,
    scene: SceneKey.corridor,
    timelineMinute: 3600,
    cgId: 'cg_audit_rescue',
    text:
        '封锁前五分钟，最后一只证物箱离开C-02。星遥的PDA音频模块被单独封存，苏弥与另一名见证人核对药品，韩骐和高原把病床抬过安全线，陈默站在门禁终端旁却没有保留单独凭证。\n“C-02永久封锁完成。”\n墙体合拢时，没有人需要在最后一秒决定是否为了自己的安全把另一个人留在里面。这没有证明我们比另一种可能性中的自己更善良；它只证明，更早到达的证据确实能改变行动条件。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch4_first_killing_prevented'},
    next: 'ch4_audit_no_death_roll_call',
  ),
  'ch4_audit_no_death_roll_call': StoryBeat(
    id: 'ch4_audit_no_death_roll_call',
    label: '这一次每个编号都有回应',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'determined',
    cgId: 'cg_audit_rescue',
    cgFrame: 1,
    text:
        '安全线外，林澄重新展开早晨的名单。她从01开始点到11，每个仍在场的编号都必须亲口回应，不能由队友代答。\n念到高原时，他躺在病床上抬不起手，只用气声说了一句“在”。\n林澄的笔尖停在纸上，最后没有画横线，而是在09旁边写下转移完成的时间。\n“为什么还要再点一次？”唐弈问。\n“因为‘没有人死’不能只看系统总数。”她把名单贴到公共记录板上，“要让每一个本来可能没有回应的人，自己留下声音。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.linCheng,
    ],
    next: 'ch4_audit_after_seal',
  ),
  'ch4_audit_after_seal': StoryBeat(
    id: 'ch4_audit_after_seal',
    label: '没有死亡也不等于冲突消失',
    speaker: Speaker.hanQi,
    scene: SceneKey.corridor,
    portraitMood: 'conflicted',
    text:
        '韩骐没有因为预演被公开就放弃对01的需求，陈默也没有突然相信韩骐会永远尊重权限边界。\n“今天没有人杀人，是因为你们提前看到了一张表。”韩骐说，“明天如果表上没有写呢？”\n这不是对新证据的否定。它指出了审计模式的真正限制：预演只能告诉我们主办方已经准备的形状，不能代替我们处理每一个没有被写下的冲突。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch4_common_aftermath',
  ),

  'ch4_standard_seal_notice': StoryBeat(
    id: 'ch4_standard_seal_notice',
    label: '死亡没有取消封锁',
    speaker: Speaker.administrator,
    scene: SceneKey.corridor,
    timelineMinute: 3600,
    text:
        '陈默的身体被移出前室后，C-02的封锁倒计仍在继续。主办方没有因为这里已经死了一个人，就将房间从候选区移除。\n“C-02永久封锁完成。”\n我们把星遥、药品和调查记录带出来，却没有人说这是一次成功撤离。安全线内外的人数已经不再相同。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch4_standard_postseal',
  ),
  'ch4_standard_postseal': StoryBeat(
    id: 'ch4_standard_postseal',
    label: '第一次主动杀人改变了所有动词',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '之前的死亡仍可以被一部分人理解为规则失控、陷阱触发或主办方的单方处决。今天不同。\n有人知道继续动作会导致死亡，知道还存在停止或救援的方法，仍然为了控制、自保或多数人的安全让那个动作继续。\n从这一刻起，“防御”“保管”“留观”和“执行规则”都不再是中性词。每个人会根据自己今天站在门的哪一侧，重新解释它们。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch4_sumi_after_killing',
  ),
  'ch4_sumi_after_killing': StoryBeat(
    id: 'ch4_sumi_after_killing',
    label: '医生开始记录救治为什么停止',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'concerned',
    text:
        '苏弥没有只在死亡记录上写最终时间。她把第一次警告、最后一次可逆状态、救援方法被拒绝的时间与实际死亡分别写成四行。\n“死因不是只有身体最后怎么停下。”她说，“也包括为什么有效救治没有继续。”\n她仍然希望至少六人活到最后。现在那个数字不再只是她想救多少人，也是有多少人开始怀疑，她每一次救治是否都在为自己的条款增加筹码。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch4_xingyao_after_killing',
  ),
  'ch4_xingyao_after_killing': StoryBeat(
    id: 'ch4_xingyao_after_killing',
    label: '她的昏厥成了杀人链的第一环',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'alarm',
    text:
        '星遥将受污染的耳机封进证物袋。她知道自己的昏厥不是死亡的直接原因，却正是那次昏厥让药柜、医疗权限和高危索引在同一个房间里爆发。\n“如果我早一点说出第一次耳鸣，我们会不会更早关掉频道？”她问。\n“可能。”我说，“但有人在知道死亡风险后继续了动作。你隐瞒症状可以被追问，不能被拿来替那个决定承担责任。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.shenYan],
    next: 'ch4_common_aftermath',
  ),
  'ch4_common_aftermath': StoryBeat(
    id: 'ch4_common_aftermath',
    label: '林澄把所有路线改成需要回应的路线',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '回到集合厅后，林澄撤掉了原先只标注距离和封锁的路线图。新图上，每一处转角旁都多了一个必须由第二人确认的空格。\n“今天之前，我们觉得危险是有人单独消失。”她说，“现在一组人一起离开，也可能是为了做一件不想让其他人知道的事。”\n她没有把“结伴”当成安全的同义词。一名同伴可以是见证人，也可以是共犯。区别在于行动结束后，是否还有一个不在现场的人能得到完整回应。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch4_inventory_status',
  ),
  'ch4_inventory_status': StoryBeat(
    id: 'ch4_inventory_status',
    label: '高危物资状态从此成为人际关系',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚要求PDA不再只显示“初始位置”。六件高危物资每次变更都必须记录封存、持有、去向不明或已使用，并与死亡记录交叉。\n“物资状态不只是背包里有什么。”她说，“它会决定谁愿意靠近你，谁要求搜身，谁在你说‘只是保管’时仍然后退。”\n索引将武器放进了地图；我们的第一次使用或成功封存，则将它放进了每一段之后的对话。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch4_e04_signal',
  ),
  'ch4_e04_signal': StoryBeat(
    id: 'ch4_e04_signal',
    label: '12号在档案库里亮起',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '傍晚，星遥在离线地图上发现一个新的白色信号。12号不再出现在已封锁的C-02，而是稳定停在档案库E-04深处。\n“信号切换发生在医疗封锁完成后三秒。”她说，“不是有人从病房跑到档案库。是另一个预装底座在那一刻接过了身份槽。”\n这一次，白色信号旁边还多了一行以前没有的字：“校验字段解锁准备：剩余六小时。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch4_day_end',
  ),
  'ch4_day_end': StoryBeat(
    id: 'ch4_day_end',
    label: '第三日结束前的清点',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我们重新清点人员、PDA、医疗物资与每一件已公开的高危物品。表格比前两天更长，却再也无法给房间里的人带来“东西都在”的安心。\n一件物资可以被封存，一道门可以被见证，一次死亡可以被拆成设计条件、工具来源、个人决定和系统执行。但从今天开始，每个人都知道其他人已经有能力将“希望你死”变成一个可执行的计划。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch4_end',
  ),
  'ch4_end': StoryBeat(
    id: 'ch4_end',
    label: '加密字段将在零点解锁',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveCorridor,
    text:
        '二十三点五十四分，E-04档案库的应急灯独自亮起。所有仍然有效的PDA同时显示六分钟倒计。\n“公开主条件校验阶段将于第四日零点启动。加密字段解锁后，所有当前条款仍然真实，但不再保证完整。”\n档案库门后传来一声类似终端底座重启的短促蜂鸣。12号的白点停在门内，像一名早已坐好、只等我们带着今天的死亡或封存记录走进去的见证人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch5_midnight',
  ),
};
