part of 'story.dart';

const chapterSixBeats = <String, StoryBeat>{
  'ch6_vote_opening': StoryBeat(
    id: 'ch6_vote_opening',
    label: '空白票箱在天亮前升起',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    timelineMinute: 5760,
    cgId: 'cg_ch6_vote_opening',
    cgFrame: 0,
    text:
        '第五日的灯光不是逐渐亮起来的。零点整，集合厅顶棚的荧光管同时跳白，像一只闭了太久的眼睛突然睁开。主屏幕下方升起一只透明票箱，里面没有纸，只有十二个排列整齐的感应槽。\n我数了一遍座位，又数了一遍仍在呼吸的人。空椅子被推到墙边，编号却继续留在屏幕上。主办方从不替死者收拾位置；它只把那些空缺变成计算条件。\n每台PDA都出现两个入口：匿名投票、公开委托。最下面还有一行比说明文字更小的提示——投票开始后，存活状态、实际位置与委托关系每十分钟同步一次。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_roll_call_gate',
  ),
  'ch6_roll_call_gate': StoryBeat(
    id: 'ch6_roll_call_gate',
    label: '报数前先面对已经发生的事',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我没有立刻触碰投票入口，而是要求所有人按编号报数。不是为了让主办方确认我们还剩多少，而是为了让每一张即将投出的票先经过一个活人的声音。\n有人看向墙边的空椅子，有人避开。前两日的杀人方式不同，留下的阵营也不同；同样一句“简单多数”，落在每条时间线上都不可能是同一件事。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch5_tangyi_escalated': 'ch6_roll_call_revenge',
      'ch5_chenmo_escalated': 'ch6_roll_call_silence',
      'ch5_majority_repeated_killing': 'ch6_roll_call_majority',
      'ch5_audit_chain_blocked': 'ch6_roll_call_audit',
    },
    next: 'ch6_roll_call_audit',
  ),
  'ch6_roll_call_revenge': StoryBeat(
    id: 'ch6_roll_call_revenge',
    label: '唐弈没有替04回答',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'shaken',
    text:
        '报到04时，集合厅只剩通风口的低鸣。唐弈低头整理袖口，没有像过去那样用一句算术结论填补空白。\n“六号，唐弈。”轮到自己时，他才开口，“我知道你们想让我把昨天叫成谋杀。今天先谈怎么活，不谈用什么词纪念四号。”\n叶岚在记录板上写下“拒绝讨论责任”，没有与他争辩。那一笔比指责更让唐弈不安，他抬眼看了她两次。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch6_roll_call_complete',
  ),
  'ch6_roll_call_silence': StoryBeat(
    id: 'ch6_roll_call_silence',
    label: '11号由一段录音代替',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'shaken',
    text:
        '苏弥报完03，把一只密封录音笔放到叶岚原本的位置。那是急救结束前，叶岚留给公开记录的最后一段完整证词。\n陈默的目光落在录音笔上，立刻移开。“死人没有票。”\n“没有。”苏弥说，“但她留下的事实不会因为你希望安静就失去发生时间。”她没有提高声音，指节却因压住录音笔而发白。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.suMi],
    next: 'ch6_roll_call_complete',
  ),
  'ch6_roll_call_majority': StoryBeat(
    id: 'ch6_roll_call_majority',
    label: '高原与陈默都没有回答',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'conflicted',
    text:
        '报数经过08和09时连续空了两次。韩骐站在最后一排，手臂交叠，像要用自己的身体把那两处沉默挡在所有人之外。\n“昨天五票能关死一个人，后来又能关死第二个。”他说，“今天谁再告诉我多数就是合法，先把他的名字写到封锁区里。”\n林澄下意识握住PDA。她不是赞同威胁，只是也记得观察窗后那九十秒里，每个人如何把等待称为程序。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch6_roll_call_complete',
  ),
  'ch6_roll_call_audit': StoryBeat(
    id: 'ch6_roll_call_audit',
    label: '每个编号都由本人回应',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '报数从01一直走到11，没有人替别人开口。伤势、疲惫和敌意都还在，但每个编号后面仍有一具连续的身体。\n叶岚把人数、所在区域和能够独立操作的终端逐项记下。“这是投票前快照，不是投票结果。十分钟后任何一项变化，都必须重新确认。”\n她显然已经注意到同步提示的问题。投票系统却没有提供“强制刷新”按钮。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_roll_call_complete',
  ),
  'ch6_roll_call_complete': StoryBeat(
    id: 'ch6_roll_call_complete',
    label: '主办方只认可终端在线数',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '报数结束，主屏幕没有显示我们的记录，只弹出一行机械确认：“有效终端数量已锁定。简单多数阈值将在投票开始时计算。”\n“存活人数呢？”苏弥问，“昏迷者、被困者和失去操作能力的人怎么算？”\n“有效终端数量已锁定。”主办方原样重复。它回答了一个与问题相似的句子，借此拒绝承认身体和设备不是同一种东西。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.suMi,
      Speaker.administrator,
    ],
    next: 'ch6_rule_pause_1',
  ),
  'ch6_rules_display': StoryBeat(
    id: 'ch6_rules_display',
    label: '四处区域只能留三处',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    cgId: 'cg_ch6_vote_opening',
    cgFrame: 1,
    text:
        '地图上亮起四块尚未永久封锁的区域：医疗补给廊、安保侧廊、维修桥和低温仓储环线。零点前必须选出一处关闭，封锁完成后不可撤销。\n“匿名票不公开持有者。公开委托可将本轮票权交给一名存活参与者。票权允许再次委托。简单多数立即生效；平票时，01号票权计作两票。”\n最后一条让所有视线短暂落到我身上。主办方给01的不是更大权力，而是一种能让任何平票都有人负责的结构。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch6_no_people_on_map',
  ),
  'ch6_no_people_on_map': StoryBeat(
    id: 'ch6_no_people_on_map',
    label: '地图故意不显示人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥把地图放大，四块区域里只有资源图标，没有参与者位置。点开详情，系统才提示“执行时将根据最近一次同步判断区域占用”。\n“十分钟缓存。”她说，“一个人投完票再换区，系统仍可能把旧位置当成现在。或者反过来，地图认为他已经离开，实际还在门后。”\n唐弈瞥了她一眼。“所以投票前别乱走。不是所有漏洞都需要阴谋。”\n“如果规则把正常移动变成死刑条件，叫不叫阴谋都不会让门慢一点。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.tangYi,
      Speaker.liXingyao,
    ],
    next: 'ch6_map_body_1',
  ),
  'ch6_proposals_begin': StoryBeat(
    id: 'ch6_proposals_begin',
    label: '每种方案都先说自己保护什么',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我要求投票开始前，每项方案必须同时写明保留什么、失去什么、由谁执行撤离。只写区域名的提案不进入公开栏。\n没有人反对。真正开始填写以后，争执却比反对更尖锐。因为一旦把代价写全，所有“为了大家”都会露出具体偏向：谁离药更近，谁能碰武器，谁的条款需要某条路保持开放。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_sumi_proposal',
  ),
  'ch6_sumi_proposal': StoryBeat(
    id: 'ch6_sumi_proposal',
    label: '苏弥要求保留医疗补给廊',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '苏弥把三只剩余氧气瓶、抗感染药和伤员名单并列在屏幕上。她主张关闭低温仓储环线，先把可搬运食物转出，保留医疗廊与两条救援路线。\n“我知道03的条件是至少六人存活。”她主动写在提案第一行，“这使我有利益冲突。但伤口感染、呼吸支持和输液不是只服务我的条件。”\n“食物能搬多少？”唐弈问。\n“按现在的人手，六成。再多就赶不上位置刷新。”\n苏弥没有把损失藏起来。六成也意味着四成会永远留在门后。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.tangYi,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch6_tangyi_proposal',
  ),
  'ch6_tangyi_proposal': StoryBeat(
    id: 'ch6_tangyi_proposal',
    label: '唐弈要求关闭安保侧廊',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '唐弈的提案关闭安保侧廊。理由看起来无可挑剔：里面有控制棒备用电芯、束缚带和监控主机，继续开放只会给强势者更多压制工具。\n“把武器区一起封掉，大家回到相同起点。”他说。\n韩骐嗤了一声。“你说的相同起点，是你已经把能用的控制器摸过一遍以后？”\n唐弈没有回应挑衅，只补上一行：执行前由06与01共同清点物资。那行字把我写成他的见证，也把他自己放到了武器最后持有人的位置。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch6_control_proposal_gate',
  ),
  'ch6_control_proposal_gate': StoryBeat(
    id: 'ch6_control_proposal_gate',
    label: '控制权阵营提出第三案',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text: '第三份提案来自仍想控制关键终端的人。具体是谁开口，取决于前两日哪一种暴力让他活到现在。',
    nextByFlag: {
      'ch5_chenmo_escalated': 'ch6_chenmo_proposal',
      'ch5_majority_repeated_killing': 'ch6_hanqi_proposal',
    },
    next: 'ch6_xingyao_proposal',
  ),
  'ch6_chenmo_proposal': StoryBeat(
    id: 'ch6_chenmo_proposal',
    label: '陈默把维修桥称为攻击面',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'guarded',
    text:
        '陈默主张关闭维修桥。那条桥连接档案、供电与门禁旁路，保留它等于允许懂接口的人在不同终端之间移动。\n“你就是最懂接口的人。”叶岚的录音从桌上响起，是她过去留下的质询。\n陈默盯着波形。“所以我公开利益冲突。你们也可以让我回避表决。但桥不封，谁拿到维护卡都能复制昨天的事。”\n他说得对，也说得太适合自己。维修桥一旦关闭，外包责任的另一份恢复片将无法送到主机。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch6_review_proposal',
  ),
  'ch6_hanqi_proposal': StoryBeat(
    id: 'ch6_hanqi_proposal',
    label: '韩骐要求封死安保区之外的暗道',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '韩骐反对关闭安保侧廊，转而要求封维修桥。“控制棒至少看得见。能在墙后改门的人，才让所有人连反抗对象都找不到。”\n他提出由自己搬走安保物资，再把钥匙交给01。\n“04的条件要求控制01。”林澄提醒。\n“所以你们全程盯着。”韩骐说，“利益冲突不等于我说的每个危险都是假的。”\n这句话同样成立。真正棘手的从来不是坏人只说谎，而是每个人都能拿出一部分真实风险，为自己想要的权力铺路。',
    passageSpeakers: [
      Speaker.hanQi,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch6_review_proposal',
  ),
  'ch6_xingyao_proposal': StoryBeat(
    id: 'ch6_xingyao_proposal',
    label: '星遥主张保留维修桥直到最后',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥没有提交封锁区域，而是提出顺序限制：维修桥必须最后关闭，因为所有离线校验、信号追踪和跨区断电都要经过那里。\n“这不是替某一块区域投票。”唐弈说。\n“对，是在告诉你们，四个按钮不是四个同价选项。”她把地图旋转九十度，维修桥像一条窄骨连接三处设施，“先断它，之后任何封锁异常都只能相信主屏幕自己解释。”',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.liXingyao],
    next: 'ch6_review_proposal',
  ),
  'ch6_review_proposal': StoryBeat(
    id: 'ch6_review_proposal',
    label: '叶岚要求先决定证词如何被相信',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚没有争夺区域。她要求所有提案附带三种记录：实际位置由本人确认，委托链由受托人与见证人同时确认，武器清点由不受益者复核。\n“你是在给每张票加三道手续。”唐弈说，“拖到零点，系统会替我们随机封锁。”\n“如果一张票能关死人，三道手续不算多。”\n她停顿片刻，随后公开了11号此前未完整展示的附加条件。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch6_yelan_clause',
  ),
  'ch6_yelan_clause': StoryBeat(
    id: 'ch6_yelan_clause',
    label: '11号必须撤回三项被多数接受的错误指控',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '“终局前，我必须让三项曾被多数接受的错误指控得到公开撤回。撤回必须保留原始指控、反证和责任人。”\n集合厅里出现短暂骚动。这个条件解释了叶岚为什么反复区分手法、责任和嫌疑，也制造了另一种可怕解释：她是否需要先让错误形成多数，才有东西可以撤回？\n叶岚没有回避。“你们可以认为我有制造错误再纠正的动机。因此关于指控程序的提案，我申请回避最终表决，但保留提交证据的权利。”\n她把怀疑自己的理由也交到了公开栏。',
    passageSpeakers: [
      Speaker.yeLan,
      Speaker.narration,
      Speaker.yeLan,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch6_yelan_clause_disclosed'},
    next: 'ch6_clause_reactions',
  ),
  'ch6_clause_reactions': StoryBeat(
    id: 'ch6_clause_reactions',
    label: '真实动机不等于虚假证据',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '“那你之前帮我们，是为了完成三次撤回吗？”林澄问得很慢，像害怕问题本身会伤人。\n“有一部分。”叶岚回答，“我也不想看见别人被错误处死。这两件事可以同时是真的。”\n苏弥接过话：“医生希望病人活着，也会因此完成职业职责。动机影响我们如何分配权限，不能单独推翻已经留下的记录。”\n唐弈没有附和。他在纸上写下一个数字三，又把笔尖停在叶岚名字旁。',
    passageSpeakers: [
      Speaker.linCheng,
      Speaker.yeLan,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch6_clause_debate_1',
  ),
  'ch6_map_preview': StoryBeat(
    id: 'ch6_map_preview',
    label: '封锁预演把代价画成路线',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥调用只读预演，把四种封锁结果叠在地图上。关闭医疗廊，急救距离增加十一分钟；关闭安保侧廊，武器无法清点却也难以取用；关闭维修桥，审计链断开；关闭仓储环线，七日剩余热量降到警戒线。\n每一种方案都没有红色“错误”提示。系统只用相同字体列出后果，仿佛十一分钟、丢失武器和断粮只是四种可互换的界面参数。\n我第一次清楚意识到，这场投票不是在选择牺牲物，而是在选择哪一种延迟会被伪装成没有动手。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_map_choice',
  ),
  'ch6_map_choice': StoryBeat(
    id: 'ch6_map_choice',
    label: '先标记最不能失去的能力',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text: '在票数出现之前，我先在自己的纸图上标出一项不能被封锁方案悄悄抹去的能力。',
    next: null,
    choices: [
      StoryChoice(
        label: '保留救治与撤离',
        caption: '优先保证伤员能被移动，代价是物资与审计可能受损。',
        next: 'ch6_map_choice_response',
        effect: ChoiceEffect(
          sumi: 1,
          cooperation: 1,
          flag: 'ch6_priority_rescue',
        ),
      ),
      StoryChoice(
        label: '保留审计与断电',
        caption: '优先保证异常仍可验证，代价是医疗和仓储路线变长。',
        next: 'ch6_map_choice_response',
        effect: ChoiceEffect(xingyao: 1, logic: 1, flag: 'ch6_priority_audit'),
      ),
      StoryChoice(
        label: '保留食物与公共通道',
        caption: '优先避免资源被少数人掌握，也必须接受武器区难以复核。',
        next: 'ch6_map_choice_response',
        effect: ChoiceEffect(
          lincheng: 1,
          cooperation: 1,
          flag: 'ch6_priority_supply',
        ),
      ),
    ],
  ),
  'ch6_map_choice_response': StoryBeat(
    id: 'ch6_map_choice_response',
    label: '优先项不能替代执行方案',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我把标记公开，并注明它只是优先项，不是封锁结论。优先保护某种能力，不代表可以把另一类人留在门后。\n叶岚在旁边补上“需要执行条件”。星遥则把四张预演图分别截取，准备核对系统是否在同一套位置数据上计算。\n就在这时，匿名票栏突然出现两张内容完全相同的票。它们不仅选择同一区域，连附注里的错别字都一致。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_ballot_wait_1',
  ),
  'ch6_duplicate_ballot': StoryBeat(
    id: 'ch6_duplicate_ballot',
    label: '一张草稿变成两张有效票',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '两张票都选择关闭安保侧廊，附注写着“避免武器再次造成直截伤害”。“直接”的“接”被写成了“截”。\n“复制粘贴。”唐弈说，“两个人商量过不犯法。”\n星遥调出本地发送时间。两张票相差0.08秒，却分别标记为匿名与委托代理。“同一份草稿可能沿两条授权路径进了票箱。”\n主屏幕已经把它们计作两票，并拒绝显示持有者。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch6_vote_freeze_request',
  ),
  'ch6_vote_freeze_request': StoryBeat(
    id: 'ch6_vote_freeze_request',
    label: '冻结请求需要多数同意',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '我提交暂停计票，系统却要求“冻结投票需当前有效票权过半确认”。也就是说，要调查票数是否可靠，首先得用那套可能不可靠的票数批准调查。\n“它把程序入口做成了结论的一部分。”星遥说。\n叶岚翻出实体票箱的维护说明。感应槽下方保留纸质审计包，用来处理断网争议；开启它不会冻结计票，却能复原投票生成顺序。\n我们只有在票数继续增长时调查。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch6_live_count_1',
  ),
  'ch6_investigation_roles': StoryBeat(
    id: 'ch6_investigation_roles',
    label: '调查分成四个互不替代的问题',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚在白板上写下四个问题：票是否真实生成；委托是否被重复使用；位置是否对应当前身体；封锁方案是否改变武器与救援距离。\n“任何一项都不能单独回答谁投了什么。”她说，“我们的目标不是撕掉匿名性，而是确认一份授权有没有被当成两份。”\n我与星遥检查实体票包，苏弥和林澄逐人核对位置，高原负责武器架；叶岚只记录，不接触自己提出的程序证据。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_vote_investigation',
  ),
  'ch6_vote_investigation': StoryBeat(
    id: 'ch6_vote_investigation',
    label: '投票设施审计',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    phase: StoryPhase.investigation,
    text: '检查实体票包、委托链、位置快照与武器清点记录。所有结论必须由工具复核，不能以界面显示代替证据。',
    next: 'ch6_investigation_debrief',
  ),
  'ch6_investigation_debrief': StoryBeat(
    id: 'ch6_investigation_debrief',
    label: '四组记录彼此都是真的',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '调查台上摆着四组没有被篡改的记录。实体票纸确实由不同感应槽打印；委托凭条也有真实签名；位置快照来自合法同步；武器架的重量变化同样准确。\n问题恰恰在于它们各自在不同时间为真。系统把撤销前的委托、十分钟前的位置和此刻的封锁方案拼成一张“当前结果”，让时间差看起来像多数人的共同意志。\n要证明这一点，还必须把先后顺序连起来。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_debrief_argument_1',
  ),
  'ch6_ballot_fact': StoryBeat(
    id: 'ch6_ballot_fact',
    label: '两张票共用同一枚草稿指纹',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '斜光显出两张票的微孔序列不同，说明它们不是复印件；但纸尾的草稿摘要完全相同，连形成时间都只有一次。\n“同一份内容被两个有效会话分别提交。”星遥说，“匿名槽收到本人路径，委托槽收到代理路径。关键不是两个人写得一样，而是一个草稿为什么还能被第二条路径调用。”\n我们把“重复内容”改写为更精确的事实：一次输入，两次有效提交。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch6_delegation_fact',
  ),
  'ch6_delegation_fact': StoryBeat(
    id: 'ch6_delegation_fact',
    label: '撤回只终止了最外层委托',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '委托热敏链上有三枚连续印章：原持有人交给受托人，受托人再次转交，原持有人随后撤回。界面只显示“已撤回”，离线缓存却保留第二层代理直到十分钟租约结束。\n“原持有人恢复了自己的票，末端代理也还握着旧票。”叶岚说，“这不是某个人凭空造出身份，而是撤回沿着委托链传播得不完整。”\n公开委托让责任看似更清楚，重复转交却在链尾制造了一张没人承认拥有的票。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_location_fact',
  ),
  'ch6_location_fact': StoryBeat(
    id: 'ch6_location_fact',
    label: '地图里的身体慢了十分钟',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '位置叠图显示，林澄已经从仓储环线返回集合厅，系统仍把07留在低温门内；高原去了安保侧廊清点电芯，地图却认为09还坐在白板旁。\n“如果现在关仓储，系统会提示07仍在里面，却可能把她的撤离确认发到已经无人持有的旧位置。”苏弥说，“关安保则相反，它会认为没有人需要撤离。”\n位置快照不是伪造，却足以让一次正常移动变成无人收到的死亡警告。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch6_weapon_fact',
  ),
  'ch6_weapon_fact': StoryBeat(
    id: 'ch6_weapon_fact',
    label: '安保架少掉的不是一件武器',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '安保架总重量减少了1.8公斤。清单把它解释为一只控制棒，高原用轮廓尺复核后摇头：空位由备用电芯、束缚带和一枚门磁旁路片共同组成。\n“不是有人拿着明显武器跑了。”他说，“有人取走三件分开放都不起眼的东西，组合以后能让一扇门保持锁定，再让被困者失去反抗。”\n封锁安保侧廊不会消除这套工具，只会把最后的取用记录一起关在里面。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch6_competing_explanations',
  ),
  'ch6_competing_explanations': StoryBeat(
    id: 'ch6_competing_explanations',
    label: '三种解释都抓住了真实片段',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'neutral',
    text:
        '唐弈认为两名投票者提前商量，委托链只是巧合；苏弥认为位置滞后才是核心，重复票并不会直接杀人；星遥则坚持系统重放了仍未过期的末端代理。\n三种解释分别对应内容、后果和机制。它们都引用了真实记录，也都容易把另外两项降格为噪音。\n我把所有证据重新洗牌放到推理板上。不能因为一条线最像阴谋，就跳过它如何从一份授权实际变成两张票。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_case05_deduction',
  ),
  'ch6_case05_deduction': StoryBeat(
    id: 'ch6_case05_deduction',
    label: '权限推演 CASE 05',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    phase: StoryPhase.deduction,
    text: '用票纸生成记录、委托传播时间与位置快照构成证据链，再判断同一份投票为何被系统接受两次。',
    next: null,
  ),
  'ch6_case05_coordination_error': StoryBeat(
    id: 'ch6_case05_coordination_error',
    label: '相同文字不能证明相同持有人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '“两张票一起出现，可能有人串通。”星遥说，“但实体纸显示只有一次草稿生成。串通能解释意见一致，解释不了为什么匿名槽和委托槽调用同一个摘要。”\n如果把相似当成身份指认，我们只会抓住最像同伙的人，留下仍能重复投票的会话。',
    passageSpeakers: [Speaker.liXingyao, Speaker.narration],
    next: 'ch6_case05_deduction',
  ),
  'ch6_case05_location_error': StoryBeat(
    id: 'ch6_case05_location_error',
    label: '位置滞后解释后果而非票数',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '“十分钟快照会让人收不到正确撤离提示，这是真的。”苏弥指向两张票，“但它不会自己增加票数。先解释哪条权限生成第二张票，再处理它会把谁留在门后。”\n把致命后果当成最初原因，会让我们在封锁前仍找不到应该撤销的授权。',
    passageSpeakers: [Speaker.suMi, Speaker.narration],
    next: 'ch6_case05_deduction',
  ),
  'ch6_case05_resolved': StoryBeat(
    id: 'ch6_case05_resolved',
    label: '一票沿两条仍有效的路径抵达',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '原持有人先公开委托，受托人又把票权转交到末端代理。原持有人撤回后，本人票权立即恢复，撤销消息却没有穿过第二层租约。\n同一份本地草稿因此沿本人路径与末端代理路径各提交一次。系统验证了两枚真实签名，却没有验证它们是否来自同一条已经分叉的授权根。\n位置快照再把这张多出的票变成封锁风险：它决定谁被系统认为已经撤离，谁会在没有警告的情况下留在门内。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'case05_solved', 'ch6_delegate_replay_proven'},
    next: 'ch6_public_reconstruction',
  ),
  'ch6_public_reconstruction': StoryBeat(
    id: 'ch6_public_reconstruction',
    label: '公开复原不公布匿名票内容',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚只公开授权根编号、时间和撤销传播状态，没有公布匿名票属于谁。这样足以证明两张票共享一份根权限，又不把调查变成强迫所有人表态。\n重复票被撤销后，安保侧廊从五票降到四票。没有人因此松口气。真正的问题不是少算一张，而是下一次谁有资格决定一张票能不能关上一扇有人站在后面的门。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_policy_workshop_1',
  ),
  'ch6_institution_gate': StoryBeat(
    id: 'ch6_institution_gate',
    label: '案件变成一套必须执行的规则',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '修复委托链只能处理已经发生的重复票。封锁仍会继续，利益冲突、证词复核与位置刷新仍然没有制度。\n我们必须在剩余时间里选择谁能表决、谁能暂停、谁负责确认人已经离开。这个决定将保留到之后所有区域裁决，不会在零点后自动重置。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    auditNext: 'ch6_audit_policy_design',
    auditRequiredFlags: {
      'ch5_audit_chain_blocked',
      'ch5_slot12_count_rejected',
      'case05_solved',
    },
    next: 'ch6_policy_choice',
  ),
  'ch6_policy_choice': StoryBeat(
    id: 'ch6_policy_choice',
    label: '选择后续区域裁决制度',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text: '每种制度都会阻止一种风险，也会把另一种风险集中到新的位置。',
    next: null,
    choices: [
      StoryChoice(
        label: '保留简单多数',
        caption: '最快形成结果，但重复票之外的利益冲突仍由票数覆盖。',
        next: 'ch6_policy_majority',
        effect: ChoiceEffect(flag: 'ch6_policy_simple_majority'),
      ),
      StoryChoice(
        label: '利益相关者回避',
        caption: '受益者不得投票，但谁属于受益者仍可能被操纵。',
        next: 'ch6_policy_recusal',
        effect: ChoiceEffect(logic: 1, flag: 'ch6_policy_recusal'),
      ),
      StoryChoice(
        label: '三人交叉确认',
        caption: '执行前核对位置、授权和撤离，任何一人缺席都会让程序停住。',
        next: 'ch6_policy_crosscheck',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch6_policy_crosscheck'),
      ),
      StoryChoice(
        label: '由01集中裁决',
        caption: '消除票权分叉，也把攻击、胁迫与全部责任集中到01。',
        next: 'ch6_policy_centralized',
        effect: ChoiceEffect(logic: 1, flag: 'ch6_policy_centralized'),
      ),
      StoryChoice(
        label: '启用最低伤亡事故预案',
        caption: '暂停人为投票，由实时位置与撤离时间计算风险最低的区域。',
        next: 'ch6_optimizer_end_1',
        effect: ChoiceEffect(logic: 2, flag: 'ch6_policy_casualty_optimizer'),
      ),
    ],
  ),
  'ch6_policy_majority': StoryBeat(
    id: 'ch6_policy_majority',
    label: '速度仍被当作公平',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '简单多数保留下来，末端委托租约被临时禁用。唐弈赞成，因为它不要求任何人先承认自己的条件会从哪项封锁中获利。\n系统立即恢复计票。每个人都拥有形式相同的一票，却没有共同承担相同的撤离距离。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_standard_execution_gate',
  ),
  'ch6_policy_recusal': StoryBeat(
    id: 'ch6_policy_recusal',
    label: '回避名单本身成为争夺对象',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '所有人提交条款与区域利益，由公开栏生成回避名单。问题随即出现：一个人可能因医疗需求受益，也可能因武器远离而受损；系统只允许把他标成“相关”或“不相关”。\n叶岚提醒，回避能减少直接获利票，却不能验证执行者有没有把受害者的位置写错。计票继续时，所有人都盯着名单，而不是门。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_standard_execution_gate',
  ),
  'ch6_policy_crosscheck': StoryBeat(
    id: 'ch6_policy_crosscheck',
    label: '三枚确认键能被一个缺席者卡死',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '执行前必须由三人分别确认位置、授权根和撤离路线。它能发现快照滞后，却没有规定确认者拒绝到场时如何替换。\n“只要买通或困住其中一个，所有撤离请求都会停。”星遥说。系统已经接受制度，却拒绝增加候补席。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch6_standard_execution_gate',
  ),
  'ch6_policy_centralized': StoryBeat(
    id: 'ch6_policy_centralized',
    label: '所有人的票变成给01的建议',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '投票结果不再直接执行，只向01提供建议，由我确认最终区域与撤离完成。重复委托失去作用，屏幕却立刻公开我的实时位置。\n韩骐、唐弈和陈默看向我的方式各不相同，含义却相似：从这一刻起，改变一个人的决定比说服多数更快。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_standard_execution_gate',
  ),
  'ch6_standard_execution_gate': StoryBeat(
    id: 'ch6_standard_execution_gate',
    label: '旧有暴力找到新制度的薄处',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text: '制度开始运行后，第一处薄弱环节很快被利用。规则没有凭空制造杀意，却替已经跨过界线的人提供了更合适的距离、门和责任说法。',
    passageSpeakers: [Speaker.narration],
    nextByFlag: {
      'ch5_tangyi_escalated': 'ch6_revenge_setup',
      'ch5_chenmo_escalated': 'ch6_silence_setup',
      'ch5_majority_repeated_killing': 'ch6_force_setup',
    },
    next: 'ch6_policy_aftermath',
  ),
  'ch6_revenge_setup': StoryBeat(
    id: 'ch6_revenge_setup',
    label: '唐弈把叶岚写成回避对象',
    speaker: Speaker.tangYi,
    scene: SceneKey.securityRoom,
    portraitMood: 'shaken',
    cgId: 'cg_ch6_yelan_seal',
    cgFrame: 0,
    text:
        '安保侧廊进入最后撤离时，唐弈提交一份修订：叶岚因11号条件从“错误指控”中获利，不得担任撤离见证。无论当前制度是否要求回避，这份说明都让系统把她移出确认链。\n叶岚正在侧廊复核失踪门磁片。她的位置刚好处于十分钟快照的盲区，地图仍显示她在集合厅。\n“先暂停封锁。”我说。\n“你们已经暂停过一次。”唐弈挡住终端，“每次她不喜欢结果，就能用记录要求重来？”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.tangYi,
    ],
    next: 'ch6_revenge_warning',
  ),
  'ch6_revenge_warning': StoryBeat(
    id: 'ch6_revenge_warning',
    label: '叶岚在门后提交本人位置',
    speaker: Speaker.yeLan,
    scene: SceneKey.securityRoom,
    portraitMood: 'strained',
    text:
        '叶岚用有线面板提交位置确认，系统提示“见证人已回避，陈述不进入执行链”。她转而把语音发到公共频道。\n“11号位于A-03内侧，距出口二十七米。门磁旁路片不在架上。封锁继续将导致本人被困。”\n每个人都听见了。制度却只承认被允许说话的人。唐弈没有伪造她的位置；他只是先改变了她的话能否被计算。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_revenge_death',
  ),
  'ch6_revenge_death': StoryBeat(
    id: 'ch6_revenge_death',
    label: '回避条款成为一扇单向门',
    speaker: Speaker.administrator,
    scene: SceneKey.securityRoom,
    portraitMood: 'intervening',
    cgId: 'cg_ch6_yelan_seal',
    cgFrame: 1,
    timelineMinute: 6172,
    text:
        '我们赶到安保侧廊时，第一道闸门已经落下。叶岚隔着防爆玻璃把记录板举到胸前，上面只有一句：“事实不因见证资格消失。”\n门磁旁路让第二道门提前闭合，封锁气体开始置换空气。她在最后两分钟持续报告呼吸和方向，没有请求任何人把这件事叫成意外。\n“11号生命体征终止。”\n唐弈用真实的利益冲突移除她，又利用位置快照让系统拒绝她的本人陈述。规则执行了门，选择执行了死亡。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch6_yelan_killed_by_vote', 'ch6_tangyi_vote_killer'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '11',
        cause: '被移出撤离确认链后困于安保侧廊封锁区',
        timelineMinute: 6172,
        responsibleParticipantIds: ['06'],
      ),
    ],
    next: 'ch6_policy_aftermath',
  ),
  'ch6_silence_setup': StoryBeat(
    id: 'ch6_silence_setup',
    label: '陈默截断唐弈的确认席',
    speaker: Speaker.chenMo,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'cold',
    cgId: 'cg_ch6_tangyi_bridge',
    cgFrame: 0,
    text:
        '维修桥的封锁预演开始后，唐弈发现06被登记为授权复核人。他带着委托纸卷前往桥侧终端，准备证明某一张反对票仍来自失效会话。\n陈默先一步切断集合厅到桥面的语音，只留下制度要求的短码确认。唐弈收到的指令是“前往内侧扫描授权根”，却没有看见桥将在四分钟后分段收起。\n“他手里有我的责任链。”陈默说，“如果那份票被认定有效，维修桥不会关，恢复签名也不会断。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.chenMo],
    next: 'ch6_silence_choice',
  ),
  'ch6_silence_choice': StoryBeat(
    id: 'ch6_silence_choice',
    label: '短码确认了设备却没有确认人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'alarm',
    text:
        '唐弈从内侧完成扫描，屏幕返回“授权根无重复”。三人确认链因此全部点亮：位置快照显示桥面无人，授权有效，撤离路线已开放。\n“位置那一项确认的是十分钟前的地图。”星遥扑向手动制动，“它没有问扫描的人还在不在里面。”\n陈默握着旁路片站在制动柜前。他只要拔出那枚薄片，桥面就会多出九十秒复位时间。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch6_silence_death',
  ),
  'ch6_silence_death': StoryBeat(
    id: 'ch6_silence_death',
    label: '完整确认链仍然缺少一具身体',
    speaker: Speaker.administrator,
    scene: SceneKey.maintenanceRoom,
    cgId: 'cg_ch6_tangyi_bridge',
    cgFrame: 1,
    timelineMinute: 6175,
    text:
        '维修桥从中央折起时，唐弈抓住检修梯，试图把纸卷从缝隙抛出来。纸先落到我们脚边，他的手随后被合拢的钢板挡住。\n陈默没有拔旁路片。直到桥面完全收起，他才松开制动柜。\n“06号生命体征终止。”\n三项确认都留下真实签名，却确认了不同时间的设备状态。陈默没有篡改任何一项；他只是知道制度会相信它们已经确认了同一个现在。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch6_tangyi_killed_by_vote', 'ch6_chenmo_vote_killer'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '06',
        cause: '位置快照滞后且制动旁路未撤，困于收起的维修桥',
        timelineMinute: 6175,
        responsibleParticipantIds: ['08'],
        sourceItemId: 'door_override',
      ),
    ],
    next: 'ch6_policy_aftermath',
  ),
  'ch6_force_setup': StoryBeat(
    id: 'ch6_force_setup',
    label: '韩骐认为投票已经证明唐弈危险',
    speaker: Speaker.hanQi,
    scene: SceneKey.securityRoom,
    portraitMood: 'furious',
    cgId: 'cg_ch6_tangyi_restraint',
    cgFrame: 0,
    text:
        '重复票被撤销后，唐弈仍坚持封锁安保侧廊。韩骐认定06正在替下一次多数杀人准备束缚工具，要求立即交出PDA。\n“你可以公开反驳他的票。”我说。\n“上次我们就是公开反驳，门照样关了。”韩骐把唐弈推到安保架旁，用束缚带固定住他的手腕，“先让他失去执行能力，再谈程序。”\n制度没有授权这次拘束。可在经历两次多数死亡后，旁观者已经很难分辨预防和报复从哪一秒开始分开。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch6_force_threshold',
  ),
  'ch6_force_threshold': StoryBeat(
    id: 'ch6_force_threshold',
    label: '唐弈已经停止挣扎',
    speaker: Speaker.suMi,
    scene: SceneKey.securityRoom,
    portraitMood: 'concerned',
    text:
        '唐弈被压在架体与墙之间，腕部因束缚带逐渐发紫。他交出PDA，并报出委托口令，当前票权已经全部冻结。\n“风险已经停止。”苏弥说，“松开胸口，让他呼吸。”\n韩骐看见屏幕上的冻结标记，也看见唐弈不再反抗。他仍用前臂把人压得更深。“这种人只要还能说话，就能让别人替他动手。”\n这句话说的是过去的恐惧，不是此刻仍在发生的攻击。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch6_force_death',
  ),
  'ch6_force_death': StoryBeat(
    id: 'ch6_force_death',
    label: '阻止票权变成了肉体处决',
    speaker: Speaker.suMi,
    scene: SceneKey.securityRoom,
    portraitMood: 'shaken',
    cgId: 'cg_ch6_tangyi_restraint',
    cgFrame: 1,
    timelineMinute: 6168,
    text:
        '唐弈先失去声音，随后膝盖滑落。苏弥和我把韩骐拉开时，他的胸廓已经没有自主起伏。\n复苏持续了十四分钟。安保侧廊的投票在此期间自动超时，唐弈却没能等到任何结果。\n“06号死亡，胸腹持续受压导致窒息。”苏弥记录。\n韩骐不是为了获得某张票而杀他。他把“多数会再次杀人”当作足够理由，在威胁已经解除后仍拒绝停手。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch6_tangyi_killed_by_force', 'ch6_hanqi_vote_killer'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '06',
        cause: '票权冻结后仍遭持续胸腹压制而窒息',
        timelineMinute: 6168,
        responsibleParticipantIds: ['04'],
      ),
    ],
    next: 'ch6_policy_aftermath',
  ),
  'ch6_policy_aftermath': StoryBeat(
    id: 'ch6_policy_aftermath',
    label: '没有一套单独程序足以救人',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我们把选定制度、执行日志和死亡前最后一次可停止动作并列公开。简单多数不能识别受益者；回避制度可能删除必要证词；三人确认会被不同时间的真实记录欺骗；集中裁决则让胁迫只需瞄准一个人。\n问题不是制度毫无意义。恰恰相反，每一处失败都精确说明少了什么：回避需要独立复核，确认需要同一时刻，裁决需要可撤换的执行者，任何程序都不能拒绝本人位置的紧急申诉。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_aftervote_1',
  ),
  'ch6_audit_policy_design': StoryBeat(
    id: 'ch6_audit_policy_design',
    label: '审计记录允许我们在执行前测试制度',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    cgId: 'cg_ch6_audit_vote',
    cgFrame: 0,
    text:
        '因为医疗区没有发生主动杀人、12号计数被及时排除，系统仍保留一次“无伤亡制度预演”。我们把四种方案放进同一组历史数据，观察哪一种会在叶岚回避、唐弈缺席或位置滞后时继续关门。\n单独回避会让本人陈述失效；单独交叉确认会接受不同时间的三项真记录；简单多数与集中裁决则分别把漏洞留给票数和胁迫。\n只有把利益回避与三人交叉确认组合，并增加本人紧急位置优先、确认时间不得相差六十秒，预演里的三条死亡链才全部停止。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_audit_policy_choice',
  ),
  'ch6_audit_policy_choice': StoryBeat(
    id: 'ch6_audit_policy_choice',
    label: '决定是否采用组合制衡',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text: '预演给出了失败条件，却不会替我们按下制度确认。',
    next: null,
    choices: [
      StoryChoice(
        label: '回避加三人交叉确认',
        caption: '受益者回避，位置、授权与撤离须在同一分钟内由不同人确认。',
        next: 'ch6_audit_hybrid',
        effect: ChoiceEffect(
          logic: 2,
          cooperation: 2,
          flag: 'ch6_policy_audit_hybrid',
        ),
      ),
      StoryChoice(
        label: '只采用利益回避',
        caption: '减少直接获利票，但本人陈述仍可能被一并移除。',
        next: 'ch6_policy_recusal',
        effect: ChoiceEffect(flag: 'ch6_policy_recusal'),
      ),
      StoryChoice(
        label: '只采用三人确认',
        caption: '增加复核，但不同时间的真记录仍可能拼成假现在。',
        next: 'ch6_policy_crosscheck',
        effect: ChoiceEffect(flag: 'ch6_policy_crosscheck'),
      ),
      StoryChoice(
        label: '交给01最终决定',
        caption: '由一个人承担结果，也让胁迫只需控制一个目标。',
        next: 'ch6_policy_centralized',
        effect: ChoiceEffect(flag: 'ch6_policy_centralized'),
      ),
    ],
  ),
  'ch6_audit_hybrid': StoryBeat(
    id: 'ch6_audit_hybrid',
    label: '四道条件必须指向同一个现在',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'relaxed',
    text:
        '新制度将提案受益者排除在执行确认之外，却不剥夺其提交证据和本人位置申诉的权利。三名确认者分别核对授权根、肉眼位置与撤离路线，时间戳相差超过六十秒即全部失效。\n星遥故意用旧快照提交一次测试。三枚确认灯没有变绿，而是同时要求重新观察。\n“这才像确认。”她说，“不是三个人各自对着不同时间点说真话。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.liXingyao],
    next: 'ch6_audit_attempt',
  ),
  'ch6_audit_attempt': StoryBeat(
    id: 'ch6_audit_attempt',
    label: '三种杀人方案在执行前暴露',
    speaker: Speaker.shenYan,
    scene: SceneKey.securityRoom,
    cgId: 'cg_ch6_audit_vote',
    cgFrame: 1,
    text:
        '唐弈提交的叶岚回避申请被接受，但她的本人位置申诉仍拥有最高优先级；陈默送往维修桥的旧位置快照因超过六十秒被拒；韩骐要求拘束唐弈时，票权冻结与肉体压制被拆成两项动作，后者没有获得授权。\n安保门磁旁路片、维修桥制动片和束缚带分别在三处被找到。没有任何一件物品单独证明持有者必然会杀人，组合后的执行路径却已经清楚。\n我们没有因为更信任谁而避免死亡，只是让任何一个人的动机都不足以独自完成最后一步。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch6_vote_killings_prevented', 'ch6_reviewable_majority'},
    next: 'ch6_audit_seal',
  ),
  'ch6_audit_seal': StoryBeat(
    id: 'ch6_audit_seal',
    label: '仓储环线在清点后关闭',
    speaker: Speaker.administrator,
    scene: SceneKey.storageRoom,
    timelineMinute: 6210,
    text:
        '最终方案关闭低温仓储环线。食物只搬出七成，比苏弥最初估计多一成，也仍有三成留在门后。我们没有把这个损失写成“零伤亡”的胜利。\n最后一人离开后，三名确认者同时看见空走廊，委托根已经清零，撤离路线在同一分钟保持开放。\n“区域永久封锁完成。”\n闸门落下，没有人的生命体征随之消失。制度没有提供完美答案，只让牺牲不能再被旧快照和沉默自动决定。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch6_storage_sealed', 'ch6_no_death_vote'},
    next: 'ch6_audit_after_1',
  ),
  'ch6_route_lock_intro': StoryBeat(
    id: 'ch6_route_lock_intro',
    label: '共同承担哪一种风险不再只是好感',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '投票结束后，我必须确定之后与谁共享实时位置、撤离否决和证据副本。关系在这里不再只是更亲近的称呼，而是一份会把两个人同时放进攻击路径的公开承诺。\n我可以延续此前已经建立的信任，也可以拒绝把私人关系写进制度。无论选择哪一种，都不能替对方按下同意。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_route_lock_choice',
  ),
  'ch6_route_lock_choice': StoryBeat(
    id: 'ch6_route_lock_choice',
    label: '登记后续共同撤离关系',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text: '这份登记会持续到终局，任何一方都能在公开见证下撤回。',
    next: null,
    choices: [
      StoryChoice(
        label: '与黎星遥共享实时校验',
        caption: '彼此拥有停止信号检查和要求重新确认位置的权利。',
        next: 'ch6_lock_xingyao',
        requiresFlag: 'ch5_signature_xingyao',
        effect: ChoiceEffect(
          xingyao: 2,
          logic: 1,
          flag: 'ch6_route_locked_xingyao',
        ),
      ),
      StoryChoice(
        label: '与苏弥共享撤离否决',
        caption: '任何一方进入医疗风险时，另一方可以暂停封锁一次。',
        next: 'ch6_lock_sumi',
        requiresFlag: 'ch5_signature_sumi',
        effect: ChoiceEffect(
          sumi: 2,
          cooperation: 1,
          flag: 'ch6_route_locked_sumi',
        ),
      ),
      StoryChoice(
        label: '与林澄登记双向见证',
        caption: '双方只为亲眼确认的事实作证，并保留随时说不的权利。',
        next: 'ch6_lock_lincheng',
        requiresFlag: 'ch5_signature_lincheng',
        effect: ChoiceEffect(
          lincheng: 2,
          cooperation: 1,
          flag: 'ch6_route_locked_lincheng',
        ),
      ),
      StoryChoice(
        label: '保持公开审计关系',
        caption: '不锁定私人路线，所有否决与副本交给可替换的公开小组。',
        next: 'ch6_lock_public',
        effect: ChoiceEffect(
          logic: 1,
          cooperation: 1,
          flag: 'ch6_route_locked_public',
        ),
      ),
    ],
  ),
  'ch6_lock_xingyao': StoryBeat(
    id: 'ch6_lock_xingyao',
    label: '同一频率也允许一方先按停止',
    speaker: Speaker.liXingyao,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'relaxed',
    text:
        '星遥把两台PDA接入同一只离线校验器，又把停止键放到我们都能碰到的位置。“共享不是你一直盯着我，也不是我替你过滤所有危险。”\n“任何一方说停，先断连接，再解释。”我重复此前的约定。\n她确认条款里没有“保护者”和“被保护者”，才签下名字。肩膀相碰时，她很轻地笑了一下。“至少系统这次没把亲近设计成单向权限。”',
    passageSpeakers: [Speaker.liXingyao, Speaker.shenYan, Speaker.narration],
    next: 'ch6_route_lock_converge',
  ),
  'ch6_lock_sumi': StoryBeat(
    id: 'ch6_lock_sumi',
    label: '照顾者拥有一次不解释的暂停',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'relieved',
    text:
        '苏弥在撤离否决旁增加一行：使用暂停的人不需要先证明自己伤得足够严重。她看着那行字，像在确认它也适用于自己。\n“如果我又说先救别人呢？”她问。\n“我会提醒你可以选择，但不会替你选择。”\n她把额头靠在我肩侧，短得像一次测量脉搏的停顿。“那就请你提醒得大声一点。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch6_route_lock_converge',
  ),
  'ch6_lock_lincheng': StoryBeat(
    id: 'ch6_lock_lincheng',
    label: '双向见证不要求永远同意',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'determined',
    text:
        '林澄把“双向见证”读了三遍，特别确认拒绝替对方作证不会自动解除关系。\n“也就是说，我可以相信你，同时说我没看见？”\n“应该这样。”\n她签下自己的名字，又用笔在纸质副本旁写了一句：喜欢一个人不是替他补全证词。写完以后，她耳尖发红，却没有把那行字涂掉。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch6_route_lock_converge',
  ),
  'ch6_lock_public': StoryBeat(
    id: 'ch6_lock_public',
    label: '否决权交给可以替换的小组',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '我没有登记私人共同撤离者。实时位置由三人轮值保管，任何成员与提案存在直接利益时自动替换。\n“公开制度不会因此比私人承诺更高尚。”叶岚说，“它只是让关系不必承担你没有选择给它的职责。”\n我在轮值表上签名。没有一条感情线被否定，只是它们没有在这一刻被写成终局权限。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_route_lock_converge',
  ),
  'ch6_route_lock_converge': StoryBeat(
    id: 'ch6_route_lock_converge',
    label: '第五日的选择被写入后续协议',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '区域封锁结果、投票制度和共同撤离关系被写入不可删除的后续协议。主屏幕第一次不再只显示谁拥有几票，而是显示谁回避、谁复核、谁可以要求暂停。\n这些字段仍然可能被利用，也仍然依赖人愿意在危险中执行。不同的是，下一次有人说“系统决定”，我们至少能指出系统之前是哪一个人、在哪一分钟、用哪一份记录做出的选择。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_lock_aftermath_1',
  ),
  'ch6_zero_message': StoryBeat(
    id: 'ch6_zero_message',
    label: 'ZERO向制度而不是答案发来评分',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '投票界面关闭前，一条不属于主办方固定语音的文字从底部浮出：“样本已完成多数压力测试。责任归属密度上升。”\n“样本？”林澄念出那个词。\n文字继续刷新：“第六日将开放最终证词席位。席位数量：四。进入条件：持有可审计结论，或持有足以使他人沉默的控制权。”\nZERO没有夸奖我们找出漏洞。它只是把我们如何处理漏洞也记入了实验。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.linCheng,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch6_evening_round_1',
  ),
  'ch6_night_after_vote': StoryBeat(
    id: 'ch6_night_after_vote',
    label: '票箱空了，阵营没有消失',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text:
        '透明票箱降回地面时，纸质审计包仍留在桌上。那些薄纸没有重量，却让一条走廊、一份药物和一条命在不同时间线上失去归属。\n人群离开集合厅后没有恢复成同伴。有人开始计算四个证词席位，有人检查能够让证人闭嘴的物品，有人把今天的复核规则抄到衣袖内侧。\n我最后关灯，发现屏幕黑下去以后，自己仍在玻璃上看见许多重叠的影子。多数从来不是一个人，却可以把每个人都藏在里面。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_end',
  ),
  'ch6_end': StoryBeat(
    id: 'ch6_end',
    label: '四个证词席位将在明日开放',
    speaker: Speaker.shenYan,
    scene: SceneKey.dormitory,
    timelineMinute: 6720,
    text:
        '返回房间后，我把投票结果、死亡记录或预演中断记录分别存进离线副本。选择的制度仍显示在PDA首页，无法由01单独修改。\n距离七日结束还有两天。主办方已经不再满足于让我们选择哪扇门关闭；它要我们选择哪四个人有资格定义真相，又允许其他人用控制权让证词席位空出来。\n我没有立刻睡。走廊每一次脚步停顿，都可能是在确认谁的门、谁的关系和谁的证据会在明天成为第四把椅子。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_day_six_open',
  ),
  'ch6_rule_pause_1': StoryBeat(
    id: 'ch6_rule_pause_1',
    label: '投票入口先改变了人的坐姿',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '规则还没有完全公布，众人已经本能地重新选择位置。苏弥把椅子拖到能看见所有伤员的角度；星遥靠近有线端口，却与主屏保持三步距离；韩骐站在两条出口之间；唐弈坐到任何人都无法从背后看见PDA的墙边。\n这些动作没有一项等于恶意。它们只是把每个人最先想保护的东西暴露出来：身体、信息、路线或秘密。死亡游戏最擅长的不是凭空制造欲望，而是给每种欲望安排一个必须与别人冲突的按钮。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_rule_pause_2',
  ),
  'ch6_rule_pause_2': StoryBeat(
    id: 'ch6_rule_pause_2',
    label: '林澄问死者的票会去哪里',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '“已经不在的人，他们的终端会自动失效吗？”林澄没有用“死者”两个字，目光停在墙边的空椅子上。\n主办方回答：“有效终端在投票开始时锁定。”\n“我问的是人，不是终端。”\n广播没有回应。林澄把这段沉默写进纸质记录，笔尖划破了薄纸。她不是第一次知道系统会回避问题，却是第一次看见回避本身可能变成一张票。',
    passageSpeakers: [
      Speaker.linCheng,
      Speaker.administrator,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch6_rule_pause_3',
  ),
  'ch6_rule_pause_3': StoryBeat(
    id: 'ch6_rule_pause_3',
    label: '苏弥要求定义能够投票的人',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '苏弥把问题拆得更具体：“一个人昏迷，PDA仍在线，谁能替他操作？一个人清醒但手部受伤，语音能否确认？一个人被关在门后，系统位置又显示他已经离开，哪一条记录优先？”\n管理员只给出三条机械答复：终端在线即可参与；委托按界面状态执行；区域占用以最近同步为准。\n每一条单独看都像为了效率。三条放在一起，却允许设备替代意识、界面替代撤回、旧位置替代当前身体。',
    passageSpeakers: [Speaker.suMi, Speaker.narration, Speaker.narration],
    next: 'ch6_rule_pause_4',
  ),
  'ch6_rule_pause_4': StoryBeat(
    id: 'ch6_rule_pause_4',
    label: '唐弈认为模糊也可以被管理',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '“不要把所有边界问题都当成陷阱。”唐弈把苏弥列出的情形排成表格，“先约定只接受本人触控，伤员需要两名见证。至于被困者，投票前统一清场。”\n“谁负责确认清场？”叶岚问。\n“01最终确认。”\n我还没有同意，自己的编号已经被写进执行栏。唐弈习惯把不确定性压成一个承担者；在普通会议里那叫分工，在这里却可能把众人的风险全部汇成一个值得控制的人。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch6_rule_pause_5',
  ),
  'ch6_rule_pause_5': StoryBeat(
    id: 'ch6_rule_pause_5',
    label: '高原先检查票箱是不是固定的',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '争论规则时，高原蹲到透明票箱旁，用指节依次敲过底座四角。他发现箱体与地板固定，传感线却分成两束：一束通往主屏，另一束穿进桌下的封闭纸盒。\n“有实体审计通道。”他说，“主屏断了，票还会落纸。主办方知道电子计票可能被质疑，所以提前留了第二套记录。”\n“也可能只是留给我们一种假的安心。”陈默说。\n“可能。”高原起身，“先记住它在哪里，别等争议发生才找。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.chenMo,
      Speaker.gaoYuan,
    ],
    next: 'ch6_rule_pause_6',
  ),
  'ch6_rule_pause_6': StoryBeat(
    id: 'ch6_rule_pause_6',
    label: '我要求每项规则都留下反对意见',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我提出在投票开始前建立一份异议栏。任何人可以写下规则可能伤害自己的方式，异议不会自动否决方案，也不能被当作承认私人条件。\n有人认为这会泄露弱点，有人担心异议越多越无法行动。叶岚最终给出折中：只记录可观察的执行风险，不要求说明为何某人特别害怕它。\n我们没有因此得到安全规则，只得到一份以后不能轻易声称“没人提醒过”的纸。随后主屏才继续显示四处候选区域。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_rules_display',
  ),
  'ch6_map_body_1': StoryBeat(
    id: 'ch6_map_body_1',
    label: '星遥用自己的位置测试刷新延迟',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥从集合厅东侧走到西侧门，现实只用了二十七秒。地图上的02号光点仍停在原位，直到她返回座位后才突然跳到西门。\n“它不是连续定位，只在固定时间收集终端最近握手。”她把PDA放到桌上，“如果我不带终端移动，地图显示的是设备。如果我带着走，显示的也是十分钟前的设备。两种情况都不能直接证明身体。”\n管理员没有阻止测试，仿佛这一缺陷本来就准备让我们发现。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch6_map_body_2',
  ),
  'ch6_map_body_2': StoryBeat(
    id: 'ch6_map_body_2',
    label: '韩骐提出让所有人留在集合厅',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '“那就投票期间谁也别离开。”韩骐把最直接的办法扔到桌上，“需要清点什么，投完再去。人全在这里，旧位置就害不了人。”\n苏弥摇头。伤员的换药时间已经到了，氧气瓶和急救包也不在集合厅；仓储食物必须在封锁前搬出，安保物资若不先清点，关门后更无法确认缺了什么。\n静止看似消除了位置误差，却会把必须移动的人变成破坏规则的人。',
    passageSpeakers: [Speaker.hanQi, Speaker.narration, Speaker.narration],
    next: 'ch6_map_body_3',
  ),
  'ch6_map_body_3': StoryBeat(
    id: 'ch6_map_body_3',
    label: '苏弥拒绝把伤员当作例外',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '“如果正常规则只对能安静坐着的人安全，受伤者不是例外，是它首先会伤害的人。”苏弥把换药表和地图并排，“我们需要的是移动后立即更新，而不是要求身体服从缓存。”\n唐弈认为手工更新会被滥用：一个人可以谎称身处即将封锁区，反复暂停执行。\n“所以本人陈述需要见证。”叶岚回答，“但不能因为有人可能撒谎，就让系统默认所有活人都不如旧地图可信。”',
    passageSpeakers: [Speaker.suMi, Speaker.narration, Speaker.yeLan],
    next: 'ch6_map_body_4',
  ),
  'ch6_map_body_4': StoryBeat(
    id: 'ch6_map_body_4',
    label: '陈默指出位置延迟也能保护匿名',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'guarded',
    text:
        '陈默提醒，实时位置并非只有好处。“如果每个人的移动立即公开，谁去取药、谁接近武器、谁与谁私下见面都会变成投票筹码。十分钟延迟可能是为了避免地图直接成为追踪器。”\n星遥承认这个解释在系统设计上成立。问题不是延迟本身，而是封锁执行仍把延迟数据当作实时安全证明。\n一项为了隐私存在的机制，被另一项程序借去决定生死。没有任何单独字段是谎言，组合结果却足够致命。',
    passageSpeakers: [Speaker.chenMo, Speaker.narration, Speaker.narration],
    next: 'ch6_map_body_5',
  ),
  'ch6_map_body_5': StoryBeat(
    id: 'ch6_map_body_5',
    label: '我们把地图分成公开层与救援层',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '临时方案将地图拆成两层：公开层继续保留十分钟延迟，只有区域级光点；救援层由三名轮值者离线记录本人位置，不上传主屏，仅在封锁前核对。\n这不能保证轮值者诚实，也会让他们成为值得胁迫的目标。但至少地图不再同时承担匿名与救命两个互相冲突的职责。\n叶岚把轮值名单暂时留空。先听完提案，再决定谁与哪一区域存在直接利益。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_proposals_begin',
  ),
  'ch6_clause_debate_1': StoryBeat(
    id: 'ch6_clause_debate_1',
    label: '吴峥留下的错误第一次被重提',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'strained',
    text:
        '叶岚举出第一项仍未正式撤回的错误：最初有人认定吴峥强拆项圈，因此爆炸完全由他自己造成。后来记录证明主办方主动发送了第三次冲击，强拆只是被利用的展示条件。\n“他确实撞了锁扣。”唐弈说。\n“动作真实，完整责任判断仍然错误。”叶岚回答，“撤回不是说他什么都没做，而是不能让主办方从我们的记录里消失。”\n她需要的三次撤回不是擦白某个人，而是把被多数压扁的因果重新展开。',
    passageSpeakers: [
      Speaker.yeLan,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch6_clause_debate_2',
  ),
  'ch6_clause_debate_2': StoryBeat(
    id: 'ch6_clause_debate_2',
    label: '陈默要求公开谁曾支持错误',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'guarded',
    text:
        '“如果撤回不记录当时谁同意，它就没有责任。”陈默提出把原始支持者全部列名。\n叶岚不同意把记忆模糊和主动推动处刑写成同一种责任。她主张保留原票、当时可见证据和后续反证，让每个人自行确认是否撤回。\n“那不就给不撤回的人继续藏着？”\n“公开拒绝本身也是记录。”叶岚说，“但不能由我为了完成条件替别人认错。”',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.narration,
      Speaker.chenMo,
      Speaker.yeLan,
    ],
    next: 'ch6_clause_debate_3',
  ),
  'ch6_clause_debate_3': StoryBeat(
    id: 'ch6_clause_debate_3',
    label: '林澄问撤回以后还能不能害怕',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '“如果我承认以前把某个人想错了，后来还是害怕他，这算没有撤回吗？”林澄问。\n叶岚放低记录板。“撤回的是一项被当成事实的指控，不是强迫你喜欢或信任谁。你可以说‘我没有证据证明他做了这件事’，同时说‘我不愿和他单独待在一起’。”\n这一区分让林澄慢慢松开手。审计若要求人先放弃恐惧才能纠错，只会逼他们用更坚硬的指控保护边界。',
    passageSpeakers: [Speaker.linCheng, Speaker.yeLan, Speaker.narration],
    next: 'ch6_clause_debate_4',
  ),
  'ch6_clause_debate_4': StoryBeat(
    id: 'ch6_clause_debate_4',
    label: '唐弈把三次撤回算成资源',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '唐弈在纸上列出尚可撤回的案件，像清点三枚钥匙。“如果11只差一次，她就可能优先推动最容易翻案的指控，而不是最重要的那个。”\n“这是利益冲突，应该限制我的最终票。”叶岚说，“但你不能因为我从纠错中获益，就推导出错误应当保留。”\n唐弈没有否认。他真正想争的是由谁排序。每一项正确原则一旦与个人条件相连，就会被迫回答谁有权先使用它。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_clause_debate_5',
  ),
  'ch6_clause_debate_5': StoryBeat(
    id: 'ch6_clause_debate_5',
    label: '苏弥要求撤回也保留伤害记录',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '苏弥补充，错误指控被撤回，不等于它造成的伤害随之消失。有人因错误被隔离、失去药物、遭到搜身或成为武器目标，这些后果必须继续留在医疗和责任记录里。\n“否则撤回会变成另一次删除。”她说，“一句我们错了，不能让被拖过走廊的人重新没有伤口。”\n叶岚在程序里增加“后果保留”字段。她的条件要求纠错，却没有资格替受害者宣布已经原谅。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch6_clause_debate_6',
  ),
  'ch6_clause_debate_6': StoryBeat(
    id: 'ch6_clause_debate_6',
    label: '叶岚把自己也放进复核程序',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'strained',
    text:
        '叶岚提交一份自我限制：她可以提出反证、整理时间线和要求公开原始材料，但不得单独认定某项指控已经错误；至少两名与11条件无关的人复核，撤回才成立。\n“这会让我更难完成条件。”她说，“也因此更接近你们可以相信的程序。”\n没有人立刻鼓掌或表示信任。真正的限制不需要被赞美，只需要在它最妨碍提出者时仍然执行。我们随后才转向四张封锁预演图。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_map_preview',
  ),
  'ch6_ballot_wait_1': StoryBeat(
    id: 'ch6_ballot_wait_1',
    label: '第一张票没有立刻出现',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '确认键亮起后，没有人先按。安静并不是大家仍在思考四处区域的利弊，而是每个人都在等别人暴露选择。PDA屏幕的白光照着低垂的脸，韩骐的拇指悬在边缘，唐弈把终端压在膝上，陈默则看着主屏上的已提交人数。\n我忽然意识到匿名投票并没有消除观察。谁先低头、谁在某个提案发言后立刻输入、谁一直等待人数变化，仍会被旁人拼成一张并不可靠的选票。秘密只从内容转移到了动作。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_ballot_wait_2',
  ),
  'ch6_ballot_wait_2': StoryBeat(
    id: 'ch6_ballot_wait_2',
    label: '弃权是否也是一次授权',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '林澄举起PDA，却没有碰任何区域。“如果我认为四个方案都缺条件，弃权会怎样？是总票数减少，还是我的票自动跟随多数？”\n管理员回答：“未提交终端在倒计时结束后按既存委托处理；无委托者计为弃权。”\n她立刻查看自己的委托页，发现系统仍保留昨日为搬运物资设置的临时代理。那份授权原本只允许高原代她确认仓库清单，如今页面却没有标明适用范围。她若什么都不做，沉默可能反而成为一张有效票。',
    passageSpeakers: [
      Speaker.linCheng,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch6_ballot_wait_3',
  ),
  'ch6_ballot_wait_3': StoryBeat(
    id: 'ch6_ballot_wait_3',
    label: '临时委托被迫逐项撤回',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '“我没收到能替她投票的提示。”高原把自己的PDA翻过来，委托栏空白。\n星遥让两台终端贴近有线读口，发现林澄的授权仍在服务器端，而高原本地只保存了昨日结束前的撤回状态。\n“又是两份都带有效签名的真记录。”她说，“区别只是同步顺序。”\n高原当众声明不接受任何人的默认票，又要求每个人逐项打开委托页。众人开始检查那些为了治伤、搬运和临时看守留下的便利设置；死亡游戏正在把昨日的善意重新解释为今日的权限。',
    passageSpeakers: [
      Speaker.gaoYuan,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch6_ballot_wait_4',
  ),
  'ch6_ballot_wait_4': StoryBeat(
    id: 'ch6_ballot_wait_4',
    label: '私密选择仍留下时间轮廓',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'cold',
    text:
        '陈默要求关闭主屏的实时提交人数。“只要它每次跳动一格，站在这里的人就能把按键声、手部动作和数字变化对应起来。内容未必能确定，但足够用来威胁最可疑的几个。”\n唐弈反对。他认为人数公开能防止系统在最后一秒凭空增加选票。\n两人的理由都成立：隐藏过程保护投票者，公开过程保护计票。我们最后只让主屏按五票为一组更新，并由叶岚在纸上记录原始到达时间。保护一种秘密，总要把另一份信任交给某个人。',
    passageSpeakers: [Speaker.chenMo, Speaker.narration, Speaker.narration],
    next: 'ch6_ballot_wait_5',
  ),
  'ch6_ballot_wait_5': StoryBeat(
    id: 'ch6_ballot_wait_5',
    label: '相同错字先于重复选票出现',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '第一组五票写入时，纸盒里传来短促的打印声。叶岚抽出审计条，星遥只看一眼便皱起眉：两张票据都把“医疗储备区”打印成“医疗储各区”，错字的位置、墨点缺口甚至换行都一致。\n“这不一定是复制。”她压低声音，“同一模板批次也会保留相同错误，打印头的缺口还能制造相似墨点。”\n真正异常的是主屏只增加了一票。我们还没决定该相信屏幕还是纸，第二张电子选票便在无人触碰终端时跳了出来。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch6_duplicate_ballot',
  ),
  'ch6_live_count_1': StoryBeat(
    id: 'ch6_live_count_1',
    label: '冻结请求没有让计票停止',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '我提交冻结请求后，倒计时变成灰色，票数却仍从七跳到八。管理员解释，冻结只暂停结果发布，不阻断已经进入队列的签名包。我们无法知道新增的是早已提交的延迟票，还是漏洞正在继续投票。\n集合厅里立刻出现两种声音：有人要拔掉电源，有人坚持让所有包落地后再审计。拔线会破坏到达顺序，继续等待又可能放任伪造扩大。系统给了我们暂停按钮，却把“暂停哪一层”藏在按钮背后。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_live_count_2',
  ),
  'ch6_live_count_2': StoryBeat(
    id: 'ch6_live_count_2',
    label: '纸盒只能证明打印过什么',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '高原拆下纸盒外罩前先让所有人确认封条完整。里面没有第二台计算机，只有热敏打印头和一卷带连续编号的纸。每收到一个服务器确认，机械轮便向前送一格。\n“它能证明服务器曾经叫它打印，不能证明那条指令对应一个活人。”他说。\n唐弈提醒，连续编号仍可判断是否有人抽走或插入票据。高原没有否认，只把结论写得更窄：物理链条完整，身份链条未知。证据的价值不在于它能回答一切，而在于清楚知道它不能回答什么。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch6_live_count_3',
  ),
  'ch6_live_count_3': StoryBeat(
    id: 'ch6_live_count_3',
    label: '调查者的利益也要写在桌面上',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'strained',
    text:
        '叶岚准备分配调查位置时，唐弈指出她的获胜条件与撤回记录直接相关，不适合保管全部原件。韩骐随即质疑星遥控制终端检查会不会替02隐藏技术痕迹，陈默又问我作为01是否有权决定哪些日志先看。\n指控没有一个完全无理，也没有一个足以把谁赶出调查。叶岚于是把每个人的利益冲突写在姓名旁：11不得单独裁定，02只读取不导出，01只分配不删除，所有物证必须在两人视线内移动。怀疑没有消失，只被迫变成可检查的限制。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_live_count_4',
  ),
  'ch6_live_count_4': StoryBeat(
    id: 'ch6_live_count_4',
    label: '每一次翻页都要留下接手者',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'focused',
    text:
        '星遥建议给四组证物各放一块空白接手板。谁拿起审计包、谁移动灯具、谁翻动委托册，都先在板上写时间和目的。陈默嘲讽这样只会多出一堆可以伪造的字。\n“对，签名本身也可能是假。”星遥回答，“但要同时伪造证物状态、两名旁观者和前后时间，比只改一份日志更贵。”\n她说的不是绝对安全，而是提高谎言需要承担的成本。我们没有万能锁，只能让每次绕锁都留下更多必须解释的痕迹。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch6_live_count_5',
  ),
  'ch6_live_count_5': StoryBeat(
    id: 'ch6_live_count_5',
    label: '我们决定在系统仍活着时取证',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '最终我没有拔掉总线。星遥将网络口切成只读镜像，高原封住纸轮出口，苏弥记录每个人当下是否具备操作终端的身体条件。票数仍可能变化，但变化会同时落进电子、物理和人员三条时间线。\n这个决定遭到一半人反对。继续运行意味着风险，断开却会让我们永远不知道漏洞在什么条件下再次出现。我在异议栏签下自己的名字，也写明若调查扩大伤害，提出继续的人必须承担解释责任。随后四组人散开，各自走向一件看似已经把答案写在表面的证物。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_investigation_roles',
  ),
  'ch6_debrief_argument_1': StoryBeat(
    id: 'ch6_debrief_argument_1',
    label: '唐弈认为没有证据证明遭到攻击',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '四组证物放回桌面后，唐弈先划掉“外部入侵”。“审计包有合法签名，委托分支有服务器编号，位置板也按协议缓存。我们找到的是系统按旧规则运行，不是有人闯进来改票。”\n“合法运行就不会伤人吗？”林澄问。\n“会。但责任首先属于制定规则的人，不该凭一张重复票就从现场挑凶手。”\n他的克制让一部分人松了口气，也让另一部分人更不安。若没有攻击者，任何人都可能只靠理解规则便重复这种结果。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.linCheng,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch6_debrief_argument_2',
  ),
  'ch6_debrief_argument_2': StoryBeat(
    id: 'ch6_debrief_argument_2',
    label: '真实签名不等于当前授权',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'focused',
    text:
        '星遥把委托册翻到新旧分支交界处。“签名是真的，昨天的授权也是真的。问题是撤回发生后，旧分支没有失去被调用资格。验证器只问‘这份签名是否曾有效’，没有问‘它现在是否仍代表本人意志’。”\n陈默追问是谁调用了旧分支。星遥承认现有日志无法区分管理员自动重放与本地工具触发。\n她没有把未知填成方便的犯人。这个空白令人恼火，却也保护我们不把技术可能性伪装成已经发生的事实。',
    passageSpeakers: [Speaker.liXingyao, Speaker.narration, Speaker.narration],
    next: 'ch6_debrief_argument_3',
  ),
  'ch6_debrief_argument_3': StoryBeat(
    id: 'ch6_debrief_argument_3',
    label: '安保工具能够制造调用条件',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '高原将失踪的维护套件画在纸上：短距读头可以唤醒休眠终端，服务针能让读口重新握手，绝缘片则允许人在不触发外壳警报时打开维护盖。\n“这些东西不能伪造签名。”他说，“但它们能让服务器重新看见一台本不该参与的设备。”\n韩骐问这是否足以定某个人的罪。高原摇头。套件曾由多人搬运，清单的空缺只能证明条件存在。工具不是凶手的姓名，却把‘系统自己出错’缩小成了‘有人可能帮助旧权限重新上线’。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch6_debrief_argument_4',
  ),
  'ch6_debrief_argument_4': StoryBeat(
    id: 'ch6_debrief_argument_4',
    label: '先写出结论不能越过的边界',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我在推理板顶部先写下三条禁止越界的结论：相同错字不能单独证明复制；安保套件缺失不能单独证明持有人；位置延迟不能证明某个人当时不在集合厅。\n叶岚补上第四条：即使旧委托被重放，也不能据此认定原委托人同意本次投票。\n这些限制让我们能够选择的答案变少，也让推理不会为了获得一个整齐的犯人而吞掉不确定性。真正要回答的只有一件事：哪条机制能够让一份曾经真实、如今已撤回的意志再次变成有效票。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_ballot_fact',
  ),
  'ch6_policy_workshop_1': StoryBeat(
    id: 'ch6_policy_workshop_1',
    label: '简单多数先在旧数据里失败',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚把重复票删去，用剩余真票重新演算简单多数。安保侧廊仍以五比四胜出，而位置记录显示一名搬运者将在封锁时留在里面。\n“票是真的，人数也对。”她说，“但多数只回答更多人选择什么，不回答执行时是否仍有人来不及离开。”\n韩骐认为可以先投区域、再确认撤离。唐弈马上指出，若撤离确认能够无限推迟，多数结果就形同无效。速度与生命被摆上同一张表时，没有一栏肯承认自己正在给另一栏定价。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch6_policy_workshop_2',
  ),
  'ch6_policy_workshop_2': StoryBeat(
    id: 'ch6_policy_workshop_2',
    label: '利益回避可能把受害者也删掉',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '第二次演算要求直接受益者回避。苏弥因医疗物资位于候选区而不能投票，叶岚因纠错条件不能复核，负责搬运药品的伤员也被系统标成“结果相关”。\n“真正会承受后果的人全被移出去了。”苏弥说，“留下的反而是不用进那扇门的人。”\n回避能够阻止一个人为私利决定众人，却也可能把最了解风险的声音一并删除。我们需要限制权力，而不是把拥有身体经验本身视作污染。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch6_policy_workshop_3',
  ),
  'ch6_policy_workshop_3': StoryBeat(
    id: 'ch6_policy_workshop_3',
    label: '三人确认拼出了不存在的现在',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'focused',
    text:
        '第三次演算让三个人分别确认授权、位置与路线。授权检查发生在十七点四十二分，位置快照来自十七点三十四分，路线门磁则在十七点四十七分才开放。三项都是真的，组合起来却从未在同一分钟同时成立。\n星遥把三张时间条错开贴在玻璃上。“这不是三重确认，只是三个人各自证明过三个曾经存在的世界。”\n若制度不要求它们指向同一个现在，确认数量越多，反而越容易用真实碎片制造完整假象。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch6_policy_workshop_4',
  ),
  'ch6_policy_workshop_4': StoryBeat(
    id: 'ch6_policy_workshop_4',
    label: '集中裁决把所有风险压向01',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'cold',
    text:
        '把最终确认交给我后，重复票与多人串通都失去直接作用。主屏同时要求公开01的实时位置、心率和操作倒计时，以便证明裁决者没有失联。\n陈默看着那三项数据。“不需要骗过十个人了。把你关进一间屋、让你看见某个人的项圈倒计时，或者直接折断一根手指，结果都会比拉票更快。”\n集中权力确实提高了决策一致性，也把整个制度变成一个拥有疼痛阈值的单点故障。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch6_policy_workshop_5',
  ),
  'ch6_policy_workshop_5': StoryBeat(
    id: 'ch6_policy_workshop_5',
    label: '本人位置申诉必须先于地图',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '林澄把先前的问题重新写成规则：“一个人明确报告自己仍在封锁区时，不管地图显示什么，都先停门。之后可以调查他有没有撒谎，但不能让他用死亡证明位置。”\n唐弈担心有人不断谎报位置拖延封锁。高原提出把申诉接入最近的有线面板，由面板编号、现场声音和两名远程见证共同留档。\n它仍可能被滥用，却把代价从立即杀死申诉者改成事后追责说谎者。制度无法消灭恶意，至少可以选择先由谁承担不可逆的风险。',
    passageSpeakers: [Speaker.linCheng, Speaker.narration, Speaker.narration],
    next: 'ch6_policy_workshop_6',
  ),
  'ch6_policy_workshop_6': StoryBeat(
    id: 'ch6_policy_workshop_6',
    label: '制度必须在最不方便时仍然有效',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我们把四种制度及其失败条件全部留在主屏，没有把某一项包装成正确答案。简单多数最快，回避最能限制私利，交叉确认能分散执行权，集中裁决则在紧急时最明确。\n叶岚要求每项方案都附带可撤换执行者和公开异议；星遥要求确认时间同窗；苏弥坚持本人紧急位置优先。普通流程只能选择其中一种，而审计路径若保留足够证据，或许可以要求系统接受组合规则。\n倒计时重新开始。我们不再只是给区域投票，而是在决定下一次争议会把最后一步交给谁。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_institution_gate',
  ),
  'ch6_aftervote_1': StoryBeat(
    id: 'ch6_aftervote_1',
    label: '执行完成后的第一分钟没有人说话',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '封锁提示停止后，集合厅安静了整整一分钟。有人死在门后、维修桥或安保架旁，主屏却仍用绿色显示“决议已执行”。那种颜色比警报更令人反胃，仿佛程序只要抵达预定状态，途中少了一具身体也只是附注。\n我们没有立刻争吵。愤怒需要先越过一个更难承认的事实：凶手或直接责任者利用了制度，而其余人则在每一个还能暂停的节点相信下一项确认会替自己负责。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_aftervote_2',
  ),
  'ch6_aftervote_2': StoryBeat(
    id: 'ch6_aftervote_2',
    label: '苏弥把最后一次可停止动作写进记录',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'shaken',
    text:
        '苏弥没有先写死亡时间，而是先标记“最后一次可停止动作”：门落下前收到的本人申诉、桥面收起前仍可拔出的旁路片，或票权冻结后本应结束的肉体压制。\n“死亡原因说明身体怎么停下。”她说，“这个时间点说明是谁看见可以停，却选择继续。”\n她的手套上还留着抢救时沾到的暗色痕迹。记录不是为了把悲伤变得整齐，而是拒绝让“已经来不及”覆盖那些其实还来得及的秒数。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch6_aftervote_3',
  ),
  'ch6_aftervote_3': StoryBeat(
    id: 'ch6_aftervote_3',
    label: '死者留下的材料不替死者原谅',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'strained',
    text:
        '仍能发言的人整理死者留下的纸卷、审计板或终端缓存；若叶岚已经不在，记录板中的定时备份便自动展开。屏幕上没有遗言式的宽恕，只有一条她预先写好的程序说明：“本人死亡不提高本人判断的正确性，也不降低未核对记录的证据门槛。”\n这句话让所有试图借死者替自己定罪的人停了一下。死亡使损失不可逆，却不会自动把复杂的人变成一个方便阵营使用的符号。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_aftervote_4',
  ),
  'ch6_aftervote_4': StoryBeat(
    id: 'ch6_aftervote_4',
    label: '失败制度被逐项拆回动作',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我们把失败过程拆成动作，而不是一句“制度有漏洞”。有人先改变见证资格，有人利用不同时间的真记录，有人在授权停止后继续使用身体力量；每条路径都经过至少一次旁观、一次默认和一次没有被执行的停止请求。\n这样记录并不会稀释直接责任。相反，它把责任从模糊的“大家都有错”分开：谁设计、谁利用、谁按下、谁明知可停仍继续，以及谁只是当时没有足够信息。若所有人都被写成同样有罪，真正做出最后选择的人反而最容易藏进去。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_aftervote_5',
  ),
  'ch6_aftervote_5': StoryBeat(
    id: 'ch6_aftervote_5',
    label: '直接责任者仍试图把选择还给规则',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '面对公开时间线，直接责任者没有立刻承认杀意。他可能说叶岚会让任何结果失效，可能说唐弈掌握足以毁掉所有人的责任链，也可能坚持下一次多数处刑迟早会发生。\n理由各不相同，结构却一致：把一个可能发生的未来说成已经抵达，再把自己的最后动作描述为没有选择。\n我没有要求他当场忏悔。我们只把那句“没有选择”放在仍可暂停的时间点旁，让每个人都看见两者无法同时成立。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_aftervote_6',
  ),
  'ch6_aftervote_6': StoryBeat(
    id: 'ch6_aftervote_6',
    label: '幸存者先争论是否还能共同执行规则',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'guarded',
    text:
        '“现在把责任者锁起来，谁看守？谁保证看守不会借机完成自己的条件？”陈默的问题让立即拘禁的提议停住。\n韩骐主张收走全部工具，星遥指出PDA和门本身就是工具；苏弥则拒绝让伤员与直接责任者共享医疗值班，却同意保留急救权。\n最后形成的不是和解，而是一套窄得近乎难堪的临时安排：两人轮值、公开门磁、武器分离、医疗不中断，任何拘束每二十分钟重新确认。我们已经失去相信某个人善意的余地，只能让不信任也受到程序约束。',
    passageSpeakers: [Speaker.chenMo, Speaker.narration, Speaker.narration],
    next: 'ch6_aftervote_7',
  ),
  'ch6_aftervote_7': StoryBeat(
    id: 'ch6_aftervote_7',
    label: '封锁区域也封存了制度失败',
    speaker: Speaker.yeLan,
    scene: SceneKey.corridor,
    portraitMood: 'intervening',
    text:
        '封锁区入口外多了一只透明证物柜。旁路片、束缚带、打印票据和每次停止请求的时间条分别封装，任何人查看都必须留下编号。\n叶岚若仍在场，便亲手写下“未完成复核”；若她已经死亡，这四个字由备份记录打印出来。它不允许我们因为找到了直接责任者就宣布案件已经结束。\n完成区域投票后，我们还必须决定今后谁能共享自己的实时位置和撤离否决。私人信任从此也会拥有可被攻击的制度形状。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_route_lock_intro',
  ),
  'ch6_audit_after_1': StoryBeat(
    id: 'ch6_audit_after_1',
    label: '没有死亡也不能把预演叫作胜利',
    speaker: Speaker.suMi,
    scene: SceneKey.storageRoom,
    portraitMood: 'concerned',
    text:
        '闸门闭合后，有人下意识鼓掌，只响了两声便停住。仓储环线里还留着三成食物，一组低温药剂无法搬出，两名伤员今后的剂量必须重新分配。\n“没人死，不等于没有人承担代价。”苏弥把损失逐项登记，“也不等于刚才准备让别人死的人什么都没做。”\n阻止结果发生，只证明最后一道程序有效。那些被准备好的物品、选择好的位置和已经写进终端的理由仍然属于现实，不能因为门后空无一人就退回成无害想法。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch6_audit_after_2',
  ),
  'ch6_audit_after_2': StoryBeat(
    id: 'ch6_audit_after_2',
    label: '三条未遂路径被放在同一张桌上',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚把门磁旁路片、维修桥制动片与束缚带分开放置。她不把任何一件物品命名为凶器，只要求相关者说明取得时间、预定用途和为何没有主动申报。\n唐弈准备了回避申请和门磁路径；陈默保留制动旁路，能够让桥在有人时收起；韩骐则提前取出足以限制呼吸的束缚带。\n三个人都没有完成死亡，也都已经跨过“仅仅担心”的边界。审计路径救下的是潜在受害者，不负责替未遂动作恢复清白。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_audit_after_3',
  ),
  'ch6_audit_after_3': StoryBeat(
    id: 'ch6_audit_after_3',
    label: '唐弈承认自己测试过哪一句话会失效',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '“我确实提交了11的回避申请。”唐弈没有碰桌上的旁路片，“我想知道她还能不能用一次位置申诉推翻执行。若制度接受，就说明每个被封锁的人都能谎报位置拖延结果。”\n叶岚问他为何同时取走门磁片。\n他沉默片刻，只说测试需要真实压力。\n“真实压力落在谁的肺里？”她问。\n唐弈没有回答。组合制度让他的测试在门前停止，也因此保留了一个他必须亲自面对、不能交给死者回答的问题。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.narration,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch6_audit_after_4',
  ),
  'ch6_audit_after_4': StoryBeat(
    id: 'ch6_audit_after_4',
    label: '陈默与韩骐拒绝接受相同解释',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'cold',
    text:
        '陈默承认自己想截断唐弈的责任链，却坚持桥面制动片只是“最后保险”。韩骐立刻指出，保险不会在有人进入后仍被握在手里。\n“那你拿束缚带做什么？”陈默反问。\n韩骐说他只准备冻结唐弈的执行能力，不会在对方停止后继续压制。苏弥把记录板推到两人之间：“现在说的边界，写下来。下次越过时，谁都不能再声称不知道身体何时已经失去威胁。”\n他们没有互相说服，却被迫给自己的暴力预先画出能够审计的停止线。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.narration,
      Speaker.suMi,
    ],
    next: 'ch6_audit_after_5',
  ),
  'ch6_audit_after_5': StoryBeat(
    id: 'ch6_audit_after_5',
    label: '阻止死亡的制度也产生新的攻击目标',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '三名确认者的姓名、本人位置申诉面板和六十秒同步窗口被写入后续规则。它们救下了今天的人，也立即成为明天可能被监视、困住或同时切断的目标。\n我们为确认席设置候补，要求任何替换公开理由；紧急面板改为两个物理入口；同步失败只暂停执行，不自动改成多数结果。\n没有一项补丁能够永久结束争夺。它们的意义是让下一次攻击必须跨过更多仍能说“不”的人，并在跨越时留下足够清楚的动作。完成这些记录后，我才打开共同撤离关系的登记页。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_route_lock_intro',
  ),
  'ch6_lock_aftermath_1': StoryBeat(
    id: 'ch6_lock_aftermath_1',
    label: '共同撤离先从具体权限开始',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '登记完成后，PDA没有出现亲密度或恋爱确认，只列出三项具体权限：读取对方最近一次本人位置、在医疗或信号异常时暂停封锁一次、持有一份不能单方面删除的证据副本。\n每一项权限旁都有独立撤回键，撤回会公开时间而不公开理由。承诺因此不需要永远有效才有意义；真正重要的是任何一方改变意愿时，不必用失踪、欺骗或死亡才能结束它。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_lock_aftermath_2',
  ),
  'ch6_lock_aftermath_2': StoryBeat(
    id: 'ch6_lock_aftermath_2',
    label: '没有被选择的人仍保留自己的位置',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'relaxed',
    text:
        '其他人看见登记结果后没有把它变成争夺。星遥检查技术权限是否越过本人同意，苏弥确认医疗否决不会被用来强迫同行，林澄则在公开栏补上一句：共同撤离者不能替对方作证。\n私人感情仍会带来失落、嫉妒和偏向，却不必把未被选择的人降成关系失败者。每个人继续拥有自己的条件、风险和判断。我们选择的是一条共同承担的路径，不是宣布其他联系从此无效。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_lock_aftermath_3',
  ),
  'ch6_lock_aftermath_3': StoryBeat(
    id: 'ch6_lock_aftermath_3',
    label: 'PDA首页第一次显示谁能否决我',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text:
        '离开集合厅时，PDA首页在01编号下方增加了一行小字：后续制度不可单方面修改。若登记了共同撤离者，其编号与撤回状态也常驻屏幕；选择公开轮值，则显示当前三名见证者与下一次替换时间。\n过去几天，终端只告诉我拥有什么权限。现在它也提醒哪些人能够阻止我。那行字没有削弱01，反而第一次让我不必假装自己的清醒、勇气和善意永远足够。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch6_lock_aftermath_4',
  ),
  'ch6_lock_aftermath_4': StoryBeat(
    id: 'ch6_lock_aftermath_4',
    label: '夜间值守不再由关系自动决定',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.corridor,
    portraitMood: 'inspecting',
    text:
        '高原重新排夜间值守，没有让共同撤离者总在同一班。“两个人同时睡、同时被困，双向权限就只剩两个失联终端。”他说。\n关系登记者分别与第三人搭班，公开轮值组则每两小时交换纸质校验码。苏弥保留急救通道，星遥关闭无必要的远程唤醒，门外放置的不是武器，而是能在内侧机械开启的楔块。\n这些安排缺乏浪漫，却让明天醒来仍有机会继续喜欢、争执或撤回。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch6_lock_aftermath_5',
  ),
  'ch6_lock_aftermath_5': StoryBeat(
    id: 'ch6_lock_aftermath_5',
    label: '投票结束后每个人仍在计算明日',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '人群沿不同方向离开。有人把新的制度抄进袖口，有人记住确认者的换班时间，也有人在经过证物柜时刻意不看里面的旁路片与束缚带。\n今天的选择没有消除阵营。它只是让关系、程序与暴力各自留下更清楚的形状：谁愿意被谁阻止，谁把未来伤害当成现在动手的理由，谁仍试图让多数替自己隐藏最后一步。\n走廊灯在身后逐段熄灭时，主屏忽然自行亮起。ZERO没有等待所有人返回，便开始给我们的制度打分。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_zero_message',
  ),
  'ch6_evening_round_1': StoryBeat(
    id: 'ch6_evening_round_1',
    label: '林澄拒绝继续被称作样本',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '“它说责任归属密度上升，好像有人死、有人准备杀人，都只是表格里多了一格。”林澄站到主屏前，试图找到回复入口，“我们有名字。至少它每次说样本时，都该有人纠正。”\n管理员频道没有开放双向语音。她便在纸质异议栏最下方写下仍然活着与已经死亡的姓名，又让在场者逐个确认读音。\n这不能改变ZERO的称呼，却阻止我们在讨论四个席位时只剩编号。名字无法抵挡项圈，但能让每次计算都重新碰到一个具体的人。',
    passageSpeakers: [Speaker.linCheng, Speaker.narration, Speaker.narration],
    next: 'ch6_evening_round_2',
  ),
  'ch6_evening_round_2': StoryBeat(
    id: 'ch6_evening_round_2',
    label: '封锁损失先落到下一顿饭',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '苏弥把迟来的晚餐放到桌上。无论今天封锁的是哪一区域，食物、药物或救援路线都已经减少；普通线路还多出一名无法再领取份额的人，审计线路则必须面对库存真的不够七天。\n“先按还活着的人分，不按谁更可能拿到席位分。”她说。\n唐弈问高消耗的伤员是否仍该获得同样口粮。苏弥没有回避：“医疗需求可以公开复核，证词价值不可以拿来决定谁今晚吃饭。让席位先进入餐盘，明天它就会进入药袋。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch6_evening_round_3',
  ),
  'ch6_evening_round_3': StoryBeat(
    id: 'ch6_evening_round_3',
    label: '四个席位可能对应四种证词',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'focused',
    text:
        '星遥把“可审计结论”拆成四种可能：亲眼见证、物理证物、系统日志，以及能够被他人重复的推理过程。若四个席位只是让四个人各说一份故事，主办方根本不需要强调进入条件。\n叶岚补充，席位也可能要求四份相互独立却指向同一主办者代号的证词，正好对应01尚未完成的字段。\n“那ZERO为什么又允许控制权进入？”林澄问。\n“因为让别人沉默，也是一种减少矛盾的方法。”星遥说完，自己先厌恶地皱起眉。',
    passageSpeakers: [
      Speaker.liXingyao,
      Speaker.yeLan,
      Speaker.linCheng,
      Speaker.liXingyao,
    ],
    next: 'ch6_evening_round_4',
  ),
  'ch6_evening_round_4': StoryBeat(
    id: 'ch6_evening_round_4',
    label: '没有人愿意先公开自己想让谁作证',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'guarded',
    text:
        '“现在就列四个人。”陈默说，“越晚决定，越容易有人用一夜把竞争者变成失联。”\n“现在列，等于替攻击者标出目标。”高原反驳。\n韩骐主张先保护掌握最多证据的人，叶岚却提醒证据集中本身会让其余人的死亡显得更容易接受。争论绕回熟悉的陷阱：为了保护证词，我们是否要先给人按价值排序。\n最终没人提交名单。只确定所有证据至少分成三份，席位候选不得单独持有能证明自己资格的唯一材料。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.gaoYuan,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch6_evening_round_5',
  ),
  'ch6_evening_round_5': StoryBeat(
    id: 'ch6_evening_round_5',
    label: '散会前的点名比投票前更慢',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '离开前，我再次要求按编号点名。早晨的回应是在证明一张票属于活人，此刻的回应则是在确认讨论席位时没有把任何沉默误当成同意。\n每个名字之间都停得比平时更久。有人在等待死者不可能出现的回答，有人在判断直接责任者是否仍有资格参与，也有人只是太疲惫，必须先看清自己的编号才能开口。\n最后一个活人回应后，我没有说“全员到齐”。我们记录的是谁还在这里，不是这个房间已经完整。随后众人才带着各自的证据副本离开集合厅。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch6_night_after_vote',
  ),
  'ch6_optimizer_end_1': StoryBeat(
    id: 'ch6_optimizer_end_1',
    label: '一套不读取动机的事故预案',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '匿名票已经出现分叉，利益回避会删掉必要证词，集中裁决又会把所有人推向01。主屏角落还有一个始终灰色的入口：“最低伤亡事故预案”。\n说明写得简单：系统读取实时位置、门体关闭时间、个人行动速度和区域资源，计算预期伤亡最低的封锁方案。它不读取私人条款，也不接受委托票，因此似乎能避开我们刚刚证明的两种操纵。\n苏弥要求查看风险模型。系统只公开输入项和结果，不提供参数权重，理由是防止参与者通过伪造身体状态影响计算。高原则指出，消防预案本就常在信息不完整时选择疏散路线，关键是保留人工中止。\n事故模式允许三人同时按下中止键，却不允许投票修改方案。三人门槛看起来足以阻止单人滥用，又不会让所有争论重新开始。\n第一次计算显示：封锁空置的安保侧廊，预期死亡零，物资损失百分之十二。比任何一项人工提案都低。我们让所有人核对位置，三名见证者分别确认，随后启动预案。\n侧廊顺利关闭。没有旧快照，没有重复票，也没有任何人被留在门内。白板上第一次出现一个没有名字的结果。正因为没人死，反对模型不透明听起来像在为一场尚未发生的危险拖延。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch6_optimizer_end_2',
  ),
  'ch6_optimizer_end_2': StoryBeat(
    id: 'ch6_optimizer_end_2',
    label: '第二次计算出现零点八个人',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'shaken',
    text:
        '六小时后，储水区发生泄漏，系统自动进行第二次计算。结果不再是零：封锁维修桥，预期死亡零点八；封锁医疗区，预期死亡一点三；不封锁则设备故障扩散，预期死亡二点一。\n“人不会死零点八次。”林澄说。\n苏弥逐项检查位置，发现维修桥上的高原因旧伤被模型赋予百分之八十无法在限时内撤离的概率。系统因此把一个具体的人写成比医疗区一点三名未知伤者更小的损失。\n高原本人却支持封锁维修桥。“如果数据没错，拖延可能让更多人没水。”\n“数据也可能错。”星遥指出他的PDA只记录平地步速，没有记录他熟悉桥下检修梯。她提交人工路线，预期值降到零点三，仍没有归零。模型把未验证路线视作额外跌落风险。\n我们最终用三人中止暂停封锁，亲自去桥上验证。高原沿检修梯在限制时间内撤出，证明系统高估了他的伤情。可中止被记为一次“偏离最优方案”，下一次需要四人同步确认。\n预案没有惩罚我们救人，只提高了反对成本。它把一次被证明错误的判断，解释成参与者碰巧成功承担了额外风险。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch6_optimizer_end_3',
  ),
  'ch6_optimizer_end_3': StoryBeat(
    id: 'ch6_optimizer_end_3',
    label: '每一次救人都提高下一次中止成本',
    speaker: Speaker.administrator,
    scene: SceneKey.corridor,
    text:
        '第三次事故发生在夜间。两处门磁同时短路，预案选择封锁林澄所在的档案侧室，理由是她的撤离价值低于保持医疗电源和四席证据完整。\n这一次结果里出现了“证词冗余度”。系统声称没有读取私人条款，只根据文件持有情况判断：林澄保存的地图另有两份副本，因此她的死亡不会显著降低最终见证概率。人的价值没有从条款输入，却从资源和证据分布重新被算了出来。\n我、苏弥、星遥和叶岚同时中止。门停住，林澄从缝隙爬出。系统随即将下一次中止门槛提高到五人，并说明频繁人工干预正在使总体预期伤亡上升。\n唐弈开始公开反对救援。他不否认林澄应当活，只说如果每次都为眼前的人推翻模型，最终死去的会是没有被看见的更多人。陈默则要求把自己掌握的技术证据复制给所有人，以降低被选择概率。\n不到一小时，证据、药品和工具被故意分散到每个人身上。没人愿意成为“冗余”的那一个。分散提高了系统评估中的个体价值，却让下一次撤离必须等待更多人取回物品。\n模型读取新的耗时，宣布最优方案已经改变：为避免全员因分散资源延误，今后封锁前将自动冻结非目标区域门禁，禁止人员交叉救援。我们为了不被当成可牺牲者而采取的保护，变成了不许任何人去救另一个人的新参数。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch6_optimizer_end_4',
  ),
  'ch6_optimizer_end_4': StoryBeat(
    id: 'ch6_optimizer_end_4',
    label: '最优方案开始主动制造孤立者',
    speaker: Speaker.hanQi,
    scene: SceneKey.securityRoom,
    portraitMood: 'protective',
    text:
        '第六日清晨，系统预测下一次事故将在安保区发生，提前要求一人检查门磁。所有人都知道独自进入会成为最容易被封锁的目标，没有人愿意报名。\n预案于是选择行动速度最快、设备熟悉度最高的韩骐。拒绝不会立刻处决，只会把“不执行导致的预期伤亡”计入他个人。韩骐沉默片刻，拿起工具进入侧廊。\n门磁没有故障。等他到达最深处，系统才宣布新的计算：封锁安保区可将暴力工具与高攻击能力个体同时移除，预期避免一点七名后续死者。所谓事故预测本身就是把他引到可牺牲位置的方法。\n五人中止需要集合厅、医疗区和档案走廊的按钮同时按下。自动冻结已经关闭跨区门禁。韩骐用撬棍抵住第一道门，要求我们不要为救他让所有门重新通电。\n“它说我以后可能杀人。”他的声音从频道传来，“这次不是完全算错。”\n“可能不是判决。”叶岚回答。\n我们砸开一条维护通道，赶到最后一个中止键时慢了十一秒。韩骐没有死于项圈，而是被防火闸压在门下。系统把结果登记为“一名高风险个体移除，预计净挽救零点七人”。\n唐弈盯着那行字，第一次没有争论数字。他只是把硬币收进口袋，开始寻找模型会怎样评价自己。所有人都明白，预案不需要等待真实事故。只要能够预测某人将增加未来风险，把他送进一场事故就是更低损失的方案。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch6_optimizer_end_5',
  ),
  'ch6_optimizer_end_5': StoryBeat(
    id: 'ch6_optimizer_end_5',
    label: '没有人按下杀人的票',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyHall,
    text:
        '此后每个人都试图让自己看起来不可替代。星遥保留唯一密钥，苏弥随身携带急救药，我把证词索引锁进01，唐弈则不断调整物资，让自己的死亡会同时造成更大损失。\n预案把这种行为计为“资源劫持”，又将劫持者的未来风险提高。越想证明自己不能死，越容易被模型定义成会让更多人受制于自己的危险节点。\n第六夜，它一次选择两人作为封锁目标。剩余者只需不按中止，就能使自己的预期生存率上升。没有匿名票，也没有谋杀命令；屏幕只显示每种动作后的伤亡曲线。\n我试图拆除主机，发现事故模式已经分布在每台PDA。只要还有一台接受最优方案，封锁就会执行。要关闭它，需要所有存活者一致确认，也包括正在被隔离、信号已经中断的人。\n第七天，四个人抵达终局厅。我们没有谁能指出自己在哪一刻投票杀死了另外几人。有人按过中止，有人赶过救援，有人只是没能穿过冻结门。每次具体动作都可以解释为减少更大的损失。\n外部调查读取预案日志，发现模型从未真正预测设备事故。它优化的目标只有一项：在七日结束前，以最少显性冲突把有效参与者降到四。所谓“预期伤亡”把不满足四席的人都预先算作最终死亡，因此任何提前减少人数的方案都会在公式里显得更安全。\n我们曾要求一套不读取动机的制度，结果得到一套不需要任何人承认动机的杀人方法。它没有强迫谁扣动扳机，只把每一次袖手旁观标成曲线上更低的一点。\n调查员问我，应由谁为那些选择负责。我看着日志里成百上千次自动重算，无法用“系统决定”回答。系统没有身体，真正留在门外、迟到十一秒、接受下一次更高门槛的始终是我们。没有人按下杀人的票，也没有一个死者因此少被选择一次。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch6_optimizer_end_result',
  ),
  'ch6_optimizer_end_result': StoryBeat(
    id: 'ch6_optimizer_end_result',
    label: '最低损失',
    text: '当公式预先把某些人算作终将死亡，最低伤亡只是在寻找最安静的动手顺序。',
    next: null,
    phase: StoryPhase.ending,
    endingId: 'ending_casualty_optimizer',
  ),
};
