part of 'story.dart';

const chapterFiveBeats = <String, StoryBeat>{
  'ch5_midnight': StoryBeat(
    id: 'ch5_midnight',
    label: '零点前最后六十秒',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    timelineMinute: 4320,
    text:
        '倒计只剩六十秒时，走廊里没有人再询问是否应该进入E-04。昨天的死亡或封存已经替我们作出一半决定：留在原地，校验字段仍会公开；向前，至少能看见是谁准备好了这场公开。\n档案库门上没有把手，只有十二枚依次亮起的身份灯。05与10已经熄灭，昨天新增的死亡也留下暗格，最末一枚白灯却比活人的编号更稳定。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_last_roll_call',
  ),
  'ch5_last_roll_call': StoryBeat(
    id: 'ch5_last_roll_call',
    label: '有人坚持再点一次名',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'anxious',
    text:
        '林澄把折过许多次的纸名单摊在门边，从01开始逐一念到11。活着的人用声音回应，死亡的人由她报出姓名和时间。\n“12号。”\n门内传来一声电子确认，像有人隔着钢板按下了应答键。林澄没有在纸上画勾，只写下“设备回应，未见本人”。\n“它越想像个人，我们越不能替它把这一笔补完。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
      Speaker.linCheng,
    ],
    next: 'ch5_unlock_bell',
  ),
  'ch5_unlock_bell': StoryBeat(
    id: 'ch5_unlock_bell',
    label: '加密锁同时打开',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveCorridor,
    text:
        '零点整，所有PDA发出同一声短促提示。条款页上维持了三天的灰锁从中间裂开，细密小字一行行替换“校验字段加密”。\n“第四日开始。完整生还条款已经可见。公开字段不改变既有条件，仅补充最终裁定方式。”\n这句话最残忍的地方不在于它新增了什么，而在于主办方早就知道我们会按照不完整的规则互相承诺。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    nextByFlag: {
      'ch4_first_killer_hanqi': 'ch5_hanqi_route_memory',
      'ch4_first_killer_alliance': 'ch5_alliance_route_memory',
      'ch4_first_killer_majority': 'ch5_majority_route_memory',
      'ch4_first_killing_prevented': 'ch5_audit_route_memory',
    },
    next: 'ch5_field_unlock_begin',
  ),
  'ch5_hanqi_route_memory': StoryBeat(
    id: 'ch5_hanqi_route_memory',
    label: '陈默没有看到完整条款',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '陈默的08号终端没有跟着解锁。它被封存在透明证物袋里，屏幕停在他死前试图复制公共撤销权的界面。\n韩骐站在离证物袋最远的位置。没有人命令他这么做；众人只是每次移动都会给他留出一圈空白。\n叶岚低声说：“完整条款来迟了，但不能因此把已经发生的动作改写成合理。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.yeLan],
    next: 'ch5_hanqi_route_response',
  ),
  'ch5_hanqi_route_response': StoryBeat(
    id: 'ch5_hanqi_route_response',
    label: '杀人者也必须听见规则',
    speaker: Speaker.hanQi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'conflicted',
    text:
        '“如果08的字段证明他当时真的要夺取全部门禁呢？”韩骐问。声音并不高，更像在给自己留一条能够站立的窄路。\n“那会证明他的动机，不会消除你的后半段动作。”我回答。\n韩骐看向自己空着的右手。控制棒已经进入“已使用”状态，系统留下的不是武器图标，而是一个无法重新封存的结果。',
    passageSpeakers: [Speaker.hanQi, Speaker.shenYan, Speaker.narration],
    next: 'ch5_field_unlock_begin',
  ),
  'ch5_alliance_route_memory': StoryBeat(
    id: 'ch5_alliance_route_memory',
    label: '韩骐的终端被留在门外',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'shaken',
    text:
        '04号终端装在隔离袋里，由苏弥提着。韩骐最后转交的门禁仍在公共组中，他本人却被永远留在C-02。\n陈默和唐弈没有并肩站立。两个人分别占据走廊两端，像只要距离足够远，那次共同拒绝开门就能拆成两件互不相干的事。\n“等字段公开以后再谈自保。”苏弥说，“但先记住，他最后一次要求开门时已经交出了门禁。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.suMi],
    next: 'ch5_alliance_route_response',
  ),
  'ch5_alliance_route_response': StoryBeat(
    id: 'ch5_alliance_route_response',
    label: '共同决定没有共同沉默',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'desperate',
    text:
        '“门一开，他会继续控制01。”陈默先开口，眼睛却只看着档案库的读卡区，“我到现在也不认为风险是假的。”\n“风险当然是真的。”唐弈接过话，“假的只是‘没有选择’。”\n陈默猛地转头。唐弈把共谋里最能替他们辩护的一层亲手抽掉，像提前切断一根将来可能勒回自己颈上的绳。',
    passageSpeakers: [Speaker.chenMo, Speaker.tangYi, Speaker.narration],
    next: 'ch5_field_unlock_begin',
  ),
  'ch5_majority_route_memory': StoryBeat(
    id: 'ch5_majority_route_memory',
    label: '票数没有跟着死者消失',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '高原死后，多数决记录被叶岚打印成两份。一份写票数，一份写每个人知道的风险、撤回条件和最后九十秒仍可执行的氧气方案。\n支持留观的人不愿靠近第二份，拒绝执行救援的人则只盯着第一份。\n“今天公开的字段会改变我们的利益，却不能倒过来改变昨天知道了什么。”叶岚把两张纸一起压在门边。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.yeLan],
    next: 'ch5_majority_route_response',
  ),
  'ch5_majority_route_response': StoryBeat(
    id: 'ch5_majority_route_response',
    label: '多数人第一次害怕再次表决',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'shaken',
    text:
        '“如果等会儿还要投票呢？”林澄问。\n没有人回答。第一次表决之前，数字意味着分担；现在每个人都知道，举手之后仍会有一个具体的人去关门、拒绝见证或选择不撤回。\n唐弈用指节轻敲PDA。“那就别再问哪一边票多。先问每张票想让谁承担结果。”',
    passageSpeakers: [Speaker.linCheng, Speaker.narration, Speaker.tangYi],
    next: 'ch5_field_unlock_begin',
  ),
  'ch5_audit_route_memory': StoryBeat(
    id: 'ch5_audit_route_memory',
    label: '死亡预测没有成为死亡记录',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '审计页仍保存着三种预演：陈默死于持续压制、韩骐死于门轨封锁、高原死于多数拒绝救援。每一条旁边都标着“未发生”。\n没有人因此显得轻松。韩骐看过自己可能杀人的动作，陈默和唐弈也看过他们如何把自保推成预谋。\n叶岚说：“预演不是无罪证明。它只让我们在动作发生前，知道哪一步不能交给恐惧代做。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.yeLan],
    flagsOnEnter: {'ch5_audit_prediction_available'},
    next: 'ch5_audit_route_response',
  ),
  'ch5_audit_route_response': StoryBeat(
    id: 'ch5_audit_route_response',
    label: '活着的人也要承担预演',
    speaker: Speaker.hanQi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'conflicted',
    text:
        '韩骐主动把01的临时门禁退回公共组。陈默关闭所有仍在后台运行的旧会话，唐弈把自己保存的柜门距离表交给叶岚。\n“别把这叫信任。”韩骐说，“我只是知道自己在什么条件下会不肯松手。”\n能准确说出自己的危险，并不等于危险消失。但这是他们第一次在主办方宣布条款之前，先公开了可能伤人的那部分自己。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch5_field_unlock_begin',
  ),
  'ch5_field_unlock_begin': StoryBeat(
    id: 'ch5_field_unlock_begin',
    label: '完整条件开始改变站位',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    text:
        '我们约定逐条宣读，任何人不得在别人读完前移动或索取终端。门还没有开启，走廊却已经像一张缓慢收紧的网：谁需要谁活着，谁需要谁失去权限，谁又能从人数减少中获利，很快都会变成可以指向具体姓名的句子。',
    passageSpeakers: [Speaker.narration],
    next: 'ch5_clause_01',
  ),
  'ch5_clause_01': StoryBeat(
    id: 'ch5_clause_01',
    label: '四份证词不能由一人代交',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    text:
        '01号新增字段要求：四名存活者必须在隔离终端独立提交相同的主办者代号，而且四个人都已经满足自己的主条件。任何托管代交无效。\n这意味着我不能只保护四具能按键的身体。我需要四个人真正理解同一答案，也需要他们各自活到条款可以成立。主办方把证词变成了互相扣住的生存条件。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_clause_02',
  ),
  'ch5_clause_02': StoryBeat(
    id: 'ch5_clause_02',
    label: '保护01也包括保护他的操作权',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'alarm',
    text:
        '02号要求01存活、中央信标在线，并在第七日零点仍保有自己终端的操作权。\n星遥读完后先看向韩骐，再看向我。“所以有人把你的PDA锁进保险柜，即使声称是保护，也会让我失败。”\n她没有把“有人”说成04。此刻保留泛称，不是回避，而是拒绝让条款提前替任何人定罪。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_clause_03',
  ),
  'ch5_clause_03': StoryBeat(
    id: 'ch5_clause_03',
    label: '六人必须都是真实参与者',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'concerned',
    text:
        '03号字段只有一行：“存活统计仅包含本轮真实初始参与者；维护、托管与重放身份无效。”\n苏弥把那行字放大到所有人都能看见。“12号不算。”\n“前提是你能证明它是维护身份。”唐弈提醒。\n“那就证明。”苏弥没有提高声音，“在证明以前，不准把一个白点当成可以少救一个人的理由。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.tangYi,
      Speaker.suMi,
    ],
    next: 'ch5_clause_06',
  ),
  'ch5_clause_06': StoryBeat(
    id: 'ch5_clause_06',
    label: '恰好四人的算盘有了主语',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'shaken',
    text:
        '06号的有效人数以裁定名册为准，而且唐弈本人必须属于最后四人。\n他读得很慢，读完后甚至笑了一声。“如果12号被算进去，真实的人只能剩三个；如果不算，就能剩四个。你们现在知道我为什么会对那盏白灯感兴趣。”\n“知道利益，不等于接受做法。”叶岚说。\n“当然。”唐弈收起笑意，“但至少从现在起，别把我每一次算人数都当成纯粹的数学兴趣。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.tangYi,
    ],
    next: 'ch5_clause_07',
  ),
  'ch5_clause_07': StoryBeat(
    id: 'ch5_clause_07',
    label: '信赖对象死后条款会变成复仇',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'anxious',
    text:
        '07号的后半段让林澄沉默了很久：若登记的信赖对象被故意杀害，责任人不得存活到次日零点。\n“如果对方死了，我不杀责任人，我自己就会失败。”她说。\n十八岁的声音在空走廊里显得过分清楚。条款没有赋予她力量，只把复仇包装成另一种陪伴义务，仿佛真正重视一个人的证明，就是在失去之后再制造一具尸体。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch5_clause_11',
  ),
  'ch5_clause_11': StoryBeat(
    id: 'ch5_clause_11',
    label: '撤回错误需要被指控者活着',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '11号必须让三项曾被多数接受的错误指控公开撤回，被指控者还要活着亲自确认。\n“我有阻止猎杀的利益。”叶岚先说，“也有制造错误再纠正的可疑利益。以后我提出延迟处置时，你们可以检查这两种可能。”\n她把最难听的解释也写进公开栏。不是为了显得坦白，而是让任何善意主张都不再免于核验。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    nextByFlag: {
      'ch4_first_killer_alliance': 'ch5_clause_branch_alliance',
      'ch4_first_killer_majority': 'ch5_clause_branch_majority',
      'ch4_first_killer_hanqi': 'ch5_clause_branch_hanqi',
      'ch4_first_killing_prevented': 'ch5_clause_branch_audit',
    },
    next: 'ch5_archive_door_request',
  ),
  'ch5_clause_branch_hanqi': StoryBeat(
    id: 'ch5_clause_branch_hanqi',
    label: '04的保护要求01失去完整控制',
    speaker: Speaker.hanQi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'conflicted',
    text:
        '04号不仅要在零点持有01初始终端，还要求01不得保留完整控制权限，并与04处于同一区域。\n韩骐读完后没有靠近我。“这条款的最短做法，是把你和终端一起控制起来。”\n“你会做吗？”星遥问。\n他停了几秒。“三天前，我会把那叫保护。现在我知道名字不重要，动作才重要。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.liXingyao,
      Speaker.hanQi,
    ],
    next: 'ch5_clause_08_posthumous',
  ),
  'ch5_clause_08_posthumous': StoryBeat(
    id: 'ch5_clause_08_posthumous',
    label: '08的字段只能从死者缓存读取',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    text:
        '陈默已经死亡，08字段不再向公共频道宣读。证物袋里的终端只弹出一行提示：“完整条款归档于E-04责任记录。”\n韩骐闭了一下眼。一个人死后才出现的动机，既可能让杀人者抓住辩护，也可能让死者永远失去解释自己选择的机会。叶岚要求等档案取出后，动机和责任分栏记录。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_clause_09_alive',
  ),
  'ch5_clause_09_alive': StoryBeat(
    id: 'ch5_clause_09_alive',
    label: '09不能允许无主身份留在核心',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'injured',
    text:
        '高原的09号要求主供电与三套安全回路保持在线，控制核心不得存在伪造或无主身份。\n“12号如果正在控制核心重放，我必须关掉它。”他说，“但直接断电也会让我失败。主办方把拆除假身份和维持设备绑在了一根线上。”\n他的伤腿仍不能完全受力，却已经开始在纸图上标出能隔离信号、又不切断安全回路的物理节点。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch5_field_conflict_table',
  ),
  'ch5_clause_branch_alliance': StoryBeat(
    id: 'ch5_clause_branch_alliance',
    label: '04的完整条件来得比本人更晚',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'alarm',
    text:
        '04终端在证物袋中解锁：韩骐必须持有01初始终端，剥离01完整控制权，并与01处于同一区域。\n陈默盯着那三行字。“我说过他不会停在保管。”\n“它能证明你的担忧有根据。”我说，“不能证明最后的门必须保持关闭。”\n真正令人不适的不是条款替韩骐洗清了什么，而是它让杀死他的人更容易把预谋重新叙述成必然。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch5_clause_08_alive',
  ),
  'ch5_clause_08_alive': StoryBeat(
    id: 'ch5_clause_08_alive',
    label: '08必须让三份责任记录无法恢复',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'guarded',
    text:
        '08号终于公开：第七日零点前永久删除三份外包责任记录。每份记录都由一名参与者持有恢复签名，只要签名者仍活着，删除就可以撤销。\n“所以最短路径是什么？”唐弈问。\n陈默的嘴唇动了一下，没有说。\n答案不需要技术知识：说服三个人放弃签名，夺走他们的终端，或者让他们无法活到零点。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch5_clause_09_alive',
  ),
  'ch5_clause_branch_majority': StoryBeat(
    id: 'ch5_clause_branch_majority',
    label: '09的字段由死亡记录代读',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '高原已经死亡，09号完整条款由系统归档页代读：主供电和安全回路必须在线，控制核心不得存在伪造或无主身份。\n白色12号灯就在这句话旁边稳定闪烁。有人曾经最有能力从物理线路判断它如何重放，却被众人的表决留在了封锁区。\n叶岚没有说“如果高原还在”。她只把“失去设备核验能力”加进死亡后果。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_clause_04_alive',
  ),
  'ch5_clause_04_alive': StoryBeat(
    id: 'ch5_clause_04_alive',
    label: '04与02在01的终端上正面冲突',
    speaker: Speaker.hanQi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'conflicted',
    text:
        '韩骐公开04字段时，主动把PDA放在地上：他需要持有我的初始终端、让我失去完整控制，并与我处于同一区域。\n“02要求他保留操作权。”韩骐说，“没有两边都满足的保管方式。”\n这次他没有把冲突叫作需要强制解决的危险，只承认自己也是危险的一端。星遥仍挡在我与终端之间，没有因一句承认就撤开。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch5_clause_08_alive',
  ),
  'ch5_clause_branch_audit': StoryBeat(
    id: 'ch5_clause_branch_audit',
    label: '所有高风险字段在行动前公开',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '04、08与09依次公开。韩骐的控制要求、陈默的三份恢复签名、高原必须清除的无主身份，把01终端、档案记录和12号信号同时变成争夺目标。\n叶岚没有要求三个人互相信任。她让韩骐退出终端保管，让陈默只口述接口，让高原的物理操作由星遥复核。\n预演带来的优势不是知道谁是坏人，而是能在第一只手伸出去前，把能力与利益拆开。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_field_conflict_table',
  ),
  'ch5_field_conflict_table': StoryBeat(
    id: 'ch5_field_conflict_table',
    label: '完整条款第一次被写成关系图',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    text:
        '我在纸上画出每条校验字段的对象。02需要我活着并保有终端，04需要剥离我的控制；03至少需要六名真人，06需要最后恰好四名；08需要恢复签名失效，11却需要被错误指控者活着确认撤回。\n线条越画越多，最后没有一个编号是孤立的。主办方没有简单写下“杀死某人”，而是让保护、人数、证据与控制彼此冲突，再把最短路径留给我们自己发现。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_sumi_counting_people',
  ),
  'ch5_sumi_counting_people': StoryBeat(
    id: 'ch5_sumi_counting_people',
    label: '苏弥拒绝把六人说成数字底线',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'concerned',
    text:
        '“至少六人”看起来给苏弥留出几条可以牺牲的余量。她却把当前存活者姓名逐个写下，在每个名字后标出伤情、能力和依赖关系。\n“少一个人不是从九减到八。”她说，“少了高原，设备故障就没有独立复核；少了叶岚，证言争议没有人整理；少了星遥，我们甚至不知道广播在向谁发送。”\n人数条件只规定最低线，活人的价值却不会在第六名以后归零。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch5_tangyi_four_seats',
  ),
  'ch5_tangyi_four_seats': StoryBeat(
    id: 'ch5_tangyi_four_seats',
    label: '唐弈公开描述最后四席',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveCorridor,
    text:
        '“如果把道德先放到一边，四个人最好包含01、能维持信标的02、能处理伤势的03，再加一个懂门禁的人。”唐弈说。\n林澄问：“那你呢？条款要求你必须在四个人里。”\n唐弈停了一下，把自己的编号写进名单，划掉原本的第四人。“看，这就是条件真正做的事。它让我把每个有用的人都算完，再亲手删除一个比我更有用的。”',
    passageSpeakers: [Speaker.tangYi, Speaker.linCheng, Speaker.tangYi],
    next: 'ch5_tangyi_no_abstraction',
  ),
  'ch5_tangyi_no_abstraction': StoryBeat(
    id: 'ch5_tangyi_no_abstraction',
    label: '最后四席必须写上姓名',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '叶岚要求唐弈不许只写编号。他重新列出姓名，每划去一个人，都要说明这个人会失去什么、其他人会失去什么。\n“这是情绪绑架。”唐弈说。\n“不是。”叶岚回答，“你的计算正在决定人的去留，让名字重新进入计算只是恢复被你删掉的成本。”\n唐弈没有撕掉纸。他把它折起来放进口袋，像保存一张赔率突然变得过于具体的赌单。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch5_lincheng_revenge_question',
  ),
  'ch5_lincheng_revenge_question': StoryBeat(
    id: 'ch5_lincheng_revenge_question',
    label: '林澄问复仇条款是否可以被绕过',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'anxious',
    text:
        '林澄把07页面转给我看。“责任人不得活到零点。如果信赖对象真的被杀，我能不能让责任人先被判定无效，而不是杀掉？”\n陈默可能会想到伪造身份，唐弈可能会想到封锁区域，韩骐则可能选择直接控制。每条方案都把“不得存活”换了一种外观，却没有消除死亡。\n“先别替未来的你找手段。”我说，“先建立一种安排，让你失去对方时不用独自面对这条倒计。”',
    passageSpeakers: [Speaker.linCheng, Speaker.narration, Speaker.shenYan],
    next: 'ch5_lincheng_refuses_weapon',
  ),
  'ch5_lincheng_refuses_weapon': StoryBeat(
    id: 'ch5_lincheng_refuses_weapon',
    label: '她拒绝提前领取自卫武器',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'determined',
    text:
        '有人提议把一件非致命工具交给林澄，理由是07最容易在信赖对象遇害后被强迫复仇。\n“我需要的是别人不能替我登记、不能把他单独带走，也不能在他死后把武器塞给我。”林澄回答，“不是提前把我训练成到时候负责杀人的人。”\n她仍然害怕，也知道自己在力量上处于劣势。拒绝武器不是天真，而是拒绝让所有保护方案都默认以杀戮为终点。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch5_xingyao_control_conflict',
  ),
  'ch5_xingyao_control_conflict': StoryBeat(
    id: 'ch5_xingyao_control_conflict',
    label: '星遥把保护与控制放进同一张表',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'alarm',
    text:
        '星遥列出所有可能让01失去操作权的动作：没收终端、强制托管、药物镇静、绑住双手、关闭个人频道。每一项都可能被04称为保护，也都能让02直接失败。\n“我不会只盯着韩骐。”她说，“任何人，包括我自己，只要替沈砚决定他不再需要操作权，就必须被第二个人制止。”\n她最后把我的名字也写在表内：如果我主动放弃终端，02同样有权拒绝。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_ye_lan_wrong_accusation',
  ),
  'ch5_ye_lan_wrong_accusation': StoryBeat(
    id: 'ch5_ye_lan_wrong_accusation',
    label: '叶岚承认她也会从错误中获利',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '11需要三项错误指控被多数接受后再公开撤回。唐弈问她，是否会故意放任一场错误指认形成，只为了让条款取得进度。\n“这个动机存在。”叶岚回答，“所以每次我主张‘先不要纠正’或‘让大家表态’，都由另一人记录我是否在制造多数。”\n她没有要求众人相信自己的职业伦理。一个人越擅长解释群体，就越应该允许群体检查她是否在利用解释。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch5_dead_conditions_boundary',
  ),
  'ch5_dead_conditions_boundary': StoryBeat(
    id: 'ch5_dead_conditions_boundary',
    label: '死者条件不被重新编造成理由',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'shaken',
    text:
        '有人提出读取05与10未公开的完整条件，仿佛其中可能藏着吴峥破坏项圈、周叙离开终端的真正理由。\n苏弥立刻拒绝。“他们死亡时不知道这些字段，我们也没有证据证明字段曾向他们解锁。不能在死人不能反驳时，给他们补一个方便活人接受的动机。”\n05和10的页面保持封存。未知没有被故事性更强的解释填满。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch5_hallway_food',
  ),
  'ch5_hallway_food': StoryBeat(
    id: 'ch5_hallway_food',
    label: '零点后的第一顿饭没人有胃口',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    text:
        '字段争论持续到零点四十分。苏弥强迫大家停下补水，林澄把能量棒按仍活着的人数分开，数到某个新空位时手指停了一下。\n死亡发生后，食物总会多出一份。最初那几次我们会把多余餐盒推到桌角，现在没有人愿意碰它，也没人愿意把它扔掉。物资变充足的事实，比饥饿更让人难以下咽。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_corridor_private_fear',
  ),
  'ch5_corridor_private_fear': StoryBeat(
    id: 'ch5_corridor_private_fear',
    label: '每个人都开始计算自己会被谁需要',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    text:
        '短暂休息里，没有人真正放松。星遥检查我终端是否仍在手中，苏弥数还能承担伤员的床位，林澄反复确认信赖登记尚未被他人代填。\n我也在计算，却不敢承认计算的内容：谁最可能成为四名证人，谁的条款最难满足，保护谁会让另一个人把我视为障碍。\n调查者并不天然高于死亡游戏。只要开始用“最终需要”替代“眼前的人”，我就会用更体面的语言做唐弈正在做的事。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_white_signal_knock',
  ),
  'ch5_white_signal_knock': StoryBeat(
    id: 'ch5_white_signal_knock',
    label: '白色信号像在门后敲了三次',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'alarm',
    text:
        'E-04门内传来三次间隔完全相同的继电器响声。白点从门中央移动到左侧墙面，又回到原位。\n“不是脚步。”星遥贴近维护口，却没有把耳朵直接靠上去，“三个固定底座依次响应，地图把设备切换画成了移动。”\n我们尚未打开门，12号已经用最机械的方式表演了一次“在房间里走动”。主办方知道人会本能地为移动的光点想象身体。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_door_three_requests',
  ),
  'ch5_door_three_requests': StoryBeat(
    id: 'ch5_door_three_requests',
    label: '三名真人授权也需要确认意志',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '门锁要求三名真实参与者共同请求。有人主张由行动能力最强的人授权最安全，唐弈则建议让条款冲突最少的人授权。\n叶岚拒绝先选人。她要求每位授权者先口述自己是否受到威胁、是否知道门内风险、是否允许随时撤回。\n系统只检查三个终端，不检查三次同意。我们必须自己补上机器故意省略的那一层。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_door_authorizers',
  ),
  'ch5_door_authorizers': StoryBeat(
    id: 'ch5_door_authorizers',
    label: '授权者来自彼此冲突的条件',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    text:
        '最终由苏弥、唐弈和我提交请求。03要保住人数，06可能希望减少人数，01需要保存证词；三个人无法从同一个结果获利。\n这不保证其中无人说谎，只让一项门禁不再完全服从单一阵营。\n林澄担任纸面记录，星遥核对终端是否由本人操作。权限、见证和技术检查被分给不同的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_door_personal_items',
  ),
  'ch5_door_personal_items': StoryBeat(
    id: 'ch5_door_personal_items',
    label: '进入者只携带公开登记的物品',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'concerned',
    text:
        '所有人把口袋清空在白布上：PDA、笔、绷带、糖片、维修手套、折叠镜。每件物品拍照后重新领取，未登记工具留在门外。\n“搜身不是为了证明谁清白。”苏弥说，“只为让出来时新增的东西有起点。”\n她检查得很慢，也允许被检查者看见自己的物品没有被替换。安全措施若剥夺尊严，迟早会成为强制控制的借口。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch5_door_return_phrase',
  ),
  'ch5_door_return_phrase': StoryBeat(
    id: 'ch5_door_return_phrase',
    label: '撤退报码不使用编号',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'determined',
    text:
        '林澄设计的撤退报码要求说出姓名、眼前物件和下一步动作，例如“黎星遥，看见红色档案车，正在后退”。\n单纯报编号可能被12号录音重放，固定暗号也可能被服务器提前取得。随现场变化的三段式报码更难伪造，还能让外组判断内组是否清醒。\n她把每个人的示例都写了一遍，唯独12号没有姓名可填。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_door_fatigue_check',
  ),
  'ch5_door_fatigue_check': StoryBeat(
    id: 'ch5_door_fatigue_check',
    label: '困倦也会改变一次同意',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'concerned',
    text:
        '苏弥最后检查瞳孔与反应速度。零点后的争论已经消耗近一小时，陈默的手指出现轻微震颤，星遥也第三次揉眼。\n“疲劳的人仍能同意，但不能假装状态与清醒时相同。”她安排每十五分钟轮换，“谁开始重复同一句话，立刻离开，不把坚持叫作负责。”\n准备完成后，我们才把三台终端同时贴近读卡区。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch5_archive_door_request',
  ),
  'ch5_archive_door_request': StoryBeat(
    id: 'ch5_archive_door_request',
    label: '门要求一名不存在的人授权',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'alarm',
    text:
        '星遥把离线测试线接入门侧维护口。屏幕显示E-04需要两份权限：任意三名真实参与者共同请求，以及“身份槽12”确认进入。\n“它不是在门里等我们。”她说，“它就是门锁的一部分。”\n白灯随即亮起，替所有人完成了第二份授权。门缝里吹出纸张、机油和长久不通风的冷气。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_door_override_notice',
  ),
  'ch5_door_override_notice': StoryBeat(
    id: 'ch5_door_override_notice',
    label: '第二批物资只公布离架状态',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveCorridor,
    text:
        '门开启的同时，PDA高危索引更新。E-04内部的门禁强制控制器解除封条，B-01强腐蚀清洗剂允许取用；系统只会公布离架，不公布持有者。\n“完整条款阶段允许参与者使用设施资源消除冲突。”\n“消除冲突。”苏弥重复这四个字，像医生在病历上圈出一个故意避开死亡的委婉说法。',
    passageSpeakers: [Speaker.narration, Speaker.administrator, Speaker.suMi],
    highRiskItemsOnEnter: {'door_override', 'corrosive_cleaner'},
    next: 'ch5_entry_protocol',
  ),
  'ch5_entry_protocol': StoryBeat(
    id: 'ch5_entry_protocol',
    label: '先决定谁不能碰什么',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '叶岚在门口划出三列：能力、利益、可接触物。懂系统的人不能单独碰服务器，拥有力量的人不能持有门禁控制器，需要恢复签名的人不能独自保管责任档案。\n“这不是对某个人的惩罚。”她说，“是让每项操作至少留下一个没有直接获利的见证人。”\n唐弈看完表格，指出一处空白：“如果见证人也想让人数减少呢？”\n“所以还要记录，而不是把见证当成清白证明。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.tangYi,
      Speaker.yeLan,
    ],
    next: 'ch5_threshold_crossing',
  ),
  'ch5_threshold_crossing': StoryBeat(
    id: 'ch5_threshold_crossing',
    label: '进入前先留下能从外面执行的撤退条件',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'intervening',
    text:
        '有人提出由行动能力最强的人守门，但04字段让这个建议立刻带上控制意味。最终方案改为两名内组、两名外组轮换，任何人都不能同时持有01终端与关门权限。\n“如果里面报警，外组先开门，不等待内组说明。”叶岚把这条写进协议。\n星遥补上一条：“如果只有12号发出求援，不进入。必须有真人频道和纸面报码同时确认。”\n规则越具体，保护才越少依赖某个人临场自称正确。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch5_archive_air_test',
  ),
  'ch5_archive_air_test': StoryBeat(
    id: 'ch5_archive_air_test',
    label: '冷气里没有适合活人的味道',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'concerned',
    text:
        '苏弥用试纸检查门缝气流，又让每个人闻过之后立刻后退。空气里有旧纸、润滑油和臭氧，没有食物、洗涤剂或长期生活产生的湿气。\n“只能说明这里不像住过人。”她强调，“不能仅凭气味宣布12号不存在。”\n在一个所有人都渴望答案的房间前，谨慎常常显得像拖延。可她坚持把“没发现”与“证明没有”分开。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch5_archive_camera_test',
  ),
  'ch5_archive_camera_test': StoryBeat(
    id: 'ch5_archive_camera_test',
    label: '镜面片先于任何人的头进入门缝',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'determined',
    text:
        '林澄把在前几日调查中留下的折叠镜绑在伸缩杆上，从半开的门缝送进去。画面掠过移动柜、工作台和服务器架，没有藏在门侧的人影。\n“上方有轨道，下方有压力板。”她报出看到的细节，“门后不是空房，是一个会记录我们怎么进入的房间。”\n她没有因为自己年纪最小就被留在最后，也没有被推到最前。工具让观察能力与身体风险第一次真正分开。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch5_archive_first_pair',
  ),
  'ch5_archive_first_pair': StoryBeat(
    id: 'ch5_archive_first_pair',
    label: '第一组只前进到能被外面看见的位置',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '我与星遥先跨过门槛，只走到外组仍能看见鞋尖的位置。地面压力板亮起01与02，白色12号同时在最深处的底座上确认。\n“它把我们算成三个人。”星遥说。\n屏幕上的“3”并没有因我们知道其中一个是假的就消失。系统错误如果被写进硬件，理解真相只能改变我们的判断，不能自动改变门会如何落下。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_archive_false_voice',
  ),
  'ch5_archive_false_voice': StoryBeat(
    id: 'ch5_archive_false_voice',
    label: '12号使用了没有主人的呼吸声',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '深处扬声器忽然传出一次急促呼吸，随后是含混的“救我”。声音没有明显性别，也找不到房间混响。\n星遥立刻切断公共频道。“样本由许多短片拼成，尾音每七秒重复。”\n那声求救仍让外组向前半步。人类对求救作出反应并不是缺陷；真正恶意的是系统把这种反应当成可以测试和利用的开关。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_archive_no_rescue_rush',
  ),
  'ch5_archive_no_rescue_rush': StoryBeat(
    id: 'ch5_archive_no_rescue_rush',
    label: '苏弥没有因假求救停止准备救援',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'concerned',
    text:
        '“确认是假声，不等于以后可以忽略所有求救。”苏弥在门外说，“下一次要检查来源、连续回应和生命迹象，不能把被欺骗一次当成冷漠的许可证。”\n她把急救包留在黄线外，确保即使内组被锁，外组也能使用。\n死亡游戏总在奖励简单反应：全信，或全不信。真正困难的是被骗以后仍保留核验与救援的能力。',
    passageSpeakers: [Speaker.suMi, Speaker.narration, Speaker.narration],
    next: 'ch5_archive_bag_count',
  ),
  'ch5_archive_bag_count': StoryBeat(
    id: 'ch5_archive_bag_count',
    label: '墙上只有十一只属于人的资料袋',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '我们在不触碰的情况下数过资料袋。01至11各有封口、重量和纸张厚度，12的位置只有四枚螺孔与一圈较浅的墙漆。\n唐弈隔门问：“会不会12的资料被拿走了？”\n“可能。”我回答，“所以这只能成为搜索方向，不能单独成为结论。”\n承认一种可能存在，不等于要把它放到与已有证据同样的重量上。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch5_archive_rotation',
  ),
  'ch5_archive_rotation': StoryBeat(
    id: 'ch5_archive_rotation',
    label: '轮换让每个人都看到同一房间',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '每五分钟轮换一次。后进入的人先复述自己在门外听见的内容，再独立描述室内，不允许直接照抄上一组结论。\n有人注意到服务器比柜体新，有人注意到地面没有长期行走的磨损，林澄则发现12号空位附近的灰尘轮廓像设备推车。\n多个观察者不是为了制造多数，而是为了让某一个人的职业判断无法垄断房间的意义。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_archive_first_view',
  ),
  'ch5_archive_first_view': StoryBeat(
    id: 'ch5_archive_first_view',
    label: '档案库并不像藏着一个人',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_e04_identity',
    cgFrame: 0,
    text:
        'E-04比地图上的面积更深。两排移动档案柜沿轨道收拢，后方是旧式缩微胶片机与一组后来加装的服务器架。墙上挂着十一只纸质资料袋，编号从01到11；本应属于12的位置只有一块带螺孔的浅色印记。\n没有床、食物或长期生活痕迹。所谓“第十二个人”在这里拥有插口、权限和统计位置，却没有任何属于身体的东西。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_archive_smell',
  ),
  'ch5_archive_smell': StoryBeat(
    id: 'ch5_archive_smell',
    label: '新旧年代被塞在同一房间',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'inspecting',
    text:
        '柜体是十多年前的规格，服务器散热却很新，地板下还有两种宽度不同的线槽。只要高原仍在，他便会指出这些差异；如果他已死亡，我们只能依靠他前几日留下的设备草图比对。\n“别按看起来的新旧排顺序。”星遥提醒，“外壳可以换，文件日期也能补。先找不能一起伪造的物理痕迹。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch5_archive_roles',
  ),
  'ch5_archive_roles': StoryBeat(
    id: 'ch5_archive_roles',
    label: '调查被拆成四个互相核对的角落',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '我把调查分成四处：纸质绑架名册与资料袋、旧员工合照、门禁备份卷、服务器镜像。每组只能收取原件，不能在现场直接连接主机；所有工具先进入公共背包，再由另一组组合验证。\n这样的步骤很慢。可当一份记录可能决定12号算不算一条命时，速度本身也会成为主办方使用的武器。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_archive_investigation',
  ),
  'ch5_archive_investigation': StoryBeat(
    id: 'ch5_archive_investigation',
    label: 'E-04档案复原',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    phase: StoryPhase.investigation,
    text: '调查档案库中四处年代与来源不同的记录，复原初始名单、改造时间和身份槽12的门禁重放方式。',
    next: 'ch5_investigation_debrief',
  ),
  'ch5_investigation_debrief': StoryBeat(
    id: 'ch5_investigation_debrief',
    label: '四类材料先分开陈述',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '叶岚不允许任何人先说“所以12号不存在”。我们依次把可观察事实放到桌上：原始绑架名册只有十一组指纹栏；员工合照里的空位原本挂着维护终端；门禁卷显示同一身份在不可能的时间跨区出现；服务器镜像则保存着批量生成的12号握手。\n结论被故意留到最后，因为一句正确结论如果来得太早，也会遮住中间仍可能出错的推理。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_roster_fact',
  ),
  'ch5_roster_fact': StoryBeat(
    id: 'ch5_roster_fact',
    label: '绑架名单从来只有十一人',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '纸质名册的压痕、页码和骑缝章连续覆盖01至11。末页后来打印过“12”，墨粉却压在装订锈斑之上，旁边没有姓名、指纹、药量或运输编号。\n那不是一名被删除的人，而是绑架完成后补进统计表的字段。若真有第十二名受害者，主办方必须同时伪造一个人从绑架、用药到运送的全部物理链，而这里一项都没有。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_photo_fact',
  ),
  'ch5_photo_fact': StoryBeat(
    id: 'ch5_photo_fact',
    label: '旧合照中的12号是一台测试终端',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'relaxed',
    text:
        '旧员工合照背面的资产标签与墙上螺孔完全对应。被后期涂黑的位置并不是人脸，而是一台立在推车上的门禁测试终端，标签写着“SLOT-12 / MAINTENANCE”。\n“维护人员用它模拟第十二个身份，测试满员、托管和封锁。”星遥说，“主办方后来没有创造新功能，只是把测试用的假人留在正式游戏里。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch5_access_fact',
  ),
  'ch5_access_fact': StoryBeat(
    id: 'ch5_access_fact',
    label: '一个身份在七秒内跨越三层楼',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '林澄把门禁卷按时间铺开。12号先在F-01确认留守，七秒后在C-02占用病房，又在E-04请求开门。最快路线也需要九分钟。\n“不是它移动得快。”她用铅笔把三个时间圈起来，“是三个底座轮流说自己是它。”\n纸上的线比任何技术术语都更直接：地图追踪的不是一具身体，只是一段被多个设备复读的身份。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch5_server_fact',
  ),
  'ch5_server_fact': StoryBeat(
    id: 'ch5_server_fact',
    label: '服务器把假身份当成可调参数',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '离线镜像中没有12号个人档案，只有三列配置：是否计入人数、是否接受托管、是否占用区域。每一列都可以独立开关，修改记录由名为ZERO的裁定进程签名。\n苏弥盯着“计入人数”一栏。“所以它可以在我的六人条件里算一个，处决时又被说成无效？”\n“不是系统算错。”我说，“是有人把矛盾做成了功能。”',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.shenYan],
    next: 'ch5_old_work_links',
  ),
  'ch5_old_work_links': StoryBeat(
    id: 'ch5_old_work_links',
    label: '三个人各自碰过项目的一小块',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '改造合同把旧工作痕迹重新拼到一起：陈默所在外包组写过权限模块，高原验收过门轨与安全回路，周叙经手的异常账目支付了服务器改装。\n三个人没有出现在同一份会议记录里，也没有任何一人接触完整系统。主办方却把他们的局部痕迹放在最容易互相怀疑的位置，让技术能力、设备经验和账目签名看起来像共同策划。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {'ch4_first_killer_hanqi': 'ch5_chenmo_posthumous_account'},
    next: 'ch5_chenmo_live_account',
  ),
  'ch5_chenmo_posthumous_account': StoryBeat(
    id: 'ch5_chenmo_posthumous_account',
    label: '死者无法再把技术解释成中立',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '陈默已经死亡，外包合同只能与他生前留下的说法比对。他曾称R-08只是普通修订号，也曾承认自己知道旧控制器会保留撤销窗口，却始终没有公开三份责任记录。\n“不要因为他不能回答，就把每一处矛盾都解释成有罪。”叶岚说，“也不要因为死亡已经惩罚了他，就停止确认周叙的责任链。”\n死亡结束了他的行动权，没有替事实结案。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch5_chenmo_belongings_review',
  ),
  'ch5_chenmo_belongings_review': StoryBeat(
    id: 'ch5_chenmo_belongings_review',
    label: '证物袋里留下了没来得及删除的摘要',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '星遥从08终端只读缓存里恢复出一段校验摘要。它不能打开责任记录，却能证明陈默在周叙死亡后反复查询“恢复签名持有者”，并在最初的A-02调查时清除过一次查询历史。\n“这是隐瞒，也是后续灭口准备的可能线索。”她说，“但摘要没有记录他是否已经决定伤害签名者。”\n我们把行为、能力和尚未发生的意图分成三栏，不让一个人的死亡把推理变得过于轻易。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_old_work_converge',
  ),
  'ch5_chenmo_live_account': StoryBeat(
    id: 'ch5_chenmo_live_account',
    label: '陈默第一次被要求逐行解释旧代码',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'guarded',
    text:
        '陈默认出权限模块，却坚持自己只写过离线测试接口。“SLOT-12原本用来模拟满员门禁。是否计入生还人数不是我的代码。”\n星遥把镜像摘要推到他面前。“这段适配层调用了你的旧函数。”\n“调用不等于我写了现在的用途。”\n这句话在技术上正确，也恰好是他三天来最常使用的防线：只承认一小块事实，让所有小块之间的责任永远没有人拼接。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.liXingyao,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch5_chenmo_contract_signature',
  ),
  'ch5_chenmo_contract_signature': StoryBeat(
    id: 'ch5_chenmo_contract_signature',
    label: '他的签名只覆盖测试交付',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '合同附件上确实有陈默的电子签名，但签署对象是“十二槽门禁压力测试”，日期早于身份统计改造六个月。后来的变更只有ZERO批准，没有陈默签名。\n这足以排除他设计整个死亡游戏，却不能排除他在被绑架后利用熟悉的旧接口。\n“你不是主办方。”我说，“这也不等于你没有用主办方留下的设备杀周叙。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.shenYan],
    next: 'ch5_chenmo_ledger_fear',
  ),
  'ch5_chenmo_ledger_fear': StoryBeat(
    id: 'ch5_chenmo_ledger_fear',
    label: '他真正害怕的是离开后的责任',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'desperate',
    text:
        '“那三份记录把所有外包故障都签到我所在的小组。”陈默终于说，“公司会说我们明知测试身份能进入正式统计，仍然交付。出去以后，我会成为最容易被推出去的那个人。”\n“所以周叙必须死？”苏弥问。\n“我没说必须。”\n“你启动中继器时知道可能发生什么。”\n陈默握住桌沿。理解他的恐惧让行动变得更可解释，却没有让被他选中的死者重新活过来。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.suMi,
      Speaker.chenMo,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch5_old_work_converge',
  ),
  'ch5_old_work_converge': StoryBeat(
    id: 'ch5_old_work_converge',
    label: '局部参与与当前杀人被分开追责',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '叶岚把结论拆成两条：陈默参与过早期测试模块，但现有材料不支持他设计死亡游戏；陈默在当前游戏中知道中继风险，仍主动利用设备造成周叙死亡。\n第一条防止我们把他方便地塑造成唯一幕后黑手，第二条防止他用“我也只是外包员工”稀释具体行动。\n一个人可以同时是制度利用过的员工，也是后来主动伤害别人的参与者。两种身份不互相抵消。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_zhou_ledger_chain',
  ),
  'ch5_zhou_ledger_chain': StoryBeat(
    id: 'ch5_zhou_ledger_chain',
    label: '周叙留下的账目不是随机证据',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '账目显示三笔异常费用：维护身份改造、项圈定位中继、终局隔离终端。周叙在绑架前一周把它们标记为“无实际交付凭证”，准备提交内部审计。\n他可能因此被选入游戏，也可能只是被主办方发现后顺势利用。现有记录无法区分。\n唯一确定的是，他持有的恢复签名能撤销08删除，而中继器让陈默有机会在不接触身体的情况下消除这个障碍。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_ledger_physical_proof',
  ),
  'ch5_ledger_physical_proof': StoryBeat(
    id: 'ch5_ledger_physical_proof',
    label: '纸张压痕保存了被删掉的公司名',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '电子表格里的收款方已经被删除，纸质复印件下层却留下笔压。林澄用斜光描出一个并不存在于工商页面的项目代号：ZERO。\n“签名、程序、收款项目都是同一个词。”她说。\n“可能是同一主体，也可能是故意统一的伪装。”我提醒。\n每增加一处ZERO，它就更像答案，也更可能成为主办方希望我们过早提交的唯一词。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch5_chenmo_record',
  ),
  'ch5_chenmo_record': StoryBeat(
    id: 'ch5_chenmo_record',
    label: '08与周叙之死终于连接起来',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '周叙掌握的异常账目正是三份外包责任记录之一，也是陈默必须永久删除的第一份。服务器调用链显示，08的托管密钥片段在周叙死亡前三分钟启动过中继器。\n这仍不能让职业、迟到或紧张动作自动变成凶手；它与A-02的设备缓存、181秒阈值和现实路线合在一起，才形成完整责任链。\n陈默知道中继会触发项圈，仍选择执行。ZERO提供设备与动机，但没有替他按下启动。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_case04_preparation',
  ),
  'ch5_case04_preparation': StoryBeat(
    id: 'ch5_case04_preparation',
    label: '先把12号的三种可能都保留下来',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '进入推理前，我要求所有人各写一种能解释12号的假说：被隐藏的真人、死亡后仍在线的编号、由设备重放的维护身份。\n每种假说都必须同时解释三件事：为什么绑架名册缺少身体记录，为什么信号能七秒跨区，为什么服务器允许单独切换人数与托管。\n不能解释的地方不准用“主办方什么都能伪造”填补，否则任何调查都只会回到无法证伪的恐惧。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_hidden_person_hypothesis',
  ),
  'ch5_hidden_person_hypothesis': StoryBeat(
    id: 'ch5_hidden_person_hypothesis',
    label: '被隐藏真人的假说仍有诱惑',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'concerned',
    text:
        '苏弥坚持保留“被隐藏真人”直到证据链完成。“如果我们因为想揭穿人数陷阱，就过早宣布没人需要救，最坏结果是放弃一名真实受害者。”\n她列出这项假说必须找到的材料：药物记录、食物消耗、连续生理信号、至少一条无法由固定底座解释的移动。\n目前一项都没有，但“没有”必须来自搜索完成，而不是来自我们更喜欢另一个答案。',
    passageSpeakers: [Speaker.suMi, Speaker.narration, Speaker.narration],
    next: 'ch5_dead_terminal_hypothesis',
  ),
  'ch5_dead_terminal_hypothesis': StoryBeat(
    id: 'ch5_dead_terminal_hypothesis',
    label: '死亡编号无法解释持续生成的新握手',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '星遥测试“死亡后继续在线”的可能。吴峥与周叙的终端在死亡时冻结最后位置，之后只保留只读记录；12号底座却每七秒生成带新时间戳的握手。\n“这不是遗留终端忘了下线。”她说，“有一个仍在运行的进程主动租用身份槽。”\n死亡参与者假说能够解释编号为何没有回应，却无法解释身份为何不断由不同地点重新签发。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_maintenance_hypothesis',
  ),
  'ch5_maintenance_hypothesis': StoryBeat(
    id: 'ch5_maintenance_hypothesis',
    label: '维护身份必须接受物理证据检验',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '维护身份假说最符合现有材料，却也不能因为听起来合理就直接提交。林澄把四类证据摆成一排：名册、照片、纸卷、镜像。\n“如果拿掉服务器配置，只凭照片，我们最多知道以前有测试设备。”她说，“如果拿掉名册，也不能排除真人和设备同时存在。”\n真正的结论不是某张卡片上写着答案，而是四项独立材料在同一假说下不再互相冲突。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch5_case04_deduction',
  ),
  'ch5_case04_deduction': StoryBeat(
    id: 'ch5_case04_deduction',
    label: 'CASE 04 / 第十二个统计身份',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    phase: StoryPhase.deduction,
    text: '用原始名单、跨区门禁与服务器配置闭合证据链，判断12号在当前游戏中的真实性质。',
    next: null,
  ),
  'ch5_case04_person_error': StoryBeat(
    id: 'ch5_case04_person_error',
    label: '把缺失记录误当成被抹除的人',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    text:
        '“没有姓名也可能意味着那个人被彻底删除。”这个解释听起来谨慎，却无法说明为何原始名册只有十一组连续指纹，也无法让同一具身体在七秒内跨越三层楼。\n叶岚要求把“可能存在”与“现有材料支持”分开。我们重新回到名单的物理装订、底座位置和批量握手，不让对未知受害者的想象替代证据。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_case04_deduction',
  ),
  'ch5_case04_deleted_error': StoryBeat(
    id: 'ch5_case04_deleted_error',
    label: '把维护账号误认成死亡参与者',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '若12号曾是参与者并已死亡，门禁记录应在死亡后固定为离线，而不是由三个底座继续取得新握手。服务器也不该把“是否计入人数”作为随时切换的配置。\n星遥将旧合照的资产标签重新放大：“这里写的是身份槽，不是遗体编号。我们不能因为它被设计得像人，就替系统补一场不存在的死亡。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch5_case04_deduction',
  ),
  'ch5_case04_resolved': StoryBeat(
    id: 'ch5_case04_resolved',
    label: '12号是可重放的维护身份槽',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_e04_identity',
    cgFrame: 1,
    flagsOnEnter: {'case04_solved', 'slot12_maintenance_proven'},
    text:
        '原始绑架名单证明真实初始参与者只有01至11；跨区门禁证明12号没有连续身体；服务器配置证明它能被选择性计入人数、托管和区域占用。\n三类材料彼此独立，却指向同一件事：12号是维护身份槽，由不同底座重放，不是被藏起来的参与者。\n我们第一次能够用可复查的证据拒绝主办方的计数，而不是凭直觉说空椅子不该算人。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_identity_argument',
  ),
  'ch5_identity_argument': StoryBeat(
    id: 'ch5_identity_argument',
    label: '证明不是人不等于立刻修改裁定',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveRoom,
    text:
        '“我们证明12号不是人，系统就必须把它从人数里删掉？”唐弈问。\n“如果规则诚实，应该。”苏弥回答。\n“可完整条件写的是裁定名册，不是真实名单。”\n唐弈指出最危险的缝隙：事实上的虚假身份，仍可能在主办方定义的有效名单里占一席。揭露骗局只完成了证据问题，接下来还要迫使裁定承认自己的矛盾。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.suMi,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch5_identity_cross_submission',
  ),
  'ch5_identity_cross_submission': StoryBeat(
    id: 'ch5_identity_cross_submission',
    label: '四份独立异议不能使用同一段文案',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '系统允许四名参与者提交身份异议，却会拒绝内容完全相同的复制文本。叶岚要求每个人只使用自己亲手验证的材料：林澄提交路线，星遥提交镜像，苏弥提交人身记录，我提交装订链。\n“不要互相润色到一样。”她说，“独立证词不是四个人轮流按同一个人的发送键。”\n这像01终局条件的一次缩小预演：一致答案必须建立在各自理解上。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch5_system_partial_reply',
  ),
  'ch5_system_partial_reply': StoryBeat(
    id: 'ch5_system_partial_reply',
    label: '系统只承认12号没有生命体征',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveRoom,
    text:
        '四份异议提交后，系统回复：“身份槽12不绑定生物体征。门禁有效性不受影响。人数有效性将在条款结算时决定。”\n它承认了最基础的事实，却把是否算人留到最后一刻。\n“这就是陷阱。”苏弥说，“它要我们在不知道六人还是七人的情况下决定救不救一个人，再在结算时选择对自己有利的定义。”',
    passageSpeakers: [Speaker.administrator, Speaker.narration, Speaker.suMi],
    next: 'ch5_tangyi_offers_bargain',
  ),
  'ch5_tangyi_offers_bargain': StoryBeat(
    id: 'ch5_tangyi_offers_bargain',
    label: '唐弈提出用共同口径交换不减员',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveRoom,
    text:
        '唐弈提出一项交易：在确认12号统计前，他暂时不推动人数减少；作为交换，所有人不得私下提交“12号无效”，必须以共同口径行动。\n“你要的是否决权。”星遥说。\n“我要的是不让你们的六人条件单方面定义有效人数。”\n这不是纯粹恶意。06确实会因口径改变而失败。可把不杀人作为谈判筹码，本身已经说明杀人被他视为可随时恢复的策略。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch5_no_killing_bargain',
  ),
  'ch5_no_killing_bargain': StoryBeat(
    id: 'ch5_no_killing_bargain',
    label: '不杀人不能成为交换条件',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'concerned',
    text:
        '“你可以要求共同核验，不能要求我们用服从换取你暂时不杀人。”苏弥说。\n唐弈问：“区别在哪里？”\n“前者承认每个人都有被说服的权利，后者把活着当成你给出的优惠。”\n房间安静下来。唐弈没有接受这套道德语言，却也没有立即反驳。他在自己的PDA上写下异议，第一次没有把异议直接换算成行动。',
    passageSpeakers: [
      Speaker.suMi,
      Speaker.tangYi,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch5_field_recalculation',
  ),
  'ch5_field_recalculation': StoryBeat(
    id: 'ch5_field_recalculation',
    label: '人数条件被迫重新计算',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'relieved',
    text:
        '苏弥在公开栏提交三类证据，要求03号统计排除12。系统没有接受，也没有拒绝，只把“有效人数”后的数字暂时改成问号。\n唐弈的06号页面同样失去确定数字。他盯着问号看了很久。“你们以为揭穿假人会让条件更公平。对我来说，它只是让还要死几个重新变成未知。”\n“未知总比被故意写错好。”苏弥回答。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.suMi],
    next: 'ch5_partner_pause',
  ),
  'ch5_partner_pause': StoryBeat(
    id: 'ch5_partner_pause',
    label: '调查结束后没有人立刻站起来',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '长时间盯着旧纸与冷光屏幕后，视野边缘像蒙了一层灰。更让人疲惫的是，每一项事实都在改变某个人必须保护或消灭的对象。\n我需要把刚刚取得的记录交给一名同行者复核。那不是奖励，也不是在危机中偷来的闲暇；谁与我共同保管下一份证据，就会同时暴露在条款和怀疑里。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_partner_choice',
  ),
  'ch5_partner_choice': StoryBeat(
    id: 'ch5_partner_choice',
    label: '选择共同保管恢复签名的人',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text: '在继续读取服务器镜像前，我需要确定由谁与我共同保管第一份恢复签名。',
    next: null,
    choices: [
      StoryChoice(
        label: '与黎星遥复核镜像',
        caption: '她能验证信号来源，也会成为08条款的直接障碍。',
        next: 'ch5_xingyao_bond',
        requiresFlag: 'route_xingyao',
        effect: ChoiceEffect(
          xingyao: 2,
          logic: 1,
          flag: 'ch5_signature_xingyao',
        ),
      ),
      StoryChoice(
        label: '与苏弥保管名册',
        caption: '她需要证明真实人数，也会因此持有不可删除的责任记录。',
        next: 'ch5_sumi_bond',
        requiresFlag: 'route_sumi',
        effect: ChoiceEffect(
          sumi: 2,
          cooperation: 1,
          flag: 'ch5_signature_sumi',
        ),
      ),
      StoryChoice(
        label: '让林澄登记见证关系',
        caption: '尊重她独立决定是否把信赖与证据绑定。',
        next: 'ch5_lincheng_bond',
        requiresFlag: 'route_lincheng',
        effect: ChoiceEffect(
          lincheng: 2,
          logic: 1,
          flag: 'ch5_signature_lincheng',
        ),
      ),
      StoryChoice(
        label: '交由叶岚双人封存',
        caption: '不建立私人持有关系，只保留公开审计链。',
        next: 'ch5_public_signature',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch5_signature_public'),
      ),
    ],
  ),
  'ch5_xingyao_bond': StoryBeat(
    id: 'ch5_xingyao_bond',
    label: '她先确认我是否明白风险',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_bond_xingyao',
    cgFrame: 0,
    portraitMood: 'alarm',
    text:
        '星遥没有立刻接过镜像存储片。“这不是请我帮忙调一个信号。恢复签名在我这里，08想让记录永久消失，就必须改变我的决定、夺走我的终端，或者让我不能活到零点。”\n“我知道。”\n“再说清楚一点。”她盯着我，“你是因为我最懂镜像才选我，还是因为你觉得我一定会跟你站在一起？”',
    passageSpeakers: [Speaker.liXingyao, Speaker.shenYan, Speaker.liXingyao],
    next: 'ch5_xingyao_answer',
  ),
  'ch5_xingyao_answer': StoryBeat(
    id: 'ch5_xingyao_answer',
    label: '信任不等于默认同意',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '“因为你懂镜像，也因为你会在我说错时直接反驳。”我回答，“不是因为你欠我同意。”\n星遥低头检查存储片的写保护，黑发末端那一小片蓝色在服务器冷光里轻轻晃动。\n“那就一人持有签名，一人持有校验摘要。”她把完整片留给自己，只把摘要交给我，“谁被迫交出终端，另一份也不能独自恢复。别把保护做成替对方决定。”',
    passageSpeakers: [Speaker.shenYan, Speaker.narration, Speaker.liXingyao],
    next: 'ch5_xingyao_near',
  ),
  'ch5_xingyao_near': StoryBeat(
    id: 'ch5_xingyao_near',
    label: '耳机只分给我一侧',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_bond_xingyao',
    cgFrame: 1,
    portraitMood: 'relaxed',
    text:
        '为了听镜像里的低电平脉冲，星遥把左侧耳机递给我，自己保留右侧。经历过定向晕厥后，她仍会在戴上前停顿一下。\n我没有催。她确认离线夹已经接好，才把耳罩压住。我们的肩膀在狭窄工作台前相碰，她没有躲开。\n“如果这次我说停，你要先摘，不准先问为什么。”\n“约定还有效。”\n“那就好。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.liXingyao,
    ],
    next: 'ch5_bond_converge',
  ),
  'ch5_sumi_bond': StoryBeat(
    id: 'ch5_sumi_bond',
    label: '她不接受把危险叫作托付',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_bond_sumi',
    cgFrame: 0,
    portraitMood: 'concerned',
    text:
        '苏弥接过名册前，先问我是否看见她手指在抖。连续三天的急救、死亡确认和人数压力都被她压在稳定语气下面，直到纸边碰到指尖才泄露出来。\n“别说因为信任我，所以把最危险的东西交给我。”她说，“信任不能替代风险说明。”\n我把08条款、恢复方式和可能的夺取手段逐项念完。她听到最后，才在交接栏签下自己的名字。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch5_sumi_answer',
  ),
  'ch5_sumi_answer': StoryBeat(
    id: 'ch5_sumi_answer',
    label: '照顾者也可以要求被保护',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'shaken',
    text:
        '“如果有人来取名册，你准备让我先跑，自己留下吗？”苏弥问。\n我没有马上回答。过去几次危机里，她总是最后离开的人，而我也习惯把拖延追兵当成理所当然的分工。\n“不是。”我说，“我们一起撤，或者一起把记录交给第三个见证人。你不需要因为会救人，就永远站在出口最远的位置。”\n她缓慢呼出一口气。“把这句话也写进方案。”',
    passageSpeakers: [
      Speaker.suMi,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.suMi,
    ],
    next: 'ch5_sumi_near',
  ),
  'ch5_sumi_near': StoryBeat(
    id: 'ch5_sumi_near',
    label: '她把额头靠过来确认体温',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_bond_sumi',
    cgFrame: 1,
    portraitMood: 'relieved',
    text:
        '苏弥说我的瞳孔反应比刚进门时慢，伸手碰了碰我的额头。她的手背很凉，停留却比普通检查多了一秒。\n“低血糖还是疲劳？”我问。\n“都有。”她没有立刻收手，“还有一点不愿承认自己也会害怕。”\n我把应急糖片掰成两半。她看着掌心那一小块，终于笑了一下。这里没有适合拥抱的安全距离，但至少这一刻，我们没有把关心伪装成纯粹的医疗操作。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch5_bond_converge',
  ),
  'ch5_lincheng_bond': StoryBeat(
    id: 'ch5_lincheng_bond',
    label: '登记之前先确认可以撤回',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_bond_lincheng',
    cgFrame: 0,
    portraitMood: 'anxious',
    text:
        '林澄没有把“共同保管”直接理解成信赖登记。她翻遍07条款的附页，找到一行很小的撤回说明：双方清醒、同场、同时确认时可以解除关系。\n“如果没有撤回，我现在点同意，就像被条款逼着一直喜欢同一个决定。”她说。\n“所以先把退出方式写清楚。”我把自己的PDA放到她看得见却拿不到的位置，“你可以只做证据见证，不需要为了条款选择我。”',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.shenYan],
    next: 'ch5_lincheng_answer',
  ),
  'ch5_lincheng_answer': StoryBeat(
    id: 'ch5_lincheng_answer',
    label: '她用自己的名字作出选择',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '林澄重新读了两遍风险说明，然后在07号页面输入“沈砚”，没有使用编号。\n“我登记你，不是因为你是01，也不是因为你现在最像能带大家出去的人。”她说，“是因为每次我说不想被替我决定，你都真的停下来听完。”\n确认键亮起时，她的手仍在抖，却没有看向任何人寻求许可。我只在自己的终端上按下自愿确认，没有替她完成最后一步。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    flagsOnEnter: {'ch5_lincheng_trust_registered'},
    next: 'ch5_lincheng_near',
  ),
  'ch5_lincheng_near': StoryBeat(
    id: 'ch5_lincheng_near',
    label: '不是编号之间的约定',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_bond_lincheng',
    cgFrame: 1,
    portraitMood: 'determined',
    text:
        '登记完成后，林澄把那张手抄名单折出一个新的小格，在07旁边写下我的名字。\n“出去以后，这个还算吗？”她问。\n“条款不算，选择可以重新问。”\n她抿了一下唇，像对这个不够浪漫却足够诚实的回答感到满意。\n“那你先活到我能重新问。”\n她伸出小指，又在碰到我之前停住。我向前补上最后一点距离，约定没有被系统记录。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.shenYan,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch5_bond_converge',
  ),
  'ch5_public_signature': StoryBeat(
    id: 'ch5_public_signature',
    label: '恢复签名不交给单独的人',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '叶岚把恢复签名拆成两段，分别封入透明袋，由我与她各持一份。任何一段都不能单独恢复记录，交接必须在公开频道留下时间。\n“这不会消除灭口动机。”她提醒，“只会让伤害一个人不再足以达到目的。”\n制度不是信任的替代品，却能让信任不必独自承担一次错误判断的全部代价。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch5_bond_converge',
  ),
  'ch5_bond_converge': StoryBeat(
    id: 'ch5_bond_converge',
    label: '恢复签名进入公开清单',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '第一份恢复签名完成交接。我们公开持有关系与撤回方式，却不公开存储片的具体藏位。\n这项安排同时保护了记录，也制造了目标。08的完整条件已经证明：只要签名者存活，外包责任就无法永久消失。档案库里的每一道目光都开始重新计算，谁的死亡能够让哪一份文件沉默。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_zero_first_trace',
  ),
  'ch5_zero_first_trace': StoryBeat(
    id: 'ch5_zero_first_trace',
    label: 'ZERO第一次出现在纸上',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '林澄在改造合同末页找到负责人签名。墨迹被刮去大半，斜光下仍能看出“ZERO”五个压痕。\n同一个词已经出现在服务器裁定进程名里。现在它又属于一个应该由人签字的位置。\n“所以ZERO是幕后的人？”林澄问。\n“只能证明有人或某个授权主体用过这个代号。”我说，“不要让一个词比证据先长出脸。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.shenYan,
    ],
    next: 'ch5_zero_second_trace',
  ),
  'ch5_zero_second_trace': StoryBeat(
    id: 'ch5_zero_second_trace',
    label: 'ZERO也在终局证词栏中',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '服务器镜像深处还有一份未启用的终局表单，标题是“ZERO PROTOCOL”。它要求四名参与者在隔离终端独立输入主办者代号，再由系统比较答案。\n负责人签名、裁定进程、证词协议，三处都使用ZERO。它可能是一个人、一台程序，也可能是一套逼参与者共同完成的裁定流程。\n三种解释都成立了一部分，也都不足以成为最终答案。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_conflict_trigger',
  ),
  'ch5_conflict_trigger': StoryBeat(
    id: 'ch5_conflict_trigger',
    label: '服务器忽然公布恢复签名在线',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveRoom,
    text:
        '公共屏幕突然刷新：“外包责任记录01已取得恢复签名。永久删除条件未满足。”\n主办方没有公布持有者，却把签名者仍然活着这件事广播给所有人。与此同时，门禁强制控制器显示“已离架”，B-01的腐蚀剂也从封存变成“去向不明”。\n有人在我们调查时取走了能够锁门的设备，也有人已经为销毁纸张或伤害持有者准备了另一种手段。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.narration,
      Speaker.narration,
    ],
    highRiskItemsMissingOnEnter: {'door_override', 'corrosive_cleaner'},
    auditNext: 'ch5_audit_projection',
    auditRequiredFlags: {'ch5_audit_prediction_available'},
    next: 'ch5_standard_branch_gate',
  ),
  'ch5_standard_branch_gate': StoryBeat(
    id: 'ch5_standard_branch_gate',
    label: '第一次杀人决定了谁最先行动',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '没有人承认取走物资。可昨天已经证明，真正的分界不是谁最可疑，而是谁已经跨过“明知可能致死仍继续”的那一步。\n第一次主动杀人留下的责任、恐惧和模仿方式在此刻重新排列。有人要为死者复仇，有人要让责任记录永远消失，也有人只是借两种理由把人数继续推向四。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch4_first_killer_hanqi': 'ch5_hanqi_revenge_start',
      'ch4_first_killer_alliance': 'ch5_alliance_silence_start',
      'ch4_first_killer_majority': 'ch5_majority_silence_start',
    },
    next: 'ch5_standard_lockdown',
  ),
  'ch5_hanqi_revenge_start': StoryBeat(
    id: 'ch5_hanqi_revenge_start',
    label: '唐弈把复仇说成风险控制',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'shaken',
    text:
        '唐弈把陈默的08条款投到公共屏幕。“现在知道他为什么复制权限了。韩骐杀了一个可能继续灭口的人，所以你们打算把韩骐重新叫成保护者？”\n“没有人这么说。”叶岚回答。\n“可你们仍让他站在离01最近的位置。”唐弈看向我，“一个已经证明自己不会及时停手的人，再加一条要求控制01的完整字段。要赌他下一次会停吗？”',
    passageSpeakers: [Speaker.tangYi, Speaker.yeLan, Speaker.tangYi],
    next: 'ch5_hanqi_revenge_lincheng',
  ),
  'ch5_hanqi_revenge_lincheng': StoryBeat(
    id: 'ch5_hanqi_revenge_lincheng',
    label: '林澄拒绝替死者接受复仇',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '“陈默没有登记任何人替他复仇。”林澄说，“你可以说韩骐危险，不能说杀掉韩骐就是陈默想要的。”\n唐弈没有与她争。他只是问：“如果韩骐先拿到01，你的信赖对象会不会成为被控制的一部分？”\n这句话精准地碰到07字段。林澄下意识挡到我前方，随后意识到自己的动作正被唐弈拿来证明他的判断。',
    passageSpeakers: [Speaker.linCheng, Speaker.tangYi, Speaker.narration],
    next: 'ch5_hanqi_override_reveal',
  ),
  'ch5_hanqi_override_reveal': StoryBeat(
    id: 'ch5_hanqi_override_reveal',
    label: '门禁控制器藏在旧档案车下',
    speaker: Speaker.hanQi,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_hanqi_shelf',
    cgFrame: 0,
    portraitMood: 'armed',
    text:
        '韩骐弯腰掀开档案车底布，门禁强制控制器就卡在轮轴内侧。他没有伸手，先后退一步。\n“这是引我来拿。”他说。\n话音未落，移动柜轨道突然启动。最外侧柜体向中央合拢，把韩骐与控制器一同隔进狭窄检修道。唐弈的PDA上闪过一次已经撤销的06号操作会话。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch5_hanqi_trap_choice',
  ),
  'ch5_hanqi_trap_choice': StoryBeat(
    id: 'ch5_hanqi_trap_choice',
    label: '强者被困后仍有可以执行的救援',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'injured',
    text:
        '高原找到轨道侧面的机械泄压栓。两个人同时拉住，柜体就能停下；代价是必须有人靠近韩骐可能触及的控制器。\n“他被夹死前还有四十秒。”高原说。\n唐弈堵住右侧泄压位。“放他出来，他第一件事就是拿控制器和01。陈默已经用命证明，靠近他以后没有第二次停手机会。”\n真实风险再次被用来覆盖仍然存在的救援动作。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch5_hanqi_last_words',
  ),
  'ch5_hanqi_last_words': StoryBeat(
    id: 'ch5_hanqi_last_words',
    label: '韩骐把终端踢出缝隙',
    speaker: Speaker.hanQi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'conflicted',
    text:
        '韩骐没有去抓控制器。他把自己的PDA从柜底缝隙踢出来，又把双手举到摄像头能看见的位置。\n“我出来以后不碰01，也不碰门禁。”他说，“先铐住我，再拉泄压。”\n这是一个可执行的退让。唐弈看见PDA离开，也看见韩骐主动放弃了04条款此刻最需要的工具，却仍没有让开泄压位。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch5_hanqi_revenge_death',
  ),
  'ch5_hanqi_revenge_death': StoryBeat(
    id: 'ch5_hanqi_revenge_death',
    label: '风险控制越过了可以停止的位置',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_hanqi_shelf',
    cgFrame: 1,
    timelineMinute: 4558,
    text:
        '柜体合拢前最后五秒，我与高原拉住左侧泄压，右侧却始终空着。金属轨道发出一声沉闷冲击，韩骐的声音随之中断。\n“04号生命体征终止。”\n唐弈没有直接推动柜体。他只是取走控制器、预置旧会话，并在仍能救援时阻止第二个人靠近泄压位。弱者没有突然获得更强的身体；他用路线、设备和别人对强者的恐惧完成了杀人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch5_revenge_killing', 'ch5_tangyi_escalated'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '04',
        cause: '门禁强制控制器启动移动柜后阻止机械泄压',
        timelineMinute: 4558,
        responsibleParticipantIds: ['06'],
        sourceItemId: 'door_override',
      ),
    ],
    next: 'ch5_standard_aftermath',
  ),
  'ch5_alliance_silence_start': StoryBeat(
    id: 'ch5_alliance_silence_start',
    label: '陈默要求单独读取自己的责任记录',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'desperate',
    text:
        '“08记录涉及我的私人工作，我有权先确认内容。”陈默站在服务器镜像前，要求持有恢复签名的人退出内间。\n“你的条款要求它永久消失。”星遥说，“这正是你不能单独确认的理由。”\n陈默的目光越过她，停在签名存储片可能所在的位置。他已经知道说服不会比夺取更快。',
    passageSpeakers: [Speaker.chenMo, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_alliance_acid_trace',
  ),
  'ch5_alliance_acid_trace': StoryBeat(
    id: 'ch5_alliance_acid_trace',
    label: '腐蚀剂不是为了清洁服务器',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'concerned',
    text:
        '苏弥先闻到刺鼻气味。服务器柜顶部的清洁管被换成B-01腐蚀剂，阀门用一根细线连着资料抽屉；谁拉开存放恢复签名的抽屉，液体就会沿柜门泼下。\n“这不是临时起意。”她说，“管线长度和落点都量过。”\n陈默后退一步，袖口却沾着与管线封胶相同的白色粉末。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch5_alliance_chenmo_admission',
  ),
  'ch5_alliance_chenmo_admission': StoryBeat(
    id: 'ch5_alliance_chenmo_admission',
    label: '他承认装置却否认想杀人',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'desperate',
    text:
        '“只会烧毁存储片。”陈默说，“我计算过角度，液体不会碰到脸。”\n“抽屉由人拉开。”苏弥指向低处的导流槽，“弯腰的人会先被泼到颈侧和手臂。”\n“我可以提前警告。”\n“那你为什么用细线触发？”\n陈默没有回答。像周叙案里的中继器一样，装置把伤害写成了打开抽屉的后果，让按下开关的人可以假装自己不在句子里。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.suMi,
      Speaker.chenMo,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch5_alliance_yelan_intervenes',
  ),
  'ch5_alliance_yelan_intervenes': StoryBeat(
    id: 'ch5_alliance_yelan_intervenes',
    label: '叶岚先去解除触发线',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_yelan_acid',
    cgFrame: 0,
    portraitMood: 'intervening',
    text:
        '叶岚戴上护目镜，用档案夹固定抽屉，再从侧面剪断触发线。陈默突然扑向她手中的半段恢复签名。\n两个人撞上移动柜，腐蚀剂容器从顶部倾倒。叶岚把签名片推向我，自己却被液体溅中肩颈。\n“冲水！”苏弥喊。\n紧急喷淋就在内间，门禁却在同一秒被强制控制器锁死。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch5_alliance_locked_shower',
  ),
  'ch5_alliance_locked_shower': StoryBeat(
    id: 'ch5_alliance_locked_shower',
    label: '解锁条件握在陈默手里',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'desperate',
    text:
        '强制控制器在陈默手中。只要他取消锁定，苏弥就能把叶岚送进喷淋间；取消后，他也会失去封闭服务器、夺取签名的最后机会。\n“把存储片给我。”他喘着气说，“我开门。”\n叶岚靠在柜边，皮肤已经出现灰白灼痕，仍摇头。“这是交换，不是救援。先开门，再谈记录。”\n陈默看着倒计，没有按下取消。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch5_alliance_silence_death',
  ),
  'ch5_alliance_silence_death': StoryBeat(
    id: 'ch5_alliance_silence_death',
    label: '灭口不需要以刀为形状',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_yelan_acid',
    cgFrame: 1,
    timelineMinute: 4564,
    portraitMood: 'shaken',
    text:
        '我们最终从外侧切断锁舌时，喷淋延迟已经超过急救窗口。苏弥持续冲洗、维持气道，叶岚却在严重化学灼伤与休克中失去生命体征。\n“11号死亡。”苏弥亲自记录，“腐蚀剂装置造成伤害，08号在持有解锁能力时以恢复签名交换救援，延误处置。”\n陈默没有亲手把液体泼向她。可从预置触发到拒绝开门，每一步都知道一个活人正替那份记录承受代价。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    flagsOnEnter: {'ch5_silencing_killing', 'ch5_chenmo_escalated'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '11',
        cause: '腐蚀剂陷阱灼伤后被门禁锁定延误冲洗',
        timelineMinute: 4564,
        responsibleParticipantIds: ['08'],
        sourceItemId: 'corrosive_cleaner',
      ),
    ],
    next: 'ch5_standard_aftermath',
  ),
  'ch5_majority_silence_start': StoryBeat(
    id: 'ch5_majority_silence_start',
    label: '众人试图再次用表决处理08',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'shaken',
    text:
        '陈默的责任链公开后，有人要求立即收走08终端，有人要求先听解释。唐弈提出最快办法。\n“投票决定他是否退出档案区。”\n上一次票数留下的空位仍在众人之间。没有人愿意第一个举手，却也没有人提出新的执行方案。\n陈默趁这段迟疑退入服务器内间，强制控制器随即把门锁死。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch5_majority_server_threat',
  ),
  'ch5_majority_server_threat': StoryBeat(
    id: 'ch5_majority_server_threat',
    label: '陈默把镜像与自己的命绑在一起',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'desperate',
    text:
        '内间扬声器传出陈默的声音。“让我删除三份记录，我交出周叙案完整调用链，也交出门禁。”\n“你交出的东西本来就是证据。”我说。\n“对你是证据，对我是出去以后再也洗不掉的罪名！”\n他终于把真正的恐惧说出来。不是项圈立即处决，而是活着离开以后仍要为自己主动做过的事负责。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.shenYan,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch5_majority_cooling_alarm',
  ),
  'ch5_majority_cooling_alarm': StoryBeat(
    id: 'ch5_majority_cooling_alarm',
    label: '内间冷却被他自己切断',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_chenmo_gas',
    cgFrame: 0,
    portraitMood: 'alarm',
    text:
        '陈默开始擦除镜像，服务器温度迅速上升。他为了阻止远程中断，切断了冷却和安全回路的控制线。\n“再升十二度，灭火气体会自动灌入内间。”星遥说，“门可以从外侧机械开启，但需要两个人同时撤销刚才的隔离请求。”\n系统把请求发给先前主张收走08终端的四个人。每个人都在等别人先撤回。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_majority_chenmo_plea',
  ),
  'ch5_majority_chenmo_plea': StoryBeat(
    id: 'ch5_majority_chenmo_plea',
    label: '被表决的人开始请求撤回',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'desperate',
    text:
        '警报响起后，陈默停止擦除。“我开门。记录也不删。撤回隔离。”\n他把强制控制器从传递槽推出来，屏幕显示锁定已经取消。外门仍因四人的隔离请求保持关闭。\n“他会不会出来再抢？”有人问。\n这与高原最后九十秒里的问题一模一样：未来风险是真实的，眼前救援也仍然可以执行。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch5_majority_silence_death',
  ),
  'ch5_majority_silence_death': StoryBeat(
    id: 'ch5_majority_silence_death',
    label: '同一种制度第二次杀人',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_chenmo_gas',
    cgFrame: 1,
    timelineMinute: 4561,
    text:
        '只有我与苏弥完成撤回。其余请求者中，有人害怕陈默出来报复，有人希望责任记录随他一起封死，还有人只是认为少一人更接近自己的条款。\n惰性气体灌入内间。陈默在失去意识前把完整调用链发送到公共频道。\n“08号生命体征终止。”\n上一次死亡没有教会多数人停止，只教会他们如何让相同动作看起来更像程序自动执行。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch5_majority_repeated_killing', 'ch5_chenmo_dead'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '08',
        cause: '服务器内间灭火气体启动后隔离请求未被撤回',
        timelineMinute: 4561,
        responsibleParticipantIds: ['06', '04'],
      ),
    ],
    next: 'ch5_standard_aftermath',
  ),
  'ch5_standard_lockdown': StoryBeat(
    id: 'ch5_standard_lockdown',
    label: '未知分支仍留下物资失踪',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text: '我们没有足够记录判断谁先取走物资，只能封闭档案库并将恢复签名拆分保管。强制控制器和腐蚀剂仍然去向不明，像两句尚未写完的威胁留在地图上。',
    passageSpeakers: [Speaker.narration],
    next: 'ch5_standard_aftermath',
  ),
  'ch5_standard_aftermath': StoryBeat(
    id: 'ch5_standard_aftermath',
    label: '复仇与灭口都留下具体责任',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '我们再次记录死亡、工具、可停止的时刻与拒绝停止的人。没有一条记录只写“死于争执”或“系统处决”。\n校验字段没有控制任何人的手，却把恐惧、利益和可用资源排列成了最短路径。走上路径的人仍然作出了选择；主办方的设计责任与参与者的行动责任必须同时保留，不能让其中一项替另一项消失。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_zero_archive_standard',
  ),
  'ch5_zero_archive_standard': StoryBeat(
    id: 'ch5_zero_archive_standard',
    label: '死亡让预演记录变得更像剧本',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '服务器在死亡发生后生成一份新文件，标题是“DAY-04 BEHAVIOR SAMPLE”。其中的预测时间只比实际动作早几十分钟，仿佛ZERO一直在等待我们选择最接近哪一种样本。\n“它没有精确预测谁会按键。”星遥说，“它预测的是只要把这些条件、武器和距离放在一起，就总有人会把风险推成杀人。”\n我们取得了样本，却已经无法用它救回今天的人。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    flagsOnEnter: {'ch5_zero_sample_after_killing'},
    next: 'ch5_common_closure',
  ),
  'ch5_audit_projection': StoryBeat(
    id: 'ch5_audit_projection',
    label: '预演在物资离架前留下了持有路径',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '审计索引在广播前恢复出三张路径图：强制控制器会被放进移动柜诱使韩骐靠近；腐蚀剂会被接到恢复签名抽屉；服务器隔离请求会重演高原之死。\n路径图没有写凶手姓名，只列出“力量持有者、删除受益者、人数受益者、签名持有者”。\n它预测的是角色位置，不是不可改变的命运。也正因此，我们仍需要验证现实里哪些准备已经发生。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_audit_split_tasks',
  ),
  'ch5_audit_split_tasks': StoryBeat(
    id: 'ch5_audit_split_tasks',
    label: '每个人核验最不利于自己的部分',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '叶岚让韩骐站在摄像区口述移动柜泄压方式，由林澄实际操作；陈默只解释服务器擦除接口，由星遥断开写入；唐弈计算隔离撤回阈值，却把自己的终端交给苏弥保管。\n“预演说你可能做什么，不是说你已经做了。”叶岚提醒，“核验的目的，是让任何人都无法独自完成预测里的整条动作。”',
    passageSpeakers: [Speaker.narration, Speaker.yeLan],
    next: 'ch5_audit_find_override',
  ),
  'ch5_audit_find_override': StoryBeat(
    id: 'ch5_audit_find_override',
    label: '控制器在启动轨道前被找到',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_audit_prevention',
    cgFrame: 0,
    portraitMood: 'determined',
    text:
        '林澄按路径图检查档案车，却没有直接掀开底布。她先用镜面片确认轮轴内有控制器，再从轨道总闸切断动力。\n韩骐站在两米外看着她完成。“如果没有这张图，我会先把它拿出来。”\n“我知道。”林澄回答，“所以我不是来证明你一定会杀人，是来让你不需要靠意志力证明自己。”',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.linCheng],
    highRiskItemsResealedOnEnter: {'door_override'},
    next: 'ch5_audit_find_acid',
  ),
  'ch5_audit_find_acid': StoryBeat(
    id: 'ch5_audit_find_acid',
    label: '腐蚀剂管线在抽屉打开前被拆除',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    portraitMood: 'concerned',
    text:
        '苏弥没有碰恢复签名抽屉，先沿预测中的落点检查柜顶。未启封的腐蚀剂容器已经被运到内间，旁边放着软管与触发线，却还没有完成连接。\n“准备本身不能证明是谁最终会用。”她说，“但它证明主办方希望任何人拉开抽屉时，伤害看起来像自己的选择。”\n容器重新封存，管线与抽屉分区保管。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    highRiskItemsResealedOnEnter: {'corrosive_cleaner'},
    next: 'ch5_audit_restore_escrow',
  ),
  'ch5_audit_restore_escrow': StoryBeat(
    id: 'ch5_audit_restore_escrow',
    label: '恢复签名被拆成无人能独自夺取的三份',
    speaker: Speaker.chenMo,
    scene: SceneKey.archiveRoom,
    portraitMood: 'guarded',
    text:
        '我们将恢复签名改为三段门限：任意两段可以恢复，一段无法定位另外两段。陈默亲自验证接口后，退出存储区。\n“这样我就算拿到一个人的终端，也删不干净。”他说。\n“你也可以选择公开责任记录，放弃最短路径。”我提醒。\n陈默看向周叙的账目，许久才回答：“我还没准备好承认全部。但至少今天，我不能再假装系统替我做过第一次选择。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.shenYan,
      Speaker.chenMo,
    ],
    flagsOnEnter: {'ch5_restore_signature_escrowed'},
    next: 'ch5_audit_slot12_challenge',
  ),
  'ch5_audit_slot12_challenge': StoryBeat(
    id: 'ch5_audit_slot12_challenge',
    label: '众人共同提交12号无效证明',
    speaker: Speaker.suMi,
    scene: SceneKey.archiveRoom,
    cgId: 'cg_ch5_audit_prevention',
    cgFrame: 1,
    portraitMood: 'relieved',
    text:
        '苏弥、星遥、林澄与我分别用纸质名单、跨区门禁、服务器配置和资产标签提交独立异议。四份答案不是互相复制，而是从不同材料到达同一结论。\n系统将12号从03的真实人数统计中排除，却仍保留它对门禁和区域的维护权限。\n“它终于承认12号不算一条命。”苏弥说。\n“只在这一栏。”星遥提醒，“别把局部胜利当成系统已经诚实。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.liXingyao,
    ],
    flagsOnEnter: {'ch5_slot12_count_rejected', 'ch5_audit_chain_blocked'},
    next: 'ch5_audit_zero_sample',
  ),
  'ch5_audit_zero_sample': StoryBeat(
    id: 'ch5_audit_zero_sample',
    label: '预演第一次被现实证据反驳',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'relaxed',
    text:
        '零点后的行为样本仍按计划生成，三条预测却都标记为“链路中断”：轨道未启动、腐蚀剂未连接、隔离请求未成立。\n星遥将现实记录附在每条预测后面。“ZERO能计算我们最可能如何互相伤害，但它不能让还没发生的动作承担责任。”\n这份被反驳的预演比一次神奇的预知更有价值。它证明杀戮链可以在资源、权限和见证的具体位置被切断。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_common_closure',
  ),
  'ch5_common_closure': StoryBeat(
    id: 'ch5_common_closure',
    label: '三种ZERO解释被并列封存',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '我们把三类ZERO记录分别装袋：负责人签名属于“可能的人类主体”，裁定进程属于“正在执行的程序”，终局表单属于“要求参与者共同完成的协议”。\n没有人获准把其中任何一类写成最终答案。01号需要四份独立证词，过早统一口径只会让我们变成主办方想要的复读终端。\n真正的共同理解，必须允许四个人先保留不同疑问，再用证据抵达同一处。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_vote_forewarning',
  ),
  'ch5_vote_forewarning': StoryBeat(
    id: 'ch5_vote_forewarning',
    label: '档案里的预案提前写着多数决',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        'ZERO终局表单旁还有一份区域管理预案：第五日开放匿名投票，以简单多数决定永久封锁顺序。文件写于绑架完成前，说明主办方早已预期人数冲突会在第四日形成阵营。\n我们以为明天的投票是规则推进，其实它与今天公开的字段属于同一套设计：先让每个人拥有不同损失，再给他们一只看起来平等的按钮。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_vote_is_not_equal',
  ),
  'ch5_vote_is_not_equal': StoryBeat(
    id: 'ch5_vote_is_not_equal',
    label: '同样一票承担的风险并不相同',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '林澄把剩余区域贴到墙上。封锁医务区会让伤者承担风险，封锁设备区会让高原与星遥失去维修能力，封锁宿舍则会迫使所有人在公共区域休息。\n“每个人都有一票，不代表每个人被关在门后的概率一样。”她说。\n学校里“少数服从多数”常被当成公平的终点；在这里，少数者失去的不是发言机会，而可能是氧气、药品和返回路线。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch5_vote_delegation_danger',
  ),
  'ch5_vote_delegation_danger': StoryBeat(
    id: 'ch5_vote_delegation_danger',
    label: '公开委托会让强者拥有多只手',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveRoom,
    portraitMood: 'alarm',
    text:
        '投票预案允许公开委托：伤者或失去操作权的人可以把票交给他人。星遥立刻指出，04若控制01终端，可能同时取得两票；08若保留旧会话，也可能在撤销后短暂代投。\n“按钮数量不会告诉我们背后有几个人。”她说，“就像12号白点不会告诉我们背后没有人。”\n明天的票箱会重复同一谜题：系统验证终端，却不保证终端背后的意志独立。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch5_vote_yelan_rule',
  ),
  'ch5_vote_yelan_rule': StoryBeat(
    id: 'ch5_vote_yelan_rule',
    label: '叶岚要求先声明利益再听提案',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '叶岚提出临时规则：每个人在说明封锁方案前，先公开自己会从中获得或失去什么；提案者不得担任唯一计票人；被封锁区域中的人拥有最后陈述权。\n“这些规则不能保证正确。”她说，“只能让一个决定日后仍能追问是谁提出、谁受益、谁知道风险、谁负责执行。”\n经历过高原之死后，可追责不再是事后文书，而是救援能否及时发生的一部分。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch5_vote_tangyi_reply',
  ),
  'ch5_vote_tangyi_reply': StoryBeat(
    id: 'ch5_vote_tangyi_reply',
    label: '唐弈认为公开利益会制造更精确的攻击',
    speaker: Speaker.tangYi,
    scene: SceneKey.archiveRoom,
    text:
        '“把利益全写出来，等于把每个人最怕失去的区域标红。”唐弈说，“对想合作的人是透明，对想杀人的人是目标清单。”\n叶岚没有否认。“所以公开程度本身也要表决。可以说明冲突类型，不公开全部实现细节。”\n透明并非越多越好。死亡游戏里，信息既能建立互相监督，也能把弱点变成主办方无需亲自整理的狩猎指南。',
    passageSpeakers: [Speaker.tangYi, Speaker.yeLan, Speaker.narration],
    next: 'ch5_vote_shenyan_fear',
  ),
  'ch5_vote_shenyan_fear': StoryBeat(
    id: 'ch5_vote_shenyan_fear',
    label: '01将成为所有失败的可见责任人',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '有人提议由01集中决定，理由是我的条款需要共同证词，最有动力保留足够的人。\n这个理由听起来合理，也让我感到一瞬间的轻松：不必再等待摇摆不定的多数，我可以选一个损失最小的答案。\n随即而来的恐惧更诚实。如果门后有人死去，所有人都可以把选择压缩成“沈砚决定”。集中责任或许清楚，也会让我成为下一轮复仇最明确的目标。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_vote_relationship_cost',
  ),
  'ch5_vote_relationship_cost': StoryBeat(
    id: 'ch5_vote_relationship_cost',
    label: '亲密关系也会进入投票怀疑',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveRoom,
    text:
        '无论我把恢复签名交给星遥、苏弥、林澄还是公开封存，明天都会有人怀疑我的票是在保护某一条关系。\n这种怀疑并非全无根据。人不可能在喜欢、亏欠和害怕失去之间保持绝对中立。真正需要记录的不是“我没有私心”，而是私心影响了哪个判断、是否有人能够提出替代方案。\n感情若只在安全场景里出现，就不会触及这场游戏真正想利用的部分。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_vote_prepare_map',
  ),
  'ch5_vote_prepare_map': StoryBeat(
    id: 'ch5_vote_prepare_map',
    label: '封锁地图被改成后果预览',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveRoom,
    portraitMood: 'determined',
    text:
        '林澄开始为每个候选区域绘制三层后果：会被切断的路线、会失去的物资、需要提前撤离的人。她拒绝在任何区域旁写“推荐”。\n“地图只能告诉大家选了以后会发生什么，不能替大家决定谁比较值得承担。”\n高原留下的步行时间、星遥的信号盲区与苏弥的伤员转运距离都被叠在同一张图上。明天的选择至少不能再假装只关闭一间空房。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch5_archive_seal_notice',
  ),
  'ch5_archive_seal_notice': StoryBeat(
    id: 'ch5_archive_seal_notice',
    label: 'E-04将在日出前永久封锁',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveRoom,
    timelineMinute: 4680,
    text:
        '清晨六点，广播宣布E-04将在三十分钟后永久封锁。所有原始档案必须留在区内，参与者只能带走经公共终端登记的副本。\n“第五日区域表决将在十二小时后开放。剩余区域的封锁顺序由有效参与者决定。”\n主办方刚让我们看见错误人数如何制造杀戮，紧接着便把下一扇门交给多数决定。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch5_copy_decision',
  ),
  'ch5_copy_decision': StoryBeat(
    id: 'ch5_copy_decision',
    label: '副本不能只由一方保管',
    speaker: Speaker.yeLan,
    scene: SceneKey.archiveRoom,
    portraitMood: 'intervening',
    text:
        '我们制作三套副本：12号身份证据、周叙案责任链、ZERO三重代号。每套拆成事实页与校验页，分给利益不同的人持有。\n若叶岚已经在本路线死亡，这套分配便由她此前留下的利益回避表执行；她不在场的后果不是少一句台词，而是每次交接都少了一个会追问“谁从这个结论获利”的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_departure_roll_call',
  ),
  'ch5_departure_roll_call': StoryBeat(
    id: 'ch5_departure_roll_call',
    label: '离开时仍从01点到12',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'determined',
    text:
        '林澄在门外再次点名。死亡编号得到姓名与死因回应，活人亲自回答。念到12号时，E-04内部的白灯仍发出电子确认。\n她在纸上写：“维护身份槽，非真实参与者；区域权限仍有效。”\n这一次，我们没有因为知道它不是人就忽略它。假身份不需要被哀悼，却仍然是一件能够关门、计数和替主办方作证的危险装置。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch5_e04_sealed',
  ),
  'ch5_e04_sealed': StoryBeat(
    id: 'ch5_e04_sealed',
    label: '档案库带着原件沉入封锁',
    speaker: Speaker.administrator,
    scene: SceneKey.archiveCorridor,
    timelineMinute: 4710,
    text:
        '钢门闭合后，十二枚身份灯依次熄灭。最后熄灭的仍是白色12号，仿佛它比任何活人都更有耐心。\n“E-04永久封锁完成。”\n我们失去了原始档案库，却带走了足以复查的副本、清楚记录的缺口，以及一个不能再被主办方随意称作“第十二名幸存者”的结论。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch5_day_four_end',
  ),
  'ch5_day_four_end': StoryBeat(
    id: 'ch5_day_four_end',
    label: '第四日留下的不只是一个答案',
    speaker: Speaker.shenYan,
    scene: SceneKey.archiveCorridor,
    text:
        '12号身份已经确认，ZERO却从一个名字扩散成三种可能。校验字段全部公开后，朋友、医生、工程师和见证人都被重新标上了“必须保护”“必须控制”或“必须消失”的用途。\n普通模式里，复仇或灭口已经让杀戮继续升级；审计模式里，我们只证明同一条链可以被提前拆开。两种结果都将进入明天的表决，没有任何制度会因为今天说对一个答案就自动变得安全。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch5_end',
  ),
  'ch5_end': StoryBeat(
    id: 'ch5_end',
    label: '下一次封锁将由众人决定',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '集合厅的主屏幕显示剩余区域、存活人数和一只空白投票箱。每个人的PDA都多出“匿名投票”与“公开委托”两个入口。\n“第五日零点前，参与者必须决定下一处永久封锁区域。简单多数即为有效结果。”\n屏幕没有显示每个区域里有什么人，只显示票。主办方准备把杀人的手从某个人手里拿走，分成许多枚看起来同样轻的选择键。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch6_vote_opening',
  ),
};
