part of 'story.dart';

const chapterEightBeats = <String, StoryBeat>{
  'ch8_final_day_open': StoryBeat(
    id: 'ch8_final_day_open',
    label: '最后二十四小时从一阵没有响起的警报开始',
    speaker: Speaker.narration,
    scene: SceneKey.dormitory,
    timelineMinute: 8640,
    text:
        '我在零点后的第十一分钟醒来，最先注意到的不是灯，而是安静。过去六天，每次整点都有风机换挡、门锁校验或PDA提示；这一次，走廊里什么都没有，像设施故意把最后一天伪装成一段可以继续睡下去的普通清晨。\n枕边的离线本仍压在手腕下。审批板、三节点拓扑、参与者输入总线，三项结论被我在睡前重写了四遍。字迹一次比一次整齐，意思却没有因此更确定。独立证词要求四个人理解同一结构，不要求他们重复我的句子。\n我坐起身，项圈内侧因整夜压迫留下发热的红痕。倒计时显示二十三小时四十九分。主办方没有催促，反而让我更清楚地意识到：它已经把最后一步交给我们自己完成。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_morning_body_check',
  ),
  'ch8_morning_body_check': StoryBeat(
    id: 'ch8_morning_body_check',
    label: '身体没有因为抵达最后一天自动恢复',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'concerned',
    text:
        '门外，苏弥把最后几片电极贴在墙边，要求每个醒来的人先报头晕、手抖和睡眠时间，再谈终局。普通路线只能听见四次回答；审计路线的九个人依次开口，声音相互覆盖，却没有人嫌点名太慢。\n“低血糖会让人把熟悉的词当成已经理解。”她把半块压缩饼干递给我，“证词前至少吃下去。别用坚持清醒证明你有资格。”\n我咬下一口，干硬的碎屑黏在舌根。最后一天仍由这些具体得近乎琐碎的身体组成，而不是四个抽象席位。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch8_last_roll_call',
  ),
  'ch8_last_roll_call': StoryBeat(
    id: 'ch8_last_roll_call',
    label: '最后一次点名仍先报姓名再报编号',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '林澄在集合厅白板上重新写下名单。她没有沿用主屏的存活排序，而是从沈砚开始，一个名字、一个编号、一次本人回应。已经死亡的人也被写入，只是不再等待回答。\n普通路线的空白几乎占满半面墙；审计路线只有吴峥与周叙两行没有声音。林澄写到最后，粉笔灰落在深色制服袖口上，她停了一会儿才说：“终端只认编号，但我们出去以后不能让记录也只剩编号。”\n没有人鼓掌。名字不是纪念仪式的装饰，而是后续调查要通知的家属、需要归还的物品，以及不能被一句实验损耗合并掉的生活。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch8_dead_names_record',
  ),
  'ch8_dead_names_record': StoryBeat(
    id: 'ch8_dead_names_record',
    label: '死者名单不接受由活人替写的最后意见',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚或仍保存她规则的人在名单旁增加一列：最后可验证陈述。周叙留下的是对距离异常的质疑，吴峥留下的是拒绝被项圈恐吓，其他死者则保留各自最后报告的位置、风险与不同意。\n“不要替他们补成支持我们的结论。”叶岚说，“死者没有机会看见CASE 06，也不能因为我们后来证明正确，就被追认成同意零点协议这个答案。”\n这条限制让共同证词更少了一份可借用的权威。我们可以引用死者发现的事实，却不能把他们的沉默变成第四票。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch8_evidence_packets',
  ),
  'ch8_evidence_packets': StoryBeat(
    id: 'ch8_evidence_packets',
    label: '三层证据被拆成不能单独完成答案的纸袋',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '高原把证据分成三类纸袋。灰袋装人类批准板的压痕和采购链，蓝袋装ZERO三节点镜像，白袋装托管、投票、封锁与撤回如何进入执行总线。每只袋子都缺少另外两层的结论。\n“四个终端会随机开一只实物槽和两份只读摘要。”他说，“没人能靠记住一个关键词通过。你必须说明眼前材料在整条责任链里做了什么。”\n唐弈问能否提前计算分配，使四席看到完全相同的组合。高原拒绝。让证据不同，正是为了判断一致来自理解，还是来自排练。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch8_terminal_approach',
  ),
  'ch8_terminal_approach': StoryBeat(
    id: 'ch8_terminal_approach',
    label: '新出现的走廊只通向四扇隔离门',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text:
        '上午六点，集合厅北墙沿一条此前不存在的接缝向两侧退开。墙后没有出口，只有一条笔直走廊。四束独立线缆从地板下伸向尽头，彼此之间隔着厚重的接地层。\n我们沿线缆前进。每经过一道摄像头，PDA就删除一项共享权限：位置广播、公共聊天、证据同步、远程医疗。抵达尽头时，终端之间唯一允许共享的只剩“已提交”或“未提交”。\n系统不是在防止作弊那么简单。它要把我们过去赖以活下来的协作全部剥掉，再问合作是否只是因为始终能看见彼此的答案。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_terminal_hall_reveal',
  ),
  'ch8_terminal_hall_reveal': StoryBeat(
    id: 'ch8_terminal_hall_reveal',
    label: '四席不是椅子而是四个互不相见的房间',
    speaker: Speaker.liXingyao,
    scene: SceneKey.testimonyHall,
    portraitMood: 'alarm',
    text:
        '走廊尽头的灯依次亮起。四间钢化玻璃隔舱并排嵌在墙内，侧壁铺满吸音材料；从外面能看到人的轮廓，却看不见任何一块屏幕。每间舱只有一把固定椅、一组证物槽和一支透明罩下的提交杆。\n星遥贴近第一间外壳，用耳机拾取电磁泄漏。她很快摘下耳罩：“没有串扰。四条线连供电时钟都分开，敲墙和电流脉冲也会被随机延迟。”\n我曾把四席想成四个人并排坐在同一张桌前。真正的终局更冷静：我们甚至不能从对方抬头的速度判断他看见了什么。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch8_terminal_rules_1',
  ),
  'ch8_terminal_rules_1': StoryBeat(
    id: 'ch8_terminal_rules_1',
    label: '管理员只解释怎样判定一致',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyHall,
    text:
        '四间隔舱同时传出管理员的声音：“最终证词包含三项字段：主办者代号、责任层级、个人生还条款的合法性。四份证词必须在含义上相容，不要求逐字相同。”\n“由谁判断含义相容？”我问。\n“ZERO只读审计进程。”\n程序既是被指认的对象之一，又负责判断指认是否相容。这个结构并不公正；但审计镜像保留了比对规则，我们至少可以验证它没有临时改写关键词。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.shenYan,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch8_terminal_rules_2',
  ),
  'ch8_terminal_rules_2': StoryBeat(
    id: 'ch8_terminal_rules_2',
    label: '提交者不能由条件完成度自动选出',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyHall,
    text:
        '“证词席需要四名存活参与者。每人必须本人入舱、本人阅读、本人拉下提交杆。托管、代理、历史录音与12号身份槽均不得替代。”\n韩骐问，若有人在舱内失去意识，能否由医疗人员开门。管理员回答可以中止本轮，但中止者当日不能再次提交。苏弥立即记下机械开门位置，没有把不许重试当成阻止急救的理由。\n普通路线恰好只剩四人，任何中止都会令人数不足；审计路线仍能更换提交者，却必须在更换前封存上一人的全部未提交输入。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_terminal_rules_3',
  ),
  'ch8_terminal_rules_3': StoryBeat(
    id: 'ch8_terminal_rules_3',
    label: '一致答案仍可能服从一套错误规则',
    speaker: Speaker.suMi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'concerned',
    text:
        '第三项字段要求每个人判断自己的生还条款是否具有处决正当性。选择“有效”能满足个人离开条件；选择“无效”则意味着主动放弃由条款保证的出口资格。\n苏弥抬头：“所以四个人就算都知道主办者是谁，也可能因为有人需要承认条款有效才能出去，得到四份不能相容的证词。”\n管理员没有否认。终局不是纯粹的知识考试。它把真相与获救重新绑在一起，逼每个人决定：一条曾经保护自己的规则，是否因此有权杀死别人。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch8_three_answer_levels',
  ),
  'ch8_three_answer_levels': StoryBeat(
    id: 'ch8_three_answer_levels',
    label: '三个主办者答案都包含一部分真实',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我们退回集合厅，将三个可能代号分开写下。H-7项目负责人回答谁批准了绑架、设施与项圈；ZERO系统回答什么此刻执行门锁和裁定；零点协议则回答人类设计、程序裁定与参与者输入如何共同让死亡继续。\n第一个答案有姓名和刑事责任，却解释不了无人操作时的七秒迁移。第二个答案能定位机器，却会让签下托管、封锁或主动牺牲的人把责任全部推给程序。第三个答案最完整，也最难让四个人在不同证据前独立理解。\n我没有在白板上给第三项画圈。提前标注正确答案，只会把共同理解重新变成服从01。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_rehearsal_dispute',
  ),
  'ch8_rehearsal_dispute': StoryBeat(
    id: 'ch8_rehearsal_dispute',
    label: '能否排练同一句话成为最后一次争论',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '唐弈提出最稳妥的办法：写出一段不超过二十字的标准答案，让四名提交者逐字记忆。只要比对器接受，离开后再讨论责任差异。\n叶岚反问：“那四份证词证明的是四个人理解，还是一个人写、三个人背？”\n“活着出去以后，证明可以补。”\n“死人也总被要求等活人出去以后再补。”\n争论没有靠道德优势结束。管理员随即公布，四席会看到不同材料并要求解释；只背代号而无法说明材料作用，证词仍被判为空白。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch8_silence_rehearsal',
  ),
  'ch8_silence_rehearsal': StoryBeat(
    id: 'ch8_silence_rehearsal',
    label: '模拟隔离时没有人替沉默填入答案',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    text:
        '我们进行一次不接通终端的模拟。四个人分别进入隔舱，只允许在纸上写自己看到证据后会先问的问题。外面的人能看见轮廓，不能知道谁已经写完。\n第三间舱很久没有动作。过去，韩骐会破门，苏弥会询问体征，星遥会检查断线；这一次，所有人只能等待本人拉起“模拟结束”杆。七分钟后，门自行打开，里面的人承认只是需要更多时间。\n没有回答不等于故障、背叛或死亡。学会不替沉默定义原因，是四席真正开始前最困难的一次练习。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_entry_inspection',
  ),
  'ch8_entry_inspection': StoryBeat(
    id: 'ch8_entry_inspection',
    label: '每个人入舱前都检查自己没有携带别人的答案',
    speaker: Speaker.liXingyao,
    scene: SceneKey.testimonyHall,
    portraitMood: 'alarm',
    text:
        '下午五点，证词厅开放正式入舱。星遥逐台检查屏蔽层，高原核对机械杆，苏弥确认紧急释放不会触发项圈。林澄则提议所有人互相展示空白袖口和没有文字的掌心。\n检查不是搜身。每个人自己翻开衣领、口袋和鞋舌，其他人只确认动作完成。任何写在皮肤上的标准答案都会在入舱前公开作废。\n最后轮到我。我摊开双手，掌心只有第六日护栏割出的伤口。它能证明我曾经抓住过谁，不能证明我今天一定会写对。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_final_meal_1',
  ),
  'ch8_final_meal_1': StoryBeat(
    id: 'ch8_final_meal_1',
    label: '最后一餐没有被包装成出征前的仪式',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '正式提交前还剩四十分钟。苏弥坚持把证物袋从餐桌移开，再把最后两盒罐头、压缩饼干和已经失去香味的速溶汤分给所有人。她按体征调整份量，却没有再把自己排在最后；属于03的杯子从一开始就放在她面前。\n没有人说这可能是最后一餐。勺子刮过金属盒的声音已经足够清楚。普通路线的四个人围着过大的桌面，空椅像一圈无法忽视的质问；审计路线的九个人也没有因此热闹，唐弈、陈默与韩骐分别坐在能被看见却不构成包围的位置。\n我喝下第一口汤，咸味迟钝得几乎尝不出来。身体仍然需要吞咽、消化和稳定血糖，这些动作没有戏剧性，却能阻止我们把终局中的自己想成只由答案组成的机器。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_final_meal_2',
  ),
  'ch8_final_meal_2': StoryBeat(
    id: 'ch8_final_meal_2',
    label: '餐桌上的闲话比标准答案更难开始',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '林澄忽然问，外面的日期是否仍是她记得的考试周。没人能确认设施时间与真实时间完全一致，高原只说救援记录最终会给出校准。这个答案没有用，她仍开始计算缺考科目和补考申请。\n星遥说自己的工作邮箱大概已经被自动回复塞满，苏弥担心诊所没人知道她为什么失联，叶岚则记起出门前忘记给阳台植物浇水。那些琐事没有降低死亡的重量，反而使每个人重新长出设施之前的轮廓。\n轮到我时，我想了很久，只说家里玄关还放着一双没有收进鞋柜的鞋。若能回去，第一件事不是发表证词，而是确认门锁能由自己从里面打开。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_personal_item_return',
  ),
  'ch8_personal_item_return': StoryBeat(
    id: 'ch8_personal_item_return',
    label: '私人物品在提交前归还本人而非并入共同证据',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '餐后，叶岚将过去六日集中保管的私人物品与案件证物分开。发带、备用眼镜、药盒、手写地图和没有记录权限的旧钥匙逐一归还；带时间戳的终端、武器和审批材料仍保留封条。\n唐弈要求把自己的硬币留作证物，因为它曾用于决定行动顺序。叶岚让他说明硬币是否实际触发任何设备。得到否定后，她把它放回他掌心：“象征不是自动证据。别让调查也按照你习惯的故事挑东西。”\n吴峥与周叙的物品无人代领。我们分别装袋，写下发现位置和最后接触者，不写“遗愿”。活着的人没有资格因为需要一个完整结尾，就替死者决定物品最后想说什么。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch8_unwritten_letters',
  ),
  'ch8_unwritten_letters': StoryBeat(
    id: 'ch8_unwritten_letters',
    label: '未必能送出的留言允许被撕掉和重写',
    speaker: Speaker.shenYan,
    scene: SceneKey.dormitory,
    text:
        '管理员提供了十二张纸，声称终局失败时会把留言交给指定联系人。没人相信这项承诺，但苏弥仍建议愿意的人写下紧急医疗信息，叶岚则提醒不要把需要调查的指控只留在无法验证的私人信里。\n我写了三次开头。第一次像遗书，第二次像为所有选择辩护的口供，第三次才只写下自己的姓名、需要通知的人，以及“请不要相信任何声称这场游戏存在合法获胜者的通知”。\n写完以后，我没有封口。纸可以被外部人员看见，也可以永远留在设施。真正需要带出去的责任已经进入多份证据，私人告别不再承担证明真相的任务。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_collar_release_review',
  ),
  'ch8_collar_release_review': StoryBeat(
    id: 'ch8_collar_release_review',
    label: '解锁预案先说明成功以后仍不能立刻触碰项圈',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.testimonyHall,
    portraitMood: 'inspecting',
    text:
        '高原用备用外壳演示终局成功后的机械顺序：无线裁定停机，储能电容放电，锁舌退开，最后才允许本人托住项圈。任一步骤缺少指示，都必须保持不动并呼叫医疗中止。\n韩骐问能否由他替反应迟缓的人摘除。苏弥回答，只有本人失去意识且现场确认断电时才进入急救代理；清醒者即使手抖，也有权自己决定谁碰颈侧。\n我们各自练习将双手停在锁扣下方，不抢先扯动。终局成功并不意味着危险在白灯亮起的一刻神奇消失，获救也不能成为再次越过同意的理由。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_exit_expectation',
  ),
  'ch8_exit_expectation': StoryBeat(
    id: 'ch8_exit_expectation',
    label: '出口之外可能仍有武装人员和无法立刻相信的命令',
    speaker: Speaker.liXingyao,
    scene: SceneKey.testimonyHall,
    portraitMood: 'alarm',
    text:
        '星遥把可能的出口状况列成三类：主办方回收人员、真正救援队，或一段仍由ZERO播放的伪造外部广播。任何制服、警灯和机构名称都不能单独证明身份。\n我们约定要求外部人员提供可独立核验的信息：当前绝对日期、公开报警编号、两家彼此无隶属关系的医院名称，以及不通过设施网络运行的气体与爆炸物检测。若对方拒绝，所有人停在掩体后，不因出口已经打开就放弃验证。\n这份预案听起来像把怀疑带到自由世界。可真正的区别在于，验证完成以后制度必须缩回去；我们不会继续追踪救援人员，也不会用一次正确判断要求彼此永久服从。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_final_clock_sync',
  ),
  'ch8_final_clock_sync': StoryBeat(
    id: 'ch8_final_clock_sync',
    label: '四套时钟的微小误差不再被强行校成同一秒',
    speaker: Speaker.liXingyao,
    scene: SceneKey.testimonyHall,
    portraitMood: 'alarm',
    text:
        '星遥最后核对四间隔舱的离线时钟，发现彼此相差零点八到三点一秒。ZERO提供一键校时，却会让所有终端重新从主节点取得同一时间源，也可能顺便覆盖已经封存的独立日志。\n“不校。”她在每块表旁分别写下偏差，“出去以后用外部时间换算。我们需要的是知道它们怎样不同，不是让屏幕看起来整齐。”\n唐弈皱眉，因为提交窗口因此无法精确同时开始。高原指出规则只要求各自在十分钟内完成，并不要求四个人同一秒拉杆。同步更漂亮，差异更可追溯。\n四块时钟继续各自走动。共同见证第一次从允许几秒钟的不一致开始。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_last_private_minute',
  ),
  'ch8_last_private_minute': StoryBeat(
    id: 'ch8_last_private_minute',
    label: '门前最后一分钟允许每个人选择靠近或独处',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    text:
        '准备完成后，管理员意外留下六十秒空白。没有新规则、没有广播，也没有必须完成的告别。有人坐回墙边，有人喝水，有人把额头抵在冰冷玻璃上确认自己的呼吸。\n关系对象站在我伸手无法碰到的位置，问：“你现在想让我说点什么吗？”\n我原本想要一句相信，最后只请她在门关闭后照顾好自己，不要为了让我安心答应一定等在原地。她也没有要求我保证回来，只说会按自己的证据作答、按自己的身体决定是否中止。\n舱外的人也作出同样困难的承诺：除非终端显示明确的生命危险，或舱内本人拉起中止杆，他们不会因等待太久就破门。担心不能自动成为代理权；若真的发生故障，他们会先保存原始状态，再由两名见证者共同启动机械释放。没人承诺绝不犯错，只把谁能在何种证据下行动写得足够清楚。终端之外的人还约定，成功以后也不把哪一席最后作答、哪一席曾经迟疑公开成道德排名。思考时间不是忠诚度，退出记录也不该成为日后指责某个人差点害死大家的材料。每个人保留自己的沉默，也共同承担不把沉默重新武器化的责任。\n倒数归零时，我们没有完成一场适合记住的告别。正因为没有把最后一分钟变成关系契约，接下来的答案才仍属于各自。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_mode_gate',
  ),
  'ch8_mode_gate': StoryBeat(
    id: 'ch8_mode_gate',
    label: '同一座证词厅容纳两种完全不同的终局',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    text:
        '四扇门的状态灯由灰转白。普通路线没有替补者，也没有完整关闭历史重放；四个活人只能带着两次死亡、残缺证据与仍在生效的个人条件入舱。\n审计路线保留九名参与者、三层证据和公开撤回制度。人数更多不代表答案自动一致，却让任何人的恐惧不必再由另一个人的死亡换取席位。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    auditNext: 'ch8_audit_candidate_meeting_1',
    auditRequiredFlags: {
      'ch7_audit_complete',
      'ch7_zero_execution_stopped',
      'ch7_four_witnesses_ready',
    },
    next: 'ch8_standard_final_four_1',
  ),
  'ch8_standard_final_four_1': StoryBeat(
    id: 'ch8_standard_final_four_1',
    label: '恰好四个人使所有替补规则失去意义',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    text:
        '主屏列出四名存活者，没有候补栏。昨天亮起的四把椅子如今变成四个必须同时存在的生命体征。任何一人中止、拒绝或被控制，其他三人的正确答案都不会得到出口。\n我看向另外三个人。有人因拿到机械钥匙活下来，有人因直接责任者暂时不再需要更多死亡而活下来，也有人已经把两条人命计入自己的终局条件。我们不是被真相选中的四人，只是死亡过程最后剩下的四人。\n管理员要求在十八点前确认席位。没有人主动走向第一扇门。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_standard_evidence_gap',
  ),
  'ch8_standard_evidence_gap': StoryBeat(
    id: 'ch8_standard_evidence_gap',
    label: '两组仍在线的重放节点把证据版本切成三份',
    speaker: Speaker.liXingyao,
    scene: SceneKey.testimonyHall,
    portraitMood: 'alarm',
    text:
        '未关闭的12号节点开始向四席分发不同版本。第一席看到完整人类批准链，第二席只看到ZERO运行镜像，第三席收到参与者输入记录，第四席则多出一份由死者声音确认条款有效的历史摘要。\n星遥或仍保存她技术记录的人指出，摘要没有伪造内容，只把不同时间的真实陈述剪成了当前同意。四席如果各自相信屏幕上的“最近确认”，会在第三字段得到互不相容的答案。\n普通路线已经没有足够人员同时切断节点并守住终端。我们只能在重放仍存在的情况下判断哪些声音属于现在。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_standard_condition_conflict',
  ),
  'ch8_standard_condition_conflict': StoryBeat(
    id: 'ch8_standard_condition_conflict',
    label: '每个幸存条件都要求有人放弃证词的一部分',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '四人的个人条款被并排展开。唐弈需要最终人数不超过四；陈默需要三份责任记录无法恢复；韩骐需要01处于自己的有效保护范围。无论谁是当前直接责任者，其条件都已被两次死亡推到几乎完成。\n另外两名幸存者的条件可能要求救治、同行、公开姓名或复核证据。它们看起来更温和，却仍要求在第三字段承认主办方有资格用项圈保证履行。\n若四个人都选择条款有效，出口最容易开启；但我们也会共同证明，前六日的死亡只是规则被正确执行。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_standard_director_gate',
  ),
  'ch8_standard_director_gate': StoryBeat(
    id: 'ch8_standard_director_gate',
    label: '仍活着的直接责任者提出自己的四席秩序',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '最后一次准备会没有形成共同方案。唐弈、陈默或韩骐分别沿着过去三日已经使用过的逻辑提出终局秩序：先固定提交顺序、先删除责任恢复、或先把01纳入保护托管。\n这些方案都能减少一类不确定，也都要求某个人先放弃拒绝。主办方不需要再投放武器；它只需要让出口必须依赖那个最善于把别人变成条件的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch8_four_seats_terms_1',
      'ch6_hanqi_vote_killer': 'ch8_custodian_terms_1',
      'ch6_chenmo_vote_killer': 'ch8_no_witness_terms_1',
    },
    next: 'ch8_no_witness_terms_1',
  ),
  'ch8_four_seats_terms_1': StoryBeat(
    id: 'ch8_four_seats_terms_1',
    label: '唐弈要求先保证四份答案可以被系统接受',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '唐弈把三种答案的通过概率写在白板上。项目负责人只有百分之四十一，因为四席材料中有两席缺少完整姓名；零点协议只有百分之五十七，因为第三字段会与个人条款冲突；ZERO系统则达到百分之九十三。\n“不是说ZERO承担全部责任。”他解释，“只是先提交比对器最容易判定一致的代号。出去以后，人的责任和我们的责任都可以继续追。”\n我问死者的证词什么时候继续。唐弈没有回避：“活人取得外部话语权以后。”这回答合理得令人疲惫，也和他每一次把不可逆代价排到计算表末尾时一模一样。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch8_four_seats_terms_2',
  ),
  'ch8_four_seats_terms_2': StoryBeat(
    id: 'ch8_four_seats_terms_2',
    label: '四人条件在数字上第一次完全相容',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'shaken',
    text:
        '他逐项证明，四名现存者都能在不新增死亡的情况下完成个人条件。人数已经精确等于席位；责任记录可以选择不恢复；01只需在终端隔舱内维持两米保护链；关系对象则能作为同一批离开者。\n“现在没有人需要再死。”唐弈说。\n这句话来得太晚，也因此具有真实分量。他确实不再需要杀人，却仍把此前死亡当作已经支付、无需影响下一步的成本。接受方案能让四个人出去，拒绝则可能让支付过成本的人也得不到结果。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch8_four_seats_terms_3',
  ),
  'ch8_four_seats_terms_3': StoryBeat(
    id: 'ch8_four_seats_terms_3',
    label: '关系对象拒绝把幸存解释成分配正确',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text:
        '入舱前，仍与我保持共同撤离关系的人把机械钥匙或证据副本交还。她没有要求我为四人的出口牺牲自己，也没有说只要我们一起出去，其他死亡便能暂时不谈。\n“你可以选择最有可能打开的答案。”她说，“但别告诉自己，系统接受就证明我们走对了。”\n我把物件收进证物袋。喜欢、信任或共同活下来的事实，都不能替第四席决定他愿意承认什么。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_four_seats_terms_4',
  ),
  'ch8_four_seats_terms_4': StoryBeat(
    id: 'ch8_four_seats_terms_4',
    label: '四个人分别写下通过方案真正要求自己放弃什么',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '唐弈原本只准备了一张通过率表。我把白板翻到背面，要求四个人不写答案，先写采用ZERO系统这一代号会让自己放弃什么。不能写“风险”或“代价”这种没有主语的词，必须说明哪一份证词、哪一个人的决定会被排除。\n唐弈写下“暂缓恢复死者责任链”；陈默写下“接受外部调查可能重新连接记录”；韩骐写下“暂时不取得01的持续停止权”。另外两个人写的是关系、医疗或公开姓名。纸条贴在一起后，所谓百分之九十三第一次有了具体形状。\n“概率没有骗你们。”唐弈看了很久才说，“只是它从来不会显示由谁支付剩下的百分之七。”\n我没有把这句话当作悔悟。至少在入舱以前，那个没有通过的人不再只是一格可以舍去的误差。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch8_four_seats_terms_5',
  ),
  'ch8_four_seats_terms_5': StoryBeat(
    id: 'ch8_four_seats_terms_5',
    label: '提交顺序不再被允许伪装成中立的操作细节',
    speaker: Speaker.tangYi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'calculating',
    text:
        '唐弈建议由他先提交，让另外三席看到一枚已亮起的状态灯。规则没有禁止，状态灯也不会显示答案；它只是能把“第一个独立判断”悄悄改成“是否愿意让已经发生的提交失败”。\n“我先承担错误。”他说。\n“也先制造沉没成本。”我回答。关系对象站在封线外，没有替我争论，只提醒第四席仍可在任何时候拒绝。\n最终我们抽签决定入舱顺序，抽签过程由四个人分别记录。唐弈接受了最后一席。他失去用第一个动作塑造后续选择的机会，也必须在看不见任何状态灯的情况下，独自相信那套由自己计算出的答案。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch8_four_seats_terms_6',
  ),
  'ch8_four_seats_terms_6': StoryBeat(
    id: 'ch8_four_seats_terms_6',
    label: '四把椅子旁仍然放着不可能入席的姓名',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    text:
        '入舱铃响前，关系对象把写有吴峥与周叙姓名的两张纸放在观察窗下。它们不是替补席，也不会让终端多计算两份证词，只提醒四个人的相容来自哪些人已经无法反对。\n唐弈没有移开纸。他重新念了一遍自己的方案：“先让活人取得外部话语权。”随后补充，外部话语权必须包括说明他怎样利用人数条件，而不是只公布主办方设计了人数条件。\n“你现在还认为这是正确方案吗？”我问。\n“我认为它最可能让四个人活着出去。”他说，“正确是出去以后也无法由我一个人决定的词。”\n门锁开始预热。我们没有得到一个让求生与责任同时干净的答案，只能带着这种不干净进入四席。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch8_standard_testimony',
  ),
  'ch8_custodian_terms_1': StoryBeat(
    id: 'ch8_custodian_terms_1',
    label: '韩骐把四席入舱改成一条保护队形',
    speaker: Speaker.hanQi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'protective',
    cgId: 'cg_ch8_custodian',
    cgFrame: 0,
    text:
        '韩骐要求自己最后入舱。前三人依次通过玻璃通道，他在外侧确认每扇门锁定，再把01终端放入双锁盒。盒子一端扣在我腕上，另一端扣在他的机械带扣上。\n“不是托管。”他说，“只是保证你提交前没人能让01离线。”\n我指出四间隔舱本来已经独立，没有外部袭击路径。他仍不肯撤掉腕带：“昨天就是因为相信门控足够，才又死人。”死亡没有削弱他的控制理由，反而为每一次新增限制提供了证据。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch8_custodian_terms_2',
  ),
  'ch8_custodian_terms_2': StoryBeat(
    id: 'ch8_custodian_terms_2',
    label: '保护范围会让两间隔舱失去物理独立',
    speaker: Speaker.liXingyao,
    scene: SceneKey.testimonyHall,
    portraitMood: 'alarm',
    text:
        '星遥检查腕带，发现距离超过两米时双锁盒会向两间隔舱同时发送中止信号。只要韩骐认为我面临风险，他便能让我的提交杆失效；而我若主动远离，也会让他的席位被系统判作保护链断裂。\n“你们看起来互相限制，实际只有他定义什么叫风险。”她说。\n韩骐没有否认。他认为终局必须有人承担最后判断，四份独立证词只是主办方制造的无人负责。问题在于，他准备通过取消别人的独立来解决这个问题。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch8_custodian_terms_3',
  ),
  'ch8_custodian_terms_3': StoryBeat(
    id: 'ch8_custodian_terms_3',
    label: '没有人愿意再用强拆验证项圈是否会执行',
    speaker: Speaker.suMi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'shaken',
    text:
        '苏弥要求解除腕带。韩骐回答可以，但必须先由我进入他能看见的第二席。争论持续到项圈发出一次低压提示，提醒距离链已登记为终局保护条件。\n所有人都停下。第一日吴峥试图破坏项圈时的爆响仍留在记忆里；没人再用肉体测试系统是否虚张声势。\n我可以拒绝入舱，让四席在这里失败；也可以戴着腕带提交，至少让其他两人离开。主办方把强迫做成一条已经生效的安全措施，再要求被保护者证明自己是自愿接受。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_custodian_terms_4',
  ),
  'ch8_custodian_terms_4': StoryBeat(
    id: 'ch8_custodian_terms_4',
    label: '我们用一次没有危险的排练检验谁能决定停止',
    speaker: Speaker.yeLan,
    scene: SceneKey.testimonyHall,
    portraitMood: 'intervening',
    text:
        '叶岚提出在断开提交线路的情况下排练一次。她故意在第二席报出并不存在的胸痛，要求所有人按各自理解执行中止。苏弥先询问症状，第四席放下证物，韩骐却直接拉紧双锁盒，把我固定在原位。\n“假警报也可能是诱导。”韩骐解释，“先控制现场，再判断真假。”\n叶岚摘下模拟标记：“那就说明你的方案不是只在危险时限制01。危险是否存在、何时结束、谁能恢复移动，全部由你一个人定义。”\n韩骐看向我腕上的红痕，没有再说这是最小代价。他仍拒绝解除，因为排练在他看来恰好证明其他人会用虚假信息破坏队形。任何反证进入这套保护逻辑，都会被重新解释成更需要保护的理由。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch8_custodian_terms_5',
  ),
  'ch8_custodian_terms_5': StoryBeat(
    id: 'ch8_custodian_terms_5',
    label: '被保护者把不同意写进无法被腕带删除的证词',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyHall,
    text:
        '高原无法在不触发项圈的情况下拆除双锁盒，只能在它外侧加装一枚独立录音片。录音片没有控制权，唯一作用是持续保存我的声音，哪怕保护会话把两台终端合并。\n我对着它说：“我不同意由04决定我的移动、提交和接触对象。我此刻进入第二席，是为了避免另外两名幸存者因四席失败继续被困，不代表接受托管关系。”\n韩骐站在一米之外听完，没有打断。他问这段声明是否会在外部交给调查人员。我说会，也会和他确实阻止过袭击、救过人的记录放在一起。\n善意与控制不会互相抵消。韩骐点头，将自己的姓名和双锁盒编号报进录音。他没有放弃方案，却第一次没有要求保护对象替他证明方案正当。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_custodian_terms_6',
  ),
  'ch8_custodian_terms_6': StoryBeat(
    id: 'ch8_custodian_terms_6',
    label: '保护队形第一次为被保护者的口令留下停止动作',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyHall,
    text:
        '苏弥要求韩骐至少接受一个不由他判断真假的停止口令。我选了“白纸”。无论现场是否危险，只要我说出这两个字，他必须松开手、后退半步并让录音片记录；双锁盒也许不会解除，但他的身体动作必须先停。\n韩骐问，如果我在袭击发生时因恐慌说错怎么办。我回答，错误属于我，不能因为我可能犯错，就让我的每一次拒绝都先经过他的风险审核。\n第一次排练时，他后退得很慢。第二次快了一些。第三次我没有说口令，只自行调整座椅，他的手仍本能地抬起，最后停在半空。\n这套练习不足以把托管变成自愿。它只是让一段仍然不平等的路上，出现了至少一个由被保护者说出、保护者必须执行的停止动作。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_standard_testimony',
  ),
  'ch8_no_witness_terms_1': StoryBeat(
    id: 'ch8_no_witness_terms_1',
    label: '陈默先确认每间终端能恢复哪一份责任记录',
    speaker: Speaker.chenMo,
    scene: SceneKey.testimonyHall,
    portraitMood: 'desperate',
    text:
        '陈默没有讨论主办者代号。他逐台读取证物槽索引，确认第一席持有外包采购，第二席持有周叙案的中继调用，第三席持有门禁测试签名，第四席只保留程序镜像。\n“只要前三席有一份把我写成当前主办者，我的条件就永远不可能完成。”他说。\n我提醒他，证词问题不是谁最有嫌疑。陈默回答：“外面的调查也不会区分得这么耐心。”他害怕的不只是无法离开，而是离开以后终于要由不受ZERO控制的人决定责任。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch8_no_witness_terms_2',
  ),
  'ch8_no_witness_terms_2': StoryBeat(
    id: 'ch8_no_witness_terms_2',
    label: '三份真记录被分别降级成不能相互引用的版本',
    speaker: Speaker.chenMo,
    scene: SceneKey.controlCore,
    portraitMood: 'cold',
    text:
        '他利用最后四十二秒写权限，把三份责任记录从“可恢复原件”改为“待外部核验副本”。内容一个字没有删除，终端却不再允许它们互相证明签名连续。\n“我没有改事实。”陈默说，“只是拒绝让这个系统给事实定最终级别。”\n动作具有一部分正确：ZERO确实不该成为外部审判者。但他选择的时间和范围只保护自己，使四席各自看见真材料，却无法确认材料是否属于同一责任链。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch8_no_witness_terms_3',
  ),
  'ch8_no_witness_terms_3': StoryBeat(
    id: 'ch8_no_witness_terms_3',
    label: '四个人带着四种无法互证的真实入舱',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyHall,
    text:
        '我要求把降级操作写入所有证词包。陈默同意，因为新记录同样只会显示为待外部核验。我们仍能看见彼此做过什么，却无法让终端承认这些行为属于同一个现在。\n幸存者之间没有发生新的袭击。恰恰相反，每个人都在保护自己手里的那部分真实，不愿再交给一个可能利用它的人。\n无人撒谎，无人拥有完整证据。主办方花六天让我们害怕被别人定义，最后只需等待四个诚实的人分别说出彼此无法共同见证的答案。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_no_witness_terms_4',
  ),
  'ch8_no_witness_terms_4': StoryBeat(
    id: 'ch8_no_witness_terms_4',
    label: '短暂开放的外部端口无法替我们验证全部材料',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '星遥尝试利用终局校时端口，把三份待核验副本的哈希发送到设施外。端口只开放二十秒，目标地址由ZERO写死为项目审计服务器。把材料交出去等于交回顾闻川控制的证据链。\n她改用窄带求救频率，数据却大到无法完整传输。我们只能发送三串哈希、设施坐标和一句“原件由不同席位分别持有”。外部即使收到，也只能证明某些数据在此刻存在，不能恢复它们此前怎样相连。\n陈默盯着发送成功标记：“至少外面会知道这里有东西。”\n“也会知道是谁让东西不能在这里互相证明。”我回答。端口关闭前，他没有撤销降级操作。比起共同见证，他仍更相信一份无法完整读取的外部可能。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.chenMo,
      Speaker.shenYan,
    ],
    next: 'ch8_no_witness_terms_5',
  ),
  'ch8_no_witness_terms_5': StoryBeat(
    id: 'ch8_no_witness_terms_5',
    label: '四个人为各自材料制作无法替代原件的纸面索引',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.testimonyHall,
    portraitMood: 'inspecting',
    text:
        '高原把最后几张防水纸裁成四份，要求每个人手写自己持有材料的来源、缺口和第一次见到它的时间。纸面无法恢复数字签名，却不会被终端在提交后远程改级。\n陈默写到“签名连续性”时停了很久，最后补上“由03主动降级”。他没有写自己是为了避免被误认成主办者，也没有用恐惧替动作免责。事实先被保留，动机留给离开后的询问。\n四张索引彼此无法合并，因为任何交换都会被终端登记为协同证词。我们只能隔着玻璃读出编号，再把纸折进各自衣袋。\n入舱铃响起时，每个人都带着真实的一角，也清楚知道缺失的不是某个聪明推论，而是我们刚刚主动放弃的共同根。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_no_witness_terms_6',
  ),
  'ch8_no_witness_terms_6': StoryBeat(
    id: 'ch8_no_witness_terms_6',
    label: '各自的诚实答案在隔离前最后一次保持未知',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyHall,
    text:
        '有人提议入舱前公开自己准备选择的代号，至少避免四份诚实证词因措辞不同失败。陈默第一个反对。他害怕被三个人共同答案重新定义，我也意识到公开会让最后发言的人承担让所有准备归零的压力。\n我们改为各自写下“最不确定的证据”，折叠后交给外部信标盒。纸条不在设施内开启，也不参与相容判断。它只在获救后说明，四个人不是带着绝对确信按下按钮。\n我的纸上写：“参与者在胁迫下仍有多少直接责任，不能由终端一次判完。”\n陈默看不见这句话，我也看不见他的。隔离门开启时，我们互相点头，没有把点头解释成同意。四个诚实的人仍可能失败，而失败不会让其中任何一份真实自动变成谎言。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch8_standard_testimony',
  ),
  'ch8_standard_testimony': StoryBeat(
    id: 'ch8_standard_testimony',
    label: '01只能提交自己的主办者答案',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyBooth,
    phase: StoryPhase.testimony,
    text: '选择01对主办者结构的判断。其他三席已经隔离，无法查看、复制或修改。',
    next: null,
  ),
  'ch8_four_seats_verdict_1': StoryBeat(
    id: 'ch8_four_seats_verdict_1',
    label: '四份答案在系统层面达成一致',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyHall,
    cgId: 'cg_ch8_four_seats',
    cgFrame: 0,
    text:
        '最后一支提交杆落下后，四间隔舱同时转为白灯。比对器没有公开原文，只给出结论：“主办者代号相容。个人条款全部有效。四席成立。”\n唐弈选择了通过率最高的ZERO系统，其余两人也沿排练留下的框架提交。无论我在自己的终端写下哪一层，系统都把四份答案压缩成“现场裁定主体一致”，忽略了人类授权和参与者输入的责任差异。\n出口锁开始退开。我们通过了终端，却没有证明四个人理解了同一件事；只证明四个人都愿意让系统使用最容易接受的共同部分。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.narration,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch8_four_seats_accepted'},
    next: 'ch8_four_seats_verdict_2',
  ),
  'ch8_four_seats_verdict_2': StoryBeat(
    id: 'ch8_four_seats_verdict_2',
    label: '唐弈没有庆祝自己算对了人数',
    speaker: Speaker.tangYi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'shaken',
    text:
        '隔舱门打开，唐弈没有像过去那样先确认结果。他看着另外三扇门，又看向本应站着更多人的观察区。\n“四个，全部满足。”他说。声音里没有喜悦，只有一次计算终于停止后的空白。\n我问他，如果第一日就知道最后会这样，是否仍会把人数削减写成最优条件。他很久才回答：“我会以为自己不会。”这不是道歉，也不是否认。他终于承认，知道结果的人也可能在每一步都选择让结果发生。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch8_four_seats_exit_1',
  ),
  'ch8_four_seats_exit_1': StoryBeat(
    id: 'ch8_four_seats_exit_1',
    label: '出口只为四个人打开一条狭窄通道',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    cgId: 'cg_ch8_four_seats',
    cgFrame: 1,
    text:
        '证词厅后方升起一道只容单人通过的闸门。门外不是阳光，而是一条消毒灯照亮的上行坡道。四只PDA依次失去地图、条件和编号，只剩证据封存编号。\n我们按提交顺序前进。没有第五个人意味着不用回头确认谁被门隔开，也意味着每一次脚步都会在空走廊里返回四重回声。\n坡道尽头，项圈同时解锁。金属落地的声音很轻，远没有第一日爆炸响亮。没有人弯腰去捡。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_four_seats_debrief_1',
  ),
  'ch8_four_seats_debrief_1': StoryBeat(
    id: 'ch8_four_seats_debrief_1',
    label: '外部人员首先问为什么只有四个人',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '救援人员在地下车库出口接住我们。医护剪开衣袖、拍摄项圈压痕，调查员则把四只证据袋放进不同箱子。第一个完整问题不是主办者是谁，而是：“其余参与者在哪里？”\n房间里没有任何终端替我们回答。死亡原因必须由活人一件件说出：谁按下门，谁维持旧值，谁知道会发生什么仍没有停。\n唐弈没有要求先整理成统一时间线。他报出自己直接造成的死亡，也报出我和其他幸存者作过的选择。四人席没有给他豁免，只给了他亲口承担的机会。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_four_seats_debrief_2',
  ),
  'ch8_four_seats_debrief_2': StoryBeat(
    id: 'ch8_four_seats_debrief_2',
    label: '四份证词在外部调查中第一次被分开审查',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '调查组将我们分别带进玻璃后的询问室。没有项圈、倒计时或共同出口，四份陈述仍出现同样事实，也出现无法调和的责任判断。\n我坚持主办者不止ZERO程序；另一份证词把全部责任归给项目负责人；唐弈则说明参与者主动利用条件时承担直接行为责任。外部调查没有把差异判成失败，而是逐条寻找可验证材料。\n直到此刻我才意识到，真正的见证从来不要求四个人说得一模一样。设施用一致换取出口，法律与家属需要的却是差异仍能被保存。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_four_seats_debrief_3',
  ),
  'ch8_four_seats_debrief_3': StoryBeat(
    id: 'ch8_four_seats_debrief_3',
    label: '幸存关系没有获得一条轻松的共同未来',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '天亮以后，四个人被安排在同一间临时休息室，却没有坐到一起。有人接受治疗，有人面对讯问，有人反复确认门外没有倒计时。\n仍活着的关系对象在离开前问我是否会继续联系。我没有用“一定”掩盖接下来的调查、愧疚和彼此可能无法原谅的部分，只把自己的真实号码写在纸上。她收下，没有立刻拨打。\n我们一起离开了设施，却不能把一起活下来当成爱情或信任已经完成。那张纸保留一次可能的以后，也保留拒绝的权利。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_four_seats_debrief_4',
  ),
  'ch8_four_seats_debrief_4': StoryBeat(
    id: 'ch8_four_seats_debrief_4',
    label: '死亡通知必须由幸存者面对具体的家属完成',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '调查组询问谁愿意协助向家属说明最后时刻。医疗与工程记录由外部人员分别整理，我和另一名现场见证者核对广播与门控。唐弈也申请参加，但吴峥家属明确拒绝见他。\n拒绝没有被解释成妨碍调查。唐弈只能写下完整书面陈述，交由律师和调查员转送；是否阅读由家属决定。他第一次无法通过亲自说明控制别人怎样理解自己的行为。\n周叙家属只问了一件事：“他最后有没有一个人？”\n我说没有，也说明陪在旁边的人仍作过无法挽回的选择。安慰不能删掉责任，责任也不能要求家属把最后几分钟想象成只有恐惧。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
    ],
    next: 'ch8_four_seats_debrief_5',
  ),
  'ch8_four_seats_debrief_5': StoryBeat(
    id: 'ch8_four_seats_debrief_5',
    label: '四人的幸存没有暂停任何一份行为调查',
    speaker: Speaker.tangYi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '七天后，四人被安排到不同住所接受保护。唐弈因两次明知后果仍维持致命条件而被限制离境，陈默的证据降级和韩骐的强制控制也分别立案。共同受害身份没有自动终止直接行为调查。\n唐弈在律师在场时给我看了一份新的表格。上面没有通过率，只有每个决定当时可见的停止机会、他选择继续的理由，以及由谁承担后果。很多格仍写着“不知道”。\n“我以前会把不知道换成估计值。”他说，“这样就能继续算。”\n我没有替他把承认换成原谅。表格会进入证据，改变只能由之后一次次不再利用别人来证明。四席使我们活着走到这里，却没有替任何人结清账目。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch8_standard_ember_gate',
  ),
  'ch8_four_seats_result': StoryBeat(
    id: 'ch8_four_seats_result',
    label: '精确四人不是无罪证明',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    phase: StoryPhase.ending,
    endingId: 'ending_four_seats',
    text:
        '四席全部通过，出口按规则开启。外部调查取得了设施镜像与四份互有差异的证词，也确认至少两次死亡来自行为人明知后果后的选择。\n唐弈得到自己计算过的四人结果，却没有得到结果正确的证明。你们活着离开，也必须带着那些被换算成人数的人继续作证。\n审计模式已经解锁。另一轮并不会抹去这条真实发生过的路线，只会开放此前无法读取的证据与阻止方式。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: null,
  ),
  'ch8_custodian_verdict_1': StoryBeat(
    id: 'ch8_custodian_verdict_1',
    label: '两份证词被保护链判作同一控制来源',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyHall,
    text:
        '提交完成后，第一席和第二席没有分别亮灯。双锁腕带把两台终端标成同一保护会话，比对器因此只承认三名独立证人。\n“证词席不足。启动托管出口。”管理员宣布。\n韩骐立即拉开自己的隔舱门，确认我仍在保护半径。他没有篡改我的答案，也没有替我拉杆；系统只是认为，被他控制中止权的证词不再独立。我们早已指出这个结果，他仍选择先保证我活着提交。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch8_custody_chain_locked'},
    next: 'ch8_custodian_verdict_2',
  ),
  'ch8_custodian_verdict_2': StoryBeat(
    id: 'ch8_custodian_verdict_2',
    label: '托管出口要求保护者继续持有01',
    speaker: Speaker.hanQi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'conflicted',
    text:
        '侧墙开启一条黄色通道。规则写得清楚：04作为有效托管者带01离开，其余两名提交者随后通行；在外部接管机构确认安全以前，双锁盒不得解除。\n“至少都能出去。”韩骐说。\n“出去以后由谁判断安全？”\n他望向没有任何机构标识的通道，第一次无法回答。保护条件没有终点，只要世界仍可能伤害01，托管者就能继续证明控制必要。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch8_custodian_exit_1',
  ),
  'ch8_custodian_exit_1': StoryBeat(
    id: 'ch8_custodian_exit_1',
    label: '离开设施时我仍不能与保护者相距两米',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    cgId: 'cg_ch8_custodian',
    cgFrame: 1,
    text:
        '韩骐走在我左后方，腕带之间的钢索保持一米半。坡道转弯时，他会先用身体挡住看不见的区域，再示意我前进。动作熟练、有效，也让每一次停步都由他发起。\n另外两名幸存者跟在后面。关系对象试图靠近，双锁盒立刻发出警告，韩骐让她退回安全线。她没有与他争抢我的手臂，只直视我：“这是你现在选择的距离吗？”\n我说不是。声音被记录在腕带里，却没有让锁立即打开。能够说出不同意，与能够结束控制之间仍隔着一整套被系统承认的保护关系。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_custodian_debrief_1',
  ),
  'ch8_custodian_debrief_1': StoryBeat(
    id: 'ch8_custodian_debrief_1',
    label: '外部救援把双锁盒当作仍在工作的危险装置',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '救援人员没有接受“保护装备”的系统分类。排爆组固定我们的手臂，医疗人员覆盖项圈触点，再用机械楔片隔断双锁盒电源。整个过程持续四十七分钟。\n韩骐多次要求由自己说明拆除顺序。他的判断大多正确，排爆员仍让他把双手放在可见位置。第一次，专业能力与决定权被明确分开。\n锁扣打开时，他本能地抓住我的肩膀，随后又自己松开。没有系统奖励这个动作，也没有人因此宣布他已经改变。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_custodian_debrief_2',
  ),
  'ch8_custodian_debrief_2': StoryBeat(
    id: 'ch8_custodian_debrief_2',
    label: '韩骐必须解释每一次保护为何由别人承担代价',
    speaker: Speaker.hanQi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '单独讯问中，调查员不问他是否想保护01，只问每个具体时刻：谁报告了风险、谁拥有停止权、谁在他的决定后失去撤离机会。\n“我以为再等五秒更安全。”他说。\n“对谁更安全？”\n这个问题反复出现。韩骐能够回答战术，却不能再用总体安全覆盖具体的人。保护意图被保留，死亡责任也没有因此减少。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_custodian_debrief_3',
  ),
  'ch8_custodian_debrief_3': StoryBeat(
    id: 'ch8_custodian_debrief_3',
    label: '关系对象不接受以获救名义继续接管生活',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '临时休息室里，她坐在我能看见、却不必伸手就碰到的位置。她没有询问双锁盒留下的淤痕，也没有替我判断应该憎恨还是感谢韩骐。\n“下次你想让我靠近，就自己说。”她把水杯放在中间的桌上，“我也会自己决定要不要过来。”\n我点头。离开设施后的第一段关系不是拥抱，而是重新学习距离不再由项圈、托管者或恐惧自动解释。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_custodian_debrief_4',
  ),
  'ch8_custodian_debrief_4': StoryBeat(
    id: 'ch8_custodian_debrief_4',
    label: '外部保护措施必须写明期限与被保护者的撤回权',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '警方建议因主办方尚未落网，为四名幸存者安排临时保护。调查组逐条写明方案：住址是否自选、定位由谁查看、何时自动失效、本人如何撤回。每项保护都必须有期限，也必须留下不接受的选项。\n韩骐被排除在我的安保决定之外。他可以向调查组提供威胁评估，却不能查看住址或成为联系人。听到这一条时，他首先列出自己比普通警员更了解设施的理由，随后停住。\n“我可以只提交报告。”他说。\n这并不表示他赞成边界，只表示制度不再等待他赞成才生效。保护第一次能够保留他的专业判断，而不把被保护者一并交给他。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch8_custodian_debrief_5',
  ),
  'ch8_custodian_debrief_5': StoryBeat(
    id: 'ch8_custodian_debrief_5',
    label: '韩骐的治疗从承认不确定仍不能接管别人开始',
    speaker: Speaker.hanQi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '创伤评估中，韩骐反复描述自己若不保持控制便会有人死亡。治疗师没有要求他相信世界安全，只让他区分“危险存在”与“因此由我决定”。两句话之间，他沉默了近十分钟。\n他后来向我提出一次当面道歉。地点、时长和是否见面都由我选择，我最终只接受书面内容。他在信里没有写“都是为了你好”，而是逐项列出自己在哪些时刻听见拒绝仍继续限制。\n我读完后没有回复。关系对象陪我把信封交给律师保存，随后问今晚想独处还是一起吃饭。\n自由并不要求我立刻原谅，也不要求永远拒绝。重要的是，韩骐的改变不再以重新获得接近我的资格作为奖励。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_standard_ember_gate',
  ),
  'ch8_custodian_result': StoryBeat(
    id: 'ch8_custodian_result',
    label: '出口打开时托管仍未自然终止',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    phase: StoryPhase.ending,
    endingId: 'ending_custodian',
    text:
        '四个人活着离开，四份证词却只有三份被判定独立。韩骐以保护者身份取得托管出口，也把设施中的控制关系带到了出口之外。\n外部人员最终拆除了腕带，并将保护意图与具体死亡责任分别记录。你重新获得了拒绝的空间，却无法把获救简单称为自由。\n审计模式已经解锁。另一轮能够让保护不再依赖一个人掌握全部停止权。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: null,
  ),
  'ch8_no_witness_verdict_1': StoryBeat(
    id: 'ch8_no_witness_verdict_1',
    label: '四份真实答案没有构成可以互证的结论',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyHall,
    cgId: 'cg_ch8_no_witness',
    cgFrame: 0,
    text:
        '四支提交杆全部锁定，状态灯却依次转红。比对器列出冲突：两席指认项目负责人，一席指认ZERO系统，一席提交零点协议；三份材料的签名连续性均为待外部核验。\n“主办者代号不相容。独立共同见证未成立。”\n没人提交虚假内容。我们只是各自抓住自己还能验证的一层，不肯让另外三层把它重新带回可能伤害自己的责任链。四份诚实证词彼此并列，仍然没有一个共同见证者。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch8_common_witness_failed'},
    next: 'ch8_no_witness_verdict_2',
  ),
  'ch8_no_witness_verdict_2': StoryBeat(
    id: 'ch8_no_witness_verdict_2',
    label: '终端关闭但没有立即处决失败者',
    speaker: Speaker.suMi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'shaken',
    text:
        '倒计时归零后，项圈没有爆炸。四间隔舱切换到证据保全模式，出口保持关闭，地面却升起一只外部求救信标。主办方宣布实验结束，未满足共同证词者不获得规则出口。\n“它不需要杀我们。”苏弥说，“只要让救援晚到，让证据在这里失去共同解释。”\n我们轮流转动信标的手摇电机。没有人知道外面是否会收到，但这一次维持信号不再完成任何个人条件，只为了让彼此的不同证词都能离开房间。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch8_no_witness_wait_1',
  ),
  'ch8_no_witness_wait_1': StoryBeat(
    id: 'ch8_no_witness_wait_1',
    label: '十一个小时的等待让冲突不再能靠倒计时跳过',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    text:
        '信标每二十分钟发送一次窄带脉冲。四个人靠墙坐下，重新交换各自终端打印的证词。没有出口奖励以后，陈默终于允许另外三人标注他的降级操作造成了哪些断裂。\n争论持续数小时。我们仍未得到一份统一答案，却能说明每份答案缺失什么、为何缺失、由谁主动造成。共同见证在终端里失败，在没有系统评分的地面上才缓慢开始。\n第十一次脉冲后，墙体外传来并非设施节拍的钻孔声。没有人敢立刻相信。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_no_witness_rescue_1',
  ),
  'ch8_no_witness_rescue_1': StoryBeat(
    id: 'ch8_no_witness_rescue_1',
    label: '外部人员从没有被规则定义为出口的墙进入',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    cgId: 'cg_ch8_no_witness',
    cgFrame: 1,
    text:
        '救援队没有打开终局闸门。他们从证词厅侧墙钻入，先伸进摄像头和气体探头，再切断项圈无线供电。那面墙在区域图上从来不是可通行路线，因此ZERO没有为它准备胜负条件。\n裂口扩大到能够爬出时，四个人都还活着。我们没有获得主办方承认的离开资格，却被一群不知道个人条款的人当作需要救援的受害者和证人带走。\n陈默最后离开，手里攥着四份互相冲突的打印纸。他没能删除责任，也没能让责任在设施里形成统一结论。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_no_witness_debrief_1',
  ),
  'ch8_no_witness_debrief_1': StoryBeat(
    id: 'ch8_no_witness_debrief_1',
    label: '调查员把互相冲突的材料分别编号保存',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '临时取证室里，调查员没有要求我们先统一口径。四份打印纸各自装袋，陈默的降级操作也作为独立事件提取。签名是否连续，将由设施外的设备、采购方和通信记录重新验证。\n我第一次看见证据离开ZERO仍能继续存在。终端说无法互证，不等于世界上再没有其他证人、时间戳或责任制度。\n但失去的现场连续性无法完全补回。家属会面对更多不确定，直接责任者也会利用差异争辩。无人作证不是无人知道，而是我们让最完整的一次共同说明在出口前破碎。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_no_witness_debrief_2',
  ),
  'ch8_no_witness_debrief_2': StoryBeat(
    id: 'ch8_no_witness_debrief_2',
    label: '关系对象没有要求我把失败改写成幸存胜利',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '她在医疗帘外等到询问结束，只问我是否还记得自己的答案。我复述三层责任，也承认它没有成为四人的共同证词。\n“那就从你能负责的部分开始。”她说。\n我们没有拥抱，也没有约定永远相信。她允许我把失败保留为失败，同时提醒我，见证可以在没有倒计时的世界里继续寻找别人，而不必再让任何人死到人数刚好。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_no_witness_debrief_3',
  ),
  'ch8_no_witness_debrief_3': StoryBeat(
    id: 'ch8_no_witness_debrief_3',
    label: '外部调查用设施以外的时间重新连接断裂记录',
    speaker: Speaker.liXingyao,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '取证组从电力公司、通信基站和设备供应商调取独立时间戳。三份在设施内无法互证的材料，分别与同一批采购序列、同一次固件下载和同一辆运输车的定位重合。共同根没有消失，只是被推迟到外部重建。\n星遥参与技术说明，却拒绝替陈默证明降级不会影响案件。“能补回一部分，不等于他的动作没有造成损害。”她把每个恢复步骤和仍无法验证的空档并列标注。\n空档给了项目方律师争辩空间，也让家属多等了数月。陈默最终承认，自己不是在保护真相免受系统裁定，而是在选择只有自己能接受的真相存活方式。\n这份承认不能恢复原始签名。它至少让调查记录不再把断裂写成设备故障。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_no_witness_debrief_4',
  ),
  'ch8_no_witness_debrief_4': StoryBeat(
    id: 'ch8_no_witness_debrief_4',
    label: '社会需要很久才接受没有统一版本不等于没有事实',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '最早的新闻把我们称作“四名互相矛盾的幸存者”。节目将四段口供并排剪辑，仿佛只要语句不同，其中三个人就必然撒谎。律师建议暂时不回应，我们却决定分别公布各自证词的证据范围和未知部分。\n我不替另外三人保证动机，只说明自己看见的门、收到的记录和没有确认的时间。关系对象也发布独立说明，其中有两处对我的记忆提出修正。\n评论因此更加混乱，却有调查记者开始追踪差异指向的设备和承包商。几个月后，四条不完整路径在设施之外第一次交叉。\n没有见证者的结局不是永远无人作证，而是真相必须走更远、承受更多误读，才能抵达本可在终局大厅保存的位置。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_standard_ember_gate',
  ),
  'ch8_no_witness_result': StoryBeat(
    id: 'ch8_no_witness_result',
    label: '没有共同答案仍然有人活着走出墙体',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    phase: StoryPhase.ending,
    endingId: 'ending_no_witness',
    text:
        '四份证词都包含真实，却因责任记录被主动割裂而无法共同成立。规则出口没有开启，外部救援最终从设施未定义的墙面进入。\n你活着离开，却失去了现场最完整的一次共同见证。真相没有消失，只变成更漫长、更容易被争辩的外部调查。\n审计模式已经解锁。另一轮可以保住证据连续性，并让差异不必以互相孤立为代价。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: null,
  ),
  'ch8_standard_ember_gate': StoryBeat(
    id: 'ch8_standard_ember_gate',
    label: '离开设施以后仍有一段关系没有结算',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '公共讯问暂告一段落后，调查员收走最后一只证物袋。规则结局已经成立，活下来的人却没有得到一张能够把感情、愧疚与责任分别结算的页面。\n我曾与一个人登记共同撤离、交换停止权，也在只能归还一枚密钥时让另一个人死去。她仍然活着，不代表那个选择因此正确；我们曾经靠近，也不代表她必须替我的幸存提供安慰。\n离开临时取证室前，我收到一张没有编号的会面申请。是否继续联系将由设施外的两个人重新决定，不再由路线锁、好感值或项圈替我们完成。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_route_locked_xingyao': 'xingyao_end',
      'ch6_route_locked_sumi': 'sumi_end',
      'ch6_route_locked_lincheng': 'lincheng_end',
    },
    next: 'ch8_standard_result_gate',
  ),
  'xingyao_end': StoryBeat(
    id: 'xingyao_end',
    label: '频道另一端先保持沉默',
    speaker: Speaker.liXingyao,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '申请来自星遥。她坐在观察室玻璃另一侧，耳机没有戴在头上，而是整齐绕好放在桌面。七天里我第一次看见她主动让自己听不见某个频道。\n“医护说高频暴露造成的眩晕会慢慢减轻。”她先报告最容易量化的部分，“听力没有永久损伤，睡眠测试很差。你的呢？”\n我说项圈压伤已经处理，左手仍会在听见门锁时发抖。她点头，把两项写进纸上，像我们还在交换行动前的状态。\n真正的问题被留在最后。第六日，我把唯一一枚归还密钥给了她。林澄因此死在另一扇门后。星遥知道那不是她抢来的，也知道自己曾明确要求我不要用亲近替她决定是否活着。可最终按键的人仍是我，活下来的人仍是她。\n“我不想听你说如果重来还会选我。”她用手指压住耳机线，“那句话只会再杀她一次，好像她的死证明我们比较重要。”\n我说不会。我只能说明当时看见什么、害怕什么，以及自己在哪一秒停止寻找第三种办法。她没有原谅，也没有离开，只把纸翻到空白一面：“那就从能复现的事实开始。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'xingyao_end_memorial',
  ),
  'xingyao_end_memorial': StoryBeat(
    id: 'xingyao_end_memorial',
    label: '地图作者不该只剩一个失败信号',
    speaker: Speaker.liXingyao,
    scene: SceneKey.memorialWall,
    portraitMood: 'epilogue',
    text:
        '一周后，调查组建立临时纪念墙。星遥带来林澄留在PDA里的地图原稿，要求技术人员不要只提取路线坐标。压痕里还有她写错后擦掉的字、给苏弥标出的休息点，以及一句很小的“毕业后想去看海”。\n系统报告把林澄的死亡写作“07密钥未归还”。星遥在旁边追加：“密钥由01分配；02接受；07在剩余时间内持续尝试撤离。”\n“你可以把接受写成我的责任。”她对我说。\n我没有把它改成被动获救。她当时知道另一扇门也有人，仍让我先完成信号校准，希望找到能同时开门的漏洞。希望失败不等于没有作过选择。\n林澄的家人拒绝见我，却愿意接收地图。星遥花了三个晚上把所有电子标记转换成普通人能读懂的路线说明，每个无法确认的位置都保留问号。她没有用技术修平不完整，也没有把最后一段路线画成抵达出口。\n交付那天，她在纪念墙前站了很久。“我以前会把无法重复的数据丢掉。”\n“现在呢？”\n“现在知道，有些人只来得及留下一次。不能因为只有一次，就当成噪声。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.liXingyao,
    ],
    next: 'xingyao_end_hearing',
  ),
  'xingyao_end_hearing': StoryBeat(
    id: 'xingyao_end_hearing',
    label: '同一频道也允许不同证词',
    speaker: Speaker.shenYan,
    scene: SceneKey.hearingRoom,
    text:
        '公开听证前，律师建议我们统一描述密钥选择，以免主办项目把矛盾解释成记忆不可靠。星遥拒绝。她记得自己在倒计时三十四秒时说“先给我”，我记得她后一句是“我再转开另一扇门”。两句话都存在，责任不能只留下对某一方更有利的半句。\n听证会上，她证明ZERO会把两个同时求救的人压成单选接口，也证明接口并没有物理上阻止我们更早拆下备用继电器。主办方制造了困境，我们仍在困境里作了具体选择。\n轮到我陈述时，我没有说自己别无选择。我承认在剩余时间里把她的技术成功率看得比林澄的未知路线更高，也承认感情影响了我愿意相信谁能完成下一步。\n休庭后，星遥在走廊等我。“你刚才可以把感情删掉。”\n“删掉会让证词更好看，不会更真。”\n她把一只新的离线记录器交给我。它有两个独立停止键，任何一方都能结束录音，结束后双方各保留一份不能覆盖的副本。\n“这不是情侣设备。”她强调。\n“我知道。”\n“也不是原谅。”\n“我知道。”\n她这才让我拿走。我们重新建立的第一个频道，不以亲密命名，也没有保证永远在线，只保证任何一端都能让沉默真正生效。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'xingyao_end_station',
  ),
  'xingyao_end_station': StoryBeat(
    id: 'xingyao_end_station',
    label: '第一次联系不以救援为理由',
    speaker: Speaker.liXingyao,
    scene: SceneKey.metroStation,
    portraitMood: 'epilogue',
    text:
        '三个月后，星遥发来一段七秒白噪声。没有求救码，没有校验任务，只在频谱角落藏着一句：“如果今天有空，地铁站出口见。”\n我提前到了十分钟，没有发送位置追踪。她晚了六分钟，走出闸机时先确认四周没有警报灯，随后才看见我。我们都注意到彼此仍会计算出口、摄像头和最近的急救点，也都没有假装那些习惯已经痊愈。\n她说正在协助建立受害者证据镜像，条件是任何人都能撤回私人医疗数据，撤回不会删除已经进入司法记录的行为证据。那是我们在设施里没能写出的边界：保留退出权，也不让退出成为抹去伤害的按钮。\n我问今天为什么叫我来。\n“耳机坏了一边，想买新的。”她回答得太快，过了几秒又补充，“还有，我想知道在没有任务时，我们能不能待在同一个地方。”\n我们沿商场走了很久。她试了几副耳机，把其中一边递给我听，却没有说这个频道只属于两个人。离开前，她问下周是否还愿意来。\n我说愿意，也说如果她临时不想见，可以只发一个停止符号。她皱眉，说普通人会把那叫取消约会，不必做成协议。\n“但你可以先保留。”她把新耳机戴好，“等哪天不需要了，再一起删。”\n列车进站的风掀起她的发梢。我们没有拥抱，只在各自上车前确认下一次见面的日期。未来第一次不是必须完成的条件，而是一项双方都可以重新回答的邀请。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.liXingyao,
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'xingyao_end_result',
  ),
  'xingyao_end_result': StoryBeat(
    id: 'xingyao_end_result',
    label: '同一频率',
    speaker: Speaker.narration,
    scene: SceneKey.metroStation,
    endingId: 'ending_xingyao',
    text:
        '你们没有用幸存证明彼此更加重要，也没有让愧疚替任何人决定必须分开。一个新的频道在设施外缓慢建立：可以呼叫，可以沉默，也可以由任意一端停止。\n它还不是永远的答案。正因为如此，每一次再次接通才真正属于两个人。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch8_standard_result_gate',
  ),
  'sumi_end': StoryBeat(
    id: 'sumi_end',
    label: '医生最后一个进入观察室',
    speaker: Speaker.suMi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '救援后的第一晚，苏弥协助医护完成所有幸存者检伤，直到外部医生把记录板从她手里拿走，指出她本人已经连续站立十一个小时。\n“我没有严重外伤。”她说。\n“这不是让你继续工作的理由。”对方回答。\n她被安排进最靠里的观察床，帘子拉上后仍隔几分钟询问一次别人的血压。直到我在帘外说所有人都有正式医疗人员照看，她才安静。几分钟后，我听见压得很低的哭声。\n第六日，我把归还密钥交给苏弥。星遥死在另一扇门后。苏弥没有要求那枚钥匙，也曾让我先确认02的信号，可她在门开后仍本能地去救治我，把自己的幸存当成一项必须立刻偿还的债。\n我没有掀开帘子，只坐在外面。\n“别说不是你的错。”她先开口，“也别说都是你的错。两句话都会让我马上开始安慰你。”\n我问现在能做什么。\n“把时间写下来。”她说，“几点给我钥匙，几点02失联，几点我们停止复苏。只写你确定的。然后今晚不要让我替任何人检查脉搏。”\n我按她说的完成记录。帘子始终隔在中间。陪伴第一次不是靠近她，而是替她守住不用照顾任何人的几个小时。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.shenYan,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'sumi_end_record',
  ),
  'sumi_end_record': StoryBeat(
    id: 'sumi_end_record',
    label: '星遥的死亡不能只剩抢救失败',
    speaker: Speaker.suMi,
    scene: SceneKey.memorialWall,
    portraitMood: 'epilogue',
    text:
        '苏弥整理死亡记录时，发现外部病历把星遥写成“爆炸致死，现场复苏失败”。医学上没有错，却把她在此前六天完成的信号校准、主动承担的监听和最后要求转开另一扇门全部压成了一次失败抢救。\n“医生很容易把人的最后几分钟当成全部。”苏弥说，“因为那是我们最熟悉、也最能填写表格的部分。”\n她联系星遥的家属，询问哪些技术记录可以公开，哪些私人通信应该封存。家属同意保留公共校验步骤，却不愿公开她在眩晕时发给我的语音。苏弥没有以调查价值施压，只在证据目录注明“存在，经本人关系人选择不公开”。\n轮到密钥分配，她把自己的名字同时写进受益者与见证者两栏。她没有说自己被动接受，因为门打开时，她确实选择先处理伤者、没有返回第二道门；也没有把所有责任揽到身上，因为决定权和剩余工具并不在她手里。\n“如果我只写幸存者，会像活下来是一项事实。”她看着表格，“可它也是一段关系。有人给了我机会，另一个人因此失去机会。”\n我问这是否意味着她后悔活着。\n“有时会。”她没有用职业性的平静躲开，“但后悔不是遗愿。星遥没有要求我用余生证明她该活、我不该活。”\n我们把记录交给调查组，保留两处意见不同的注释。共同签名不再表示共同无罪，只表示这份差异也必须进入档案。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.shenYan,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'sumi_end_treatment',
  ),
  'sumi_end_treatment': StoryBeat(
    id: 'sumi_end_treatment',
    label: '照顾者也必须成为治疗对象',
    speaker: Speaker.suMi,
    scene: SceneKey.hearingRoom,
    portraitMood: 'epilogue',
    text:
        '听证结束后，苏弥开始接受创伤治疗。第一次会谈她带去完整病历，准备从症状、药物和睡眠数据讲起。治疗师却先问：“今天你希望我知道什么，而不是你认为一个合格患者应该报告什么？”\n她后来告诉我，自己在这个问题前沉默了十二分钟。\n我们也被建议暂时减少单独见面。只要我呼吸加快，她就会自动判断是否需要干预；只要她脸色发白，我便想替她取消工作。设施里的照顾关系在安全环境里仍会迅速接管双方决定。\n于是我们改成每周一次短讯，各自只报告一件愿意分享的日常，不报告血压、睡眠时长和是否按时吃药。她第一次发来的是窗台新长出的薄荷，第二次是忘记带伞被雨淋湿，第三次才写自己在地铁里听见警报后提前下车。\n我没有提供治疗建议，只问她是否想让我打电话。她回复“不用，今晚只想让你知道”。\n一个月后，她主动提出见面。会面地点是医院外的普通咖啡店，不在急诊通道旁。她到达后先说：“如果我开始检查你，请提醒我；如果你不想回答身体状态，可以拒绝。”\n我也告诉她，若我把陪伴说成替她休息，她可以立即结束会面。我们把边界说得有些笨拙，却比一句“我会照顾你”更接近能够继续的关系。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'sumi_end_return',
  ),
  'sumi_end_return': StoryBeat(
    id: 'sumi_end_return',
    label: '轮到她决定什么时候回来',
    speaker: Speaker.suMi,
    scene: SceneKey.riversideEvening,
    portraitMood: 'epilogue',
    text:
        '半年后，苏弥没有回到急诊一线。她选择参与灾难医疗伦理项目，研究自动分诊系统如何在资源不足时保存异议、知情与撤回，而不是只输出一张优先级名单。\n第一次公开讲座结束，她在河边找到我。晚风很冷，她把围巾向上拉了一点，没有像过去那样先问我手是否冰凉。\n“我今天漏讲了一页。”她说，“关于救援者不能用牺牲自己迫使别人接受被救。”\n我问为什么。\n“讲到一半想到，我也一直在这么做。只要我累倒，别人就不好意思拒绝我的安排。”她停了一下，“承认这件事不代表以前的照顾都是假的，只是好意也需要允许别人说不。”\n我们沿河走到灯光较暗的地方。她伸出手，又在碰到前停住：“现在可以吗？”\n我说可以，握住她。那不是紧急搬运、测量脉搏或阻止谁倒下，只是两个人都愿意继续走一段。\n分别前，她没有承诺以后每次都能问得这么清楚。我也没有承诺永远不会把被照顾当作爱的证明。我们约定出现旧习惯时可以指出，指出不等于否定关系。\n苏弥靠近了一点，把额头轻轻抵在我肩上。几秒后她自己退开，笑着说今天到这里。她决定何时靠近，也决定何时结束。我的手仍留着她掌心的温度，却不需要以握得更紧来证明它真实。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.shenYan,
      Speaker.suMi,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'sumi_end_result',
  ),
  'sumi_end_result': StoryBeat(
    id: 'sumi_end_result',
    label: '脉搏之外',
    speaker: Speaker.narration,
    scene: SceneKey.riversideEvening,
    endingId: 'ending_sumi',
    text:
        '她不再用照顾偿还幸存，你也不再用被照顾确认爱意。关系没有消除创伤，只让两个人都能在需要时成为被看见、也能说不的人。\n脉搏仍会因恐惧加快，也会因一次被询问过的牵手加快。它们终于不必由医生替彼此判断含义。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch8_standard_result_gate',
  ),
  'lincheng_end': StoryBeat(
    id: 'lincheng_end',
    label: '她拒绝让成年人替自己说明幸存',
    speaker: Speaker.linCheng,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '林澄的监护人赶到临时医院后，第一反应是把她抱住，第二反应是要求所有调查员离开。她还穿着损坏的校服外套，手腕留着拖拽伤，看起来确实像最应该被保护、最不该继续回答问题的人。\n她接受休息，却拒绝让律师直接替她提交证词。“我可以晚一点说，也可以有人陪着说，但不能变成他们问你们、你们猜我会怎么回答。”\n第六日，我把归还密钥交给她。苏弥死在医疗门另一侧。林澄知道自己当时在哭，也知道自己曾说“不想死”。她担心这句话会被理解成要求我放弃苏弥，于是反复解释自己还说过“能不能再找一把”。\n调查员让她只陈述记得的部分，不必证明哪一句更像真正意愿。恐惧、求生和不愿别人死亡可以同时存在。\n轮到我时，她要求留在房间。不是为了替我作证，而是要听我是否把她描述成无法负责的学生。\n我承认自己因她年纪更小、与我登记信赖关系而优先相信必须先救她，也承认这个判断把苏弥长期承担的救援角色误当成“她总会有办法”。\n林澄没有说谢谢。她把双马尾重新扎好，低声回答：“我想活，不等于她比较应该死。你以后不要替我把这两句话连起来。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
    ],
    next: 'lincheng_end_memorial',
  ),
  'lincheng_end_memorial': StoryBeat(
    id: 'lincheng_end_memorial',
    label: '地图上补回医疗区的名字',
    speaker: Speaker.linCheng,
    scene: SceneKey.memorialWall,
    portraitMood: 'epilogue',
    text:
        '临时纪念墙开放时，林澄带来重新绘制的设施地图。过去她习惯用颜色标记危险、物资与可通行路线，这一次每个死亡地点旁都写了姓名，没有用叉号把区域涂黑。\n苏弥的名字在医疗门旁。林澄写了三遍才满意，又补上一条细线，连接到第一日她替自己包扎手腕的医务台。\n“如果只画她最后没出来的门，会像她一直待在那里。”林澄说，“她还去过很多地方。”\n她把苏弥在七天里经过的每一条救援路线都补进地图。线条因此密得几乎看不清，却让一个人不再只等于死亡坐标。\n苏弥的家属来看图时，问林澄最后是否很痛。她没有因为对方需要安慰就编造答案，只说隔着门听见呼吸越来越慢，苏弥仍在指导外面处理伤者。家属哭了，她也哭，两个成年人没有要求她停止。\n离开前，林澄把那条从医务台到死亡地点的线复印给我。“你可以记得她救过我，但不能拿这个当成她会同意把钥匙给我。”\n我收下。地图保存关系，却不替死者签署任何遗愿。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'lincheng_end_school',
  ),
  'lincheng_end_school': StoryBeat(
    id: 'lincheng_end_school',
    label: '回到教室不等于恢复原样',
    speaker: Speaker.linCheng,
    scene: SceneKey.schoolClassroom,
    portraitMood: 'epilogue',
    text:
        '三个月后，林澄尝试返校。学校安排她从半天课程开始，允许避开广播和实验室警报。第一周她在上课铃响起时钻到桌下，第二周能够站在走廊听完整段铃声，第三周又因同学从背后碰肩而提前回家。恢复没有按不断上升的直线发生。\n同学最初不敢问，后来有人偷偷搜索新闻，把她的幸存称作“通关”。林澄当场反驳，第二天却躲在洗手间不愿进教室。她既不想被当成脆弱受害者，也没有力气每天教育所有人。\n我没有直接去学校找她。她仍是学生，关系又在极端依赖中形成，任何未经邀请的出现都可能把“我担心你”变成她必须接待的压力。我们只通过监护人和创伤辅导员确认联络边界。\n第一次由她主动打来的电话很短。她问我是否还记得毕业典礼的约定。\n我说记得，但是否见面由她到时重新决定，过去的答应不能替未来的她确认。\n“你现在讲话好像同意书。”她终于笑了一声，“我只是问记不记得。”\n通话结束前，她说班级要做一份校园疏散图，自己申请负责。她会把每条路线画出至少两个出口，也会标注行动不便者能在哪些位置请求暂停。设施教给她的地图没有消失，只是第一次被用来让一群人不必服从唯一道路。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'lincheng_end_graduation',
  ),
  'lincheng_end_graduation': StoryBeat(
    id: 'lincheng_end_graduation',
    label: '约定在没有倒计时的日子重新确认',
    speaker: Speaker.linCheng,
    scene: SceneKey.riversideEvening,
    portraitMood: 'epilogue',
    text:
        '毕业典礼那天，我没有进入校园，只在她指定的河边等。仪式结束一个小时后，林澄才穿着制服过来，胸前别着一朵有些歪的纸花。她说临时想和同学多拍几张照片，所以没有按原计划离场。\n“我迟到了。”\n“你没有倒计时。”\n她愣了一下，随后用力点头。迟到不再意味着别人会死，也不需要用道歉换取继续见面的资格。\n我们沿河走到曾经约好的桥下。她谈起志愿选择，想读城市安全与空间设计，又担心别人会把它理解成创伤决定了人生。我没有说经历一定会变成力量，只问哪个部分是她现在真的感兴趣。\n“我喜欢画路。”她想了很久，“以前就喜欢。只是现在知道一条路不能只在图上存在，还要有人能说自己走不了。”\n分别时，她把那条青绿色发带从书包上解下，没有再系到我的终端，而是重新扎回自己的头发。\n“以前给你，是怕你忘记回来。”她说，“现在我想自己留着。”\n我告诉她这样很好。她又从毕业册里取出一张写着新号码的纸，问我是否愿意以普通联系方式保存。没有编号，没有信赖条件，也没有必须立刻回复的规则。\n我接过纸。她没有用拥抱或亲吻把约定封口，只向前走了几步，又回头确认我是否跟上。我们保持各自能够选择的距离，沿同一条河走到下一个路口。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.shenYan,
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'lincheng_end_result',
  ),
  'lincheng_end_result': StoryBeat(
    id: 'lincheng_end_result',
    label: '毕业约定',
    speaker: Speaker.narration,
    scene: SceneKey.riversideEvening,
    endingId: 'ending_lincheng',
    text:
        '她活下来，不是为了替任何死者完成未来，也不必把信赖永久交给救过自己的人。毕业约定在没有倒计时的世界重新成立，并且仍可被任何一方改变。\n地图尽头没有唯一出口。你们只是在一个普通路口，再次决定暂时同行。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch8_standard_result_gate',
  ),
  'ch8_standard_result_gate': StoryBeat(
    id: 'ch8_standard_result_gate',
    label: '余烬没有改写公共结果',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '这段关系获得了继续或停止的空间，却没有覆盖七日里已经发生的死亡、控制与证据断裂。私人余烬必须与公共责任并列保存，不能替最终结果换一个更温柔的名字。',
    passageSpeakers: [Speaker.narration],
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch8_four_seats_result',
      'ch6_hanqi_vote_killer': 'ch8_custodian_result',
      'ch6_chenmo_vote_killer': 'ch8_no_witness_result',
    },
    next: 'ch8_no_witness_result',
  ),
  'ch8_audit_candidate_meeting_1': StoryBeat(
    id: 'ch8_audit_candidate_meeting_1',
    label: '九个人没有把四席误认为四个获救名额',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚先把“提交席”和“离开资格”写在白板两端。四个人入舱，九个人仍是证人；未入舱者负责封存候选材料、监督紧急中止，并在外部调查中保留自己的不同意见。\n“选席不是决定谁更值得活。”她说，“也不是把没被选中的人降成观众。四席只是当前接口能同时读取的上限。”\n这句话让持续了一夜的紧张稍微改变形状。没人需要靠杀死第五个人证明自己不可替代，但被选中仍意味着独自面对一套会把求生条件伪装成正当性的问卷。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch8_audit_candidate_meeting_2',
  ),
  'ch8_audit_candidate_meeting_2': StoryBeat(
    id: 'ch8_audit_candidate_meeting_2',
    label: '每名候选人先声明自己最可能偏向的答案',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '唐弈承认自己更容易选择ZERO，因为可计算的程序边界能把直接杀人行为与设计责任分开；陈默承认自己希望三层记录继续不完整；韩骐则说，只要01仍在危险里，他就可能把保护权看得比证词独立更重要。\n星遥害怕把系统技术问题说成全部真相，苏弥害怕一旦否定个人条款，过去依靠医疗条件救下的人会被解释成偶然。林澄最担心的不是答案错误，而是自己看见成年人都很确定以后，跟着说出没有真正理解的话。\n没有一项声明取消候选资格。偏向被记录出来，才有可能在入舱前被本人识别，而不是在提交后冒充客观结论。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_candidate_meeting_3',
  ),
  'ch8_audit_candidate_meeting_3': StoryBeat(
    id: 'ch8_audit_candidate_meeting_3',
    label: '四席需要来自不同证据入口而非同一阵营',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '高原提出四项来源：亲手恢复人类审批、追踪ZERO迁移、撤回参与者执行输入，以及从未掌握技术却能说明规则如何作用于普通人的现场经历。任何两席可以重叠，四席不能全部依赖同一个解释者。\n“我会核对设备，不替任何人写结论。”他说着将四种颜色的纸袋放到桌面，“你们拿到的袋子不同，问到的问题也不同。最终相容只能来自结构，不会来自句子。”\n随后轮到关系与公开轮值决定最后的人员组合。亲近不自动构成可靠，疏远也不自动构成独立；我们必须说明为什么由这四个人承担四种不同的误差。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch8_audit_seat_objection_1',
  ),
  'ch8_audit_seat_objection_1': StoryBeat(
    id: 'ch8_audit_seat_objection_1',
    label: '未入选者逐一说明自己反对哪一种席位安排',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚没有让名单直接进入表决。每名未入选者必须指出一项具体风险，且反对不能只写“我更合适”。高原质疑技术席是否会把结构问题缩成程序故障；苏弥质疑身体状态最差的人是否会因不愿拖累大家而隐瞒；林澄则指出成年人可能把流畅表达误当作更独立。\n唐弈反对将自己排除在外，理由是四席需要有人理解通过概率。叶岚要求他继续说明：“概率错误会伤害哪一层证词？”\n他最终承认，自己真正担心的是别人无法在倒计时内选出可通过答案。也就是说，他仍把席位当作求解器，而不是四名可以各自拒绝的证人。\n异议被写入名单附件，没有一条因说话者未入选而降级。被质疑的人也无需立刻证明自己没有风险，只需说明风险如何被其他席位和外部监督发现。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_audit_seat_objection_2',
  ),
  'ch8_audit_seat_objection_2': StoryBeat(
    id: 'ch8_audit_seat_objection_2',
    label: '候选人可以退出而无需为席位失败负责',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '苏弥把退出条款读了两遍。终局开始前，候选人可因身体、记忆或个人意愿退出；退出后重新抽选，不触发惩罚，也不记录为反对共同证词。真正让她犹豫的不是危险，而是另外八个人会不会因此认为她让准备白费。\n“如果我最后一分钟说不行呢？”她问。\n“那就停。”叶岚回答，“我们可以失去一套安排，不能用已经准备了很久逼你继续。”\n九个人分别签下同意退出条款。签名不能保证无人失望，却使失望不再拥有项圈和倒计时的力量。苏弥在自己的名字旁加了一句：照顾四席也包括允许其中一席不再承担。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch8_audit_outside_witness_protocol',
  ),
  'ch8_audit_outside_witness_protocol': StoryBeat(
    id: 'ch8_audit_outside_witness_protocol',
    label: '舱外五人建立不依赖终端结果的见证记录',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.testimonyHall,
    portraitMood: 'inspecting',
    text:
        '高原在观察区铺开五本纸质记录。舱外人员不会看到答案，只记录入舱时间、候选人是否自行行走、是否要求退出、终端灯何时变化，以及管理员播报的原始文字。每本记录使用不同纸张和笔，结束后分别封存。\n星遥担心五份日志仍会在同一个房间被广播影响，于是把一只机械计时器放到最远角落。它与ZERO没有连接，只提供另一条时间轴。林澄负责每十分钟拍摄表盘和主屏，不解释两者差异。\n“我们可能什么也救不了。”高原说，“但至少能证明四席是在什么条件下作答，而不是只拿到系统宣布成功的一句话。”\n未入舱者因此不是候补生命，也不是等待结果的观众。他们保存的是终端最容易省略的过程。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch8_audit_emergency_rehearsal',
  ),
  'ch8_audit_emergency_rehearsal': StoryBeat(
    id: 'ch8_audit_emergency_rehearsal',
    label: '最后一次排练故意让正确答案无法按时提交',
    speaker: Speaker.linCheng,
    scene: SceneKey.testimonyHall,
    portraitMood: 'determined',
    text:
        '排练开始后，叶岚在第七分钟切断模拟第三席的显示器。候选人已经完成三层责任说明，只差拉杆。若按效率，她应该借用旁边人的屏幕或口述答案；按新的规则，她只能报告设备失效并等待替换。\n倒计时归零，模拟系统宣告四席失败。没有项圈动作，也没有人指责第三席。舱外人员按预案封存已完成的三份材料，再检查故障不是候选人故意制造。\n林澄看着红色失败字样，脸色仍然发白。“知道是假的也很难。”她说，“可刚才没有人冲进来替她按。”\n排练没有证明我们一定成功。它只证明当正确答案与一个人的停止权冲突时，九个人至少练习过让答案失败。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch8_audit_candidate_gate',
  ),
  'ch8_audit_candidate_gate': StoryBeat(
    id: 'ch8_audit_candidate_gate',
    label: '不同关系路线选出不同的相互校验方式',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '名单没有按好感、体力或编号排序。我们先确认谁能在隔离中保持判断，再确认四份材料不会由同一人解释。被选中的人有权退出，未被选中的人有权质疑理由。\n我在自己的名字旁留下空白。无论与谁并肩走到这里，入舱后都不能把她的声音想象成答案。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_route_locked_xingyao': 'ch8_audit_xingyao_seats_1',
      'ch6_route_locked_sumi': 'ch8_audit_sumi_seats_1',
      'ch6_route_locked_lincheng': 'ch8_audit_lincheng_seats_1',
      'ch6_route_locked_public': 'ch8_audit_public_seats_1',
    },
    next: 'ch8_audit_public_seats_1',
  ),
  'ch8_audit_xingyao_seats_1': StoryBeat(
    id: 'ch8_audit_xingyao_seats_1',
    label: '星遥拒绝与我共享最后一次校验结果',
    speaker: Speaker.liXingyao,
    scene: SceneKey.testimonyHall,
    portraitMood: 'relaxed',
    text:
        '名单确定为我、星遥、叶岚与唐弈。星遥负责程序迁移，我负责人类审批，叶岚核对撤回制度，唐弈则必须解释自己如何利用人数条件，而不是只计算通过概率。\n她把两侧耳机都戴回去，删除我们之间最后一条临时频道。“现在断线不是失约。”她说，“你写你的，我写我的。出来以后再比较。”\n我点头，没有要求一个私下暗号。我们终于把关系从实时互证中拿开，让相信对方与检查对方可以同时成立。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch8_audit_copy_test_1',
  ),
  'ch8_audit_sumi_seats_1': StoryBeat(
    id: 'ch8_audit_sumi_seats_1',
    label: '苏弥把随时中止写进四席医疗预案',
    speaker: Speaker.suMi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'concerned',
    text:
        '名单确定为我、苏弥、高原与韩骐。苏弥承担身体与处决条款，高原核对物理审批，韩骐必须说明保护何时变成夺取他人决定权；我的材料则来自输入总线。\n她在每间舱外贴上同样的红色释放标记：“胸痛、呼吸困难、意识混乱，任何一项都先中止。少一席不等于那个人害死另外三席。”\n我问她自己出现手抖时会不会按。她看了我两秒，回答会。这是她今天给出的第一个不以照顾别人为前提的承诺。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch8_audit_copy_test_1',
  ),
  'ch8_audit_lincheng_seats_1': StoryBeat(
    id: 'ch8_audit_lincheng_seats_1',
    label: '林澄要求用自己的语言说明每层责任',
    speaker: Speaker.linCheng,
    scene: SceneKey.testimonyHall,
    portraitMood: 'determined',
    text:
        '名单确定为我、林澄、陈默与叶岚。陈默掌握被他主动破坏的责任记录，叶岚掌握规则边界，我恢复审批签名；林澄没有最完整的技术材料，却走过每条被编号和距离改变过的路线。\n“不要因为我是学生就给我简单版本。”她将三张空白卡片推回来，“也不要在我说错一个术语时替我改成你们的答案。我会说明我看到规则怎样让人行动。”\n她把双马尾重新束紧，手指仍有轻微颤抖。害怕没有让她失去席位，也没有被包装成天赋。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch8_audit_copy_test_1',
  ),
  'ch8_audit_public_seats_1': StoryBeat(
    id: 'ch8_audit_public_seats_1',
    label: '公开轮值让最熟悉答案的人留在舱外',
    speaker: Speaker.yeLan,
    scene: SceneKey.testimonyHall,
    portraitMood: 'intervening',
    text:
        '公开轮值选出我、星遥、苏弥与高原。叶岚主动留在外面保管证据，尽管她最熟悉撤回制度；唐弈、陈默与韩骐也留在监督区，他们的偏向将由外部口供单独保存。\n“制度不能永远由提出制度的人坐在关键位置。”叶岚把封条编号交给林澄，“否则公开只是在公开地依赖同一位解释者。”\n四席因此少了一名最有把握的答题人，多了四种互不相同的证据入口。通过概率下降，独立性反而上升。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch8_audit_copy_test_1',
  ),
  'ch8_audit_copy_test_1': StoryBeat(
    id: 'ch8_audit_copy_test_1',
    label: '四个人先解释一份从未共同讨论的材料',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.testimonyHall,
    portraitMood: 'inspecting',
    text:
        '正式入舱前，高原从维修日志中随机抽出一段从未进入公共摘要的记录：一扇门因参与者托管、ZERO超时和项目安全策略同时保持关闭。四名提交者分别在隔间里写下“谁能让门打开”。\n答案没有一句相同。有人写撤回托管，有人写中止裁定线程，有人写外部断电，还有人指出设计者根本没有提供无条件人工逃生。四份说明却都识别出门锁同时受三层约束。\n比对器给出“结构相容，文字独立”。这不是终局答案，只证明我们没有用同一段背诵替代思考。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_copy_test_2',
  ),
  'ch8_audit_copy_test_2': StoryBeat(
    id: 'ch8_audit_copy_test_2',
    label: '错误也被保留在纸面而不是当场修成统一口径',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyHall,
    text:
        '我的测试纸把安全策略写成了即时人工命令。星遥从时间戳指出，那其实是绑架前预置、由程序自动读取的策略。我划线改正，却没有换一张干净纸。\n她也漏写了托管者能够主动撤回。我将对应总线编号指给她看，保留她第一次答案。互相纠正并不等于互相复制，前提是错误如何改变、由什么证据改变都可追溯。\n四张带修改痕迹的纸分别封袋。共同理解不是四个从不犯错的人，而是四条看得见的修正路径最终没有被一人吞并。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_clause_review_1',
  ),
  'ch8_audit_clause_review_1': StoryBeat(
    id: 'ch8_audit_clause_review_1',
    label: '否定处决正当性不等于否定获救愿望',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '第三字段仍是最难统一的一项。苏弥把“希望条款带来的结果实现”与“承认项圈有权强迫结果”分成两列。她希望所有人得到治疗，不等于同意未接受治疗者应被处决。\n林澄希望与可信对象共同离开，不等于独自选择路线就该死；韩骐希望01安全，也不等于01因此失去拒绝保护的权利。\n我们逐条念出自己的生还愿望，再逐条删除它们对别人的惩罚权限。愿望可以保留，主办方替愿望装上的爆炸物不能因此合法。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_clause_review_2',
  ),
  'ch8_audit_clause_review_2': StoryBeat(
    id: 'ch8_audit_clause_review_2',
    label: '直接利用规则的人不能用受到胁迫抹去全部行为责任',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'shaken',
    text:
        '唐弈起初把所有参与者输入都归入胁迫。叶岚让他只回答一件事：当人数已经不再威胁他的项圈，他是否仍主动维持会杀人的门。\n他很久没有说话，最后回答是。陈默也承认自己删除责任记录并非程序自动完成；韩骐承认曾用保护条件夺取我的移动权。项目设计与系统裁定解释了武器如何被放到手里，却没有替使用武器的人按下动作。\n这份承认不把他们和绑架者写成同一种责任。恰恰相反，分层以后，胁迫、利用、阻止与主动伤害才不会被一句“大家都是参与者”混成同样。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_clause_review_3',
  ),
  'ch8_audit_clause_review_3': StoryBeat(
    id: 'ch8_audit_clause_review_3',
    label: '四席分别签下个人条款不具有处决效力',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    text:
        '四名提交者没有在同一张声明上签名。每个人得到一张只写自己条件的纸，独自补完：“我仍希望……，但拒绝因此……”\n有人写希望她回应呼叫但拒绝把断线视为背叛；有人写希望救下患者但拒绝让失败成为死刑；有人写希望共同离开却拒绝强迫同行；公开路线则写希望保全证据但拒绝用监督剥夺沉默。\n四张纸措辞不同，第三字段都指向无效。我们没有否定活下去的欲望，只把生与死的裁决权从欲望上拆下来。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch8_personal_clauses_rejected'},
    next: 'ch8_audit_director_reveal_1',
  ),
  'ch8_audit_director_reveal_1': StoryBeat(
    id: 'ch8_audit_director_reveal_1',
    label: '被酸洗的签名终于恢复完整姓名',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    cgId: 'cg_ch8_director_reveal',
    cgFrame: 0,
    text:
        '临近提交时，高原发现审批板侧边还有第二层压痕。第一层是我们恢复过的H-7代号，第二层则被金属框遮住，只在固定螺钉附近留下几个反向笔画。\n他没有拆下证物，而是将四个角度的斜光照片投到透明片上。星遥校正镜像，林澄按笔顺重新描线，三个汉字逐渐从噪点中成形：顾闻川。\n名字出现时，房间没有得到抓住幕后黑手的轻松。一个姓名终于能进入通缉和调查，也提醒我们，知道人类负责人仍只回答责任链的第一层。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch8_director_name_recovered'},
    next: 'ch8_audit_director_reveal_2',
  ),
  'ch8_audit_director_reveal_2': StoryBeat(
    id: 'ch8_audit_director_reveal_2',
    label: '项目负责人留下了一段为自己准备的免责说明',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    cgId: 'cg_ch8_director_reveal',
    cgFrame: 1,
    text:
        '姓名恢复后，审批板解锁一段离线录音。顾闻川的声音平静地说明：ZERO会在无人干预下运行，所有具体死亡均由系统裁定或参与者选择产生，项目方仅提供研究框架。\n录音刻意把“没有实时按键”说成“没有行为”。可绑架名单、项圈参数、个人条件冲突和武器位置都在实验开始前由他的团队批准。程序的自动执行不是责任真空，而是设计者决定把手从按钮上拿开。\n我们保留原始录音，不对它进行剪辑反驳。它会成为人类责任证据，而不是取代另外两层的最终答案。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_director_reveal_3',
  ),
  'ch8_audit_director_reveal_3': StoryBeat(
    id: 'ch8_audit_director_reveal_3',
    label: '零点协议成为可以被说明而不是被背诵的名称',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'relaxed',
    text:
        '星遥在录音元数据里找到项目全称：“ZERO-POINT RESPONSIBILITY PROTOCOL”。它原本不是主办方自称，而是一套把设计决策、自动裁定和现场输入拆开记账，再利用拆分结果制造无人承担全部责任的协议。\n“所以答案不是把三个人捆成一个凶手。”她说，“是说明三层怎样接上，又说明每层该承担什么。协议成立，不代表责任平均。”\n零点协议终于不再是我们临时起的漂亮名字。它是对方用来分散责任的结构，也将成为我们把责任重新连接起来的证词代号。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    flagsOnEnter: {'ch8_zero_protocol_understood'},
    next: 'ch8_audit_director_family_record',
  ),
  'ch8_audit_director_family_record': StoryBeat(
    id: 'ch8_audit_director_family_record',
    label: '一个完整姓名也意味着设施外存在不应被擅自利用的人',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '搜索离线人事包时，终端同时显示顾闻川的家庭联系人。有人提出将姓名和地址一起广播，迫使他现身。那是这七天最容易理解的报复方案：主办者把我们的关系变成弱点，我们也可以把他的关系变成筹码。\n叶岚关闭地址页面，只保留与项目任职有关的身份字段。“家属不是他的替补项圈。”\n唐弈指出公开地址可能提高抓捕概率，却没有坚持。他把这一项从方案里划掉，承认概率收益不能让无关者自动成为可支付成本。\n我们复制姓名、任职、签名和审批时间，封存私人地址交给外部执法核验。对顾闻川追责不需要继续使用他设计的关系逻辑。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_audit_answer_independence_check',
  ),
  'ch8_audit_answer_independence_check': StoryBeat(
    id: 'ch8_audit_answer_independence_check',
    label: '四席在入舱前最后一次拒绝交换标准答案',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyHall,
    text:
        '距离十八点还有十二分钟，主屏弹出一份“推荐陈述模板”。模板准确写出顾闻川、ZERO与参与者输入三层，最后却把三者合称为不可分割的共同主体。照抄几乎肯定相容，也会抹掉每层不同责任。\n我们没有讨论如何修改。四名候选人各自阅读后，将模板放进不同证物袋，再在封口处写下自己认为最危险的一句。袋子要到外部调查时才能互相打开。\n关系对象隔着封线看我。我很想从她的表情确认自己是否抓住同一句话，最后仍低下头，只检查自己的证据编号。\n独立不是假装彼此从未影响。它是在已经共同走过七天以后，仍为最后那部分不能代答的判断留下真正的隔离。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_audit_dead_witnesses',
  ),
  'ch8_audit_dead_witnesses': StoryBeat(
    id: 'ch8_audit_dead_witnesses',
    label: '共同证词不替死者补写他们没有机会作出的选择',
    speaker: Speaker.suMi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'concerned',
    text:
        '终端提示四席可以引用死者记录作为相容依据。吴峥反抗项圈、周叙留下门锁速写，这些行为都能证明他们不接受规则；但没有人知道他们会怎样回答三层责任，也不知道经历后续事实以后是否会改变。\n苏弥把两人的材料标为“证据”，拒绝标为“代理证词”。“我们可以说他们做过什么，不能说他们如果活着一定会同意我们。”\n这项限制降低了相容分数，因为终端原本允许用死者行为填补四席差异。我们仍将代理字段全部留空，只在附件中保留原始时间与动作。\n记住死者不是让他们永远站在幸存者一边。共同证词必须承认，死亡夺走的也包括继续解释、反对和修改自己的权利。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_audit_last_names',
  ),
  'ch8_audit_last_names': StoryBeat(
    id: 'ch8_audit_last_names',
    label: '入舱前九个人只核对姓名不核对答案',
    speaker: Speaker.linCheng,
    scene: SceneKey.testimonyHall,
    portraitMood: 'determined',
    text:
        '最后三分钟，林澄提议不再讨论证据。她拿出第一日自我介绍时留下的名单，从沈砚开始，一个个核对九名幸存者希望写入外部记录的姓名。有人保留本名，有人暂时只用姓氏，选择由本人决定。\n念到吴峥和周叙时，没有人代答。林澄只在姓名后写“死亡，证词权未转移”。12号槽位则单独标注为系统身份，不列入十二个人。\n“这次不是点名。”她说，“谁不想回应也可以。”\n有人沉默，有人轻声说在。答案不同，没有一盏灯因此变红。随后四名候选人走向各自隔舱，带走不同证物，也把刚才没有被迫统一的声音留在身后。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch8_audit_entry_1',
  ),
  'ch8_audit_entry_1': StoryBeat(
    id: 'ch8_audit_entry_1',
    label: '四扇隔离门依次关闭',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyHall,
    cgId: 'cg_ch8_testimony_open',
    cgFrame: 0,
    text:
        '十八点整，第一扇门为我打开。座椅比预想更低，固定带只绕过腰部，没有锁住手腕。三只证物槽分别吐出审批压痕、节点迁移摘要与一段参与者撤回记录，顺序与排练完全不同。\n隔着双层玻璃，我只能看到另外三个人先后进入模糊的白光。第四扇门闭合后，外面的九人被遮光板彻底挡住。耳机里没有呼吸、暗号或管理员提示。\n我把掌心按在桌面，等因安静而放大的心跳慢下来。今天最后一次选择必须由我本人完成。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_entry_2',
  ),
  'ch8_audit_entry_2': StoryBeat(
    id: 'ch8_audit_entry_2',
    label: '终端要求先解释材料再选择主办者代号',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyBooth,
    cgId: 'cg_ch8_testimony_open',
    cgFrame: 1,
    text:
        '屏幕没有直接显示三个选项。它先让我说明顾闻川的签名为何早于绑架、ZERO迁移为何不需要实时操作，以及撤回输入为何能停止一部分执行。每个文本框提交后立即封存，不能返回修改。\n最后一页才出现三个主办者代号。下方还有第三字段：我的个人条款是否拥有处决正当性。\n我读完全部文字，没有寻找哪个按钮颜色更像正确答案。透明罩缓慢升起，三枚选择键和提交杆同时解锁。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_testimony',
  ),
  'ch8_audit_testimony': StoryBeat(
    id: 'ch8_audit_testimony',
    label: '隔离证词只接受本人理解后的答案',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyBooth,
    phase: StoryPhase.testimony,
    text: '请选择能够同时解释人类设计、程序裁定与参与者可执行输入的主办者代号。',
    next: null,
  ),
  'ch8_audit_human_answer_error': StoryBeat(
    id: 'ch8_audit_human_answer_error',
    label: '人类负责人无法解释仍在运行的裁定链',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyBooth,
    text:
        '顾闻川批准绑架、项圈和冲突条件，承担不可转移的人类设计责任。但眼前的迁移记录表明，他离开控制端以后，ZERO仍会读取现场输入并自行执行。\n只提交他的姓名，会把程序持续裁定和参与者主动利用条件都压回“幕后黑手做的一切”。这能指认一个重要嫌疑人，却不能说明我手中三份材料怎样共同造成死亡。\n终端允许在拉下提交杆前撤回本次选择。我松开按键，重新查看三层责任图。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_testimony',
  ),
  'ch8_audit_zero_answer_error': StoryBeat(
    id: 'ch8_audit_zero_answer_error',
    label: '程序执行不能抹去设计与主动利用',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyBooth,
    text:
        'ZERO确实控制门锁、项圈与迁移裁定，也在无人实时操作时保持实验。但它的目标、输入接口和免责结构来自人类设计；参与者撤回后执行变化，又证明现场选择不只是被观察的数据。\n只提交ZERO，会让顾闻川把预先授权叫作研究框架，也让主动维持杀人条件的人把动作叫作算法结果。程序不是无辜工具，却也不是能吞下所有责任的单一人格。\n我取消选择。三层之间的连接，才是这套游戏真正用来继续运转的主办结构。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_testimony',
  ),
  'ch8_audit_testimony_resolved': StoryBeat(
    id: 'ch8_audit_testimony_resolved',
    label: '零点协议被作为三层责任结构提交',
    speaker: Speaker.shenYan,
    scene: SceneKey.testimonyBooth,
    cgId: 'cg_ch8_protocol_unlock',
    cgFrame: 0,
    text:
        '我选择零点协议，并在责任层级中分别填入：顾闻川及项目团队预先设计与绑架，ZERO持续裁定与执行，参与者输入在胁迫环境中仍可能构成具体阻止、利用或伤害。三层相连，不平均，也不互相抵消。\n个人条款一栏，我写下“不具有处决正当性”。我仍想和重要的人一起离开，仍想让全部证据被保存，但任何愿望都不能让项圈有资格杀死拒绝的人。\n提交杆落到底部。我的屏幕熄灭，只剩一枚白色状态灯。其余三席仍不可见。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch8_shen_testimony_submitted'},
    next: 'ch8_audit_testimony_wait_1',
  ),
  'ch8_audit_testimony_wait_1': StoryBeat(
    id: 'ch8_audit_testimony_wait_1',
    label: '等待期间无法知道沉默意味着犹豫还是拒绝',
    speaker: Speaker.narration,
    scene: SceneKey.testimonyBooth,
    text:
        '第一分钟，第二枚席位灯变白。第五分钟，第三枚亮起。第四席始终保持灰色。我的终端不显示是谁，也不允许已经提交的人中止别人。\n我想到排练时那间长久没有动作的隔舱。沉默可能是重新阅读、身体不适、拒绝条款，或终于不愿跟随我们的结论。任何一个原因都属于里面的人，不能由我的焦虑代写。\n第九分钟，最后一枚灯亮起。四席没有同时作答，却都在本人允许的时间里完成。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_testimony_wait_2',
  ),
  'ch8_audit_testimony_wait_2': StoryBeat(
    id: 'ch8_audit_testimony_wait_2',
    label: '比对器逐项确认相容而不是逐字重复',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyHall,
    text:
        '遮光板没有立刻升起。管理员依次播报比对结果：“主办者代号，四份相容。责任层级，四份相容。个人条款正当性，四份否定。”\n随后屏幕列出差异：有人将ZERO称为共同实施工具，有人称为具备裁定能力的执行系统；有人强调参与者受到胁迫，有人强调主动行为仍需调查。差异被标注为保留意见，没有被系统抹平。\n最后一行出现：“独立共同见证成立。”那不是胜利宣言，只是四条不同路径终于抵达能够共同保存的结构。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch8_common_witness_established'},
    next: 'ch8_audit_unlock_1',
  ),
  'ch8_audit_unlock_1': StoryBeat(
    id: 'ch8_audit_unlock_1',
    label: '项圈先失去指示灯再松开锁舌',
    speaker: Speaker.suMi,
    scene: SceneKey.testimonyHall,
    portraitMood: 'relieved',
    cgId: 'cg_ch8_protocol_unlock',
    cgFrame: 1,
    text:
        '我颈侧先传来一声轻响，随后是金属锁舌真正退开的重量。项圈没有弹飞，只沿皮肤缓慢松开。我用双手托住它，直到确认内部电容灯完全熄灭才放到桌面。\n四扇隔舱同时开启。外面的五个人仍站在封线之后，苏弥没有立刻冲进来，而是隔着线问每一席是否允许她检查。得到四次回答后，她才逐个触摸颈动脉和烧伤边缘。\n九枚项圈依次进入断电托盘。没有欢呼盖过锁舌声。每一次解锁都要由那个人自己确认。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch8_all_collars_released'},
    next: 'ch8_audit_unlock_2',
  ),
  'ch8_audit_unlock_2': StoryBeat(
    id: 'ch8_audit_unlock_2',
    label: '管理员最后一次试图把幸存称作项目结果',
    speaker: Speaker.administrator,
    scene: SceneKey.testimonyHall,
    text:
        '主屏显示：“七日项目完成。有效共同证词：四。存活样本：九。”\n林澄走到拾音器前，清楚地报出九个人的姓名，再报出吴峥和周叙。叶岚要求将“样本”改为“被绑架参与者”，系统拒绝修改，但星遥已经把拒绝日志写入只读镜像。\n管理员倒数十秒后永久离线。它保留了最后一个错误称呼，也因此留下最后一条可供外部调查证明项目如何看待人的记录。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.narration,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch8_zero_final_shutdown'},
    next: 'ch8_audit_exit_1',
  ),
  'ch8_audit_exit_1': StoryBeat(
    id: 'ch8_audit_exit_1',
    label: '出口之外先出现的是救援灯而不是自由的象征',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text:
        '终局闸门升起后，外面仍是一段水泥通道。尽头传来切割机和扩音器，救援人员要求我们停在原地、举起空手，并依次说明是否携带爆炸物。\n过去六天，服从陌生指令往往意味着陷阱。九个人没有立刻向前。直到对方把警员编号、医院名称与外部时间写在可视板上，又送入独立气体探头，叶岚才确认这是一套允许复核的程序。\n我们分三批走过临时防爆门。晨光还没出现，通道里的白色救援灯已经足以让我眯起眼睛。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_debrief_1',
  ),
  'ch8_audit_debrief_1': StoryBeat(
    id: 'ch8_audit_debrief_1',
    label: '外部人员没有要求先选出一名统一发言者',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '临时取证室由透明隔板分成九个区域。调查员说明，口供会分别记录，任何人可以休息、申请律师或拒绝回答；医疗检查与证词有效性不绑定。\n我第一反应仍是寻找其他人的屏幕。隔板后只有自己的录音指示灯和一杯温水。没人能因我停顿而失去出口，这让沉默第一次不再需要解释。\n我从醒来的宿舍开始讲，报出每次选择前自己知道什么、不知道什么。说到吴峥和周叙时，调查员没有替我跳过。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_debrief_2',
  ),
  'ch8_audit_debrief_2': StoryBeat(
    id: 'ch8_audit_debrief_2',
    label: '完整证据让设计责任与直接行为分别进入调查',
    speaker: Speaker.yeLan,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '三层证据分别装入防静电箱。顾闻川及项目团队进入绑架、故意伤害和非法人体实验调查；ZERO镜像由独立取证组封存；参与者输入则逐项核对是否在胁迫下、是否存在停止机会、是否造成具体后果。\n唐弈、陈默与韩骐没有被一概称为无辜幸存者，也没有在医疗床边被当场判罪。他们获得律师和治疗，相关未遂、控制与主动利用行为同时保留。\n叶岚在每张移交单上检查封条号码。“活着带出来的证据，不是为了在门外重新找一个可以省略程序的裁定者。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.yeLan],
    next: 'ch8_audit_debrief_3',
  ),
  'ch8_audit_debrief_3': StoryBeat(
    id: 'ch8_audit_debrief_3',
    label: '两名死者不再被压缩成推动幸存者成长的代价',
    speaker: Speaker.suMi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '苏弥协助法医核对吴峥的项圈残片，却在闻到绝缘材料焦味时停在门外。她没有逼自己进去，只将生前体征、急救时间与主办方广播交给另一名医生。\n周叙留下的速写本由高原逐页拍照，原件封存后通知家属。那些未完成的走廊透视、门锁尺寸和潦草疑问都被当作个人遗物，不只挑出对案件有用的几页。\n我们不能靠更好的结局让他们复活。审计路线保存的是死亡没有继续增加，以及他们已经留下的东西不会被活人擅自补成同意。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_audit_debrief_4',
  ),
  'ch8_audit_debrief_4': StoryBeat(
    id: 'ch8_audit_debrief_4',
    label: '媒体在建筑外等待一个比事实更短的答案',
    speaker: Speaker.liXingyao,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '天亮前，建筑外已经聚集媒体。问题透过玻璃传来：谁是最终凶手、谁赢得游戏、九个人是否达成和解。每个问题都试图把七天压回一个主语。\n星遥将公开材料上传到由律师和调查组共同确认的只读站点，只发布时间线、证据类别与尚待核验事项，不发布医疗记录和私人关系。“他们可以慢慢读。”她说，“我们不用为了直播时长重新说错。”\n九个人共同拒绝现场采访。拒绝不是沉默结盟，而是第一次由我们自己决定哪些内容、在什么条件下对外出现。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    flagsOnEnter: {'ch8_evidence_handed_over'},
    next: 'ch8_audit_first_sleep',
  ),
  'ch8_audit_first_sleep': StoryBeat(
    id: 'ch8_audit_first_sleep',
    label: '没有倒计时的第一夜仍然没有人能够立刻入睡',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '医院熄灯后，走廊每隔十五分钟仍会响起推车声。第一次金属轮撞上门框时，九个房间几乎同时按亮呼叫灯。护士逐间确认，没有要求谁为了证明安全而关掉灯。\n我躺在床上数到原本会出现整点广播的时刻。墙上电子钟继续跳过零点，项圈没有提示，门也没有锁。身体却在每个整数分钟前提前绷紧，像恐惧仍保存着一套离线程序。\n凌晨两点，医护问是否需要镇静药。我先询问作用、风险和是否会影响第二天证词，得到完整说明后选择暂时不用。能够问清再拒绝，比强迫自己睡着更接近自由。\n天亮时我只睡了二十七分钟。没有人把这记作恢复失败，早餐也不会因我状态不足被撤回。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_audit_external_contact',
  ),
  'ch8_audit_external_contact': StoryBeat(
    id: 'ch8_audit_external_contact',
    label: '拨给家人的第一通电话没有一份通用台词',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '协调员准备了联系家属的房间，也明确说明可以今天不打。有人在号码接通前哭出声，有人只让警方转达平安，还有人发现失踪期间家属已被主办方发送的假消息分裂成互相怀疑的两组。\n轮到我时，电话另一端先沉默，随后问：“真的是你吗？”我报出只有家里人知道的一件小事，却在对方追问发生了什么时无法从七天里选出一个开头。\n“我活着。”我最后说，“但不是所有人都回来了。我还需要很久才能讲清。”\n这三句话没有完成解释。它们至少没有把创伤剪成一通让亲人放心的电话，也没有要求我用幸存证明自己已经回到失踪前的样子。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch8_audit_survivor_boundaries',
  ),
  'ch8_audit_survivor_boundaries': StoryBeat(
    id: 'ch8_audit_survivor_boundaries',
    label: '九个人为今后的共同联络先写下可以退出的边界',
    speaker: Speaker.yeLan,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '出院前，九个人需要决定是否建立联络渠道。有人希望每天确认平安，有人一看见编号头像就呼吸困难。叶岚提出群组只处理证据移交、失联风险和自愿求助，不承担情感考勤。\n每个人可以匿名阅读、关闭通知或永久退出；退出不会被公布理由。若有人明确发出危险信号，联络人只能联系其预先指定的机构，不能擅自追踪位置或召集所有幸存者上门。\n韩骐要求加入紧急联系人名单，我没有选择他。唐弈要求保存全部消息用于风险分析，也被其他人拒绝。两人的意见仍记录在会议纪要里，却不因专业或能力自动获得权限。\n群组建立时只显示姓名，没有编号。第一条消息不是报数，而是叶岚上传的边界文件，以及一句“阅读后不需要回复”。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_audit_recovery_plan',
  ),
  'ch8_audit_recovery_plan': StoryBeat(
    id: 'ch8_audit_recovery_plan',
    label: '长期恢复计划允许九个人选择完全不同的速度',
    speaker: Speaker.suMi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '医疗团队提供创伤治疗、法律援助、学业与工作复归四类支持。苏弥先想替大家分配优先级，话到一半停下来，把表格一份份交回本人。有人立即预约，有人只保留电话，也有人暂时拒绝谈论。\n林澄要求学校不得公开她的参与者身份；星遥要求技术取证安排不能默认她随叫随到；高原则申请在维修现场之外接受治疗。每项需求都与“合作调查”分开审批。\n我在复归日期一栏写下未知。协调员没有要求估计一个星期，只问是否需要把住房与收入支持延长到下一次评估。\n设施把七天写成封闭实验，仿佛零点以后所有数据都已经完成。真正的离开没有统一截止时间，也没有一条最优恢复路线。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_audit_epilogue_gate',
  ),
  'ch8_audit_epilogue_gate': StoryBeat(
    id: 'ch8_audit_epilogue_gate',
    label: '离开设施以后关系终于不再决定任何人的生死',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '医疗观察结束前，每个人都得到新的衣物、自己的手机和一份长期心理支持说明。联系人栏不再自动填入关系对象，是否拨出第一个号码由本人决定。\n出口已经在身后。接下来的靠近、疏远、作证和等待都不会触发项圈，也不会被系统计入结局条件。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_route_locked_xingyao': 'ch8_xingyao_epilogue_1',
      'ch6_route_locked_sumi': 'ch8_sumi_epilogue_1',
      'ch6_route_locked_lincheng': 'ch8_lincheng_epilogue_1',
      'ch6_route_locked_public': 'ch8_public_epilogue_1',
    },
    next: 'ch8_public_epilogue_1',
  ),
  'ch8_public_epilogue_1': StoryBeat(
    id: 'ch8_public_epilogue_1',
    label: '七十二小时后九个人没有被安排成一张幸存者合影',
    speaker: Speaker.yeLan,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '医疗观察的第三天，协调人员询问是否愿意拍摄一张九人合影，用于向家属和公众证明救援结果。叶岚先问用途、保存期限和撤回方式，最后有五人同意，四人拒绝。\n照片没有因此取消。画面里留下五把普通椅子，说明文字只写“部分获救者自愿出镜”，没有用空位暗示另外四人羞于面对公众。\n我们第一次在同一件事上得到不同结果，却不需要把少数人的选择修成一致。共同见证已经完成，生活不必继续模拟四席。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_public_epilogue_2',
  ),
  'ch8_public_epilogue_2': StoryBeat(
    id: 'ch8_public_epilogue_2',
    label: '公开听证把一周经历拆回可追问的具体决定',
    speaker: Speaker.shenYan,
    scene: SceneKey.hearingRoom,
    text:
        '两个月后，第一次公开听证举行。顾闻川仍未归案，项目承包商否认了解项圈用途，设备供应商则把爆炸模块称为未经授权的改装。完整审批压痕使三份声明无法同时成立。\n九个人没有坐在同一排。有人通过视频作证，有人只提交书面材料，唐弈、陈默与韩骐的律师分别回应对具体行为的调查。幸存者不是天然的同一阵营，责任也没有因共同受害而停止区分。\n轮到我时，我没有讲如何赢下游戏，只解释一扇门怎样经过三层决定保持关闭。听证席第一次把问题从“谁按按钮”改成“谁设计按钮只能这样工作”。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_public_epilogue_3',
  ),
  'ch8_public_epilogue_3': StoryBeat(
    id: 'ch8_public_epilogue_3',
    label: '纪念会允许家属拒绝接受幸存者的解释',
    speaker: Speaker.suMi,
    scene: SceneKey.memorialWall,
    portraitMood: 'epilogue',
    text:
        '吴峥与周叙的家属分别举行纪念会。我们没有集体出现，只由家属选择愿意见的人。吴峥的姐姐收下急救记录，没有说原谅；周叙的父亲看完速写本，要求暂时不公开最后一页。\n苏弥在会场外坐了很久。“救治过程写得再完整，也不能要求家属用理解换我们好受。”\n我们把两个名字保留在公开时间线上，同时尊重家属对私人物品的决定。见证能够对抗删除，不能成为侵入悲伤的新理由。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch8_public_epilogue_4',
  ),
  'ch8_public_epilogue_4': StoryBeat(
    id: 'ch8_public_epilogue_4',
    label: '幸存者联络群没有变成必须维持的临时家庭',
    speaker: Speaker.liXingyao,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '最初每晚九点，群里都会进行一次报平安。半个月后，星遥提出取消固定点名，只保留任何人可以主动发起的求助。没有回应不再触发追踪，也不会被解释为退出共同体。\n群消息逐渐变少。有人分享复诊结果，有人询问证据进度，也有人连续数周不出现。我们不再用高频联系证明七天里的合作真实。\n一年后，群名从“ZERO获救人员”改为“零点协议证据联络”。它仍然存在，只承担仍然需要共同完成的事。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_public_ordinary_lives',
  ),
  'ch8_public_ordinary_lives': StoryBeat(
    id: 'ch8_public_ordinary_lives',
    label: '公开作证之外九个人仍要处理不适合写进案件的日常',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    text:
        '案件时间线持续更新，生活却没有按听证日期排列。林澄为补考发愁，星遥因地铁广播错过三站，苏弥第一次请完整年假，高原则在听见电动门闭合时无法继续工作。它们都不构成新的证据，却同样属于七天留下的后果。\n幸存者援助基金最初只报销身体伤害。九个人分别提交意见，要求把停学、转岗、法律陪同与家属治疗纳入。申请没有使用“足够严重”的统一评分，而由本人说明哪些功能受到影响。\n唐弈的申请也被受理。他同时面对行为调查和创伤治疗，两者没有互相取消。惩罚不能代替治疗，受到胁迫也不能让主动伤害消失。\n公开路线没有把人分成纯粹受害者与纯粹加害者。它要求制度承受这种不方便的并存，而不是把复杂重新压成一张适合报道的阵营图。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_public_epilogue_5',
  ),
  'ch8_public_epilogue_5': StoryBeat(
    id: 'ch8_public_epilogue_5',
    label: '案件尚未全部结束但我们的叙述不再由倒计时决定',
    speaker: Speaker.narration,
    scene: SceneKey.hearingRoom,
    cgId: 'cg_ch8_public_after',
    cgFrame: 0,
    text:
        '顾闻川在海外转机时被捕，诉讼仍可能持续数年。ZERO镜像成为自动决策责任案件的重要证物，参与者的具体行为则依照各自证据分别处理，没有一条“游戏规则”被法院当作合法契约。\n公开听证中，我用三层结构说明一扇门如何被保持关闭。星遥、苏弥和调查员分别从技术、身体后果与设计批准提出补充，没有人被要求坐成统一的幸存者席。\n听证结束时，法官没有宣布一个能概括全部责任的单一凶手。案件终于开始按证据分层，而不是按终端要求压成一句相容答案。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_public_epilogue_6',
  ),
  'ch8_public_epilogue_6': StoryBeat(
    id: 'ch8_public_epilogue_6',
    label: '证物展保留共同证词也保留各自离开的方向',
    speaker: Speaker.narration,
    scene: SceneKey.hearingRoom,
    cgId: 'cg_ch8_public_after',
    cgFrame: 1,
    text:
        '集合厅白板最终进入证物展。林澄要求展签写下十二个姓名，包括从未作为真人存在的12号槽位，并明确标注它是主办方制造的身份工具，不能替代任何死者。\n断电项圈排列在玻璃柜中。星遥停下来检查说明是否混淆系统与协议，苏弥确认没有公开医疗隐私，其他人则依自己的意愿参观、回避或提前离开。\n我们没有在出口合影。有人去赶下一场复诊，有人留下回答研究者的问题。共同证词完成以后，彼此仍然拥有不同方向。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_public_result',
  ),
  'ch8_public_result': StoryBeat(
    id: 'ch8_public_result',
    label: '真相允许分歧继续存在',
    speaker: Speaker.narration,
    scene: SceneKey.hearingRoom,
    phase: StoryPhase.ending,
    endingId: 'ending_zero_protocol',
    text:
        '九个人保留各自证词，在不同材料与不同立场中独立确认零点协议的三层责任。项圈失去裁定权，证据与差异一同离开设施。\n真相没有把幸存者变成永远一致的共同体，也没有用幕后黑手替所有直接行为免责。它只是让每个人终于能在没有倒计时的世界里继续说、拒绝、修正和追问。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: null,
  ),
  'ch8_xingyao_epilogue_1': StoryBeat(
    id: 'ch8_xingyao_epilogue_1',
    label: '星遥在医疗观察室里第一次主动关闭所有频道',
    speaker: Speaker.liXingyao,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '离开设施后的第一晚，星遥把手机、耳机和医院呼叫器全部放进金属抽屉。设备断开的一瞬，她肩膀明显绷紧，却没有立刻重新连接。\n“我想试试不知道所有人在哪里。”她坐在床边说，“十分钟。如果我反悔，也不算失败。”\n我留在门外，没有用敲门证明自己还在。十分钟后，她亲手打开抽屉，又把门拉开一条缝：“实验结果，安静很难受，但不会死人。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.liXingyao],
    next: 'ch8_xingyao_epilogue_2',
  ),
  'ch8_xingyao_epilogue_2': StoryBeat(
    id: 'ch8_xingyao_epilogue_2',
    label: '我们把固定报平安改成可以不回答的邀请',
    speaker: Speaker.shenYan,
    scene: SceneKey.debriefRoom,
    text:
        '最初一个月，我们每天晚上交换一条不含定位的信息。后来她漏回一次，第二天凌晨才发现。我也曾看见消息后选择睡完午觉再答。\n没有一次延迟被计算成背叛。我们约定只有明确写下“需要帮助”时，另一人才启动联系医院、律师或共同朋友的流程；普通沉默不再自动升级。\n关系因此少了实时证明，却多出真正可以期待的回应。我开始知道她喜欢在雨天听旧广播，她也知道我偶尔只是没有话说。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_xingyao_signal_trigger',
  ),
  'ch8_xingyao_signal_trigger': StoryBeat(
    id: 'ch8_xingyao_signal_trigger',
    label: '一段普通故障广播让旧频道重新压过现实',
    speaker: Speaker.liXingyao,
    scene: SceneKey.metroStation,
    portraitMood: 'epilogue',
    text:
        '第三个月，地铁因信号故障停在隧道里。广播重复“请保持原位等待指令”，星遥立刻打开手机频谱，试图寻找车门控制和备用通信。乘客的抱怨声逐渐消失，她只听得见设施里的管理员。\n她没有给我发定位，而是按治疗师写下的步骤确认日期、车厢编号和身边三个普通物件。做到最后一项时，她看见有人提着会漏水的菜袋，才重新听见现实里的声音。\n列车恢复后，她在下一站下车，明确发来“需要陪伴，但不要追踪”。我问她想通话还是见面，她选择在有工作人员的站厅等。\n我们坐了四十分钟。她没有修好那段信号，也没有因独自完成前半套步骤失去向我求助的资格。依赖与自主终于不再被迫选一个。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_xingyao_epilogue_3',
  ),
  'ch8_xingyao_epilogue_3': StoryBeat(
    id: 'ch8_xingyao_epilogue_3',
    label: '法庭上的技术说明没有把她重新变成02号',
    speaker: Speaker.liXingyao,
    scene: SceneKey.hearingRoom,
    portraitMood: 'epilogue',
    text:
        '半年后的证据听证中，辩方反复称她为“02号技术参与者”，试图让节点分析听起来像游戏内部意见。星遥停下回答，要求记录员使用她的姓名，并说明自己是在受到生命威胁时完成取证。\n她解释ZERO如何跨三节点迁移，也明确指出技术能力不使她同意被绑架。屏幕上的拓扑图第一次在没有倒计时的房间里接受公开质询。\n走出法庭时她摘下耳机，手仍在抖。我没有说“你做得很好”结束它，只问她接下来想去安静的地方，还是想让街道声音把法庭盖过去。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_xingyao_epilogue_4',
  ),
  'ch8_xingyao_epilogue_4': StoryBeat(
    id: 'ch8_xingyao_epilogue_4',
    label: '一段没有任务目标的广播成为新的约会',
    speaker: Speaker.liXingyao,
    scene: SceneKey.broadcastTower,
    portraitMood: 'epilogue',
    cgId: 'cg_ch8_xingyao_after',
    cgFrame: 0,
    text:
        '她选了河边一座仍在使用的旧广播塔。值班员允许我们在关闭的观景层听城市频段，耳机里混着出租车调度、天气播报和深夜点歌，没有任何一条要求我们去开门或救人。\n星遥把左侧耳机递给我。我们肩并肩坐在窗前，她忽然问：“沈砚，你现在还留在这个频道，是因为协议，还是因为我？”\n“因为你。”我回答，“但你可以随时关掉。”她低头笑了一下，没有关。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.shenYan],
    next: 'ch8_xingyao_epilogue_5',
  ),
  'ch8_xingyao_epilogue_5': StoryBeat(
    id: 'ch8_xingyao_epilogue_5',
    label: '告白没有被包装成设施中早已注定的结果',
    speaker: Speaker.liXingyao,
    scene: SceneKey.broadcastTower,
    portraitMood: 'epilogue',
    text:
        '“我分不清里面那些靠近有多少是恐惧。”她慢慢说，“所以我等到现在。没有项圈、没有共同撤离、你也不需要我修设备的时候，我还是想见你。”\n我告诉她，我也无法把七天里的感情剥离干净。但此刻的选择发生在可以回家、可以不回答、也可以喜欢别人的世界里。\n她向我伸出手，不是急救，也不是拉我离开危险区。我握住以后，她问能不能再靠近一点。',
    passageSpeakers: [Speaker.liXingyao, Speaker.narration, Speaker.narration],
    next: 'ch8_xingyao_epilogue_6',
  ),
  'ch8_xingyao_epilogue_6': StoryBeat(
    id: 'ch8_xingyao_epilogue_6',
    label: '第一次亲吻前她仍然等到清楚的回答',
    speaker: Speaker.shenYan,
    scene: SceneKey.broadcastTower,
    cgId: 'cg_ch8_xingyao_after',
    cgFrame: 1,
    text:
        '城市灯光从玻璃上掠过，她的额头轻轻碰到我的额头。“这样可以吗？”\n我说可以，也问她是否愿意。她点头，我们在只剩普通广播底噪的观景层接吻。没有倒计时替这个动作增加意义，也没有系统记录它完成了哪一项条件。\n分开后，她仍握着我的手，耳机滑到两人之间。频道里有人点了一首我们都没听过的歌，于是我们安静地听完。',
    passageSpeakers: [Speaker.liXingyao, Speaker.narration, Speaker.narration],
    next: 'ch8_xingyao_result',
  ),
  'ch8_xingyao_result': StoryBeat(
    id: 'ch8_xingyao_result',
    label: '同一频道允许安静也允许离线',
    speaker: Speaker.narration,
    scene: SceneKey.broadcastTower,
    phase: StoryPhase.ending,
    endingId: 'ending_final_xingyao',
    text:
        '黎星遥与沈砚在彼此可以拒绝、延迟和离开的世界里重新建立联系。信号不再承担生死证明，安静也不再等于失去。\n他们没有忘记零点协议，只是不再让那七天替以后每一次靠近作出决定。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: null,
  ),
  'ch8_sumi_epilogue_1': StoryBeat(
    id: 'ch8_sumi_epilogue_1',
    label: '苏弥在体检表上第一次写下自己的症状',
    speaker: Speaker.suMi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '医院要求每名获救者填写睡眠、疼痛和闪回频率。苏弥先替所有人解释量表，轮到自己时却把“手抖”和“金属声触发”两栏留空。\n我没有替她填写，只把笔推回去。过了很久，她补上真实频率，并在是否需要转介一栏勾选“是”。\n那道勾很轻，却比设施里任何一次准确诊断更难。她不再需要先证明别人都得到照顾，才允许自己成为患者。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_sumi_epilogue_2',
  ),
  'ch8_sumi_epilogue_2': StoryBeat(
    id: 'ch8_sumi_epilogue_2',
    label: '治疗关系之外我们重新学习怎样关心对方',
    speaker: Speaker.suMi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '出院后，我第一次问她有没有吃饭，她立刻反问我的颈部伤口。我们都停住，意识到又把关心变成了交换体检。\n后来约定，一次只回答被问到的人。她可以说没胃口，我可以说今天不想谈噩梦；回答不是获得继续追问的许可。\n几周后，她发来一张烤焦的吐司照片，只写“晚餐失败”。我回了一张同样失败的煎蛋。没有谁需要立刻赶去救谁。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_sumi_leave_of_absence',
  ),
  'ch8_sumi_leave_of_absence': StoryBeat(
    id: 'ch8_sumi_leave_of_absence',
    label: '苏弥没有用重新上班证明自己仍然能够救人',
    speaker: Speaker.suMi,
    scene: SceneKey.debriefRoom,
    portraitMood: 'epilogue',
    text:
        '原单位提出让她先回门诊，理由是熟悉的医疗环境有助于恢复。第一次试岗中，治疗盘里一枚金属卡扣落地，她在病人面前僵住，直到同事接手。下班后，她准备把过程写成一次可忽略的疲劳。\n心理医生问，如果出现同样症状的是她的病人，她会不会要求对方继续值班。苏弥沉默，随后申请延长休假和分阶段复岗。\n她担心同事因此认为她不再可靠。我提醒她，在设施里正是所有人都默认她永远可靠，才让她没有位置报告自己的伤。\n一个月后，她只承担有第二名医生在场的短班，也允许自己在触发前退出。救人的能力没有因需要保护而消失，职业也不必成为拒绝脆弱的终身条件。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch8_sumi_epilogue_3',
  ),
  'ch8_sumi_epilogue_3': StoryBeat(
    id: 'ch8_sumi_epilogue_3',
    label: '急救记录在听证会上接受不带罪责的复核',
    speaker: Speaker.suMi,
    scene: SceneKey.hearingRoom,
    portraitMood: 'epilogue',
    text:
        '法医听证逐分钟复核吴峥死亡后的急救。对方律师问，如果她更早判断项圈结构，是否可能避免爆炸。苏弥回答，未经图纸拆解正在工作的爆炸装置会增加死亡风险，而真正应回答为何装置存在的人是设计和批准者。\n她没有声称每个动作完美，也没有接受“医生在场所以死亡本可避免”的偷换。记录显示她在可用条件下持续救治，系统则拒绝提供解除权限。\n离开时，她在洗手间吐了很久。出来后没有说没事，只问我能不能陪她坐到手抖停下。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_sumi_epilogue_4',
  ),
  'ch8_sumi_epilogue_4': StoryBeat(
    id: 'ch8_sumi_epilogue_4',
    label: '纪念日的拥抱先从询问开始',
    speaker: Speaker.shenYan,
    scene: SceneKey.memorialWall,
    cgId: 'cg_ch8_sumi_after',
    cgFrame: 0,
    text:
        '一年后的纪念日，我们把一束白花放在吴峥家属指定的公共纪念墙前。苏弥念完记录，没有把花摆成医院里整齐的角度。\n她的呼吸逐渐变浅。我问能不能抱她，她先摇头，过了一会儿才主动靠近。改变主意不需要道歉，拒绝也没有让关心失效。\n我们在墙前站了很久。她没有停止哭，我也没有要求拥抱必须让她好起来。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_sumi_epilogue_5',
  ),
  'ch8_sumi_epilogue_5': StoryBeat(
    id: 'ch8_sumi_epilogue_5',
    label: '她问我是否只是在继续履行互相照顾',
    speaker: Speaker.suMi,
    scene: SceneKey.memorialWall,
    portraitMood: 'epilogue',
    text:
        '离开纪念墙后，苏弥在街角停下。“沈砚，你陪我复诊、听证、过纪念日，是因为觉得欠我，还是因为喜欢我？”\n我承认最初分不清。可这一年里，她拒绝过我的陪同，我也拒绝过她的检查；每次拒绝之后，我们仍会在不需要救命的日子里想见对方。\n“所以现在是喜欢。”我说，“不需要用照顾来偿还。”她低头揉了揉已经没有项圈的颈侧，眼里终于有一点放松的笑意。',
    passageSpeakers: [Speaker.suMi, Speaker.narration, Speaker.shenYan],
    next: 'ch8_sumi_epilogue_6',
  ),
  'ch8_sumi_epilogue_6': StoryBeat(
    id: 'ch8_sumi_epilogue_6',
    label: '亲密不再以谁更需要被救为前提',
    speaker: Speaker.suMi,
    scene: SceneKey.debriefRoom,
    cgId: 'cg_ch8_sumi_after',
    cgFrame: 1,
    text:
        '她牵住我的袖口，问：“那我现在可以亲你吗？”\n我回答可以。她靠近时仍带着消毒皂的淡味，吻很短，结束后我们都没有立即检查对方的呼吸和脉搏。她笑起来，这次不是为了让病人安心。\n回程的地铁里，她靠着我的肩睡着。我没有替她决定下车地点，只在到站前轻声叫醒她，再问今晚是想一起吃饭，还是各自回家。',
    passageSpeakers: [Speaker.suMi, Speaker.narration, Speaker.narration],
    next: 'ch8_sumi_result',
  ),
  'ch8_sumi_result': StoryBeat(
    id: 'ch8_sumi_result',
    label: '照顾可以抵达彼此也可以停下来',
    speaker: Speaker.narration,
    scene: SceneKey.debriefRoom,
    phase: StoryPhase.ending,
    endingId: 'ending_final_sumi',
    text:
        '苏弥不再用照顾所有人换取自己休息的资格，沈砚也不再把陪伴当作需要偿还的急救。\n两个人保留求助、拒绝和改变主意的权利。脉搏继续跳动，却不再是衡量关系是否有效的仪器。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: null,
  ),
  'ch8_lincheng_epilogue_1': StoryBeat(
    id: 'ch8_lincheng_epilogue_1',
    label: '林澄回到学校后的第一张地图只标普通教室',
    speaker: Speaker.linCheng,
    scene: SceneKey.schoolClassroom,
    portraitMood: 'epilogue',
    text:
        '复学第一周，林澄把教学楼画成新的分区图：教室、保健室、楼梯、可以独处的天台入口。她没有标安全等级，只在容易触发闪回的广播室旁画了一枚小三角。\n班主任建议她暂时不用参加集会，她接受了，也要求保留随时重新选择的权利。缺席不是失败，参加也不再需要证明已经康复。\n她把地图照片发给我，末尾写：“这里每条路都能回头。暂时还不习惯，但挺好。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.linCheng],
    next: 'ch8_lincheng_epilogue_2',
  ),
  'ch8_lincheng_epilogue_2': StoryBeat(
    id: 'ch8_lincheng_epilogue_2',
    label: '我们的联系不再需要把她当作必须被保护的学生',
    speaker: Speaker.linCheng,
    scene: SceneKey.schoolClassroom,
    portraitMood: 'epilogue',
    text:
        '我曾在她晚归时连续发了三条询问。林澄第二天明确告诉我，那让她重新想起位置共享和保护托管。她已经向家人说明行程，不需要我追加一层监视。\n我道歉并停止。她没有因为指出边界而失去联系，几天后仍把志愿表发来，只问我是否愿意听她比较两个专业。\n她需要的不是一个永远替她选安全路线的人，而是一个相信她能评估风险、也能在需要时主动求助的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_lincheng_exam_day',
  ),
  'ch8_lincheng_exam_day': StoryBeat(
    id: 'ch8_lincheng_exam_day',
    label: '考试倒计时第一次只决定一张试卷是否完成',
    speaker: Speaker.linCheng,
    scene: SceneKey.schoolClassroom,
    portraitMood: 'epilogue',
    text:
        '复学后的第一次模拟考试，墙上电子钟进入最后七分钟。林澄的项圈旧伤开始发痒，监考老师走过金属探测门的声音让她无法读完题目。学校预案允许她离场并在单独考场补时。\n她举手时仍担心其他人会觉得特殊照顾不公平。走到门外以后，她对心理老师说自己想继续，但需要拿掉教室里的倒计时投影。要求被接受，剩余时间改由老师每十五分钟口头提醒一次。\n试卷最终没有做完两题。她把分数拍给我，下面写：“不是满分，也不是逃跑。”\n我只回了一句“收到”。没有分析正确率，也没有把她坚持到最后称作胜利。那天她自己决定去吃一份甜点，庆祝的不是成绩，而是中止、调整和继续都没有让任何门锁上。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch8_lincheng_epilogue_3',
  ),
  'ch8_lincheng_epilogue_3': StoryBeat(
    id: 'ch8_lincheng_epilogue_3',
    label: '她以本人姓名提交未成年人保护制度建议',
    speaker: Speaker.linCheng,
    scene: SceneKey.hearingRoom,
    portraitMood: 'epilogue',
    text:
        '公开听证允许匿名提交意见，林澄却决定使用姓名。她指出项目方利用年龄与“保护对象”标签，让成年人替年轻参与者做决定，再把服从包装成安全。\n发言前她反复练习，站上台仍忘了一行。她停下来翻页，没有向台下寻找我的口型。完整说完后，她要求记录同时保留停顿，不剪成一段毫无恐惧的励志视频。\n媒体想称她为“勇敢少女”，她拒绝采访标题，只同意刊登制度建议全文。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_lincheng_epilogue_4',
  ),
  'ch8_lincheng_epilogue_4': StoryBeat(
    id: 'ch8_lincheng_epilogue_4',
    label: '毕业典礼终于只是一次会迟到的普通约定',
    speaker: Speaker.linCheng,
    scene: SceneKey.schoolClassroom,
    portraitMood: 'epilogue',
    cgId: 'cg_ch8_lincheng_after',
    cgFrame: 0,
    text:
        '一年多后，林澄完成毕业考试，也已经成年。典礼那天我因为证据听证晚到十二分钟，手机里没有任何倒计时，只有她发来的座位排号和一句“结束后在旧体育馆门口等你”。\n我赶到时，她已经脱下学士式的纪念披肩，双马尾换成了更简洁的发束。看见我，她先抱怨错过了合照，再把一张重新画过的校园地图塞进我手里。\n地图出口没有红线，只有校门外两家餐馆。她问我想去哪一家，也明确说这次由我们各投一票。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.linCheng],
    next: 'ch8_lincheng_epilogue_5',
  ),
  'ch8_lincheng_epilogue_5': StoryBeat(
    id: 'ch8_lincheng_epilogue_5',
    label: '喜欢不再与同行条款共用一个答案',
    speaker: Speaker.linCheng,
    scene: SceneKey.riversideEvening,
    portraitMood: 'epilogue',
    text:
        '晚餐后，她带我走到地图上没有标注的一段河堤。“以前问你会不会来毕业典礼，有一半是在确认我们能不能一起活到那天。”\n她看着路灯下自己的影子，继续说：“现在已经到了。我还是想问另一件事。我喜欢你，不是因为你是01，也不是因为你答应保护我。你呢？”\n我告诉她，我喜欢的是会害怕、会反驳、会把路线重新画一遍，也会在不需要我时清楚说出来的林澄。',
    passageSpeakers: [Speaker.linCheng, Speaker.linCheng, Speaker.shenYan],
    next: 'ch8_lincheng_epilogue_6',
  ),
  'ch8_lincheng_epilogue_6': StoryBeat(
    id: 'ch8_lincheng_epilogue_6',
    label: '靠近以前两个人仍然把问题和回答说完整',
    speaker: Speaker.linCheng,
    scene: SceneKey.riversideEvening,
    cgId: 'cg_ch8_lincheng_after',
    cgFrame: 1,
    text:
        '她问能不能牵手。我伸出手，让最后一点距离由她自己走完。她的掌心有毕业纪念册留下的油墨，不再是项圈爆炸后冰冷的汗。\n走到河堤转弯处，她停下来，把额头轻轻抵在我额前。近到能听见彼此呼吸时，她仍然问：“这样可以吗？”\n“可以。”我回答，也没有把她的靠近当作下一步的默认许可，“林澄，我可以吻你吗？”\n她睁眼看了我几秒，确认我没有替她催促答案，才清楚地点头：“可以。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.shenYan,
      Speaker.linCheng,
    ],
    next: 'ch8_lincheng_first_kiss',
  ),
  'ch8_lincheng_first_kiss': StoryBeat(
    id: 'ch8_lincheng_first_kiss',
    label: '这一次的吻不需要任何生存条件',
    speaker: Speaker.narration,
    scene: SceneKey.riversideEvening,
    cgId: 'cg_ch8_lincheng_after',
    cgFrame: 2,
    text:
        '我低下头，她也向前走完自己的那一半距离。嘴唇相触时，没有警报、门锁或倒计时替这一刻规定意义，只有河面吹来的晚风和她握住我衣襟的手。\n那个吻很轻，也没有持续太久。分开以后，她先看了看我，像在确认刚才的回答仍然可以被修改。我没有追上去，她却笑着再次牵住我的手。\n这一次没有地图标记终点。我们在路口讨论末班车，各自保留回家的路线，也约定下一次见面的日期。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch8_lincheng_result',
  ),
  'ch8_lincheng_result': StoryBeat(
    id: 'ch8_lincheng_result',
    label: '地图之外仍然可以一起走',
    speaker: Speaker.narration,
    scene: SceneKey.riversideEvening,
    phase: StoryPhase.ending,
    endingId: 'ending_final_lincheng',
    text:
        '林澄以自己的姓名、边界和选择回到生活，也在成年与毕业以后重新确认对沈砚的感情。\n他们可以同行，也可以分别回家。没有一条路线因关系而失效，没有一次拒绝会触发惩罚。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: null,
  ),
};
