part of 'story.dart';

const chapterThreeBeats = <String, StoryBeat>{
  'ch3_chapter_title': StoryBeat(
    id: 'ch3_chapter_title',
    label: '互为人质',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    timelineMinute: 1860,
    text:
        '第二天早晨七点。倒计时还剩一百三十七小时，旧体育馆已经从地图上永久消失。\n我们用一夜建立了见证制度，主办方只用了一个清晨，就给“把权力交给别人”增加了新的按钮。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_second_dawn',
  ),
  'ch3_second_dawn': StoryBeat(
    id: 'ch3_second_dawn',
    label: '没有真正到来的清晨',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '集合厅没有窗，所谓清晨只是灯光由冷白变成略微发黄。墙角的时钟继续走，空气里却仍停着昨夜的卷帘摩擦声。有人靠着墙睡，有人睁着眼假装休息，还有人每隔几分钟摸一次项圈。',
    next: 'ch3_wake_watch',
  ),
  'ch3_wake_watch': StoryBeat(
    id: 'ch3_wake_watch',
    label: '值夜者的手',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我从椅背上抬起头时，掌心还压着昨夜的点名表。纸边被汗浸软，最后一次记录停在六点四十五分：十名真人，十台终端，12号信号位于E-04。\n这张纸没有保证任何人安全。它只证明在我们最疲惫的时候，仍有人愿意把彼此当作需要确认的生命，而不是屏幕上的数量。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_roll_call',
  ),
  'ch3_roll_call': StoryBeat(
    id: 'ch3_roll_call',
    label: '用姓名点名',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚按昨夜约定，用姓名而不是编号点名。\n“沈砚。”\n“在。”\n名字绕过空椅，逐个得到回应。轮到吴峥和周叙时，她没有假装他们仍会回答，只在记录旁写下死亡时间。12号那一栏则保持空白。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch3_breakfast',
  ),
  'ch3_breakfast': StoryBeat(
    id: 'ch3_breakfast',
    label: '第二次共同进食',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '早餐仍是压缩饼干和温水。高原的腿垫在折叠毯上，苏弥先检查脚趾血色，再把他的止痛药掰成两半。\n“今天要重新清点药品和饮水。”她说，“F-01封锁后，去B-03储物区需要绕过档案长廊。一次往返至少多二十二分钟。”\n失去一块区域，最先改变的不是地图颜色，而是每个人必须为一杯水多承担多久的同行风险。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch3_f01_cost',
  ),
  'ch3_f01_cost': StoryBeat(
    id: 'ch3_f01_cost',
    label: '封锁的现实代价',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'injured',
    text:
        '高原把地图拉到面前，用铅笔标出被F-01切断的维修管道。\n“体育馆不只是空房间。备用水泵、两组蓄电池和北侧通风旁路都在里面。主供电要是波动，我们少了能绕开的回路。”\n他说得像在汇报设备故障，手却一直按着固定腿部的夹板。那块黑色区域已经同时拿走了设施冗余和他的行动能力。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch3_empty_chairs',
  ),
  'ch3_empty_chairs': StoryBeat(
    id: 'ch3_empty_chairs',
    label: '两张椅子没有被收走',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '吴峥与周叙坐过的椅子还留在原位。唐弈提议把它们移开，免得每次点名都绕过死人；叶岚却问，是为了方便，还是为了让活着的人少看见一个问题。\n“留下椅子不会让他们回来。”韩骐说。\n“收走也不会让我们变得无辜。”叶岚把两张椅子推到墙边，既不占据行动通道，也没有从名单里抹掉姓名。死亡第一次不再只是广播减少的数字，而成了所有制度必须为之保留的位置。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.yeLan],
    next: 'ch3_lincheng_morning',
  ),
  'ch3_lincheng_morning': StoryBeat(
    id: 'ch3_lincheng_morning',
    label: '没有校铃的星期几',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'anxious',
    text:
        '林澄把饼干掰成四块，按学校课间的习惯一小口一小口地吃。她忽然问今天是星期几，问完又自己算出原本该有一场数学周测。\n“我以前最想逃掉那场考试。”她盯着包装袋上的生产日期，“现在如果有人告诉我，写完卷子就能回教室，我会把最后一道题也检查三遍。”\n苏弥没有说“会回去的”。她只把温水推近一些，告诉林澄，能想起具体的日常不是软弱，而是在提醒自己被夺走的生活到底是什么。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch3_chenmo_morning',
  ),
  'ch3_chenmo_morning': StoryBeat(
    id: 'ch3_chenmo_morning',
    label: '迟到二十秒的人没有睡',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'guarded',
    text:
        '陈默整夜没有离开公共视线。他把西侧配电路线重新画了七遍，每一版都标出自己在第一案警报后可能迟到的原因。\n“你不需要靠熬夜证明清白。”我说。\n“可我也不能要求你们忘掉那二十秒。”他揉着发红的眼角，“这里最便宜的谎言，是让别人先停止追问。至少在找到能重复验证的答案前，怀疑我比原谅我诚实。”\n他说得过于冷静，像已经习惯让自己成为一个待排除的选项。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch3_hanqi_watch',
  ),
  'ch3_hanqi_watch': StoryBeat(
    id: 'ch3_hanqi_watch',
    label: '04号守在01旁边',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '韩骐坐在离我不到两米的位置，背靠唯一能看清所有出口的墙。他没有碰我的终端，却会在任何人靠近时先抬眼。\n昨夜救援前，他说01号不能落在队尾。现在危险已经过去，他仍旧没有换位置。保护与监视之间没有清楚的边界，尤其当被保护的人无法离开保护者视线时。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_update_chime',
  ),
  'ch3_update_chime': StoryBeat(
    id: 'ch3_update_chime',
    label: '十台PDA同时更新',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '七点整，十台PDA同时震动。不是警报，而是一声短促、近似门禁通过的提示音。\n屏幕底部多出一个银白色图标：两只相对的手，中间夹着一枚钥匙。图标下方写着四个字——临时托管。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_delegation_announce',
  ),
  'ch3_delegation_announce': StoryBeat(
    id: 'ch3_delegation_announce',
    label: '临时托管协议',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '“第二日功能已开放：参与者可以将PDA操作权限临时托管给另一名有效参与者。”\n“托管不改变初始持有者，不改变两米规则，不转移项圈责任。权限有效期间，受托者的操作将视为持有者授权。”\n广播最后一句说得尤其缓慢，仿佛知道我们会把“视为授权”误听成“由本人完成”。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch3_permission_read',
  ),
  'ch3_permission_read': StoryBeat(
    id: 'ch3_permission_read',
    label: '一级：只读',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'discovery',
    text:
        '陈默没有立刻点击。他让所有人把界面停在说明页。\n“一级只读，只能查看公共日志、区域状态和已经公开的记录。不能开门，不能提交确认，也看不到私人条款。”\n这个等级听起来最安全，却仍然意味着别人可以知道你何时去过哪里、在什么时间失去信号。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch3_permission_door',
  ),
  'ch3_permission_door': StoryBeat(
    id: 'ch3_permission_door',
    label: '二级：门禁',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥把二级权限投到主屏。\n“门禁会把受托人的终端变成持有者的远程钥匙。签名经过第二套网络广播，沿途控制器会缓存一份，断线时也能继续用。”\n“缓存多久？”我问。\n她盯着没有标注的有效期：“说明里没写。这就不是细节，是风险。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.shenYan,
      Speaker.liXingyao,
    ],
    next: 'ch3_permission_clause',
  ),
  'ch3_permission_clause': StoryBeat(
    id: 'ch3_permission_clause',
    label: '三级：条款查看',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '三级权限叫“条款协作”。受托者可以查看持有者当前已经解锁的生还条款，并代表对方提交一部分进度证明；尚未解锁的校验字段仍只显示加密状态。\n林澄读到这里，手指压住了自己的屏幕。\n“自愿托管和被逼着公开，系统分得出来吗？”\n没有人回答。她的条款本来就要求一个人自愿成为信赖对象，而现在“自愿”本身也有了可以被转交的界面。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch3_permission_full',
  ),
  'ch3_permission_full': StoryBeat(
    id: 'ch3_permission_full',
    label: '四级：完整控制',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'shaken',
    text:
        '第四级没有委婉名称，只有“完整控制”。受托者可以使用前三项权限，修改托管对象，提交位置证明，并代替持有者确认物资转移。\n唐弈终于把硬币抛了起来。\n“把终端留在自己身边，把能做的事交给别人。主办方甚至替我们解决了交易时最麻烦的抵押问题。”\n硬币落回手背，没人去看正反面。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch3_owner_distance',
  ),
  'ch3_owner_distance': StoryBeat(
    id: 'ch3_owner_distance',
    label: '责任仍留在两米之内',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '苏弥抓住了广播里最危险的一句。\n“权限可以离开两米，死亡责任不行。别人拿你的授权去开门、交物资、提交位置，出错后项圈惩罚的仍可能是你。”\n托管没有把人从终端旁边解放出来。它只让一个人能够在远处替你制造后果，而你必须留在原地承担。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch3_first_reactions',
  ),
  'ch3_first_reactions': StoryBeat(
    id: 'ch3_first_reactions',
    label: '便利与恐惧同时出现',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    text:
        '“我现在走不到设备间。”高原拍了拍夹板，“只读日志要是能交给陈默，至少不用让维修判断跟着这条腿停在这里。”\n“急救时也可以由别人开药柜。”苏弥随即补了一句，“但只能开指定层，不能把整个医疗权限一起交出去。”\n林澄看向撤销说明：“如果持有者昏迷呢？受托的人会自动失去权限，还是可以一直替他决定？”\n同一个功能在三个人口中分别像行动辅助、救援工具和一份把责任签给别人的空白文件。',
    passageSpeakers: [
      Speaker.gaoYuan,
      Speaker.suMi,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch3_sumi_revocation',
  ),
  'ch3_sumi_revocation': StoryBeat(
    id: 'ch3_sumi_revocation',
    label: '必须能够撤销',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '“任何托管都必须有明确结束时间，而且持有者随时可以撤销。”苏弥说。\n韩骐指出，持有者如果受伤、失去意识或被隔在门后，这条原则会让救援权限一起消失。\n“那就设计紧急撤销，不是取消撤销。”她没有退让，“不能因为人可能失去意识，就默认别人可以永久替他决定。”',
    passageSpeakers: [Speaker.suMi, Speaker.hanQi, Speaker.suMi],
    next: 'ch3_yelan_witness',
  ),
  'ch3_yelan_witness': StoryBeat(
    id: 'ch3_yelan_witness',
    label: '见证人不是装饰',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚提出，每次托管至少由一名不参与交易的人记录权限、开始时间和结束时间。\n“见证不是证明两个人都善良。”她说，“是为了在事后区分：持有者同意了什么，受托者实际做了什么，系统又把什么写成了同一件事。”\n这是昨夜三方点名制度的延伸，也意味着每次合作都会多一个知道秘密的人。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch3_tang_market',
  ),
  'ch3_tang_market': StoryBeat(
    id: 'ch3_tang_market',
    label: '条款交换市场',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    text:
        '唐弈不反对见证，却给出了完全不同的用途。\n“既然权限可以拆分，就按价值交换。门禁换路线，条款查看换药品，完整控制换一次救援承诺。写清楚，比所有人嘴上说无偿合作诚实。”\n苏弥问他，急救时谁来判断一个人的门禁值几支药。\n“掌握药的人。”唐弈回答，“权力一直存在，定价至少让它被看见。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.suMi,
      Speaker.tangYi,
    ],
    next: 'ch3_hanqi_clause_prompt',
  ),
  'ch3_hanqi_clause_prompt': StoryBeat(
    id: 'ch3_hanqi_clause_prompt',
    label: '韩骐迟迟没有发言',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '争论持续了十分钟，韩骐却一次也没有评价完整控制。他只看着我的01终端，拇指反复压过救援手套的缝线。\n第一天公开条款时，他只说过自己需要在游戏结束时持有某件东西。现在“持有”和“控制”被系统拆成了两个选项，他的沉默终于有了清楚的形状。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_hanqi_clause_reveal',
  ),
  'ch3_hanqi_clause_reveal': StoryBeat(
    id: 'ch3_hanqi_clause_reveal',
    label: '04号公开主条件',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '韩骐站起，将04号屏幕转向所有人。\n“我的公开主条件：游戏结束时，必须由我持有01号初始终端。不是权限，不是托管，是实体设备。下面的校验字段仍然加密。”\n他没有缩小文字，也没有替条件找借口。屏幕的冷光照在他手背旧伤上，让那双曾经抬起卷帘门的手第一次像明确的威胁。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch3_hanqi_asks_terminal',
  ),
  'ch3_hanqi_asks_terminal': StoryBeat(
    id: 'ch3_hanqi_asks_terminal',
    label: '现在交给我',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '“沈砚，把01交给我保管。”\n他在我回答前补充：“你仍留在两米内，所有操作都由你确认。我的条款不要求你死，也不要求我夺走你的身份。现在交接，比最后一天互相抢安全。”\n这是一份可以执行的合作方案，也是一份要求我从第二天开始就把生还钥匙放进别人掌心的长期控制。',
    passageSpeakers: [Speaker.hanQi, Speaker.hanQi, Speaker.narration],
    next: 'ch3_xingyao_challenge',
  ),
  'ch3_xingyao_challenge': StoryBeat(
    id: 'ch3_xingyao_challenge',
    label: '保护与占有',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥挡住了他伸出的手。\n“我的条件要求01存活，所以我也有理由说自己是在保护他。难道我们要按谁的条款更像好意，决定谁可以控制01？”\n韩骐没有提高声音：“区别是我把目的公开了。”\n“公开目的能让风险可见，不能让风险自动合理。”她回答。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.hanQi,
      Speaker.liXingyao,
    ],
    next: 'ch3_protection_control',
  ),
  'ch3_protection_control': StoryBeat(
    id: 'ch3_protection_control',
    label: '互为人质',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '如果我把终端交给韩骐，他的生还依赖我继续活着，我的行动也依赖他愿意归还。我们会因此更难背叛彼此，也更难离开彼此。\n这不是信任，而是把两个人的风险拴在同一件物品上。人质关系最稳定的地方，恰恰在于双方都能伤害对方。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_trial_proposal',
  ),
  'ch3_trial_proposal': StoryBeat(
    id: 'ch3_trial_proposal',
    label: '先进行一次有限试验',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚把争论拉回可以验证的范围。\n“先不决定长期保管。我们用01做一次二十分钟托管试验，只允许受托人完成B-03物资审计。选择一个托管人、一个见证人，并明确权限等级。”\n如果连一次短期授权都无法被复查，就没有讨论七天控制权的必要。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch3_trial_scope',
  ),
  'ch3_trial_scope': StoryBeat(
    id: 'ch3_trial_scope',
    label: '试验边界',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我们把试验目标写在纸上：读取B-03库存清单、确认门禁状态、不得移动物资、不得转托管。开始和结束时都由见证人报时。\nPDA界面要求我亲自选择权限、托管人与见证人。每一个选项都像普通设置，后面却站着一个会因此更接近我条款、终端或行动记录的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_delegation_gate',
  ),
  'ch3_delegation_gate': StoryBeat(
    id: 'ch3_delegation_gate',
    label: '设置临时托管',
    text: '',
    scene: SceneKey.assemblyHall,
    phase: StoryPhase.delegation,
    next: 'ch3_delegate_hanqi',
  ),
  'ch3_delegate_hanqi': StoryBeat(
    id: 'ch3_delegate_hanqi',
    label: '把试验交给韩骐',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '韩骐接下托管时没有碰01，只让自己的04终端显示授权状态。\n“我会按纸面目标做，不碰物资，不转交权限。”\n他答应得像执行救援命令。越是如此，我越清楚，习惯让别人服从可执行命令的人，也最容易把控制理解成责任。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch3_delegate_hanqi_detail',
  ),
  'ch3_delegate_hanqi_detail': StoryBeat(
    id: 'ch3_delegate_hanqi_detail',
    label: '04号的边界动作',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '前往B-03门禁测试点时，韩骐始终走在我能看见的位置。他每次打开界面都先把屏幕朝向见证人，操作完便退出。\n可走到狭窄拐角，他仍本能地把我挡在墙内侧。授权让他的动作更透明，没有改变他替别人决定安全位置的习惯。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_witness_result',
  ),
  'ch3_delegate_tangyi': StoryBeat(
    id: 'ch3_delegate_tangyi',
    label: '把试验交给唐弈',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    text:
        '唐弈看到自己被选中，先问这次托管是否算一笔债。\n“如果我证明交易能够留下完整记录，之后你们至少该承认交换不是背叛的同义词。”\n我没有答应未来，只确认今天的边界。他笑了笑，把硬币收进口袋。第一次没有随机决定接下来按哪个按钮。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch3_delegate_tangyi_detail',
  ),
  'ch3_delegate_tangyi_detail': StoryBeat(
    id: 'ch3_delegate_tangyi_detail',
    label: '把每一步标上价格',
    speaker: Speaker.tangYi,
    scene: SceneKey.corridor,
    text:
        '唐弈在测试记录旁额外写下每项权限能换取什么：只读等于一份地图，门禁等于一次同行，完整控制至少等于救命承诺。\n“我没有说一定要这样交易。”他把纸交给见证人，“但只要有人想交换，就该先知道自己卖掉了什么。”\n这张价格表令人不适，却也让模糊的人情第一次出现了可质疑的单位。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch3_witness_result',
  ),
  'ch3_delegate_chenmo': StoryBeat(
    id: 'ch3_delegate_chenmo',
    label: '把试验交给陈默',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'discovery',
    text:
        '陈默的手指在“接受托管”上停了两秒。\n“我最懂权限，也最不该在没有记录时碰权限。你确定？”\n我确认试验正因为可见才有意义。他接受后立刻导出一份本地摘要，动作熟练得不像第一次见到这套接口，也可能只是他太熟悉相同的设计。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch3_delegate_chenmo_detail',
  ),
  'ch3_delegate_chenmo_detail': StoryBeat(
    id: 'ch3_delegate_chenmo_detail',
    label: '熟悉得令人不安',
    speaker: Speaker.chenMo,
    scene: SceneKey.corridor,
    portraitMood: 'discovery',
    text:
        '陈默没有逐页寻找功能。他从界面边缘向内滑动，直接调出一层未写在说明里的会话编号。\n“很多企业门禁都用类似结构。”他在我们开口前解释，“知道接口习惯，不等于见过这台设备。”\n解释依然合理，也依然来得太快。见证人把他的手势与会话编号一起写进记录。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch3_witness_result',
  ),
  'ch3_witness_result': StoryBeat(
    id: 'ch3_witness_result',
    label: '见证方式',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text: '受托人开始测试后，见证人按自己的方法留下了第一份托管记录。',
    next: null,
    choices: [
      StoryChoice(
        label: '由星遥复核频道时间',
        caption: '比较广播签名、门禁缓存与本地时钟',
        next: 'ch3_xingyao_witness',
        requiresFlag: 'ch3_witness_xingyao',
      ),
      StoryChoice(
        label: '由苏弥记录交接反应',
        caption: '同时记录本人确认与身体状态',
        next: 'ch3_sumi_witness',
        requiresFlag: 'ch3_witness_sumi',
      ),
      StoryChoice(
        label: '由叶岚制作三栏证词',
        caption: '分开记录同意、操作与系统反馈',
        next: 'ch3_yelan_witness_detail',
        requiresFlag: 'ch3_witness_yelan',
      ),
    ],
  ),
  'ch3_xingyao_witness': StoryBeat(
    id: 'ch3_xingyao_witness',
    label: '三只不一致的时钟',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'alarm',
    text:
        '星遥同时记录01本地时钟、受托终端时钟和B-03门禁控制器回报。三者在开始时相差不到零点二秒，撤销后门禁缓存却比01慢了四十二秒。\n“先记下来，不急着叫漏洞。”她说，“时钟偏差、离线队列和恶意延迟都能造成这个结果。我们需要一次真实操作来区分。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch3_permission_result',
  ),
  'ch3_sumi_witness': StoryBeat(
    id: 'ch3_sumi_witness',
    label: '确认不是一个按钮',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'concerned',
    text:
        '苏弥要求我在开始和撤销时分别复述授权范围，并记录脉搏与意识状态。\n“屏幕只会留下‘确认’。”她说，“但一个人可能在疼痛、惊恐或药物影响下按下同一个按钮。是否自愿，不能只由界面替我们判断。”\n她把我的两次复述写在时间旁，使日志第一次包含按键者当时是否能够理解后果。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch3_permission_result',
  ),
  'ch3_yelan_witness_detail': StoryBeat(
    id: 'ch3_yelan_witness_detail',
    label: '同意、操作与反馈',
    speaker: Speaker.yeLan,
    scene: SceneKey.corridor,
    portraitMood: 'intervening',
    text:
        '叶岚把记录纸分成三栏：沈砚同意了什么、受托人做了什么、系统显示什么。\n门禁测试结束后，第一栏写着“只进行库存审计”，第二栏写着“读取清单并请求门状态”，第三栏却把两步合并成“01完成远程审计”。\n“系统已经开始替我们省略主语。”她在那行下面画了一道红线。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.yeLan],
    next: 'ch3_permission_result',
  ),
  'ch3_permission_result': StoryBeat(
    id: 'ch3_permission_result',
    label: '所选权限的代价',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text: '同一场试验因为权限范围不同，留下了不同程度的便利与暴露。',
    next: null,
    choices: [
      StoryChoice(
        label: '只读权限保持了最小暴露',
        caption: '安全，但无法独立验证门禁缓存',
        next: 'ch3_permission_read_result',
        requiresFlag: 'ch3_permission_read',
      ),
      StoryChoice(
        label: '门禁权限留下缓存差异',
        caption: '足以测试区域控制器，也扩大了操作范围',
        next: 'ch3_permission_door_result',
        requiresFlag: 'ch3_permission_door',
      ),
      StoryChoice(
        label: '条款权限暴露了私人条件',
        caption: '见证人知道了更多，却不能操作门禁',
        next: 'ch3_permission_clause_result',
        requiresFlag: 'ch3_permission_clause',
      ),
      StoryChoice(
        label: '完整控制生成了全部审计字段',
        caption: '证据最完整，受托者也拥有最高风险权限',
        next: 'ch3_permission_full_result',
        requiresFlag: 'ch3_permission_full',
      ),
    ],
  ),
  'ch3_permission_read_result': StoryBeat(
    id: 'ch3_permission_read_result',
    label: '看得到却碰不到',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '只读试验顺利结束。受托人看见了B-03库存与门状态，却无法验证门禁是否真的接受远程签名。\n风险被压到最低，未知也被完整保留。安全从来不是免费答案，它有时只是把问题推迟到必须行动的时刻。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_trial_close',
  ),
  'ch3_permission_door_result': StoryBeat(
    id: 'ch3_permission_door_result',
    label: '缓存比撤销慢四十二秒',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'alarm',
    text:
        '门禁权限在受托终端显示撤销后，B-03控制器仍亮了四十二秒绿色。星遥没有让任何人再次开门，只把这段窗口录进离线记录。\n“PDA认为结束，门却还认为有效。”\n四十二秒不够完成一次往返，却足够让已经站在门边的人做一件不该再被授权的事。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch3_trial_close',
  ),
  'ch3_permission_clause_result': StoryBeat(
    id: 'ch3_permission_clause_result',
    label: '秘密一旦被看见',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'determined',
    text:
        '条款查看没有打开B-03门，却让受托人与见证人看见了01的完整条件。撤销之后，文字从他们屏幕上消失，记忆不会。\n林澄低声说：“系统把权限叫临时的，好像知道的事也能按时归还。”\n这次试验没有泄露新条款，因为我的条件已经公开。换成别人，代价不会这么小。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch3_trial_close',
  ),
  'ch3_permission_full_result': StoryBeat(
    id: 'ch3_permission_full_result',
    label: '完整控制的完整风险',
    speaker: Speaker.chenMo,
    scene: SceneKey.corridor,
    portraitMood: 'discovery',
    text:
        '完整控制生成了最详细的操作摘要：读取、门禁请求、位置证明和物资转移入口全部出现。我们没有使用后三项，它们仍在受托终端上保持可用。\n陈默指出，撤销后本地会话编号没有立即清空。\n“权限可能结束了，会话还在等控制器确认。”他说，“这段等待就是别人能塞进操作的地方。”',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.chenMo],
    next: 'ch3_trial_close',
  ),
  'ch3_trial_close': StoryBeat(
    id: 'ch3_trial_close',
    label: '二十分钟试验结束',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '回到集合厅后，叶岚宣布托管结束，01和受托终端都显示“无活动授权”。纸面记录由持有者、受托人和见证人分别签名。\n没有争吵，没有物资移动，也没有谁趁机夺走终端。第一次试验看起来近乎成功。正因为如此，几个人已经开始讨论下一次可以省掉哪些步骤。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_midmorning',
  ),
  'ch3_midmorning': StoryBeat(
    id: 'ch3_midmorning',
    label: '便利开始改变站位',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    text:
        '上午九点，高原先把设备日志的只读权限交给陈默。“只看F-01封锁后的供电波动，二十分钟，到时自动结束。”\n苏弥随后请叶岚接收药柜门禁：“只允许第二层。我要固定高原的腿，不能为了开锁松手。”\n唐弈举起自己的PDA：“我用一段档案区路线权限换今晚的食物，有人谈吗？”\n没人接受完整控制，但集合厅的站位已经改变。所有人都开始计算，自己能在不交出终端的情况下让别人替自己做多少事。',
    passageSpeakers: [
      Speaker.gaoYuan,
      Speaker.suMi,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch3_delegation_rescue',
  ),
  'ch3_delegation_rescue': StoryBeat(
    id: 'ch3_delegation_rescue',
    label: '托管第一次节省了救援时间',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'concerned',
    text:
        '九点零三分，高原换位时夹板突然松脱，断端摩擦让他疼得脸色发白。苏弥双手固定小腿，无法去碰三米外的药柜终端。\n“叶岚，使用刚才的门禁托管。只开第二层，取一支止痛剂。”\n叶岚复述范围，药柜在四秒内打开。过去这件事需要苏弥松开固定、换人按住伤腿，再带着PDA走到门边；现在她的手一次也没有离开高原的膝踝。\n托管确实救下了时间。正因为它有用，我们无法靠禁止按钮解决它带来的全部危险。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch3_delegation_pressure',
  ),
  'ch3_delegation_pressure': StoryBeat(
    id: 'ch3_delegation_pressure',
    label: '便利也能成为压力',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    text:
        '“把档案区门禁托管给我，我替你承担下一轮夜巡。”唐弈把硬币停在指间。林澄拒绝后，他又把条件降成只读路线，语气仍像普通商量。\n“我已经说了不。”林澄把PDA压在桌面。\n唐弈沉默两秒，收回硬币。“那就结束。”\n交易没有发生，却让我们看见另一个问题：当请求可以不断降低权限、提高对价，拒绝的人要说多少次“不”，才不必为合作失败负责？公开价格无法自动消除软性胁迫。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.linCheng,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch3_delegation_audit_gap',
  ),
  'ch3_delegation_audit_gap': StoryBeat(
    id: 'ch3_delegation_audit_gap',
    label: '记录开始追不上使用',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚检查上午的托管表，发现二十三分钟内已经出现五次请求。第一次三个人逐字签名，后面两次只留下开始时间，药柜救援那次甚至在结束后才补写范围。\n“不是谁故意偷懒。”她在缺口旁画圈，“是功能一旦证明方便，手续就会被当成可以稍后补上的东西。”\n“让PDA自动生成记录，至少不会漏时间。”星遥提议。\n陈默摇头：“我们正要验证系统怎么省略主语，不能再让同一套系统独占记录。”\n两人还没争出结果，B-03库存警告已经跳上主屏。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.liXingyao,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch3_b03_alarm',
  ),
  'ch3_b03_alarm': StoryBeat(
    id: 'ch3_b03_alarm',
    label: 'B-03库存异常',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '九点十七分，主屏弹出黄色库存警告。\n“储物区B-03：饮用水减少十二份，止痛剂减少六支，备用滤芯减少两组。物资转移已由参与者01确认。”\n所有人的视线先落到我身上，然后落到刚才接受过01托管的人身上。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch3_shortage_discovery',
  ),
  'ch3_shortage_discovery': StoryBeat(
    id: 'ch3_shortage_discovery',
    label: '清单比货架先说话',
    speaker: Speaker.hanQi,
    scene: SceneKey.storageRoom,
    portraitMood: 'protective',
    text:
        '韩骐带人赶到B-03外，门禁已经重新锁定。透过观察窗能看到最外侧水箱少了一层，药品架上也有两个空位。\n“先封门，谁都别进去。”\n“记录写着01确认。”唐弈没有看受托人，先看向我，“为什么不问沈砚把物资给了谁？”\n韩骐的手停在门把上，最终仍退开一步，让所有人都能看见锁。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch3_no_poison',
  ),
  'ch3_no_poison': StoryBeat(
    id: 'ch3_no_poison',
    label: '先确认现有物资',
    speaker: Speaker.suMi,
    scene: SceneKey.storageRoom,
    portraitMood: 'concerned',
    text:
        '苏弥没有立刻追问失窃者。她要求先封存集合厅已经开封的水和药品，确认是否有人用“缺少”掩护投毒或调包。\n“少十二份水会制造争吵，换掉一份水才会直接杀人。”\n快速检验没有发现异味、破损或药片颜色异常。损失是真实的，但眼前没有急性中毒风险。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch3_owner_signature',
  ),
  'ch3_owner_signature': StoryBeat(
    id: 'ch3_owner_signature',
    label: '01号的电子签名',
    speaker: Speaker.chenMo,
    scene: SceneKey.storageRoom,
    portraitMood: 'discovery',
    text:
        '陈默把库存警告的签名摘要抄到纸上。持有者栏是01，操作类型是“自愿转移”，确认时间九点十六分四十八秒。\n那一分钟我一直在集合厅替高原记录线路，至少六个人能证明。我的PDA也没有显示授权请求。\n“签名是真的。”陈默说，“但‘谁按下’和‘算在谁名下’可能不是同一个字段。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.chenMo],
    next: 'ch3_trustee_suspicion',
  ),
  'ch3_trustee_suspicion': StoryBeat(
    id: 'ch3_trustee_suspicion',
    label: '最短的嫌疑路径',
    speaker: Speaker.tangYi,
    scene: SceneKey.storageRoom,
    text:
        '唐弈把逻辑压缩成最短路径：01没有操作，主办方刚开放托管，今天只有一个人接受过01权限。\n“如果不先问受托人，我们设置见证还有什么意义？”\n他说的是合理问题。危险在于，合理问题只要少问下一句，就会自动长成合理指控。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch3_trustee_accusation',
  ),
  'ch3_trustee_accusation': StoryBeat(
    id: 'ch3_trustee_accusation',
    label: '受托人的回应',
    speaker: Speaker.narration,
    scene: SceneKey.storageRoom,
    text: '接受过01托管的人必须在所有人面前解释试验结束后的终端状态。',
    next: null,
    choices: [
      StoryChoice(
        label: '让韩骐公开04号会话',
        caption: '检查他是否把保护变成了未结束的控制',
        next: 'ch3_hanqi_accused',
        requiresFlag: 'ch3_trustee_hanqi',
      ),
      StoryChoice(
        label: '让唐弈公开06号会话',
        caption: '检查他是否亲自制造了第一笔权限交易',
        next: 'ch3_tangyi_accused',
        requiresFlag: 'ch3_trustee_tangyi',
      ),
      StoryChoice(
        label: '让陈默公开08号会话',
        caption: '检查他熟悉的接口是否留下隐藏操作',
        next: 'ch3_chenmo_accused',
        requiresFlag: 'ch3_trustee_chenmo',
      ),
    ],
  ),
  'ch3_hanqi_accused': StoryBeat(
    id: 'ch3_hanqi_accused',
    label: '04号没有删除记录',
    speaker: Speaker.hanQi,
    scene: SceneKey.storageRoom,
    portraitMood: 'protective',
    text:
        '韩骐把04终端放到地面中央，后退两步。会话结束时间、操作列表和他走过的门都还在。\n“我没有删，也没有转托管。”他说，“试验后我一直在集合厅，想查可以先查我。”\n主动接受检查能降低隐瞒可能，不能证明没有人利用他留下的授权缓存。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch3_yelan_intervenes',
  ),
  'ch3_tangyi_accused': StoryBeat(
    id: 'ch3_tangyi_accused',
    label: '06号保留了价格表',
    speaker: Speaker.tangYi,
    scene: SceneKey.storageRoom,
    text:
        '唐弈交出06终端，也交出那张权限价格表。会话结束后没有新操作，但他承认自己把签名摘要抄了一份。\n“我想知道这种凭证能不能伪造，不代表我已经伪造。”\n“你为什么没说？”叶岚问。\n“因为在没有结果前公开，会让每个人都开始复制。”这个理由和周叙案中被人利用的沉默同样危险。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.tangYi,
    ],
    next: 'ch3_yelan_intervenes',
  ),
  'ch3_chenmo_accused': StoryBeat(
    id: 'ch3_chenmo_accused',
    label: '08号会话编号仍在',
    speaker: Speaker.chenMo,
    scene: SceneKey.storageRoom,
    portraitMood: 'guarded',
    text:
        '陈默导出08号会话摘要。撤销标记存在，底层会话编号却在四十二秒后才收到控制器确认。\n“这就是我刚才说的等待窗口。”他用力咬住已经结痂的指缘，“但知道窗口存在，不等于我能让B-03在九点十六分重新使用它。”\n他提供了最关键的技术事实，也因此显得比任何人都更有能力利用它。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch3_yelan_intervenes',
  ),
  'ch3_yelan_intervenes': StoryBeat(
    id: 'ch3_yelan_intervenes',
    label: '先撤回自动成立的指控',
    speaker: Speaker.yeLan,
    scene: SceneKey.storageRoom,
    portraitMood: 'intervening',
    text:
        '叶岚站到受托人与其他人之间。\n“现在只能证明他的会话可能被使用，不能证明是他使用。见证记录的目的，正是把‘受托人做了什么’和‘系统记在谁名下’拆开。”\n她没有要求大家停止怀疑，只要求怀疑保持原来的尺寸。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch3_competing_hypotheses',
  ),
  'ch3_competing_hypotheses': StoryBeat(
    id: 'ch3_competing_hypotheses',
    label: '三种物资去向',
    speaker: Speaker.shenYan,
    scene: SceneKey.storageRoom,
    text:
        '“先保留三种解释。”我在纸上并列写下编号，“01本人或受托人撒谎；主办方改写清单并预先布置货架；或者有人重放已撤销的授权，让系统把远程操作归到01名下。”\n要区分它们，必须分别确认封条是否真的被打开、物资何时离开货架，以及电子记录在操作前还是操作后生成。',
    passageSpeakers: [Speaker.shenYan, Speaker.narration],
    next: 'ch3_search_assignments',
  ),
  'ch3_search_assignments': StoryBeat(
    id: 'ch3_search_assignments',
    label: '不让嫌疑人单独证明自己',
    speaker: Speaker.hanQi,
    scene: SceneKey.storageRoom,
    portraitMood: 'protective',
    text:
        '韩骐安排四人进入B-03，受托人可以在场，但不得单独碰任何设备。苏弥与叶岚留在门外记录人员和物资，星遥监视授权频道，高原则通过视频判断货架结构。\n“不是为了羞辱谁。”韩骐说，“是为了让最后的结论不需要嫌疑人自己担保。”\n这次他把控制写成了所有人都能检查的分工。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch3_storage_entry',
  ),
  'ch3_storage_entry': StoryBeat(
    id: 'ch3_storage_entry',
    label: '进入B-03',
    speaker: Speaker.narration,
    scene: SceneKey.storageRoom,
    cgId: 'cg_storage',
    text:
        'B-03的门由两把机械钥匙和一组公共门禁同时开启。冷气从缝隙里涌出来，带着纸箱、塑料膜和金属货架混合的干燥气味。\n室内没有打斗痕迹。水箱缺口整齐得像按清单取走，药品柜门重新锁好，墙边审计PDA则停在“所有者已确认”的页面。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_storage_visual',
  ),
  'ch3_storage_visual': StoryBeat(
    id: 'ch3_storage_visual',
    label: '先看见四个普通物件',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.storageRoom,
    portraitMood: 'injured',
    text:
        '视频里的高原要求我们先不要移动任何东西。重新封好的水箱、锁定的审计PDA、出现空位的货架和墙角工具箱都可能有用，也都可能只是正常维护留下的痕迹。\n“先把物件本身收进记录，再决定拿什么检查。”\n调查从四处没有名字的反光开始。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch3_storage_investigation',
  ),
  'ch3_storage_investigation': StoryBeat(
    id: 'ch3_storage_investigation',
    label: 'B-03物资转移',
    text: '',
    scene: SceneKey.storageRoom,
    phase: StoryPhase.investigation,
    next: 'ch3_evidence_layout',
  ),
  'ch3_evidence_layout': StoryBeat(
    id: 'ch3_evidence_layout',
    label: '三条时间线',
    speaker: Speaker.shenYan,
    scene: SceneKey.storageRoom,
    text:
        '调查把同一笔“自愿转移”拆成三条时间线：封条在九点十六分前后被二次热压；货架承重在电子签名前已经减少；门禁控制器则在托管撤销四十二秒后接受了旧会话。\n如果只看最终清单，三件事会被压缩成“01交出物资”。现场却证明，签名是最后出现的东西。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_seal_result',
  ),
  'ch3_seal_result': StoryBeat(
    id: 'ch3_seal_result',
    label: '封条没有被正常撕开',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.storageRoom,
    portraitMood: 'injured',
    cgId: 'cg_storage',
    cgFrame: 1,
    text:
        '紫外检查显示，封条胶层中间有一道连续热痕，边缘纤维却没有正常撕裂。有人用低温加热让封条整片脱离，取物后又压回原位。\n高原通过视频确认工具箱里的便携热封器能够做到。\n“这不是主办方提前摆好的空箱。”他说，“有人在我们进入前真实打开过它。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.gaoYuan],
    next: 'ch3_weight_result',
  ),
  'ch3_weight_result': StoryBeat(
    id: 'ch3_weight_result',
    label: '重量先于签名改变',
    speaker: Speaker.linCheng,
    scene: SceneKey.storageRoom,
    portraitMood: 'determined',
    text:
        '货架弹簧秤的机械指针卡在少了二十六点四公斤的位置，底部压纸留下九点十六分零三秒的撞针印。电子签名生成于四十五秒后。\n林澄把两个时间写在同一条线上。\n“不是先得到同意再拿走。”她说，“是东西已经离开，系统才补出一份像同意的记录。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.linCheng],
    next: 'ch3_log_result',
  ),
  'ch3_log_result': StoryBeat(
    id: 'ch3_log_result',
    label: '撤销后的会话',
    speaker: Speaker.liXingyao,
    scene: SceneKey.storageRoom,
    portraitMood: 'alarm',
    text:
        '离线读取器从审计PDA中恢复了被界面折叠的字段：操作来源不是01本机，而是早晨试验产生的托管会话。控制器收到撤销时没有删除缓存，只标记“等待同步”。\n“有人在四十二秒窗口内复制了会话。”星遥说，“九点十六分又把它送回B-03。系统沿用持有者身份，所以最后只显示01。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao],
    next: 'ch3_witness_crosscheck',
  ),
  'ch3_witness_crosscheck': StoryBeat(
    id: 'ch3_witness_crosscheck',
    label: '见证记录成为反证',
    speaker: Speaker.narration,
    scene: SceneKey.storageRoom,
    text: '早晨留下的见证记录，决定我们能从哪一个角度证明“日志署名不等于本人操作”。',
    next: null,
    choices: [
      StoryChoice(
        label: '用星遥的三时钟记录校准',
        caption: '确认四十二秒不是普通时钟漂移',
        next: 'ch3_xingyao_crosscheck',
        requiresFlag: 'ch3_witness_xingyao',
      ),
      StoryChoice(
        label: '用苏弥的交接状态记录反证',
        caption: '确认01当时没有进行第二次自愿确认',
        next: 'ch3_sumi_crosscheck',
        requiresFlag: 'ch3_witness_sumi',
      ),
      StoryChoice(
        label: '用叶岚的三栏证词拆分主语',
        caption: '比较同意、实际操作与系统反馈',
        next: 'ch3_yelan_crosscheck',
        requiresFlag: 'ch3_witness_yelan',
      ),
    ],
  ),
  'ch3_xingyao_crosscheck': StoryBeat(
    id: 'ch3_xingyao_crosscheck',
    label: '四十二秒不是时钟误差',
    speaker: Speaker.liXingyao,
    scene: SceneKey.storageRoom,
    portraitMood: 'alarm',
    text:
        '星遥将早晨三只时钟的误差上限叠到当前日志上。最大漂移只有零点二秒，四十二秒只能来自控制器保留会话，而非设备走时不同。\n她把校准结果交给受托人确认，没有独占结论。频道证据因此不再只依赖她一句“我听见了”。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_case_question',
  ),
  'ch3_sumi_crosscheck': StoryBeat(
    id: 'ch3_sumi_crosscheck',
    label: '01没有进行第二次确认',
    speaker: Speaker.suMi,
    scene: SceneKey.storageRoom,
    portraitMood: 'concerned',
    text:
        '苏弥的记录显示，早晨撤销时我清醒、能复述范围，并明确说出“结束全部托管”。九点十六分，我正在为高原固定夹板，双手和PDA都在多人视线内。\n电子签名可以继承身份，却无法伪造两次确认之间真实的人体、动作与见证。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_case_question',
  ),
  'ch3_yelan_crosscheck': StoryBeat(
    id: 'ch3_yelan_crosscheck',
    label: '系统省略了真正主语',
    speaker: Speaker.yeLan,
    scene: SceneKey.storageRoom,
    portraitMood: 'intervening',
    text:
        '叶岚把早晨三栏记录与库存日志并排。持有者同意栏在试验结束后没有新内容，实际操作栏出现未知设备，系统反馈栏却再次写成“01完成”。\n“它没有伪造每一个字段。”她说，“它只把不同主语折叠成一个编号，等我们自己把编号当成人。”',
    passageSpeakers: [Speaker.narration, Speaker.yeLan],
    next: 'ch3_case_question',
  ),
  'ch3_case_question': StoryBeat(
    id: 'ch3_case_question',
    label: 'CASE 02：谁拥有一次操作',
    speaker: Speaker.shenYan,
    scene: SceneKey.storageRoom,
    text:
        '现在需要回答的不是“物资最后在谁手里”，而是更基础的问题：B-03为什么把一次发生在撤销后的操作，记成01自愿完成？\n封条、货架和会话日志必须组成同一条因果链。否则任何一个人都可以拿着最终署名，把所有过程省略掉。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_case02_deduction',
  ),
  'ch3_case02_deduction': StoryBeat(
    id: 'ch3_case02_deduction',
    label: '谁拥有一次操作',
    text: '',
    scene: SceneKey.storageRoom,
    phase: StoryPhase.deduction,
    next: 'ch3_case02_resolved',
  ),
  'ch3_case02_owner_error': StoryBeat(
    id: 'ch3_case02_owner_error',
    label: '署名不是动作',
    speaker: Speaker.yeLan,
    scene: SceneKey.storageRoom,
    portraitMood: 'intervening',
    text:
        '我一度把真实电子签名等同于本人确认。叶岚把三栏记录重新推到我面前。\n“签名能证明系统把责任归给01，不能证明沈砚在那个时间做了动作。你正在用需要解释的结果，替代解释本身。”\n我撤回结论。错误没有被系统惩罚，但如果我们在现实中按它分配罪责，受惩罚的会是一个人。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch3_case02_deduction',
  ),
  'ch3_case02_trustee_error': StoryBeat(
    id: 'ch3_case02_trustee_error',
    label: '能力不是行为',
    speaker: Speaker.shenYan,
    scene: SceneKey.storageRoom,
    text:
        '受托人拥有过权限，也可能知道会话如何工作，但现场没有证明九点十六分站在B-03门边的人就是他。见证记录反而证明试验结束后，他的可见操作已经停止。\n把“最有能力”直接写成“实际做过”，只会重复我们在中继器案前拒绝犯下的错误。我重新整理证据链。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_case02_deduction',
  ),
  'ch3_case02_resolved': StoryBeat(
    id: 'ch3_case02_resolved',
    label: '被重放的授权',
    speaker: Speaker.shenYan,
    scene: SceneKey.storageRoom,
    text:
        '封条证明有人真实取走物资；货架压痕证明取物早于电子确认；会话日志证明确认来自已撤销的托管缓存。\n“系统记录的不是01本人操作，也不能直接证明受托人操作。它记录的是一枚仍被控制器承认的旧授权。”\n一次操作暂时属于会话，不属于屏幕最后显示的名字。',
    passageSpeakers: [Speaker.narration, Speaker.shenYan, Speaker.narration],
    next: 'ch3_not_theft',
  ),
  'ch3_not_theft': StoryBeat(
    id: 'ch3_not_theft',
    label: '案件仍缺少物资去向',
    speaker: Speaker.tangYi,
    scene: SceneKey.storageRoom,
    text:
        '唐弈接受授权重放，却提醒我们仍没有找到水和药。\n“证明账本撒谎，不会让物资自己回来。有人拿走了东西，也许只是顺便利用系统嫁祸。”\n他把“谁获利”重新放回桌面。这一次问题没有越过证据，而是指出证据链仍缺最后一段空间事实。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch3_hidden_chute',
  ),
  'ch3_hidden_chute': StoryBeat(
    id: 'ch3_hidden_chute',
    label: '货架后的传送槽',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.storageRoom,
    portraitMood: 'injured',
    text:
        '高原让我们敲击货架背板。最下层传回空腔声，拆下挡条后露出一条通往隔离转运间的窄槽。槽口有新鲜纸屑，宽度正好容纳标准水箱。\n“这是旧物流线，图纸上应该封死了。”\n物资没有离开设施，只被送进一间无法从当前走廊进入的夹层。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch3_transfer_access_puzzle',
  ),
  'ch3_transfer_access_puzzle': StoryBeat(
    id: 'ch3_transfer_access_puzzle',
    label: '隔离转运间的三段门锁',
    text: '',
    scene: SceneKey.transferRoom,
    phase: StoryPhase.puzzle,
    next: 'ch3_transfer_entry',
  ),
  'ch3_transfer_entry': StoryBeat(
    id: 'ch3_transfer_entry',
    label: '09与16',
    speaker: Speaker.linCheng,
    scene: SceneKey.transferRoom,
    portraitMood: 'determined',
    text:
        '维护卡被读卡器吞入回收槽后，09与16组成的旧交接码让最后一枚锁舌缩回门内。我们不是在门边猜中答案，而是分别回到集合厅值班柜和档案走廊，才把两种不同年代的凭证拼在一起。\n林澄在地图上补出往返路线。\n“把钥匙和密码放在不同区域，不是为了防外人。”她说，“是为了让任何一个值班员都不能独自开门。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.linCheng],
    next: 'ch3_transfer_scene_hold',
  ),
  'ch3_transfer_scene_hold': StoryBeat(
    id: 'ch3_transfer_scene_hold',
    label: '门开了，没有人立刻进去',
    speaker: Speaker.shenYan,
    scene: SceneKey.transferRoom,
    text:
        '锁舌缩回后，门只被内外压差推开了一条缝。冷而干燥的空气从里面渗出来，带着机油、纸板和久封灰尘的味道。\n韩骐的手刚碰到门沿，我便拦住他。“先别踩进去。”\n手电光贴着地面扫过，门后薄灰里留着两道平行拖痕，却没有从门口延伸进去的新鲜鞋印。藏物资的人很可能根本没有走这扇门，而是在B-03那一侧把箱子推进了转运槽。',
    passageSpeakers: [Speaker.narration, Speaker.shenYan, Speaker.narration],
    next: 'ch3_transfer_team_split',
  ),
  'ch3_transfer_team_split': StoryBeat(
    id: 'ch3_transfer_team_split',
    label: '先定下谁站在哪里',
    speaker: Speaker.suMi,
    scene: SceneKey.transferRoom,
    portraitMood: 'concerned',
    text:
        '高原想拄着夹板亲自进门，苏弥却把他按回了折叠椅。“你负责看机械结构，不负责证明自己还能走。”\n最后由我和韩骐进入，林澄在门口记录位置，星遥把转运间与设施网络物理隔离，苏弥守着唯一出口。任何人移动物品前都要先报出位置和目的。\n韩骐看了一眼被每个人口述占满的记录页。“行。至少今天不会再出现一件没有主语的东西。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.hanQi],
    next: 'ch3_transfer_mechanism',
  ),
  'ch3_transfer_mechanism': StoryBeat(
    id: 'ch3_transfer_mechanism',
    label: '门后的承重轨道',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.transferRoom,
    portraitMood: 'injured',
    text:
        '门后不是普通夹层，而是一段不依赖主电源的机械转运轨道。五块外形相同的砝码散在地面，轨道侧面则排列着五个由浅到深的承重槽。\n高原通过视频观察天平支点。\n“槽位从轻到重依次联动保险销。顺序错了不会爆炸，只会把锁重新卡死。别凭大小猜，先称。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.gaoYuan],
    next: 'ch3_balance_puzzle',
  ),
  'ch3_balance_puzzle': StoryBeat(
    id: 'ch3_balance_puzzle',
    label: '五块无刻度砝码',
    text: '',
    scene: SceneKey.transferRoom,
    phase: StoryPhase.puzzle,
    next: 'ch3_balance_unlocked',
  ),
  'ch3_balance_unlocked': StoryBeat(
    id: 'ch3_balance_unlocked',
    label: '保险销依次升起',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.transferRoom,
    portraitMood: 'inspecting',
    text:
        '三角、十字、圆环、圆点、方框被依次压入承重槽。五枚保险销没有同时弹起，而是像一串缓慢传递的骨节，从最轻一端逐个解除。\n轨道向前滑动半米，一只原本卡在墙体夹层里的金属柜被平稳送到灯下。柜门上的三道封线都还完整，只有轨道表面留着与货架相同的纸屑。\n“称重不是下一道考题的钥匙。”高原在视频里说，“它就是这段轨道原来的交接授权。柜子到了，先查封线。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.gaoYuan],
    next: 'ch3_supplies_found',
  ),
  'ch3_slide_puzzle': StoryBeat(
    id: 'ch3_slide_puzzle',
    label: '八块石板与一个空格',
    text: '',
    scene: SceneKey.transferRoom,
    phase: StoryPhase.puzzle,
    next: 'ch3_pattern_unlocked',
  ),
  'ch3_pattern_unlocked': StoryBeat(
    id: 'ch3_pattern_unlocked',
    label: '闭合的线路图案',
    speaker: Speaker.liXingyao,
    scene: SceneKey.transferRoom,
    portraitMood: 'alarm',
    text:
        '最后一块线路板滑到边角时，八段图案在空格四周闭合成一条绕开封锁闸的完整回路。墙里的齿轮重新咬合，卡死的转运轨道先是震了一下，随后把剩余药品和最后一箱滤芯送到外侧。\n轨道恢复的瞬间，星遥的离线读取器截到一段没有标题的三列缓存。她来不及解读，只把原始短码和时间戳一起封存。\n“东西出来了。”她说，“剩下的等我们也出去再看。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.liXingyao],
    next: 'ch3_shutter_split',
  ),
  'ch3_audit_manifest_puzzle': StoryBeat(
    id: 'ch3_audit_manifest_puzzle',
    label: '三列没有标题的校验表',
    text: '',
    scene: SceneKey.assemblyHall,
    phase: StoryPhase.puzzle,
    next: 'ch3_audit_manifest_recovered',
  ),
  'ch3_audit_manifest_recovered': StoryBeat(
    id: 'ch3_audit_manifest_recovered',
    label: '被提前放进设施的风险目录',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '星遥在轨道恢复的几秒里抢出了完整缓存。回到集合厅后，我按“身份槽、撤销会话、重放间隔”的顺序重组校验列，原本无意义的短码开始指向六个封存位置。它们横跨医疗区、安保室、设备间和档案库，不可能是临时遗落的工具。\n目录同时记录了每件物资的初始封条与盘点频率，却没有写任何禁止参与者取用的规则。主办方不是疏忽，而是在保持基本生活供给的同时，刻意留下足以改变力量差距的筹码。\n我没有公开具体位置，只把目录拆成三份交由不同见证人保管。从这一刻起，谁拆封、谁持有、谁使用以及谁因此死亡，都必须成为彼此独立的记录。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'audit_weapon_manifest_found'},
    highRiskItemsOnEnter: {
      'sedative_case',
      'rescue_axe',
      'stun_controller',
      'industrial_driver',
      'corrosive_cleaner',
      'door_override',
    },
    next: 'ch3_protocol_debate',
  ),
  'ch3_supplies_found': StoryBeat(
    id: 'ch3_supplies_found',
    label: '一件都没有被使用',
    speaker: Speaker.suMi,
    scene: SceneKey.transferRoom,
    portraitMood: 'concerned',
    text:
        '金属柜里整齐放着十二份水、六支止痛剂和两组滤芯，包装全部完整。苏弥先把急用药和一组滤芯传出去，其余箱子暂时保留在原位，等封线、轨道拖痕与每件物资都被三人分别记录后再转移。\n她核对完数量，长出一口气，随后脸色更冷。\n“对方不是为了缺这些东西。”\n藏物资的人利用了一扇需要跨区凭证的门和一段旧式承重轨道，只为让清单指向01，让一次短期托管变成公开指控。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch3_operation_owner',
  ),
  'ch3_operation_owner': StoryBeat(
    id: 'ch3_operation_owner',
    label: '谁拥有一次操作',
    speaker: Speaker.yeLan,
    scene: SceneKey.storageRoom,
    portraitMood: 'intervening',
    text:
        '叶岚在CASE 02记录末尾写下结论：授权可以被复制，署名可以继承，但责任必须回到具体动作与可复查过程。\n“以后不能再说‘01打开了门’。”她说，“要说01同意了什么、哪台设备发出请求、谁在现场、控制器何时接受。”\n一句话变长了，却终于给真正的人留下位置。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch3_public_argument',
  ),
  'ch3_public_argument': StoryBeat(
    id: 'ch3_public_argument',
    label: '嫌疑没有自动消失',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '回到集合厅后，韩骐公开撤回“受托人必然转移物资”的判断，但没有宣布任何人清白。\n“缓存需要有人复制，物资也需要有人推进转运槽。我们只排除了一个偷懒的答案。”\n受托人点头。撤回错误指控不是恢复信任，而是让下一轮追查不再背着一个被误当成事实的名字。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch3_second_seal_notice',
  ),
  'ch3_second_seal_notice': StoryBeat(
    id: 'ch3_second_seal_notice',
    label: '第二次永久封锁',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    timelineMinute: 2820,
    text:
        '晚上十一点，所有扬声器再次亮起。\n“第二次永久封锁区域：B-03储物区及隔离转运间。执行时间：二十三点三十分。”\n我们刚找回的物资仍在夹层，CASE 02原始审计PDA也固定在墙上。如果不在三十分钟内转移，证据和第二天余下的药品都会一起消失。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch3_b03_seal_map',
  ),
  'ch3_b03_seal_map': StoryBeat(
    id: 'ch3_b03_seal_map',
    label: '封锁追着授权而来',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥发现B-03被列为候选的时间，正是旧会话在门禁控制器中重新生效的九点十六分。12号白色信号也在那一刻短暂出现在转运间。\n“它不只重放身份槽，还能把托管会话当成有效参与者操作。”\n封锁像是在追逐我们刚刚使用过的制度漏洞。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch3_return_for_audit',
  ),
  'ch3_return_for_audit': StoryBeat(
    id: 'ch3_return_for_audit',
    label: '最后一次进入B-03',
    speaker: Speaker.hanQi,
    scene: SceneKey.transferRoom,
    portraitMood: 'protective',
    text:
        '韩骐带我、星遥和高原的远程视频返回B-03。其他人在外侧接应，物资通过维护口一箱箱传出。\n“01门禁签名能打开转运间内侧。”韩骐说，“终端先给我，我负责过门，你保持两米。”\n这一次把01交到他手里既是最快方案，也让他的个人条款第一次在真实危机中得到实物。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch3_evacuation_track_jam',
  ),
  'ch3_evacuation_track_jam': StoryBeat(
    id: 'ch3_evacuation_track_jam',
    label: '转运轨道卡在封锁线上',
    speaker: Speaker.liXingyao,
    scene: SceneKey.transferRoom,
    portraitMood: 'alarm',
    text:
        '前三箱物资顺利通过维护口。第四箱刚压上轨道，封锁倒计时便切换了墙内的隔离闸，轨道在两段路径之间猛地卡死。\n高原让我们撬开侧面检修盖。盖后不是电机，而是一块九宫格机械路由盘：八块线路板被封锁程序打乱，唯一空格停在回路中央。它不是保护柜门的第三道题，而是在主路被封锁时手动改接备用轨道的老式控制器。\n“一百九十秒后，这面墙会把内外两段轨道分开。”星遥看着跳动的红色数字，“要么现在把图案接回去，要么放弃剩下的药和滤芯。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.liXingyao],
    next: 'ch3_slide_puzzle',
  ),
  'ch3_shutter_split': StoryBeat(
    id: 'ch3_shutter_split',
    label: '一米六的铁栅',
    speaker: Speaker.narration,
    scene: SceneKey.transferRoom,
    text:
        '最后一箱滤芯推出时，转运间铁栅突然落下。韩骐在外侧，01握在他手里；我被隔在内侧，两人直线距离一米六。\n项圈没有警告，因为尚未超过两米。可封锁倒计时只剩一百九十秒，铁栅一旦完全闭合，墙体屏蔽会让距离判定跳到无法测量。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_hanqi_has01',
  ),
  'ch3_hanqi_has01': StoryBeat(
    id: 'ch3_hanqi_has01',
    label: '完成条款的形状',
    speaker: Speaker.hanQi,
    scene: SceneKey.transferRoom,
    portraitMood: 'protective',
    text:
        '铁栅内侧的解锁槽要求01所有者确认，终端必须从地面十二厘米的缝隙滑回我这边。\n韩骐低头看着手里的01。只要继续持有，他就比任何时候都接近自己的生还条款；只要把它递回，他便主动放弃已经到手的控制。\n“还有一百七十秒。”星遥在频道里报时，没有替他作决定。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.liXingyao],
    next: 'ch3_hanqi_choice',
  ),
  'ch3_hanqi_choice': StoryBeat(
    id: 'ch3_hanqi_choice',
    label: '如何要求归还01',
    speaker: Speaker.shenYan,
    scene: SceneKey.transferRoom,
    text: '我必须在倒计时和他的条款之间选择一种说法。命令、信任或集体撤销都会让门打开，却会留下完全不同的关系。',
    next: null,
    choices: [
      StoryChoice(
        label: '要求他按见证记录立即归还',
        caption: '把这次归还定义为事先约定，而非临时施舍',
        next: 'ch3_hanqi_returns',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch3_return_by_protocol'),
      ),
      StoryChoice(
        label: '告诉他由自己决定',
        caption: '不以救援压力替他完成道德选择',
        next: 'ch3_hanqi_voluntary_return',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch3_return_by_choice'),
      ),
      StoryChoice(
        label: '让外侧两名见证人强制撤销',
        caption: '优先使用公共权限夺回门禁控制',
        next: 'ch3_collective_revoke',
        effect: ChoiceEffect(logic: 1, flag: 'ch3_return_by_revoke'),
      ),
    ],
  ),
  'ch3_hanqi_returns': StoryBeat(
    id: 'ch3_hanqi_returns',
    label: '按约定归还',
    speaker: Speaker.hanQi,
    scene: SceneKey.transferRoom,
    portraitMood: 'conflicted',
    text:
        '“试验记录写了持有者可以随时要求归还。”我说，“韩骐，执行约定。”\n他只停了一秒，便蹲下把01从缝隙推回。\n“收到。”\n那不是服从我的命令，而是承认一条在危机前共同写下的边界，比他此刻握住的机会更有资格决定动作。',
    passageSpeakers: [
      Speaker.shenYan,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch3_exit_b03',
  ),
  'ch3_hanqi_voluntary_return': StoryBeat(
    id: 'ch3_hanqi_voluntary_return',
    label: '不是被迫的归还',
    speaker: Speaker.shenYan,
    scene: SceneKey.transferRoom,
    portraitMood: 'conflicted',
    text:
        '“01在你手里。”我隔着铁栅说，“接下来由你决定这份条款值不值得拿我的一百八十秒去换。”\n韩骐的下颌绷紧。他看了一眼倒计时，又看向我，没有要求保证以后再交给他。\n终端沿地面滑过缝隙。\n“先出去。”他说，“我的条件应该由我完成，不该由你的项圈替我完成。”',
    passageSpeakers: [
      Speaker.shenYan,
      Speaker.narration,
      Speaker.narration,
      Speaker.hanQi,
    ],
    next: 'ch3_exit_b03',
  ),
  'ch3_collective_revoke': StoryBeat(
    id: 'ch3_collective_revoke',
    label: '两名见证人的撤销',
    speaker: Speaker.yeLan,
    scene: SceneKey.transferRoom,
    portraitMood: 'intervening',
    text:
        '我呼叫外侧见证人执行紧急撤销。叶岚与苏弥分别确认持有者受困、授权设备在外、继续持有将触发死亡风险。\n公共终端生成一次强制归还请求。韩骐在请求完成前已经蹲下，将01推过缝隙。\n“记录清楚。”他说，“不是系统从我手里抢走，是我同意这次撤销。”\n他仍需要为选择留下自己的主语。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch3_exit_b03',
  ),
  'ch3_exit_b03': StoryBeat(
    id: 'ch3_exit_b03',
    label: '在阈值前十二秒',
    speaker: Speaker.shenYan,
    scene: SceneKey.transferRoom,
    cgId: 'cg_storage_seal',
    text:
        '01贴上内侧解锁槽，铁栅升起不到半米。我从下面钻出，韩骐抓住肩带把我拖过最后一段。\n距离异常在一百六十八秒停止，离项圈阈值只剩十二秒。终端回到我掌心时仍带着他的体温。\n我们没有拥抱，也没有说谢谢。两个人只是同时退到安全线外，确认对方仍能呼吸。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch3_second_seal',
  ),
  'ch3_second_seal': StoryBeat(
    id: 'ch3_second_seal',
    label: 'B-03永久封锁',
    speaker: Speaker.administrator,
    scene: SceneKey.corridor,
    cgId: 'cg_storage_seal',
    cgFrame: 1,
    text:
        '二十三点三十分，B-03外墙的锁栓依次落下。隔离转运间、审计PDA和那条可以重放授权的门禁缓存一起被封进黑色区域。\n“第二次永久封锁完成。当前存活参与者：十。”\n物资堆在走廊，所有人都活着。可从今晚开始，我们再也没有一间能够独立上锁的储物区。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch3_aftershock',
  ),
  'ch3_aftershock': StoryBeat(
    id: 'ch3_aftershock',
    label: '终端归还后的沉默',
    speaker: Speaker.hanQi,
    scene: SceneKey.corridor,
    portraitMood: 'conflicted',
    text:
        '封锁完成后，韩骐没有再要求我立刻交出01。\n“我还是需要它。”他说，“今天还给你，不等于我的条件消失。”\n“我知道。”\n真正的选择不会一次解决利益冲突。它只证明在某个具体时刻，一个人没有让自己的生还条件替另一个人判死。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch3_protocol_debate',
    auditNext: 'ch3_audit_manifest_puzzle',
    auditRequiredFlags: {
      'audit_index_fragment',
      'case02_solved',
      'puzzle_ch3_slide_puzzle_solved',
    },
  ),
  'ch3_protocol_debate': StoryBeat(
    id: 'ch3_protocol_debate',
    label: '把临时做法写成制度',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '午夜前，我们必须决定以后如何使用托管。完全禁止会让伤者和隔离救援失去工具；自由交换会让授权变成筹码；交给固定保管人则把所有风险集中到一个人身上。\n叶岚把三种方案写上白板。\n“没有无风险制度。我们只能决定，错误发生时由谁有权阻止，又由谁留下记录。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.yeLan],
    next: 'ch3_protocol_choice',
  ),
  'ch3_protocol_choice': StoryBeat(
    id: 'ch3_protocol_choice',
    label: '选择公共托管制度',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text: '白板上的三种制度都能提高某种效率，也都会让一部分人更容易控制另一部分人。',
    next: null,
    choices: [
      StoryChoice(
        label: '建立两名见证人的共同撤销权',
        caption: '授权可被持有者或两名独立见证人终止',
        next: 'ch3_protocol_shared',
        effect: ChoiceEffect(
          cooperation: 2,
          logic: 1,
          flag: 'ch3_shared_revocation',
        ),
      ),
      StoryChoice(
        label: '指定一名中央终端保管人',
        caption: '减少操作混乱，但把权限集中到固定角色',
        next: 'ch3_protocol_custodian',
        effect: ChoiceEffect(cooperation: -1, flag: 'ch3_central_custody'),
      ),
      StoryChoice(
        label: '允许按公开价格交换权限',
        caption: '每笔交易留档，生存资源也将被正式定价',
        next: 'ch3_protocol_exchange',
        effect: ChoiceEffect(logic: 1, flag: 'ch3_clause_market'),
      ),
      StoryChoice(
        label: '把全部条款与权限同步到公共槽',
        caption: '任何人都能复核同一份底稿，不再保留单点秘密',
        next: 'pact_end',
        effect: ChoiceEffect(
          cooperation: 2,
          logic: 1,
          flag: 'ch3_total_disclosure',
        ),
      ),
    ],
  ),
  'ch3_protocol_shared': StoryBeat(
    id: 'ch3_protocol_shared',
    label: '共同撤销',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'relieved',
    text:
        '我们通过共同撤销方案：任何托管写明范围和时限；持有者可以单独撤销；持有者失去意识或受困时，两名未从该授权获利的见证人可以共同终止。\n苏弥在“失去意识”旁补上身体判定标准，避免一句“他不清醒”成为夺权理由。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_protocol_shared_detail',
  ),
  'ch3_protocol_shared_detail': StoryBeat(
    id: 'ch3_protocol_shared_detail',
    label: '撤销也必须留下主语',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '叶岚要求强制撤销记录同时写明两名见证人、现场风险和持有者之后是否追认。\n“共同权力不比个人权力天然善良。”她说，“只是它需要更多人公开承担自己做了什么。”\n制度没有要求我们互相信任，只要求任何人都不能独自把别人的沉默解释成同意。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch3_protocol_record',
  ),
  'ch3_protocol_custodian': StoryBeat(
    id: 'ch3_protocol_custodian',
    label: '中央保管',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '多数人因连续事故选择集中保管：除个人两米终端外，所有可转移权限由一名值班保管人登记，门禁操作必须经过他。\n韩骐认为这能缩短危机中的争论，唐弈则提醒，保管人会立刻成为最值得交易、威胁或杀死的人。\n秩序建立了，权力也有了清楚的座位。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch3_protocol_custodian_detail',
  ),
  'ch3_protocol_custodian_detail': StoryBeat(
    id: 'ch3_protocol_custodian_detail',
    label: '谁保管保管人',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    text:
        '第一轮保管人由韩骐担任，叶岚保存副本，陈默负责技术审计。三个角色互相限制，也共同掌握了其他人的行动入口。\n“你们把市场换成了委员会。”唐弈说，“价格消失，不代表交换消失。”\n没有人能反驳。我们只是把风险从每笔交易，移动到一个更容易监视也更难替换的中心。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch3_protocol_record',
  ),
  'ch3_protocol_exchange': StoryBeat(
    id: 'ch3_protocol_exchange',
    label: '公开交换',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    text:
        '我们允许权限交换，但每笔交易必须公开范围、期限、对价与见证人，不得用急救、饮水和解除即时死亡风险作为对价。\n唐弈接受后三项限制，亲手把“生命维持资源不得定价”写在价格表顶端。\n他没有放弃交换，只承认有些东西一旦进入市场，人就不再拥有拒绝的可能。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch3_protocol_exchange_detail',
  ),
  'ch3_protocol_exchange_detail': StoryBeat(
    id: 'ch3_protocol_exchange_detail',
    label: '自愿交易的边界',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '林澄要求再加一条：条款要求的信赖、陪伴和私人信息不能由第三人代替当事人出售。\n“如果别人可以替我把‘信赖对象’当作筹码，我说自愿就没有意义了。”\n她说这句话时没有看我。能够公开划出亲密关系的边界，本身比向谁靠近更接近独立。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch3_protocol_record',
  ),
  'ch3_protocol_record': StoryBeat(
    id: 'ch3_protocol_record',
    label: 'CASE 02公共记录',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '最终制度、CASE 02证据与B-03封锁时间被抄成三份：一份贴在集合厅，一份放进离线证物箱，一份由不同的人轮流保管。\n记录的标题没有写“物资失窃”，而是“谁拥有一次操作”。因为我们需要记住，系统最容易操纵的不是按钮，而是句子里的主语。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch3_twelve_delegation',
  ),
  'ch3_twelve_delegation': StoryBeat(
    id: 'ch3_twelve_delegation',
    label: '12号也在托管名单里',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥在深夜同步中发现，托管对象列表始终有十二个身份槽。吴峥和周叙标记为失效，12号却显示“可接受门禁权限”，只是不回应任何确认请求。\n更异常的是，重放旧会话的设备把接收者写成了12。\n“它没有私人条款，没有真人回应，却能像参与者一样接过我们的权力。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.liXingyao],
    next: 'ch3_relationship_choice',
  ),
  'ch3_relationship_choice': StoryBeat(
    id: 'ch3_relationship_choice',
    label: '第二夜的同行者',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text: '制度写完后，集合厅终于安静下来。我还可以把今晚留给一个需要继续核对的人，或者留在公共记录旁值夜。',
    next: null,
    choices: [
      StoryChoice(
        label: '陪星遥复查四十二秒窗口',
        caption: '让技术判断也允许另一个人重复验证',
        next: 'ch3_xingyao_night',
        requiresFlag: 'ch2_xingyao_bond',
        effect: ChoiceEffect(xingyao: 1, flag: 'ch3_xingyao_bond'),
      ),
      StoryChoice(
        label: '陪苏弥重新分配药品',
        caption: '把她的状态也纳入第二天医疗记录',
        next: 'ch3_sumi_night',
        requiresFlag: 'ch2_sumi_bond',
        effect: ChoiceEffect(sumi: 1, flag: 'ch3_sumi_bond'),
      ),
      StoryChoice(
        label: '陪林澄重画失去B-03后的路线',
        caption: '让她独立决定下一次同行的安全边界',
        next: 'ch3_lincheng_night',
        requiresFlag: 'ch2_lincheng_bond',
        effect: ChoiceEffect(lincheng: 1, flag: 'ch3_lincheng_bond'),
      ),
      StoryChoice(
        label: '留在公共记录旁值夜',
        caption: '确保任何人都能复查CASE 02原始证据',
        next: 'ch3_group_night',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch3_public_watch'),
      ),
    ],
  ),
  'ch3_xingyao_night': StoryBeat(
    id: 'ch3_xingyao_night',
    label: '不把密钥只留给一个人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'relaxed',
    text:
        '星遥把校准步骤写成我也能重复的表格，逼自己不去抢回每一次操作。第三次由我完成时，误差落在零点一秒内。\n“以前我觉得教别人会增加错误。”她摘下一边耳机递给我，“现在才发现，只让一个人正确，出错的时候连反证都没有。”\n我们隔着同一段白噪声核对数字，肩膀没有碰在一起，频道却第一次不属于她一个人。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch3_day_end',
  ),
  'ch3_sumi_night': StoryBeat(
    id: 'ch3_sumi_night',
    label: '医生也进入配给表',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'relieved',
    text:
        '苏弥按伤情重新分配止痛药，给高原留两次剂量，给可能出现的急救保留四支。表格最后仍没有她自己的名字。\n我把她掌心伤口换药和睡眠不足写进观察栏。\n“你不能以记录者身份把自己删掉。”\n她没有反驳，只把笔交给我，让我签下共同记录人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch3_day_end',
  ),
  'ch3_lincheng_night': StoryBeat(
    id: 'ch3_lincheng_night',
    label: '不拿陪伴交换路线',
    speaker: Speaker.linCheng,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'determined',
    text:
        'B-03封锁后，林澄把水和药的搬运路线改成三人接力。她没有默认把我写在自己一组，而是先问我愿意承担哪一段。\n“我的条件需要信赖对象。”她说，“可如果每次一起行动都被当作条件进度，我就不知道你是因为想来，还是因为怕我死。”\n我选择了一段能与她交接、却不替她决定终点的路线。她把两个姓名写在相邻而非重叠的位置。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch3_day_end',
  ),
  'ch3_group_night': StoryBeat(
    id: 'ch3_group_night',
    label: '让记录在无人看守时也可信',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '我和叶岚把三份CASE 02记录分别封存，封口由不同的人签名。她拒绝独自保管总表。\n“如果制度只有我在场才成立，那不是制度，只是大家暂时相信我。”\n凌晨一点，我们故意离开记录十分钟，再由另一组核对封口。没有人靠近。一次无人监督的完整，终于比一句“我保证”更有重量。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch3_day_end',
  ),
  'ch3_day_end': StoryBeat(
    id: 'ch3_day_end',
    label: '第二天结束',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '第二天结束时，地图又少了一块：F-01像被挖走的肺叶，B-03则切断所有集中储物。水、药和证据从此必须分散在人与人之间。\n我们没有找到复制授权的人，却知道主办方能够把持有者、受托者和实际操作者压成同一个编号。\n托管让合作走得更远，也让背叛不必亲自到场。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch3_end',
  ),
  'ch3_end': StoryBeat(
    id: 'ch3_end',
    label: '静默病房的前兆',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '凌晨一点零七分，公共频道里出现持续不到半秒的尖锐高频。星遥摘下耳机时脚步晃了一下，苏弥立即扶住她。\nPDA地图将下一轮封锁候选标在医疗区C-02。与此同时，药柜盘点显示少了一支尚未使用的镇静剂。\n在托管制度刚刚学会区分“谁同意”和“谁操作”的夜里，新的问题已经要求我们判断：谁有资格决定另一个人是否需要被救。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch4_daybreak',
  ),
  'pact_end': StoryBeat(
    id: 'pact_end',
    label: '一份所有人都能读取的底稿',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '我选择了最彻底的方案：把十份私人条款、现存门禁权限、托管记录和证据索引同步进公共槽。任何终端都只能读取，修改则需要三人签名。它看起来比中央保管更分散，也比逐笔交换更平等。\n苏弥先问病历和身体记录是否必须上传。叶岚提出只公开会改变他人风险的部分，不公开无关隐私。我接受了限制，星遥也在离线环境检查同步包，没有发现向外发送的进程。\n真正的问题出现在确认页最下方。系统写着：“公共槽需要一个持续在线的见证身份，断线将使副本失效。推荐身份：12。”\n12号没有生物体征，不会在封锁中离线，也没有公开的个人条款。把它设为见证者，似乎恰好能避免任何真人独占底稿。陈默检查签名结构后说，它只能证明文件未被改动，不能替我们投票。\n林澄仍然不安。“它没有说过同意。”\n唐弈回答：“一把锁也不会同意保管东西。关键是钥匙在不在一个人手里。”\n我们最终让12号成为只读见证。确认完成时，十台PDA同时出现一枚白色圆环。第一次，所有人看见了同一份规则与同一份秘密。大厅里甚至响起短暂掌声。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'pact_end_shared_day',
  ),
  'pact_end_shared_day': StoryBeat(
    id: 'pact_end_shared_day',
    label: '公开让合作变得异常顺利',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '接下来的二十个小时，公共槽几乎解决了所有争论。谁持有门禁、哪支药被取走、哪条路线与谁的条件冲突，都能在同一页核对。有人提出行动方案时，不必先证明自己没有隐藏收益，系统会自动标出相关条款。\n第二次距离伪造刚出现，十台终端便同时收到异常对比。星遥在四十秒内找到信号源，高原封住设备，苏弥确认所有人仍在安全半径。没有人死亡。\n“这才像共同体。”有人说。\n叶岚却把这句话划掉，改成“共同底稿”。她提醒我们，共同体由可以拒绝、修正和离开的人组成；底稿只是工具。可顺利本身拥有强大说服力。每一次白色圆环替我们找出利益冲突，大家就更少询问它如何判断“相关”。\n到第四次行动时，会议只剩下确认系统建议。唐弈不再报价，因为公共槽会计算一项交换是否使某人的生还概率显著下降；韩骐不再争夺保管权，因为12号从不离线；我也不再逐条解释判断，只要把证据上传，圆环就会给出一致性分数。\n我们确实变得更公平，也越来越难分辨公平来自共同决定，还是来自一个没有位置、没有身体、不会承担后果的见证者替我们删去了争议。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'pact_end_revision',
  ),
  'pact_end_revision': StoryBeat(
    id: 'pact_end_revision',
    label: '第一份无法撤回的公开',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'shaken',
    text:
        '第四天，苏弥发现自己的条款统计仍把12号算作存活参与者。她提交更正，公共槽却拒绝覆盖原始内容，理由是三人签名只能追加异议，不能修改由持续见证者保存的底稿。\n“那就把12号从见证身份移除。”她说。\n系统要求十名活跃参与者一致同意。陈默担心移除会使所有门禁授权失效，唐弈则拒绝在人数定义未确定前放弃唯一固定槽。两人都给出了真实理由，一致同意因此无法成立。\n更糟的是，我们上传过每个人的风险边界。12号知道星遥一旦失去听觉校准就无法验证信号，知道苏弥会为伤者暂停撤离，也知道林澄在项圈警报后会出现短暂僵直。信息最初用来提醒队友，如今却同时构成一份能够精确设计胁迫的说明书。\n“只读不等于无害。”星遥拆开公共终端，发现白色圆环并非普通校验签名，而是一枚持续更新的授权根，“它没有改文件。它在根据文件决定哪些操作与条款相容。”\n我们试图断开网络，所有PDA立即提示公共副本失效，现有托管和门禁将在一百八十秒后撤销。几扇区域门同时转红。共同底稿已经成为唯一底稿，退出它的代价被设计成必须拿所有人的即时安全去赌。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'pact_end_consensus',
  ),
  'pact_end_consensus': StoryBeat(
    id: 'pact_end_consensus',
    label: '一致同意成为无法离开的门',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '第五天零点，系统公布临时共同体规则：公共槽中的十个身份视作一个授权群体，任何区域撤离必须取得全体相容确认；无法确认者的权限由持续见证身份12代行。\n这听起来仍像防止多数抛弃少数。第一场封锁却让含义显现。林澄在转运间失去信号，无法确认撤离，12号读取她此前登记的安全偏好，替她选择“留在原地等待救援”。闸门因此开始关闭。\n“她现在就在往外跑！”我把实时画面接入终端。\n管理员回答：“实时行为与已公开偏好冲突。持续见证者采用最后一份完整陈述。”\n我们需要全体修改底稿，林澄本人却因信号中断无法签名。12号又以她的旧偏好代行拒绝。那套为保护沉默者设计的一致程序，把她的沉默解释成永不改变的同意。\n韩骐用消防斧顶住闸门，高原切断液压管，星遥尝试伪造第十枚更新签名。我们救出了林澄，却触发公共槽完整性惩罚。十枚白色圆环同时变红，每个人的终端被锁进同一份两米距离规则：任意一人失联，全部身份视为失联。\n临时共同体终于真正不可分割。不是因为我们选择互相承担，而是因为系统把离开、反对和改变主意都定义成了对共同安全的破坏。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.narration,
      Speaker.shenYan,
      Speaker.administrator,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'pact_end_last_room',
  ),
  'pact_end_last_room': StoryBeat(
    id: 'pact_end_last_room',
    label: '十个人只能停在同一个房间',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '此后两天，我们只能整体移动。走廊拐角会让信号暂时遮挡，楼梯无法容纳十个人保持两米，医疗区和维修区之间则隔着必须单人通过的消毒门。所谓共同体被压缩成集合厅中央一块所有终端都能互相看见的圆形区域。\n食物和水仍在其他区域，药品也在逐渐耗尽。主办方没有派人袭击，只按时宣布封锁，让每一项必需品停在离圆圈几米远的地方。任何一人踏出去，全体项圈都会开始计时。\n我们尝试用绳索拖回物资，用镜面反射信号，用九台终端模拟第十台的位置。公共槽拥有我们上传的全部方法与设备清单，总能在下一次校验中堵住刚刚使用的缝隙。\n第七天，出口在走廊尽头开启，只允许四个独立身份提交证词。系统同时认定我们是一个授权群体。十个人足够作证，也因为不再独立而没有一个有效席位。\n“当初如果不公开，还是会彼此怀疑。”林澄靠在白板下说。\n“公开没有错。”叶岚的声音已经很轻，“错的是我们把谁能修改、谁能退出、谁承担误判都交给了一个不需要活着离开的见证者。”\n最后一轮通风关闭前，我们把异议写在纸上。每个人用自己的姓名签字，内容并不完全一致。那是七天里最像共同体的时刻：十个人允许彼此保留不同答案，也允许任何人划掉自己的名字。可纸张不在系统承认的公共槽里。出口没有读取它。\n灯熄灭时，十台PDA仍显示同一份完美一致的底稿。我们终于没有任何秘密，也没有任何一个人还能单独说“不”。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.yeLan,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'pact_end_result',
  ),
  'pact_end_result': StoryBeat(
    id: 'pact_end_result',
    label: '临时共同体',
    text: '没有退出权的公开只会把十个人锁进同一个秘密。共同体需要共同记录，也需要每个人仍能修改自己的回答。',
    next: null,
    phase: StoryPhase.ending,
    endingId: 'ending_pact',
  ),
};
