part of 'story.dart';

const chapterTwoBeats = <String, StoryBeat>{
  'ch2_case_conclusion': StoryBeat(
    id: 'ch2_case_conclusion',
    label: '没有名字的凶手',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlRoom,
    timelineMinute: 1290,
    text:
        '隐藏日志证明周叙的距离信号遭到中继，证据却没有留下操作者的名字。储物袋没有指纹，备用通道避开了摄像头，连剪断屏蔽层的工具都来自公共设备间。\n“我们证明了他是怎么死的，还没有证明是谁做的。”\n我说完后，原本因为推理成立而稍微松开的空气又绷紧了。十分钟以前，所有人都想知道规则有没有漏洞；现在他们知道了，也知道最先找到漏洞的人就在这座楼里。',
    passageSpeakers: [Speaker.narration, Speaker.shenYan, Speaker.narration],
    next: 'ch2_unanswered_culprit',
  ),
  'ch2_unanswered_culprit': StoryBeat(
    id: 'ch2_unanswered_culprit',
    label: '最危险的空白',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlRoom,
    portraitMood: 'shaken',
    text:
        '唐弈把硬币按在仍有余温的中继器上，没有像往常一样抛起。\n“手法公开以后，凶手的优势就没有了。可我们的优势也没有增加，因为下一次谁都能照着做。”\n韩骐要求立刻搜身，陈默反问要由谁保管搜出的设备。争论绕了一圈，最后又回到同一个问题：在没有裁判、没有警察、也没有可信管理者的地方，谁有资格决定别人是否清白。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch2_admin_silence',
  ),
  'ch2_admin_silence': StoryBeat(
    id: 'ch2_admin_silence',
    label: '主办方拒绝裁决',
    speaker: Speaker.administrator,
    scene: SceneKey.controlRoom,
    text:
        '我对着摄像头报告了中继器、时间日志和我们的推论，要求主办方确认周叙是否遭到谋杀。\n扬声器沉默了足足二十秒，随后只吐出一句没有起伏的回答：“规则仅裁定结果，不裁定动机。”\n这不是回避，而是一种许可。只要手段没有直接破坏主机，参与者利用规则杀死参与者，也属于“未被禁止的行为”。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch2_return_hall',
  ),
  'ch2_return_hall': StoryBeat(
    id: 'ch2_return_hall',
    label: '回到十把椅子之间',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '我们把周叙的身体移到集合厅旁的空办公室。回程时，每个人仍旧保持两人一组，却不再有人自然地走在别人身后。转弯、开门、接水，所有动作都先确认自己的终端，再确认同伴的手。\n集合厅原本摆着十二把折叠椅。吴峥和周叙的位置空下来后，椅子的圆环看上去像被生生掰掉了两颗牙；属于12号的那把仍然没有人坐，却没有任何人敢把它收走。',
    next: 'ch2_chapter_title',
  ),
  'ch2_chapter_title': StoryBeat(
    id: 'ch2_chapter_title',
    label: '封锁顺序',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text: '距离第一次永久封锁还有两个半小时。屏幕上的倒计时不再只是一个遥远的七日时限，而开始精确切割我们能够站立、藏匿和逃跑的每一块地面。',
    next: 'ch2_meal_silence',
  ),
  'ch2_meal_silence': StoryBeat(
    id: 'ch2_meal_silence',
    label: '第一顿共同进食',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    text:
        '叶岚把压缩食品按人数摆开，坚持所有包装都在众人面前拆封。没人说自己担心下毒，可每个人都等别人先咽下第一口。\n“沉默不是平静。”她把自己那份水喝掉一半，才继续说，“现在所有人都在观察谁不吃、谁换位置、谁的手靠近别人的终端。我们至少应该把正在做的判断说出来，免得猜测替事实生长。”\n这句话没有让气氛变好，却让周叙留下的那份食物被收进证物柜，而不是像他从未存在过一样重新分掉。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch2_watch_protocol',
  ),
  'ch2_watch_protocol': StoryBeat(
    id: 'ch2_watch_protocol',
    label: '交叉点名',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '韩骐在白板上写下新的行动规则：每十五分钟报一次编号与地点；任何人离开当前区域前，必须由两人同时在纸面记录；终端出现距离变化时，附近的人先确认真人位置，不能立刻追逐屏幕上的数字。\n“这不是让你们信任我。”他说，“是让任何一个想撒谎的人必须同时骗过纸、终端和两双眼睛。”\n陈默指出主办方随时可以改写终端显示。韩骐没有否认，只在“纸面记录”下面又重重画了一道横线。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch2_map_update',
  ),
  'ch2_map_update': StoryBeat(
    id: 'ch2_map_update',
    label: '第一封锁区域',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '所有PDA同时震动。区域地图上的F-01由灰色变成不断闪烁的红色，旧体育馆周围的通道被一条条粗线截断。\n“第一次永久封锁区域：F-01旧体育馆。执行时间：零点。封锁完成后，区域内的有效参与者将被处决。”\n屏幕下方还有一行新出现的小字：区域内活动终端三台。可名单上，只有08号陈默和09号高原申请进入过旧体育馆。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch2_gym_signals',
  ),
  'ch2_gym_signals': StoryBeat(
    id: 'ch2_gym_signals',
    label: '第三个信号',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥把地图放大。08和09的光点停在体育馆北侧设备间，第三个光点却没有编号，只显示一圈白色脉冲。\n“它不是刚出现的。”她调出缓存记录，“至少四十分钟前就在里面，只是地图以前把无编号终端过滤掉了。封锁名单刷新后，它才被当成区域占用者。”\n我看向那把空椅。白色脉冲每七秒亮一次，和广播回路里的第二套网络完全同频。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch2_chen_call',
  ),
  'ch2_chen_call': StoryBeat(
    id: 'ch2_chen_call',
    label: '08号的求援',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'discovery',
    text:
        '公共频道里先传来一阵布料摩擦声，随后是陈默刻意压低的声音。\n“体育馆的卷帘门控制页没有退出选项。我只查看了一次，系统就把我登记成现场操作员。现在门锁不接受远程指令。”\n背景里响起高原用金属敲击管壁的声音，三短一长。他们还活着，但至少有一扇门已经落下。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_gao_warning',
  ),
  'ch2_gao_warning': StoryBeat(
    id: 'ch2_gao_warning',
    label: '制动器异响',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '高原接过频道。他没有喊救命，先报告卷帘门的状态。\n“北门制动索断了，不是老化。断口太齐。南门还能抬，但控制箱必须一直有人压住旁路开关，手一松就落。”\n他说到最后一个字时，头顶传来沉重的金属撞击。频道短暂中断，只剩终端上09号仍在闪烁的定位点。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch2_chen_entry_reason',
  ),
  'ch2_rush_corridor': StoryBeat(
    id: 'ch2_rush_corridor',
    label: '奔向F-01',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '韩骐带上撬棍和绳索，苏弥把止血包塞进外套，星遥则边跑边监视三个信号。我落在队伍中间，保证前后都有人能看见01终端。\n通往体育馆的走廊比地图标注多了两道防火门。每经过一道门，身后的磁锁都会自动合拢，像整座建筑正在把我们一步步吞进预定的区域。\n“剩余两小时十七分。”林澄报时。她没有说快一点，因为所有人已经在用不会摔倒的最快速度奔跑。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.linCheng],
    next: 'ch2_route_recovery',
  ),
  'ch2_gym_entry': StoryBeat(
    id: 'ch2_gym_entry',
    label: '旧体育馆',
    speaker: Speaker.narration,
    scene: SceneKey.oldGym,
    cgId: 'cg_gym',
    text:
        '体育馆不是学校礼堂，而是一间被企业改造成训练场的巨大室内空间。磨损的木地板保留着褪色球场线，折叠看台上积着灰，所有高窗都被钢板封死。新安装的卷帘门与老旧墙面格格不入，黑黄警戒条在应急灯下像一排咬合的牙。\n陈默站在西侧控制箱旁，右手一直压着红色旁路柄。隔着半落的卷帘门，高原侧身卡在器材架与墙之间，左腿被倒下的金属框压住。',
    next: 'ch2_first_visual_sweep',
  ),
  'ch2_ghost_ping': StoryBeat(
    id: 'ch2_ghost_ping',
    label: '场内没有第三个人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.oldGym,
    text:
        '星遥沿着白色光点的方向走到中线。那里只有一只上锁的球车、几张发霉软垫和贴墙固定的空充电底座。\n“信号就在这里，误差不到半米。”\n韩骐和我分别检查球车与软垫后方，没有藏人，也没有第二条出口。地图坚持体育馆里存在第三台终端，肉眼却只能看见八个人和一道正在下降的门。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch2_shutter_drop',
  ),
  'ch2_shutter_drop': StoryBeat(
    id: 'ch2_shutter_drop',
    label: '卷帘门坠落',
    speaker: Speaker.narration,
    scene: SceneKey.oldGym,
    text:
        '陈默脚下的指示灯忽然由黄转红。他没有松手，旁路柄却像被另一股力量夺走一样弹回原位。\n卷帘门从三米高处坠下。韩骐把撬棍横着塞进底缘，金属撞击声震得牙齿发酸，只争取到不足四十厘米的缝隙。苏弥和叶岚退在门外，陈默、星遥、林澄与我被截在体育馆内侧，高原仍被困在另一道门后。',
    next: 'ch2_after_drop',
  ),
  'ch2_after_drop': StoryBeat(
    id: 'ch2_after_drop',
    label: '灰尘落定以后',
    speaker: Speaker.yeLan,
    scene: SceneKey.oldGym,
    portraitMood: 'intervening',
    text:
        '灰尘从门框上簌簌落下。有人本能地去抓项圈，又在碰到金属前停住。\n“先报伤，不要报猜测。”叶岚隔着门缝说，“能呼吸的回答，不能移动的说明位置。”\n逐个声音响起以后，最糟的事实仍然没有改变：门内的人都活着，但唯一能抬门的控制箱在封锁区域深处，倒计时仍在继续。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch2_split_sides',
  ),
  'ch2_split_sides': StoryBeat(
    id: 'ch2_split_sides',
    label: '门的两侧',
    speaker: Speaker.hanQi,
    scene: SceneKey.oldGym,
    portraitMood: 'protective',
    text:
        '韩骐趴低身体，从四十厘米的缝隙把绳索、千斤顶和苏弥的止血包推了进来。\n“我可以钻进去换你们出来，但门内必须留一个人压住旁路。高原的腿不能拖，至少需要两个人抬。”\n他说得像一份普通救援分工，视线却越过门缝落在陈默身上。陈默最懂控制台，也是在他操作后门才坠落；让他留守既合理，又像一场没有证据的判决。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch2_gao_pinned',
  ),
  'ch2_gao_pinned': StoryBeat(
    id: 'ch2_gao_pinned',
    label: '09号的判断',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.oldGym,
    portraitMood: 'inspecting',
    text:
        '高原用手摸过压住小腿的器材架，又听了几秒卷帘门电机的声音。\n“腿骨没断，先别拿命换时间。旁路最多连续工作十二分钟，电机过热后会锁死。到那时，外面的人就算有钥匙也抬不起来。”\n他停了一下，声音比刚才更低：“还有，制动索的断口上没有灰。有人今天割过。”',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.gaoYuan],
    next: 'ch2_control_limit',
  ),
  'ch2_control_limit': StoryBeat(
    id: 'ch2_control_limit',
    label: '十二分钟窗口',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    portraitMood: 'discovery',
    text:
        '陈默重新拆开控制箱面板。他的指甲边缘已经被咬破，手指碰到线路时却稳得几乎没有颤动。\n“旁路不是普通开关。它同时检查压力和一台场内终端的握手信号，所以不能用绳子绑住。系统要求‘有人’留在控制箱前。”\n地图上的白色光点又亮了一次。一个不存在的人，恰好满足了控制箱正在索取的条件。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_admin_lock',
  ),
  'ch2_admin_lock': StoryBeat(
    id: 'ch2_admin_lock',
    label: '封锁规则确认',
    speaker: Speaker.administrator,
    scene: SceneKey.oldGym,
    text:
        '我向主办方确认封锁时的处决范围。扬声器没有立刻回答，像在等待问题被说得足够精确。\n“零点整，F-01内所有有效参与者执行处决。设备、终端及无效身份不计入幸存人数。”\n无效身份。它第一次主动使用了这个词，却拒绝说明白色光点属于设备、终端，还是某个不被计入幸存者的人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch2_han_plan',
  ),
  'ch2_han_plan': StoryBeat(
    id: 'ch2_han_plan',
    label: '必须留下一个人',
    speaker: Speaker.hanQi,
    scene: SceneKey.oldGym,
    portraitMood: 'protective',
    text:
        '韩骐给出当前唯一能执行的方案：先指定一人留在控制箱旁持续压住旁路，其余人利用十二分钟窗口抬出高原、搜索制动器和白色信号源。如果找不到替代方法，留守者必须在电机锁死前最后撤离。\n“别把留守说成牺牲。”他盯着我，“我们是在决定谁最有能力把最后一道门撑到所有人回来。但做决定的人，也要承担选错的后果。”\n门内外的目光同时落到我身上。01号需要别人共同作证，而现在，我必须先决定把谁留在最接近封锁中心的位置。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch2_leave_choice',
  ),
  'ch2_leave_choice': StoryBeat(
    id: 'ch2_leave_choice',
    label: '留守人选',
    speaker: Speaker.shenYan,
    scene: SceneKey.oldGym,
    text:
        '控制箱的红灯每秒闪一次。留守者必须理解何时松手，也必须相信出去的人会回来接他。韩骐有救援经验，却公开要求过01号终端；陈默最熟悉权限，却也是最后碰过控制页的人。我也可以亲自留下，但那意味着把搜索和高原的救援交给门外，并让我的同行者一起承担01终端的风险。',
    passageSpeakers: [Speaker.narration],
    next: null,
    choices: [
      StoryChoice(
        label: '让韩骐留守机械旁路',
        caption: '信任他的救援纪律，也把01终端置于他的控制范围',
        next: 'ch2_leave_hanqi',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch2_guard_hanqi'),
      ),
      StoryChoice(
        label: '让陈默继续控制权限台',
        caption: '技术效率最高，但他必须解释门为何在操作后坠落',
        next: 'ch2_leave_chenmo',
        effect: ChoiceEffect(logic: 1, flag: 'ch2_guard_chenmo'),
      ),
      StoryChoice(
        label: '我和黎星遥留在控制箱',
        caption: '让她监视握手信号，由我承担最后撤离风险',
        next: 'ch2_stay_xingyao',
        requiresFlag: 'bond_xingyao',
        effect: ChoiceEffect(
          xingyao: 1,
          cooperation: 1,
          flag: 'ch2_guard_xingyao',
        ),
      ),
      StoryChoice(
        label: '我和苏弥留在控制箱',
        caption: '将伤员交给他人抬出，由我们守住最后窗口',
        next: 'ch2_stay_sumi',
        requiresFlag: 'bond_sumi',
        effect: ChoiceEffect(sumi: 1, cooperation: 1, flag: 'ch2_guard_sumi'),
      ),
      StoryChoice(
        label: '我和林澄留在控制箱',
        caption: '使用她记录的门位变化寻找不依赖蛮力的解法',
        next: 'ch2_stay_lincheng',
        requiresFlag: 'bond_lincheng',
        effect: ChoiceEffect(lincheng: 1, logic: 1, flag: 'ch2_guard_lincheng'),
      ),
    ],
  ),
  'ch2_leave_hanqi': StoryBeat(
    id: 'ch2_leave_hanqi',
    label: '把后门交给04',
    speaker: Speaker.hanQi,
    scene: SceneKey.oldGym,
    portraitMood: 'protective',
    text:
        '韩骐没有因为被选中而露出胜利的神色。他先让我把01终端放回贴身口袋，再当着所有人的面检查旁路柄和自己的04终端。\n“你怀疑我想要你的终端，这个怀疑没错。”他说，“但救援时，出口最后一个交给谁，与平时最信任谁不是一回事。”\n他接过控制箱位置时，刻意站在离我两米以外。那是一种很笨拙的证明：他仍需要01，却不打算在这一刻利用需要。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch2_hanqi_guard_detail',
  ),
  'ch2_leave_chenmo': StoryBeat(
    id: 'ch2_leave_chenmo',
    label: '让08继续操作',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    portraitMood: 'discovery',
    text:
        '我让陈默继续压住旁路，同时要求他把每一步操作念给门内外的人听。陈默怔了一下，随后将面板完全拆开，让所有线路暴露在灯下。\n“输入端一、压力正常；输入端二、场内握手；电机温度六十八。”他像在给一段程序做公开审计，“你不必先相信我。你只要确保我没有任何一步能躲开别人的眼睛。”\n怀疑没有消失，却第一次被变成了可以共同检查的动作。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_chenmo_guard_detail',
  ),
  'ch2_stay_xingyao': StoryBeat(
    id: 'ch2_stay_xingyao',
    label: '同一条撤离频道',
    speaker: Speaker.liXingyao,
    scene: SceneKey.oldGym,
    portraitMood: 'alarm',
    text:
        '我握住旁路柄，星遥把终端接到控制箱的握手线上。门外的人开始抬高原，她却没有看他们，而是先确认我与01终端的距离。\n“你留下可以，但频道不能静默。”她把耳机塞给我一边，“每十秒叫一次我的名字。哪怕没有新情况也要叫。”\n我照做。第三次叫到“黎星遥”时，她低声回答“我在”，手背贴住我的手腕，像在确认的不只是脉搏，也是一个不会突然断开的连接。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch2_xingyao_guard_detail',
  ),
  'ch2_stay_sumi': StoryBeat(
    id: 'ch2_stay_sumi',
    label: '留守者也需要观察',
    speaker: Speaker.suMi,
    scene: SceneKey.oldGym,
    portraitMood: 'concerned',
    text:
        '我握住旁路柄，苏弥先检查我的手指能否持续发力，又把一条绷带绕在掌心最容易磨破的位置。\n“高原交给叶岚和韩骐，我留下。”她没有使用医生式的命令口吻，“不是因为你需要监护，是因为我不接受你替所有人承担风险以后，再把自己的状态从记录里删掉。”\n电机震动沿着金属柄传进骨头。苏弥的手覆在我手背上分担压力，温度清楚得让我无法把自己只当成一件临时工具。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch2_sumi_guard_detail',
  ),
  'ch2_stay_lincheng': StoryBeat(
    id: 'ch2_stay_lincheng',
    label: '两个人的门位图',
    speaker: Speaker.linCheng,
    scene: SceneKey.oldGym,
    portraitMood: 'determined',
    text:
        '我握住旁路柄，林澄蹲在地上，用粉笔标记卷帘门每次抬升的高度和电机声变化。她没有逞强去碰控制线，而是把自己能够确认的事实一项项写在我脚边。\n“我知道你可能想让我先出去。”她没有抬头，“但地图不是站在安全地方才画得出来的。我留在这里，是因为我能做这件事，不是因为你没来得及赶我走。”\n我答应不擅自替她决定。她这才把第一条可能通向手动制动器的虚线延伸到器材室。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch2_lincheng_guard_detail',
  ),
  'ch2_search_window': StoryBeat(
    id: 'ch2_search_window',
    label: '十二分钟调查',
    speaker: Speaker.narration,
    scene: SceneKey.oldGym,
    text:
        '旁路重新接通，卷帘门缓慢抬起。韩骐和叶岚从门缝下钻向高原，其他人分开检查控制箱、制动机构和白色信号源。\n我们只有十二分钟。每多花一分钟确认一件物品，留守者就少一分钟撤离余量；可如果只顾着抬人出去，下一道门仍会用同样的方法逼我们留下一个人。',
    next: 'ch2_gym_investigation',
  ),
  'ch2_gym_investigation': StoryBeat(
    id: 'ch2_gym_investigation',
    label: 'F-01现场调查',
    text: '',
    scene: SceneKey.oldGym,
    next: 'ch2_three_sabotages',
    phase: StoryPhase.investigation,
  ),
  'ch2_three_sabotages': StoryBeat(
    id: 'ch2_three_sabotages',
    label: '不是一次故障',
    speaker: Speaker.shenYan,
    scene: SceneKey.oldGym,
    text:
        '三件物品拼出了同一个方向。控制箱内部的铜线桥接早于陈默打开面板；制动索是今天被工具齐整割断；空终端底座则一直向主机回放无编号握手。\n这不是老建筑在封锁前碰巧坏掉。有人提前保证门会落下、远程操作会失效，并让地图显示体育馆里比实际多一个“参与者”。\n真正的问题不再是谁必须留下，而是系统为什么愿意把一只空底座认成一个人。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_fault_hypotheses',
  ),
  'ch2_bridge_detail': StoryBeat(
    id: 'ch2_bridge_detail',
    label: '预先桥接的输入端',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    portraitMood: 'discovery',
    text:
        '陈默用绝缘夹抬起两根交叉铜线。新铜的颜色比周围旧端子亮得刺眼。\n“这组桥接让控制页第一次打开时自动登记操作者，再在十分钟后撤销旁路权限。门不是因为我按错才落下，它等的就是有人来查看。”\n他把自己的操作记录投到公共频道。那份记录不能证明他无辜，却证明陷阱在他碰到面板之前已经存在。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_control_countertest',
  ),
  'ch2_cable_detail': StoryBeat(
    id: 'ch2_cable_detail',
    label: '没有灰的断口',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.oldGym,
    portraitMood: 'inspecting',
    text:
        '高原被抬出器材架后，坚持先看制动索照片。断开的钢丝向同一方向倾斜，封条碎片却落在不可能由坠落造成的位置。\n“液压钳，两次剪切。切完以后又把断口搭回滑轮，所以第一次测试还能升门。”\n也就是说，破坏者不只来过体育馆，还知道高原会采用怎样的检查顺序。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch2_cable_countertest',
  ),
  'ch2_cradle_detail': StoryBeat(
    id: 'ch2_cradle_detail',
    label: '12号握手缓存',
    speaker: Speaker.liXingyao,
    scene: SceneKey.oldGym,
    portraitMood: 'alarm',
    text:
        '星遥撬开空底座的接口盖，将读取线接到离线终端。缓存里只有一条循环记录：身份槽12，状态有效，持有者距离零点零米。\n“它没有定位一个人。”她说，“它在每七秒重播一次‘12号就在这里’。”\n主办方把12号计入初始人数，却允许一段没有持有者的握手通过验证。空椅、空宿舍和这个空底座，第一次由同一条技术证据连在一起。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch2_cradle_countertest',
  ),
  'ch2_twelve_hypotheses': StoryBeat(
    id: 'ch2_twelve_hypotheses',
    label: '人，还是占位符',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    text:
        '陈默认为12号可能曾经存在，只是终端被回收后留下了用于测试的身份槽。星遥却指出缓存每天都被重新签名，说明主机至今仍主动维护这个空身份。\n“要么有一个我们看不见的12号在系统外操作，”我说，“要么12号从一开始就不是参与者，而是主办方为了让人数与规则成立，故意留在名单里的占位符。”\n两种解释都无法立即验证，但空底座给了我们一个更紧迫的用途：它可以替代控制箱要求的场内握手。',
    passageSpeakers: [Speaker.narration, Speaker.shenYan, Speaker.narration],
    next: 'ch2_escape_proposal',
  ),
  'ch2_escape_proposal': StoryBeat(
    id: 'ch2_escape_proposal',
    label: '让空身份留守',
    speaker: Speaker.shenYan,
    scene: SceneKey.oldGym,
    text:
        '我把空底座、桥接输入和封锁规则写在同一张纸上。控制箱要的不是呼吸和脉搏，只是一段通过验证的场内终端握手；封锁规则处决的是有效参与者，不处决设备和无效身份。\n“我们不需要留下任何一个人。”\n我指向仍在闪烁的白色光点：“让12号留在这里。既然主办方把它算作占用者，就让它替我们守住最后一扇门。”',
    passageSpeakers: [Speaker.narration, Speaker.shenYan, Speaker.shenYan],
    next: 'ch2_handshake_test',
  ),
  'ch2_handshake_test': StoryBeat(
    id: 'ch2_handshake_test',
    label: '零点零米',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    portraitMood: 'discovery',
    text:
        '陈默没有立刻接线。他先用自己的终端模拟旁路请求，确认错误输入只会落门，不会触发项圈；星遥则把12号缓存复制到一块与主网隔离的测试模块。\n第三次验证后，他们将空底座接入控制箱。红灯熄灭，屏幕出现一行绿色状态：场内操作员有效，距离零点零米。\n所有人都看着旁路柄。留守者慢慢松开手，卷帘门没有落下。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_test_doubt',
  ),
  'ch2_false_occupant': StoryBeat(
    id: 'ch2_false_occupant',
    label: '地图上的假人',
    speaker: Speaker.liXingyao,
    scene: SceneKey.oldGym,
    portraitMood: 'alarm',
    text:
        '区域地图立即更新：08和09的光点开始向出口移动，白色光点仍停在体育馆中线。占用人数没有从三变成二，反而始终维持为三。\n“系统认为12号在替我们压着开关。”星遥盯着信号强度，“它甚至不知道底座里没有终端。”\n这是漏洞，也是主办方亲手留下的证词。只要所有人能在零点前离开，封锁就会替我们验证12号究竟算不算活人。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch2_release_start',
  ),
  'ch2_release_start': StoryBeat(
    id: 'ch2_release_start',
    label: '救援开始',
    speaker: Speaker.hanQi,
    scene: SceneKey.oldGym,
    portraitMood: 'protective',
    text:
        '“停止讨论，按顺序撤离。”韩骐把绳索绕过器材架横梁，“先高原，再无法负重的人，最后拆线组。”\n没有人反驳。苏弥固定高原的小腿，叶岚在门外报卷帘高度，林澄把最短路线的粉笔箭头一直画到防火门外。先前互相怀疑的声音没有消失，只是在这几分钟里被更具体的动作压到后面。',
    passageSpeakers: [Speaker.hanQi, Speaker.narration],
    next: 'ch2_rescue_obstacle',
  ),
  'ch2_rescue_gao': StoryBeat(
    id: 'ch2_rescue_gao',
    label: '抬出09号',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.oldGym,
    portraitMood: 'inspecting',
    text:
        '器材架被千斤顶顶起时，高原咬住折叠毛巾，没有让自己喊出声。脱困后的第一件事却是伸手摸卷帘门轨道。\n“还撑得住七分钟。”他说。\n苏弥骂了他一句，让他至少在被抬出去以前先像伤员。高原怔了怔，终于把身体重量交给韩骐和叶岚，闭眼承认自己的腿正在发抖。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch2_last_exit',
  ),
  'ch2_last_exit': StoryBeat(
    id: 'ch2_last_exit',
    label: '最后撤离顺序',
    speaker: Speaker.narration,
    scene: SceneKey.oldGym,
    text:
        '陈默和星遥最后检查了一次空底座的供电，把读取副本和纸面记录分别交给门内外两个人。没人把全部证据放在同一只终端里。\n我跨过体育馆门槛时，01号与身体的距离始终没有超过半米。韩骐在外侧逐个点名：01、02、03、04、06、07、08、09、11。九个活人的声音依次回答。\n地图仍显示区域内有一个占用者。白色光点独自留在我们刚刚清空的木地板中央。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_final_seconds',
  ),
  'ch2_final_seconds': StoryBeat(
    id: 'ch2_final_seconds',
    label: '零点前两分钟',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    timelineMinute: 1438,
    text:
        '我们退到F-01边界黄线之外。没有人坐下，高原也坚持靠墙站着。体育馆内的应急灯由黄转红，卷帘门一层层落下，将空底座和那道白色信号封在里面。\n倒计时最后十秒，所有人都摸到了自己的终端，却没有人去碰项圈。星遥开始报秒，声音在第五秒轻微发紧；苏弥接过第六秒，韩骐报到九。\n零点到来时，整栋建筑的灯同时熄灭。',
    next: 'ch2_seal_complete',
  ),
  'ch2_seal_complete': StoryBeat(
    id: 'ch2_seal_complete',
    label: '第一次永久封锁',
    speaker: Speaker.administrator,
    scene: SceneKey.corridor,
    timelineMinute: 1440,
    text:
        '黑暗只持续了三秒。灯光恢复后，F-01的防火门已经变成没有接缝的红色墙面，区域地图覆盖上一层黑色网格。\n“第一次永久封锁完成。区域内有效参与者：零。执行处决人数：零。当前存活人数：十。”\n白色光点在黑色网格下闪烁最后一次，随后消失。主办方承认体育馆里有占用者，却不承认那里有需要被处决的人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch2_seal_silence',
  ),
  'ch2_survivor_count': StoryBeat(
    id: 'ch2_survivor_count',
    label: '十名存活者',
    speaker: Speaker.tangYi,
    scene: SceneKey.corridor,
    text:
        '唐弈第一个发现人数仍然是十。\n“可我们这里只有九个会回答点名的人。”他把硬币在指节间转了一圈，这次没有笑，“主办方一直把12号算进存活人数，却在处决时又称它为无效身份。它想什么时候把12号当人，就什么时候当人。”\n这意味着所有以“存活人数”为条件的条款都可能被一个不存在的人改变。苏弥的至少六人、唐弈的恰好四人，甚至我需要的四名证人，都建立在一份可以被主办方随时改写的名册上。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch2_aftershock',
  ),
  'ch2_aftershock': StoryBeat(
    id: 'ch2_aftershock',
    label: '活下来以后的颤抖',
    speaker: Speaker.yeLan,
    scene: SceneKey.corridor,
    portraitMood: 'intervening',
    text:
        '危险解除以后，身体才开始追上刚才发生的事。陈默坐在地上反复擦手，高原疼得无法继续站立，星遥仍戴着已经没有信号的耳机。林澄把粉笔折成了三段，自己却没有察觉。\n叶岚让每个人说出眼前能确认的一件事。有人说门已经封死，有人说高原还活着，有人说自己的终端就在手里。\n轮到我时，我说：“我们没有留下任何人。”这句话出口以后，走廊里才第一次有人真正呼出一口长气。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.shenYan],
    next: 'ch2_triage_gao',
  ),
  'ch2_confront_chen': StoryBeat(
    id: 'ch2_confront_chen',
    label: '08号保留的记录',
    speaker: Speaker.chenMo,
    scene: SceneKey.corridor,
    portraitMood: 'discovery',
    text:
        '陈默承认，他在体育馆控制页里还看见过一份封锁队列，却没有第一时间公开。队列不是固定日期，而是根据“区域内有效身份数量”实时排序。\n“我怕说出来以后，所有人会为了改变顺序把别人赶进某个区域。”他盯着被咬破的指甲，“但我不说，陷阱还是照样利用了我们不知道的规则。”\n韩骐没有原谅他的隐瞒，只要求他把原始缓存、读取方法和自己删过的每一条临时文件全部交给三个人分别保管。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_order_algorithm',
  ),
  'ch2_order_algorithm': StoryBeat(
    id: 'ch2_order_algorithm',
    label: '封锁顺序会选择人',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '陈默恢复出的队列显示，旧体育馆并不是主办方提前指定的第一封锁区。白色12号信号进入F-01后，那里的“有效身份数量”被提高，排序才在四十分钟前跳到第一。\n封锁顺序看似在选择房间，实际是在追逐人群。只要有人能伪造一个区域里有多少身份，就能决定下一道墙落在哪里，也能把任何救援变成是否留下同伴的表决。\n中继器杀死周叙，是利用规则伪造距离；体育馆陷阱则更进一步，开始利用我们对彼此的怀疑安排空间。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_map_cost',
  ),
  'ch2_aftermath_choice': StoryBeat(
    id: 'ch2_aftermath_choice',
    label: '封锁后的第一小时',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '众人把高原送到临时医务点，开始重新绘制已经失去F-01的地图。身体和神经都在要求休息，可今晚留下的恐惧不会因为散会消失。我可以先去陪那个与我共同承担风险的人，也可以留在集合厅参与公开复盘，把所有细节整理成任何人都能检查的记录。',
    passageSpeakers: [Speaker.narration],
    next: null,
    choices: [
      StoryChoice(
        label: '与黎星遥复核私人频道',
        caption: '确认连接仍在，也确认她没有独自吞下刚才的恐惧',
        next: 'ch2_xingyao_aftercare',
        requiresFlag: 'bond_xingyao',
        effect: ChoiceEffect(xingyao: 1, flag: 'ch2_xingyao_bond'),
      ),
      StoryChoice(
        label: '帮苏弥完成最后一份检伤',
        caption: '让她也成为被记录和照顾的人',
        next: 'ch2_sumi_aftercare',
        requiresFlag: 'bond_sumi',
        effect: ChoiceEffect(sumi: 1, flag: 'ch2_sumi_bond'),
      ),
      StoryChoice(
        label: '和林澄补全封锁后的地图',
        caption: '把她在门内确认的事实写进所有人的路线',
        next: 'ch2_lincheng_aftercare',
        requiresFlag: 'bond_lincheng',
        effect: ChoiceEffect(lincheng: 1, flag: 'ch2_lincheng_bond'),
      ),
      StoryChoice(
        label: '留在集合厅主持公开复盘',
        caption: '优先把12号和封锁算法变成公共证据',
        next: 'ch2_group_debrief',
        effect: ChoiceEffect(cooperation: 1, logic: 1, flag: 'ch2_open_record'),
      ),
    ],
  ),
  'ch2_xingyao_aftercare': StoryBeat(
    id: 'ch2_xingyao_aftercare',
    label: '频道仍然在线',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'alarm',
    text:
        '星遥坐在封闭区外的地面上，一遍遍扫描已经没有回应的F-01频率。我在她身边坐下，没有先问结果，只按约定叫了一次她的名字。\n“我在。”她几乎立刻回答，随后才意识到我们之间根本没有隔着耳机。\n她将共享频道调成只够两副耳机接收的低功率模式，肩膀靠过来。“这个不是为了保密。只是今晚，我想先确认一个不会突然消失的声音。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.liXingyao],
    next: 'ch2_xingyao_aftercare_detail',
  ),
  'ch2_sumi_aftercare': StoryBeat(
    id: 'ch2_sumi_aftercare',
    label: '把名字写进检伤表',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'relieved',
    text:
        '苏弥处理完高原的腿伤，才发现自己掌心被卷帘门边缘划开了一道口子。她说只是表皮伤，继续低头整理器械。\n我把最后一张检伤卡放到她面前，在姓名栏写下“苏弥”。\n她盯着自己的名字看了很久，终于把手交给我清洗伤口。“你可以包得难看一点。”她轻声说，“这样我明天还有理由重新教你一次。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.suMi],
    next: 'ch2_sumi_aftercare_detail',
  ),
  'ch2_lincheng_aftercare': StoryBeat(
    id: 'ch2_lincheng_aftercare',
    label: '名字写在路线终点',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '林澄把F-01涂成黑色，却没有把里面的路线擦掉。她说封锁区仍然属于证据，不能因为再也进不去就假装那里不存在。\n新地图的撤离终点旁，她没有写01和07，而是写了“沈砚、林澄”。\n“刚才我真的很怕你会让我先走。”她捏着只剩半截的铅笔，“后来你问我能做什么，而不是替我决定。我想把这件事也记下来，免得以后害怕的时候忘了。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.linCheng],
    next: 'ch2_lincheng_aftercare_detail',
  ),
  'ch2_group_debrief': StoryBeat(
    id: 'ch2_group_debrief',
    label: '公开的封锁记录',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    text:
        '我把控制箱照片、制动索断口、12号缓存和每个人的行动时间写到四张纸上，分别交给不同的人校对。陈默补充自己隐瞒的队列，高原修正设备判断，星遥删除了只有她才能读懂的缩写。\n叶岚在记录末尾写下：本次无人被留下，不是因为所有人互相信任，而是因为任何一个结论都允许别人复查。\n这份记录没有让我们成为朋友，却让下一次有人说“必须牺牲一个人”时，其他人会先问一句：这个前提是谁给的。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch2_debrief_dissent',
  ),
  'ch2_dawn_map': StoryBeat(
    id: 'ch2_dawn_map',
    label: '失去一块区域的地图',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '凌晨一点，重新绘制的地图贴满集合厅整面墙。F-01被黑线封死，所有通往体育馆的捷径一并消失，医疗区与宿舍区之间只剩一条必须经过档案库的长廊。\n空间真的变小了。此前可以绕开的冲突、可以分散保管的物资、可以独处冷静的角落，都随着一道墙永久减少。\n可地图旁边多出了一条所有人签名的规则：任何封锁人数必须同时由真人点名、纸面位置和终端握手三方确认。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_night_watch',
  ),
  'ch2_next_seal': StoryBeat(
    id: 'ch2_next_seal',
    label: '移动的12号',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '新一轮封锁候选区刷新时，星遥忽然站起。原本应该和空底座一起被封在F-01里的白色光点，出现在档案库E-04。\n信号仍然每七秒闪烁一次，身份槽仍然是12，距离却跨过了一道已经永久封死、没有任何门缝的墙。\n“不是底座在移动。”她把频谱投上主屏，“是有人在不同区域重放同一个12号。封锁顺序会追着这个幽灵走。”',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.liXingyao],
    next: 'ch2_end',
  ),
  'ch2_end': StoryBeat(
    id: 'ch2_end',
    label: '12号第一次拥有方向',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '屏幕上的12号光点停在档案库深处，正好覆盖林澄曾经画出的那条备用通道。下一次封锁还有二十三小时五十七分。\n我们救出了体育馆里真实存在的人，也证明了主办方能够让不存在的人决定门落在哪里。第一天结束时，死亡游戏不再只是要求我们满足各自的条款；它开始主动安排我们必须怀疑谁、放弃谁。\n我在新的地图上圈住E-04。隔着已经封死的体育馆，12号第一次拥有了方向。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch3_chapter_title',
    auditNext: 'ch2_audit_index',
    auditRequiredFlags: {'case01_solved'},
  ),
  'ch2_audit_index': StoryBeat(
    id: 'ch2_audit_index',
    label: '被普通界面折叠的灰色索引',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '地图刷新前，审计周目保留的离线层突然多出一行灰字。它不属于12号的位置记录，而像一张被主界面藏起来的目录：F-01空身份、B-03撤销会话、E-04高危物资校验，共用同一组审计表头。\n星遥把PDA断网后，那行字仍在。“一周目我们只看见系统愿意解释的结果。”她压低声音，“这次它把删去内容的页码也留下了。”\n目录没有给出物资名称，只留下三种字段：身份槽、会话尾码、重放间隔。我将它复制进离线证据区。只有同时复原两起案件，才可能在后面的转运缓存里还原对应记录。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    flagsOnEnter: {'audit_index_fragment'},
    next: 'ch3_chapter_title',
  ),
};

const chapterTwoExpansionBeats = <String, StoryBeat>{
  'ch2_chen_entry_reason': StoryBeat(
    id: 'ch2_chen_entry_reason',
    label: '08为何进入体育馆',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'discovery',
    text:
        '我要求陈默先说明他为什么在封锁名单公布前进入体育馆。频道沉默了两秒，像他没想到求救还要先接受询问。\n“控制页在二十三点零四分主动给我发了权限异常。”他说，“提示F-01有一台未登记终端。我以为和中继器日志有关，所以叫高原一起看设备，没有告诉所有人。”\n他担心公开异常会让凶手先一步销毁证据。这个理由成立，也意味着他又一次独自决定了哪些危险可以不告诉别人。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_gao_entry_reason',
  ),
  'ch2_gao_entry_reason': StoryBeat(
    id: 'ch2_gao_entry_reason',
    label: '09听见了什么',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'inspecting',
    text:
        '高原补充，他从晚间设备循环里听见体育馆卷帘电机多转了半圈。旧建筑的声音会沿管道传到集合厅，只有这一台在停止后又出现一次短促回拉。\n“我以为制动器卡涩。陈默要看控制页，我要看机械端，所以一起进来。”\n他没有替陈默保证权限操作，也没有为自己辩护。两个人分别被不同异常引进同一间即将封锁的房间，这本身就像有人按职业准备好的诱饵。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch2_self_staged_suspicion',
  ),
  'ch2_self_staged_suspicion': StoryBeat(
    id: 'ch2_self_staged_suspicion',
    label: '是否自导自演',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    text:
        '唐弈没有立刻主张救援。他问陈默，既然控制页能登记操作者，是否也能把另一个人登记成受困者；又问高原，器材架与断索会不会只是为了把所有人引向F-01。\n“救人当然可以。”他把硬币扣在指间，“但别忘了，体育馆里那两个人最清楚门怎么坏，也最有机会提前让它坏。”\n苏弥冷冷提醒，高原的频道呼吸和撞击声符合真实压伤。怀疑可以决定我们带多少人进去，不能成为拖延急救的借口。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch2_rescue_inventory',
  ),
  'ch2_rescue_inventory': StoryBeat(
    id: 'ch2_rescue_inventory',
    label: '出发前分工',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'protective',
    text:
        '韩骐把救援物资摊在地上，只拿绳索、千斤顶、撬棍、止血包和两支手电。多一件工具就多一只需要看管的手，也可能让门口更拥挤。\n“苏弥负责伤情，高原只提供设备判断，不参与抬升；星遥监视信号；林澄记录来路；叶岚留在门外点名。”\n他说到我时停了一下：“01不能落在队尾。你的终端同时是别人的条款目标，所有人必须看见它在哪里。”',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.hanQi],
    next: 'ch2_approach_choice',
  ),
  'ch2_approach_choice': StoryBeat(
    id: 'ch2_approach_choice',
    label: '选择接近路线',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '通往F-01有三种走法。西侧设备梯最快，但经过两道状态不明的卷帘门；档案库绕行更远，却能确认白色信号是否曾经过E-04；沿主走廊全员同行最稳妥，但无法同时从另一侧观察体育馆出口。我们没有一条完全安全的路，只能决定优先保住时间、信息还是队伍完整。',
    passageSpeakers: [Speaker.narration],
    next: null,
    choices: [
      StoryChoice(
        label: '走西侧设备梯抢时间',
        caption: '最快抵达，并沿途确认卷帘机构的异常声响',
        next: 'ch2_route_service',
        effect: ChoiceEffect(logic: 1, flag: 'ch2_route_service'),
      ),
      StoryChoice(
        label: '绕行档案库追踪白色信号',
        caption: '牺牲几分钟，验证12号是否与E-04存在连接',
        next: 'ch2_route_archive',
        effect: ChoiceEffect(logic: 1, flag: 'ch2_route_archive'),
      ),
      StoryChoice(
        label: '全员沿主走廊共同进入',
        caption: '不拆分救援组，避免第二处诱饵让队伍失联',
        next: 'ch2_route_together',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch2_route_together'),
      ),
    ],
  ),
  'ch2_route_service': StoryBeat(
    id: 'ch2_route_service',
    label: '设备梯里的刮擦声',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.corridor,
    portraitMood: 'inspecting',
    text:
        '设备梯只能容纳两人并肩。我们下到F层时，墙内传来一声短促刮擦，像钢索被绷紧后又突然松开。\n高原在频道里听见我描述声音，立刻说那不是电机，而是制动索末端扫过空滑轮。体育馆北门的机械制动在我们抵达前就已经失效。\n这条路节省了时间，也提前排除了“陈默按错控制页才让门损坏”的一种解释。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_rush_corridor',
  ),
  'ch2_route_archive': StoryBeat(
    id: 'ch2_route_archive',
    label: 'E-04门前的回声',
    speaker: Speaker.liXingyao,
    scene: SceneKey.archiveCorridor,
    portraitMood: 'alarm',
    text:
        '经过档案库E-04时，星遥的屏幕上短暂出现第二圈白色脉冲。它只维持十四秒，随后与体育馆里的信号重新重合，像同一个身份在两处底座之间完成了一次握手切换。\n门禁拒绝开启，缝隙后也没有脚步。林澄在地图上圈住E-04，写下准确时间。\n我们因此晚了三分钟，却第一次知道白色信号并不只属于体育馆。它可以沿着建筑内部看不见的网络换位置。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_rush_corridor',
  ),
  'ch2_route_together': StoryBeat(
    id: 'ch2_route_together',
    label: '所有声音都在频道里',
    speaker: Speaker.yeLan,
    scene: SceneKey.corridor,
    text:
        '我们沿主走廊保持前后两米内可见，每过一道门就由最前和最后的人同时报姓名。没有人单独去查看侧面响动，也没有人因为熟悉设备而脱离队伍。\n“把九个人排成一串，正适合被一扇门全部关住。”唐弈看着头顶连续亮起的门位灯，“至少分两组，还有一组能在外面想办法。”\n“分组也等于给诱饵两次把人引走的机会。”叶岚没有停步，“这条路线的代价是慢，收益是任何人想改变方向，都得在九双眼睛前解释。”\n唐弈没有赞同，却仍按约定在下一扇门报出自己的名字。速度最慢的走法没有提供新线索，但抵达体育馆时，每个人的去向都有共同证言。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch2_rush_corridor',
  ),
  'ch2_route_recovery': StoryBeat(
    id: 'ch2_route_recovery',
    label: '地图上没有的防火门',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'determined',
    text:
        '第二道防火门在队伍通过一半时突然落下。林澄立即翻到地图背面，指出右侧维护凹槽与上一层墙线不一致，后面应该留有供线缆穿过的窄门。\n韩骐没有直接撬门，而是先让所有人退离下落轨道。高原通过频道指导他扳开机械锁，整组人用了九十秒重新会合。\n如果林澄没有保留那些看似无用的墙厚记录，我们会在离体育馆不到三十米的位置被迫分成两边。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_radio_dead_zone',
  ),
  'ch2_radio_dead_zone': StoryBeat(
    id: 'ch2_radio_dead_zone',
    label: '最后二十米的静默',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'alarm',
    text:
        '靠近F-01后，公共频道被宽带噪声盖住。星遥让大家关闭自动增益，改用每十秒一次的短按发射确认位置。陈默和高原的声音仍能传出，却像隔着一层不断收紧的金属。\n噪声频谱与12号七秒脉冲不相同，说明有人不仅准备了门的故障，也准备让救援者在最后一段路失去连续沟通。\n我们无法再从频道判断他们是否撒谎，只能带着尚未解决的怀疑进入现场。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_gym_entry',
  ),
  'ch2_first_visual_sweep': StoryBeat(
    id: 'ch2_first_visual_sweep',
    label: '先数人，再看设备',
    speaker: Speaker.yeLan,
    scene: SceneKey.oldGym,
    text:
        '叶岚站在门外逐个确认身体：陈默在控制箱，高原被压在北侧，救援组全部抵达。体育馆没有第三个人回应，看台后的阴影也没有移动。\n“每人只报一项亲眼所见。”她抬起记录板，“不要说‘有人设陷阱’，不要说‘12号在里面’。只说现在能指给别人看的东西。”\n“北门离地四十厘米。”韩骐先开口。苏弥紧接着说：“高原意识清醒，左腿受压。”星遥盯着终端：“白色信号在中线，但中线没有人。”\n“控制箱红灯每秒一次。”林澄补上最后一项。叶岚把四句话逐字写下。这套近乎笨拙的点名把想象压回可检查的范围，也让任何人都不能悄悄把推测说成亲眼所见。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.hanQi,
      Speaker.linCheng,
    ],
    next: 'ch2_chen_panel_account',
  ),
  'ch2_chen_panel_account': StoryBeat(
    id: 'ch2_chen_panel_account',
    label: '陈默的操作顺序',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    portraitMood: 'discovery',
    text:
        '陈默按照时间重新念出自己的每一步：打开只读页、读取未登记终端、页面自动切换到现场操作员、北门坠落、南门提示旁路保持。他没有省略自己曾尝试远程撤销登记。\n“撤销按钮出现了不到一秒，随后被管理员权限覆盖。”他说，“我截到了缓存，但不敢松手拿给你们看。”\n星遥要求他先报缓存校验值而不是发送文件。值与集合厅收到的求援包一致，至少证明这份记录没有在我们赶来途中被重新编辑。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_gao_device_account',
  ),
  'ch2_gao_device_account': StoryBeat(
    id: 'ch2_gao_device_account',
    label: '高原的十二秒',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.oldGym,
    portraitMood: 'inspecting',
    text:
        '高原说北门坠落前，电机先空转了十二秒。他赶去拉机械制动时，器材架被卷帘末端带倒，压住左腿。\n“如果制动索自然老化，断裂会发生在负载最高的时候，不会先空转十二秒。”\n他看不见控制箱，也无法证明陈默没有动手；陈默同样看不见北门，无法证明器材架不是高原提前布置。两人的证言互相补足设备过程，却没有互相提供不在场证明。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch2_ghost_ping',
  ),
  'ch2_hanqi_guard_detail': StoryBeat(
    id: 'ch2_hanqi_guard_detail',
    label: '04号的撤离口令',
    speaker: Speaker.hanQi,
    scene: SceneKey.oldGym,
    portraitMood: 'protective',
    text:
        '接管旁路后，韩骐先试了三次门位，把“松手后两秒开始下落、四秒触及肩高”报给门内外所有人。他要求任何撤离命令都必须由门外叶岚复述一次，避免有人只对他下达别人听不见的指令。\n“我想要01终端是事实。”他对我说，“所以你更不能只靠我说自己不会拿。”\n他把欲望放进公开流程，不等于欲望消失，却让它第一次有了别人能够监督的边界。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch2_search_window',
  ),
  'ch2_chenmo_guard_detail': StoryBeat(
    id: 'ch2_chenmo_guard_detail',
    label: '08号的公开操作',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    portraitMood: 'discovery',
    text:
        '陈默把螺丝刀和备用线交到门外，只留下压住旁路所需的一只手。每当控制页刷新，他都先念时间，再念输入值，最后由星遥核对频道缓存。\n“你们可以继续怀疑我。”他说到第三次时嗓子已经发干，“但别用怀疑代替记录。记录至少能告诉你我哪一步真的做过。”\n我没有回答他是否清白，只让叶岚把那句话和时间一起写下。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch2_search_window',
  ),
  'ch2_xingyao_guard_detail': StoryBeat(
    id: 'ch2_xingyao_guard_detail',
    label: '共享一边耳机',
    speaker: Speaker.liXingyao,
    scene: SceneKey.oldGym,
    portraitMood: 'alarm',
    text:
        '星遥将一边耳机留给我，另一边监听控制箱。她把十秒一次的呼叫改成五秒，因为宽带噪声仍在缓慢增强。\n“如果我突然不回答，先看我的手，不要立刻松开旁路。”她说，“断线可能只是频道问题。别让声音替现实做决定。”\n几分钟前她还需要我不断叫她的名字，现在她又提醒我不要只依赖回应。信任不是把判断交给对方，而是在慌乱时仍愿意一起核对。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch2_search_window',
  ),
  'ch2_sumi_guard_detail': StoryBeat(
    id: 'ch2_sumi_guard_detail',
    label: '握力与脉搏',
    speaker: Speaker.suMi,
    scene: SceneKey.oldGym,
    portraitMood: 'concerned',
    text:
        '苏弥每隔一分钟检查我握旁路的手指颜色和腕部脉搏。她没有用“坚持住”催促，而是提前告诉我出现麻木、视野缩窄或无法完整说句子时必须换人。\n“牺牲通常不是一瞬间决定的。”她替我调整绷带，“更多时候，是所有人默认某个人还能再撑一分钟。”\n我答应把每一次疼痛说出来。对习惯用事实压住情绪的我而言，这比握紧金属柄更难。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch2_search_window',
  ),
  'ch2_lincheng_guard_detail': StoryBeat(
    id: 'ch2_lincheng_guard_detail',
    label: '不依赖蛮力的门位图',
    speaker: Speaker.linCheng,
    scene: SceneKey.oldGym,
    portraitMood: 'determined',
    text:
        '林澄把每次电机震动对应的门高写成一列数字，又用粉笔在地面画出旁路柄松开后的下降曲线。第三次记录后，她发现门在二十七厘米处会短暂停顿半秒。\n“不是足够让人钻出去的时间。”她强调，“但可以在最后撤离时给绳结多一次脱开的机会。”\n她没有把观察夸大成解法。正因为只说自己确认的半秒，那半秒才成为所有人能够使用的安全余量。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch2_search_window',
  ),
  'ch2_fault_hypotheses': StoryBeat(
    id: 'ch2_fault_hypotheses',
    label: '先不把故障叫作陷阱',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.oldGym,
    portraitMood: 'inspecting',
    text:
        '高原要求我们暂时不用“蓄意破坏”这个词。桥接线可能是维修遗留，钢索可能在旧裂口上二次断开，空底座也可能只是测试设备。\n“三件异常同时出现很可疑，但可疑不是机械结论。”\n我们分别为每件物品寻找一种无恶意解释，再设计能够推翻它的检查。只有三个反证都成立，体育馆事故才不是被恐惧拼出来的阴谋。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch2_bridge_detail',
  ),
  'ch2_control_countertest': StoryBeat(
    id: 'ch2_control_countertest',
    label: '维修遗留不成立',
    speaker: Speaker.chenMo,
    scene: SceneKey.oldGym,
    portraitMood: 'discovery',
    text:
        '陈默把端子图摊在控制箱旁。“正常维修桥接会绕过故障传感器。这根线没碰传感器，它把‘首次查看’直接接到了‘登记操作者’。”\n“也可能是工人测试后忘了拆。”唐弈仍没有放下那种最普通的解释。\n星遥接上从维修推车找到的离线测试线。“那就不接设施主机，只复现一次输入。”页面亮起后，十分钟撤权计时立刻出现。她把屏幕转向众人，“遗留测试线不会专门等第一个查看的人。”\n铜线长度刚好够藏回面板，线头没有多余弯折。控制箱不是修坏了，而是被改造成谁来调查异常，谁就会被登记进陷阱。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.tangYi,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch2_cable_detail',
  ),
  'ch2_cable_countertest': StoryBeat(
    id: 'ch2_cable_countertest',
    label: '旧裂口不成立',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.oldGym,
    portraitMood: 'inspecting',
    text:
        '高原让林澄分别把断口、滑轮槽和地面的灰装进纸袋。“旧钢索如果早就裂开，裸露金属会氧化，滑轮里也会积断丝。别只看断口亮不亮，三个位置要能对上。”\n林澄把纸袋排成一列。“滑轮槽是旧灰，断面没有氧化。金属碎屑只落在这片被移动过的封条上，所以切断和移动封条发生在同一段时间。”\n高原用折叠放大镜对准钢丝两侧。“这里，还有这里。两道角度一样的钳口咬痕。自然断裂不会从两边整齐地咬一口。”\n第二种无恶意解释被排除：不是旧损伤终于撑不住，而是有人让新剪断的钢索看起来像在负载中突然断开。',
    passageSpeakers: [
      Speaker.gaoYuan,
      Speaker.linCheng,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch2_cradle_detail',
  ),
  'ch2_cradle_countertest': StoryBeat(
    id: 'ch2_cradle_countertest',
    label: '普通测试设备不成立',
    speaker: Speaker.liXingyao,
    scene: SceneKey.oldGym,
    portraitMood: 'alarm',
    text:
        '星遥先切断底座外部网络。白色指示灯仍按七秒间隔闪烁，她把离线脉冲记录给陈默看。“不是主机临时回包。握手预先写在底座里。”\n陈默再拔掉身份模块，签名却继续被控制页接受。“验证密钥不在这只空壳里。有人让主机预先信任了12号。”\n“普通测试账号应该标记为模拟，也不该进入存活人数。”星遥将身份槽、状态和距离三项并排投到终端上，“它唯一稳定完成的功能，就是让系统相信一个不存在的人在场。”\n第三种无恶意解释也无法成立。空底座不是被遗忘的测试设备，而是仍在参与封锁判断的伪造身份。',
    passageSpeakers: [
      Speaker.liXingyao,
      Speaker.chenMo,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch2_twelve_hypotheses',
  ),
  'ch2_test_doubt': StoryBeat(
    id: 'ch2_test_doubt',
    label: '测试成功不等于能够活着',
    speaker: Speaker.tangYi,
    scene: SceneKey.oldGym,
    text:
        '唐弈提醒我们，控制箱接受12号握手只证明门不会立刻落下，不证明零点时主办方会把它视为无效身份。系统完全可能先允许替代，再用“场内仍有参与者”执行处决。\n“你们是在拿所有人的撤离时间赌一个词的定义。”\n他说得没错。我们只能用广播刚才的原句限制风险：封锁处决“有效参与者”，而管理员已经亲口把设备与无效身份排除在幸存人数之外。主办方留下的措辞成为我们唯一能反过来约束它的东西。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch2_guard_release',
  ),
  'ch2_guard_release': StoryBeat(
    id: 'ch2_guard_release',
    label: '一根一根松开手指',
    speaker: Speaker.narration,
    scene: SceneKey.oldGym,
    text:
        '留守者没有直接松手，而是按约定一根手指一根手指减轻力量。门轨先发出低沉震动，控制页的压力值从真人输入切换到12号握手，红灯短暂亮起又熄灭。\n所有人都停住呼吸。两秒、四秒、十秒，卷帘门仍维持原位。\n直到旁路柄完全回弹，站在门内的人才真正相信控制箱正在把一个不存在的身份当作操作者。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_false_occupant',
  ),
  'ch2_rescue_obstacle': StoryBeat(
    id: 'ch2_rescue_obstacle',
    label: '千斤顶第一次滑脱',
    speaker: Speaker.suMi,
    scene: SceneKey.oldGym,
    portraitMood: 'concerned',
    cgId: 'cg_gym',
    cgFrame: 1,
    text:
        '千斤顶顶到一半，器材架底部从积灰的木地板上滑开两厘米。高原的脸瞬间失去血色，苏弥立刻叫停，拒绝在看不清受力点时继续硬抬。\n林澄把折叠垫塞进滑动方向，韩骐改用绳索把架体固定到看台立柱，高原则用没有受伤的腿确认地面震动。\n这次停顿消耗了一分二十秒，却避免救援本身成为第二次砸伤。倒计时越紧，越不能把“更快”误写成“更安全”。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_rescue_gao',
  ),
  'ch2_seal_silence': StoryBeat(
    id: 'ch2_seal_silence',
    label: '没有爆炸声的零点',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    text:
        '广播结束后，所有人仍等了几秒。吴峥死亡时的焦味和金属爆响像身体记忆一样抢先回来，可封锁墙后没有处决声，也没有任何人倒下。\n苏弥从01开始重新摸过每个人的颈侧脉搏，星遥则确认九台真人终端都在移动。直到最后一个编号回答，韩骐才把一直举在门前的撬棍放低。\n“零人处决”不是一句系统提示。它需要由九个仍在呼吸的人共同验证。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_survivor_count',
  ),
  'ch2_triage_gao': StoryBeat(
    id: 'ch2_triage_gao',
    label: '救出不等于无事',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.infirmary,
    portraitMood: 'injured',
    text:
        '医务室的灯比体育馆亮得刺眼。苏弥剪开高原左腿裤管，小腿已迅速肿起，大片淤血正从受压位置向外扩散。她固定夹板时，高原仍试图坐起来看门位记录。\n“我还能感觉到脚趾，骨头应该没断。”高原咬着牙说，“先把控制箱照片给我，桥接线的端子——”\n“能感觉到不等于能走。”苏弥把他的肩膀按回诊疗床，“从现在起左腿不得负重。疼痛加重、麻木或尿色变化，立刻告诉我，别替自己的身体做设备验收。”\n陈默说手掌只是压痕，不必处理。苏弥把他的名字也写进检伤表。“被救出来不是检查结束。谁都别用还能说话证明自己没事。”',
    passageSpeakers: [
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.suMi,
      Speaker.suMi,
    ],
    next: 'ch2_accusation_round',
  ),
  'ch2_accusation_round': StoryBeat(
    id: 'ch2_accusation_round',
    label: '门外的追责',
    speaker: Speaker.hanQi,
    scene: SceneKey.infirmary,
    portraitMood: 'protective',
    text:
        '苏弥完成固定后，韩骐才把椅子拉到两张诊疗床之间。“陈默，你为什么又把权限异常压在自己手里？高原，你听见卷帘多转半圈，为什么不先报公共频道？”\n“公开频道里可能就有布置陷阱的人。”陈默握着包扎后的手掌，“我一广播，缓存也许会先被删。”\n高原闭了闭眼。“我把异响当成了设备故障。以为自己先确认，比把所有人叫来围着一台旧电机更负责。”\n“所以你们替九个人决定，两个人就够承担风险。”韩骐的声音没有提高，“最后是九个人被迫来收拾一个没人知道的决定。”\n救援成功没有取消这笔责任。高原和陈默值得被救，也必须为隐瞒留下可复查的解释。',
    passageSpeakers: [
      Speaker.hanQi,
      Speaker.chenMo,
      Speaker.gaoYuan,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch2_public_audit',
  ),
  'ch2_public_audit': StoryBeat(
    id: 'ch2_public_audit',
    label: '逐项公开缓存',
    speaker: Speaker.yeLan,
    scene: SceneKey.infirmary,
    text:
        '叶岚把记录板分成三栏。“现在不接受‘我觉得’。每一条分别标成亲眼确认、专业推断、从别人处听说。”\n陈默把缓存时间填进第一栏，又在自己的路线旁停住。“二十二点五十一到二十三点零四，只有门禁记录，没有同行者。这十三分钟没人能替我证明。”\n“制动索是液压钳剪的，这是专业判断。”高原在床上接过笔，“但我没看见谁拿过钳子。把‘凶手使用’从我那栏删掉，那是推论。”\n星遥也删掉了自己写的“12号操作者”。“我只能确认身份槽被持续签名，不能确认签名后面是参与者、管理员，还是自动任务。”\n公开记录降低了两人的部分嫌疑，却没有把任何人洗成无辜。十三分钟、液压钳和签名来源依然空着；至少现在，没有人能用语气把空白伪装成答案。',
    passageSpeakers: [
      Speaker.yeLan,
      Speaker.chenMo,
      Speaker.gaoYuan,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch2_confront_chen',
  ),
  'ch2_map_cost': StoryBeat(
    id: 'ch2_map_cost',
    label: '失去F-01的代价',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '林澄把封锁后的路线重新量了一遍。F-01消失不仅少了一间体育馆，也切断宿舍区与医疗区之间最宽的运输通道；折叠担架今后无法通过档案库窄门，储物区的水也必须多绕十一分钟。\n高原需要每天换药，这十一分钟从抽象距离变成了伤员必须承担的疼痛。\n第一次封锁没有带走人，却永久拿走了一条救援路线。我们赢下零点，不等于没有支付代价。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_aftermath_choice',
  ),
  'ch2_xingyao_aftercare_detail': StoryBeat(
    id: 'ch2_xingyao_aftercare_detail',
    label: '允许频道安静',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'alarm',
    text:
        '我们戴着耳机坐了几分钟，谁也没有说话。星遥先后确认三次连接灯，第四次伸手时停在半空，最终把终端屏幕扣到膝上。\n“以前频道一安静，我就觉得一定有什么断了。”她说，“刚才你没有叫我的时候，我也知道你还在旁边。”\n我没有用回答填满这段静默。肩膀相触的重量、相同频率里的呼吸和无需确认的几分钟，比一句保证更接近她想验证的东西。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch2_dawn_map',
  ),
  'ch2_sumi_aftercare_detail': StoryBeat(
    id: 'ch2_sumi_aftercare_detail',
    label: '不合格的绷带',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'relieved',
    text:
        '我替苏弥包扎掌心，第一圈太松，第二圈又压住指节。她真的没有接手，只在我快把结打到伤口上时用另一只手点了点位置。\n“很难看。”她检查完说，嘴角却第一次有了很浅的弧度，“但血止住了，手指也能动。医学上暂时及格。”\n她把自己的检伤卡放进公共记录，没有像过去那样悄悄抽走。被照顾没有削弱她作为医生的资格，反而让那份记录终于包含完整的人数。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch2_dawn_map',
  ),
  'ch2_lincheng_aftercare_detail': StoryBeat(
    id: 'ch2_lincheng_aftercare_detail',
    label: '不擦掉害怕的路线',
    speaker: Speaker.linCheng,
    scene: SceneKey.assemblyHall,
    portraitMood: 'determined',
    text:
        '林澄在地图边缘补了一条很细的虚线，标记她在防火门落下时曾经想往回跑的位置。她说那不是正确路线，本来不该留下。\n“可如果擦掉，就会像我当时一点都没怕。”她握着橡皮想了很久，最后只在旁边写上“停三秒后继续”。\n我告诉她，地图记录的不只是哪条路正确，也记录一个人如何从错误方向重新找到出口。她把橡皮放回笔袋，没有再修改那条线。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch2_dawn_map',
  ),
  'ch2_debrief_dissent': StoryBeat(
    id: 'ch2_debrief_dissent',
    label: '公开不等于同意',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    text:
        '公开复盘结束后，唐弈仍拒绝在“12号不是参与者”这一结论旁签名。他同意底座没有人，却认为主办方既然把12号计入存活人数，就可能赋予它比真人更高的资格。\n“记录可以公开，解释仍然可以不同。”\n我保留了他的异议。共同证据的意义不是强迫所有人得到相同感受，而是让下一次争论至少围绕同一组事实发生。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch2_dawn_map',
  ),
  'ch2_night_watch': StoryBeat(
    id: 'ch2_night_watch',
    label: '第一夜无人真正入睡',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '凌晨以后，集合厅仍保持两盏灯。高原在临时担架上短暂睡着，陈默每次闭眼都会因卷帘声惊醒，韩骐则把工具全部移到众人可见的墙边。\n值夜表按姓名而不是编号排列，每组两人，任何终端异常都必须先叫醒第三名见证者。\n我们建立的制度仍然脆弱，甚至需要靠疲惫的人一笔笔维持。但在第一天结束前，至少没有谁再独自带着异常走进下一间房。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch2_next_seal',
  ),
};
