part of 'story.dart';

const chapterSevenBeats = <String, StoryBeat>{
  'ch7_day_six_open': StoryBeat(
    id: 'ch7_day_six_open',
    label: '第六日从一条过长的走廊开始',
    speaker: Speaker.narration,
    scene: SceneKey.corridor,
    timelineMinute: 7200,
    cgId: 'cg_ch7_core_opening',
    cgFrame: 0,
    text:
        '零点后的设施没有真正进入夜晚。六处永久封锁把原本交错的通道压成一条狭长走廊，集合厅在一端，控制核心在另一端，中间只剩医疗前室、配电夹层和一段没有岔路的维护桥。\n墙上的区域图每隔三十秒刷新一次。已经封闭的房间仍显示温度、电力和12号白色信号，像那些区域并未死亡，只是把我们从自己的身体旁边删去。\n我在走廊中央停下。昨天我们决定由谁确认门可以关闭；今天，所有还活着的人都必须穿过这些决定留下的形状。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_remaining_map',
  ),
  'ch7_remaining_map': StoryBeat(
    id: 'ch7_remaining_map',
    label: '地图只剩一条能够抵达出口的线',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'determined',
    text:
        '林澄把纸质地图铺在墙边，将无法返回的区域涂黑。留下的线从集合厅穿过医疗前室，经配电夹层抵达控制核心；任何一处闸门落下，后面的人都没有第二条回路。\n“不是迷宫了。”她说，“更危险。迷宫至少允许走错以后退回来。”\n她又在三处墙体后画出虚线。12号信号正从已经永久封闭的体育馆、档案区和仓储环线依次出现，时间间隔仍然只有七秒。实体无法穿过封锁，信号却像在黑色区域间接力。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch7_roll_call_gate',
  ),
  'ch7_roll_call_gate': StoryBeat(
    id: 'ch7_roll_call_gate',
    label: '四席开放前先确认还有谁能回答',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '集合厅的椅子没有再按十二人摆放。苏弥只为仍会坐下的人留下水，高原或其他幸存者把空位旁的终端全部断电。\n我要求按姓名点名，不报编号，也不允许录音代替本人。普通路线已经只剩六个声音；审计路线仍有九个，却没有一个声音因此显得轻松。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch7_roll_tangyi',
      'ch6_chenmo_vote_killer': 'ch7_roll_chenmo',
      'ch6_hanqi_vote_killer': 'ch7_roll_hanqi',
      'ch6_vote_killings_prevented': 'ch7_roll_audit',
    },
    next: 'ch7_roll_audit',
  ),
  'ch7_roll_tangyi': StoryBeat(
    id: 'ch7_roll_tangyi',
    label: '唐弈站在三个空位之间',
    speaker: Speaker.tangYi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'calculating',
    text:
        '沈砚、黎星遥、苏弥、唐弈、林澄、高原。六个名字依次落下。韩骐、陈默与叶岚留下的空位把唐弈围在中间，他没有移动椅子。\n“再少两个人，四席就不需要争。”他说得很轻，像只是在指出一个几何事实。\n高原立即问：“你是在预测，还是提案？”\n唐弈看向主屏，没有回答。沉默没有构成威胁证据，却让所有人都知道他已经把四这个数字放进了活人的名单。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch7_roll_complete',
  ),
  'ch7_roll_chenmo': StoryBeat(
    id: 'ch7_roll_chenmo',
    label: '陈默先确认谁持有他的责任记录',
    speaker: Speaker.chenMo,
    scene: SceneKey.assemblyHall,
    portraitMood: 'cold',
    text:
        '沈砚、黎星遥、苏弥、林澄、陈默、高原。念到叶岚和唐弈时，没有录音，也没有替答。陈默却在点名结束前先问三份外包责任记录分别由谁保管。\n“姓名还没报完。”林澄提醒。\n“名字不会改变谁能让我出不去。”陈默说。\n他没有要求立即交出记录，只把保管者写进自己的PDA。动作足够冷静，也足够明确：在他眼里，四席之前先存在三份必须沉默的证据。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.linCheng,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch7_roll_complete',
  ),
  'ch7_roll_hanqi': StoryBeat(
    id: 'ch7_roll_hanqi',
    label: '韩骐把保护名单压在桌面上',
    speaker: Speaker.hanQi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'conflicted',
    text:
        '沈砚、黎星遥、苏弥、韩骐、林澄、叶岚。六个名字之后，韩骐把一张值守表推到桌面。01始终位于他或苏弥视线内，控制核心行动由他决定前后顺序。\n“这是安排，不是托管。”他说。\n叶岚指出01从未同意。韩骐没有撕掉表，只把“决定”改成“建议”。字变软了，位置却没有变化。经历过两次多数死亡后，他越来越相信保护必须先于被保护者的许可。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch7_roll_complete',
  ),
  'ch7_roll_audit': StoryBeat(
    id: 'ch7_roll_audit',
    label: '九个名字仍然各自携带危险',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '除吴峥与周叙外，九个人逐一回答。唐弈、陈默与韩骐都仍在，也都知道昨天的组合制度分别阻止了自己准备完成的哪一步。\n叶岚没有把无伤亡写成互相信任。“九名存活者，九台本人终端，三项未遂动作已登记。任何人离开集合厅前，先公开目的地和预计返回时间。”\n三个人都没有反对。接受监督不是悔改，却让危险至少暂时保持可见。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    next: 'ch7_roll_complete',
  ),
  'ch7_roll_complete': StoryBeat(
    id: 'ch7_roll_complete',
    label: '主办方开始计算四个证词席位',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '最后一个名字得到回应后，主屏从地图切换成四把空椅。每把椅子下面都有两种进入条件：持有一项可独立复核的主办者结论，或持有足以让其他候选人无法提交的控制权。\n“最终证词席位将在十八小时后锁定。”管理员宣布，“控制核心即刻开放。席位资格不保证生存，不限制取得方式。”\n它没有直接命令互相残杀。它只是让证据与暴力出现在同一张资格表里，再把倒计时放在旁边。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch7_zero_directive',
  ),
  'ch7_zero_directive': StoryBeat(
    id: 'ch7_zero_directive',
    label: '最后一次永久封锁由控制核心决定',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    cgId: 'cg_ch7_core_opening',
    cgFrame: 1,
    text:
        '四把椅子缩到屏幕上方，设施剖面随即展开。控制核心外侧的三组重放节点同时亮白，分别连接封闭体育馆、档案区和仓储环线。\n“十八时整，控制核心将执行最后封锁。三组节点任意一组在线，系统可继续调用历史托管、投票与位置记录。全部离线，最终裁定仅接受现场输入。”\n星遥盯着“历史记录”四个字。12号从来不是一个人，也不只是一台维护设备；它是主办方将已经撤回的选择重新带回现在的方法。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch7_signal_test_1',
  ),
  'ch7_signal_test_1': StoryBeat(
    id: 'ch7_signal_test_1',
    label: '星遥让所有终端保持静默一分钟',
    speaker: Speaker.liXingyao,
    scene: SceneKey.assemblyHall,
    portraitMood: 'alarm',
    text:
        '星遥要求所有人关闭PDA发送功能，只保留被动接收。第一个七秒周期里，体育馆白点照常出现；第二个周期换到档案区；第三个周期则落在仓储环线。\n“不是我们的终端在转发。”她把频谱投到主屏，“三个封锁区各有独立发射源，共享同一签名种子。切断一个，另外两个仍能补出完整身份。”\n陈默问能否从集合厅远程关闭。星遥摇头。每组节点都要求本地物理断开，远程命令只会被ZERO当作新的可重放输入。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_signal_test_2',
  ),
  'ch7_signal_test_2': StoryBeat(
    id: 'ch7_signal_test_2',
    label: '封锁墙后仍有一条维护神经',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.corridor,
    portraitMood: 'inspecting',
    text:
        '高原沿墙体测量电流，发现封锁区电源并未真正断开。一束低压维护线穿过配电夹层，像神经一样连接三处节点与控制核心。\n“门封住的是人，不是设备。”他说，“我们进不去，但控制核心可以通过维护线切断它们。问题是三组节点有储能，断开顺序错了，剩下的会替前一组重写身份。”\n唐弈迅速算出最坏窗口：从第一组失联到第三组失联不能超过六十秒。超过后，ZERO会把一次关闭识别为故障恢复。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch7_signal_test_3',
  ),
  'ch7_signal_test_3': StoryBeat(
    id: 'ch7_signal_test_3',
    label: '普通路线没有足够的人同时站在三处',
    speaker: Speaker.suMi,
    scene: SceneKey.assemblyHall,
    portraitMood: 'concerned',
    text:
        '三处维护端分别位于北侧配电夹层、档案回路端口和维修桥下方。每处至少需要一人操作、一人确认；控制核心还必须有人维持主线供电。\n苏弥数完普通路线的六名幸存者，发现人数刚好，却没有任何伤病、敌意或失联余量。“理论上够，现实里只要一个人拒绝，整组就断。”\n审计路线有更多人，却必须让曾经准备互相杀害的人分散到彼此看不见的区域。人数不是合作，最多只是让合作成为物理可能。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_resource_count',
  ),
  'ch7_resource_count': StoryBeat(
    id: 'ch7_resource_count',
    label: '最后的工具和食物被放在同一张表上',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'injured',
    text:
        '可用物资只剩两套绝缘服、一只手摇发电机、三卷光纤、四十七分钟氧气和一枚未登记的武器槽位。武器槽位来自安保架旧图，实体却从未出现在清单里。\n“槽位长四十二厘米，前端有气瓶接口。”高原说，“可能是工业射钉器，也可能是捕捉栓。近距离都足以穿透颅骨。”\n主办方没有把所有武器放进明面。它留下一件任何阵营都能声称只是工具的东西，等待有人先找到它。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch7_relationship_gate',
  ),
  'ch7_relationship_gate': StoryBeat(
    id: 'ch7_relationship_gate',
    label: '共同撤离关系先接受一次真实检查',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '前往控制核心前，PDA要求共同撤离关系双方确认实时位置共享仍然有效。昨天的签名不能替今天的任何人继续同意。\n公开轮值关系则要求三名见证者重新报到。无论私人还是公共制度，都必须在最需要它时允许退出；否则所谓保护只是延迟生效的托管。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_route_locked_xingyao': 'ch7_xingyao_check_1',
      'ch6_route_locked_sumi': 'ch7_sumi_check_1',
      'ch6_route_locked_lincheng': 'ch7_lincheng_check_1',
      'ch6_route_locked_public': 'ch7_public_check_1',
    },
    next: 'ch7_public_check_1',
  ),
  'ch7_xingyao_check_1': StoryBeat(
    id: 'ch7_xingyao_check_1',
    label: '星遥先问我是否仍愿意被她叫停',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'relaxed',
    text:
        '星遥没有直接按确认。她把停止权限逐项念给我听：信号异常、位置无法复核、耳机出现定向脉冲，任何一项都允许她中断我的前进。\n“你可以不同意我的判断。”她说，“但不能先答应，等我真的叫停时又说情况特殊。”\n我重新确认。她也确认自己的位置可由我复核。关系在最危险的时候没有变成默契猜测，而是两个人仍愿意说清楚什么可以阻止自己。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_relationship_converge',
  ),
  'ch7_sumi_check_1': StoryBeat(
    id: 'ch7_sumi_check_1',
    label: '苏弥拒绝让医疗否决只保护我',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'concerned',
    text:
        '苏弥检查我的瞳孔、脉搏和手部反应，随后把自己的右手递过来。连续急救让她腕部持续发抖，昨晚却没有写进任何医疗风险。\n“共同否决不是你受伤时我来停门。”她说，“我无法操作时，你也必须替我叫停。别把照顾又变成我一个人的权限。”\n我记录她的震颤频率，她记录我的睡眠不足。承认彼此都可能成为需要撤离的人，比一句会保护你更难，也更接近今天真正能用的承诺。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_relationship_converge',
  ),
  'ch7_lincheng_check_1': StoryBeat(
    id: 'ch7_lincheng_check_1',
    label: '林澄为自己保留一条不同意的路线',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'determined',
    text:
        '林澄在共享路线旁画出一条细虚线。若她认为我的指令会把人困在单向通道，她可以沿虚线独立撤离，不需要先说服01。\n“共同走不等于永远走同一条。”她看着我，“你不能因为我选择过你，就把我下一次选择也提前拿走。”\n我签下见证，不替她删除虚线。她随后才确认共享位置。喜欢没有让她变成我的附属证人，也没有让我成为她所有风险的唯一答案。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch7_relationship_converge',
  ),
  'ch7_public_check_1': StoryBeat(
    id: 'ch7_public_check_1',
    label: '公开轮值先替换所有直接受益者',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '公开轮值组逐项申报与控制核心的利益。需要删除责任记录、满足四人条件或控制01的人自动退出唯一见证席，由其余人按区域替换。\n叶岚此前制定的轮值条款仍留在共享页：“退出见证不等于禁止行动。相关者仍可提交证据，只不能独自确认自己的证据已经足够。”若她仍在场，便由她复核；若她已经死亡，系统也不能替活人删去这条限制。\n轮值表因此比私人关系更慢，也没有人可以把亲近当作默认资格。它不保证公正，只让每次替换都有可以追问的理由。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_relationship_converge',
  ),
  'ch7_relationship_converge': StoryBeat(
    id: 'ch7_relationship_converge',
    label: '所有关系在出发前仍允许撤回',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '确认页关闭时，没有任何关系获得永久锁定。PDA只保存本次行动有效的停止权、见证范围和证据副本去向。\n我们没有因此变得更疏远。恰恰因为退出不必以背叛命名，留下来才重新成为一次真实选择。随后队伍沿唯一走廊向控制核心移动。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_core_approach',
  ),
  'ch7_core_approach': StoryBeat(
    id: 'ch7_core_approach',
    label: '控制核心外没有摄像头盲区',
    speaker: Speaker.chenMo,
    scene: SceneKey.corridor,
    portraitMood: 'guarded',
    text:
        '越靠近控制核心，摄像头越密。每隔两米便有一只镜头，互相覆盖，墙面却没有任何可见线缆。陈默指出镜头不走设施主网，而是直接接入项圈裁定总线。\n“在这里切断监控，ZERO会先失去画面，项圈却不会失去命令。”他说。\n韩骐问他为何知道。陈默没有再用职业常识敷衍，只承认自己曾参与同类外包架构评审。那份迟来的坦白提供了路径，也再次说明他比任何人更清楚怎样让系统继续杀人。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch7_locked_anteroom',
  ),
  'ch7_locked_anteroom': StoryBeat(
    id: 'ch7_locked_anteroom',
    label: '前室要求三种彼此冲突的凭证',
    speaker: Speaker.administrator,
    scene: SceneKey.corridor,
    text:
        '控制核心前室的门没有把手，面板同时要求三项凭证：01本人终端、一个仍在线的12号维护槽，以及一份未被多数撤回的区域决议。\n“12号已经被证明不是参与者。”星遥说。\n管理员回答：“维护资格不依赖参与者身份。”\n昨天的胜利只把12号从人数里排除，没有删除它作为系统工具的权限。主办方把不同规则中的“有效”分开保存，需要时再挑最方便的一种。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch7_access_debate_1',
  ),
  'ch7_access_debate_1': StoryBeat(
    id: 'ch7_access_debate_1',
    label: '唐弈主张借用一次12号权限',
    speaker: Speaker.tangYi,
    scene: SceneKey.corridor,
    portraitMood: 'calculating',
    text:
        '“我们不需要承认12号是人，只需要让它完成一次开门。”唐弈提出从最近的维护底座复制在线凭证，“使用工具不等于接受它的身份。”\n审计模板立刻弹出一项未决风险：凭证进入01终端后，系统可能把操作重新记录成参与者主动调用12号。那是叶岚在前一日留下的问题；她是否还活着，不会改变日志的写法。\n唐弈承认会，却认为记录可以事后解释。问题在于项圈裁定从不等待事后解释。一次方便的借用，可能立刻成为ZERO证明我们仍愿意让虚假身份代替活人的证据。',
    passageSpeakers: [Speaker.tangYi, Speaker.narration, Speaker.narration],
    next: 'ch7_access_debate_2',
  ),
  'ch7_access_debate_2': StoryBeat(
    id: 'ch7_access_debate_2',
    label: '星遥要求只重放握手而不复制身份',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'alarm',
    text:
        '星遥提出从墙内维护线读取12号握手时序，不复制签名内容。门只检查三段脉冲是否按七秒顺序抵达，身份字段则由本地面板自己补全。\n陈默认为可行，却指出读取必须打开项圈总线旁的检修盖。任何金属工具碰错一根线，都可能被解释为干扰项圈通信。\n“所以不用金属。”高原摸到门框下方的陶瓷锁片，“先找原厂光纤夹和绝缘拨片。它们应该就在前室应急柜里。”',
    passageSpeakers: [Speaker.liXingyao, Speaker.narration, Speaker.gaoYuan],
    next: 'ch7_access_debate_3',
  ),
  'ch7_access_debate_3': StoryBeat(
    id: 'ch7_access_debate_3',
    label: '区域决议必须由受害者记录复核',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'concerned',
    text:
        '第三项凭证更棘手。普通路线的区域决议已经导致死亡，审计路线也永久失去三成食物。若直接提交“决议有效”，门会把伤害一起压成一枚通过标记。\n苏弥要求附上最后可停止时刻、本人申诉和物资损失。“我们可以证明门确实关过，不能替它证明整个过程都正当。”\n面板没有附注栏。旧审计模板提供了一种办法：把伤害记录编码进决议校验值，让门若想接受结果，就必须连同异议一起接受。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_access_debate_4',
  ),
  'ch7_access_debate_4': StoryBeat(
    id: 'ch7_access_debate_4',
    label: '01终端不能由关系对象代交',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '01凭证最简单，也因此最危险。面板只要求我的终端贴近读口，没有要求我的手、意识或同意。\n韩骐提出由他站在读口旁防止夺取，星遥提醒任何人靠得太近都可能在门开时连同终端把我拖进前室。苏弥则把心率警报接入暂停权限。\n最后我自己持有PDA，另外两人只看手和门，不碰设备。我们不把风险交给一个更强的人解决，而是让不同人分别阻止不同动作。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_access_debate_5',
  ),
  'ch7_access_debate_5': StoryBeat(
    id: 'ch7_access_debate_5',
    label: '三项凭证必须在同一分钟成立',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '我们把昨天的六十秒同刻规则移到前室操作：12号只提供握手时序，区域决议携带异议校验，01由本人持有，三项输入相差超过一分钟便全部作废。\n这不是绕开门的条件，而是拒绝让门把三个不同时间、不同含义的真记录拼成一次虚假同意。共享页保存方案与全部反对意见，不把它归功于某个可能已经不在的人。\n普通路线仍有人反对把程序做得这么慢，审计路线则担心三项同时暴露会引来攻击。倒计时没有替我们选择，门内的机械锁已经开始预热。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_core_entry',
  ),
  'ch7_core_entry': StoryBeat(
    id: 'ch7_core_entry',
    label: '控制核心只接受带异议的开门记录',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '星遥用光纤夹重现七秒握手，高原将异议记录压进决议校验，我把01终端贴上读口。三盏灯在同一分钟变绿，门锁却迟疑了近五秒，像系统第一次遇见一份拒绝删去反对意见的有效凭证。\n厚重隔离门向两侧缩进。冷空气带着臭氧和旧塑料的气味涌出，里面没有操作员，只有三排服务器、一道横跨房间的输入总线，以及墙上被酸洗过的人类签名板。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_core_opened_with_dissent'},
    next: 'ch7_core_first_view',
  ),
  'ch7_core_first_view': StoryBeat(
    id: 'ch7_core_first_view',
    label: '主办方把人类名字和程序名放在不同墙上',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '左墙是项目审批板，所有姓名都被化学溶剂擦到只剩压痕；右墙服务器反复显示进程名ZERO；中央总线则实时滚动我们的托管、投票、位置申诉和撤回请求。\n“如果只问谁在运行游戏，右边已经回答了。”星遥说，“可左边有人决定把我们带进来，中间又在用我们的签名继续执行。”\n房间没有一张能独自解释全部责任的纸。它把三种答案分开放置，仿佛等着我们为了四个席位各自挑走最有利的一块。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_investigation_brief',
  ),
  'ch7_investigation_brief': StoryBeat(
    id: 'ch7_investigation_brief',
    label: '调查先限定四个能够回答的问题',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '现存审计记录将现场问题限制为四项：谁批准H-7实验；ZERO怎样跨三处节点保持同一身份；参与者输入是否只是被观察，还是会直接触发执行；未登记武器槽位究竟装过什么。\n记录页最下方留着一条原则：不要因为四席需要四份结论，就强迫四件物证各自给出完整主办者；先让每件物证只回答它真的能回答的范围。\n我们把工具放到房间中央，不预先分给任何阵营。每次取用都要在墙面摄像头和两名见证者前登记。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_core_investigation',
  ),
  'ch7_core_investigation': StoryBeat(
    id: 'ch7_core_investigation',
    label: '控制核心四组物证需要交叉工具',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    phase: StoryPhase.investigation,
    text: '调查酸洗审批板、三节点拓扑、参与者输入总线与空武器槽。工具藏在其他物证的维护附件中，必须先观察、收纳，再跨目标组合验证。',
    next: 'ch7_investigation_debrief',
  ),
  'ch7_investigation_debrief': StoryBeat(
    id: 'ch7_investigation_debrief',
    label: '四件物证没有给出同一个凶手姓名',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '审批板恢复出人类授权，拓扑板证明ZERO跨三组节点运行，输入总线显示参与者签名会直接改变门与项圈，空槽则留下未登记射钉器的气瓶和导轨痕迹。\n四项事实彼此连接，却不能被缩成“某个人用某件武器控制一台服务器”。若我们为了四席急着挑一个答案，剩余两层责任就会继续藏在正确答案的阴影里。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_ledger_fact',
  ),
  'ch7_ledger_fact': StoryBeat(
    id: 'ch7_ledger_fact',
    label: '酸洗下面保留人类批准的笔压',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '石墨转印膜从审批板上揭下时，七个被擦除的姓名只恢复出残缺轮廓，最下方项目负责人栏却保留完整笔压和个人印章序列。签署时间早于第一名参与者被绑架四十七天。\n我把时间与药物运输批次对齐。它不是程序自己生成的授权：有人知道实验会限制人身自由，仍批准了招募、运输和项圈部署。\n姓名最后两字仍被酸蚀覆盖，责任却已经不能再推给无人值守的系统。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_topology_fact',
  ),
  'ch7_topology_fact': StoryBeat(
    id: 'ch7_topology_fact',
    label: '三组服务器共享一颗会迁移的心跳',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '光纤示踪器让拓扑板上的隐蔽线路依次发亮。体育馆、档案区和仓储环线不是三份备份，而是同一进程的三个轮值节点：每七秒转交一次裁定心跳，上一节点只保留无法单独执行的碎片。\n“关掉一台不会杀死ZERO。”星遥说，“它会把缺失片段从另外两台补回来，再把关闭动作记成一次需要恢复的故障。”\nZERO不是屏幕里的声音，也不是某个固定机箱。它是一套能在设施内部迁移执行权的程序。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_input_bus_fact',
  ),
  'ch7_input_bus_fact': StoryBeat(
    id: 'ch7_input_bus_fact',
    label: '我们的选择不是观测数据而是执行参数',
    speaker: Speaker.chenMo,
    scene: SceneKey.controlCore,
    portraitMood: 'guarded',
    text:
        '校验桥接器将输入总线切到只读。每一条托管、投票、见证资格与撤回请求后面都有两组输出：一组写入实验记录，另一组直接进入门锁、项圈和区域封锁队列。\n“它不只是看我们会不会互相牺牲。”陈默说，“我们的签名本身就是执行许可。主办方把最后一步拆给参与者，再保留系统裁定，任何一边都能说不是自己完成全部动作。”\n被迫不等于无责，签名也不等于自由同意。总线把这两种真相残酷地叠在一起。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    next: 'ch7_weapon_fact',
  ),
  'ch7_weapon_fact': StoryBeat(
    id: 'ch7_weapon_fact',
    label: '空槽曾固定一把短管射钉器',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.controlCore,
    portraitMood: 'inspecting',
    text:
        '硅胶取形膜凝固后，空槽留下短管、折叠托和气瓶卡扣的完整轮廓。高原与旧安保图比对，确认它是一把近距离工业射钉器，原本用于将锚钉打进混凝土。\n导轨内侧有新鲜擦痕，说明它在我们进入设施后才被取走。槽底维护标签则指向控制核心前室，不属于任何已公开高危物资清单。\n它无法解释三层主办者，却会立刻改变谁有能力在狭窄走廊里让别人沉默。调查事实与即将发生的追猎在这里第一次接触。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    highRiskItemsMissingOnEnter: {'pneumatic_nailer'},
    next: 'ch7_scope_argument_1',
  ),
  'ch7_scope_argument_1': StoryBeat(
    id: 'ch7_scope_argument_1',
    label: '韩骐要求先找武器再谈责任层级',
    speaker: Speaker.hanQi,
    scene: SceneKey.controlCore,
    portraitMood: 'armed',
    text:
        '“射钉器已经不在槽里。现在讨论谁设计系统，只会给持枪的人时间。”韩骐要求封锁控制核心，逐个搜身，再由行动能力最强的人带队搜前室。\n苏弥同意武器风险紧急，却拒绝让“最强”自动等于唯一持械者。上一轮每次集中保护，最后都变成某个人可以替所有人决定何时停止。\n韩骐没有放下警戒姿势。迫近的物理危险是真的，利用危险扩大控制同样是真的，两件事不能互相抵消。',
    passageSpeakers: [Speaker.hanQi, Speaker.narration, Speaker.narration],
    next: 'ch7_scope_argument_2',
  ),
  'ch7_scope_argument_2': StoryBeat(
    id: 'ch7_scope_argument_2',
    label: '唐弈认为人类负责人是唯一可提交答案',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlCore,
    portraitMood: 'calculating',
    text:
        '唐弈把审批板转印放在最上方。“终局问主办者。程序不会绑架人，签名也不会自己制定实验。找到项目负责人姓名，四席就有可提交答案。”\n星遥指出ZERO在负责人不在场时仍实时选择执行路径。审计记录也提醒，即使抓到设计者，参与者已经签下的托管和投票仍能让系统继续关门。\n“责任可以分层，答案必须可输入。”唐弈说。\n他担心的不是理论不完整，而是不完整答案比复杂真相更容易让四个人活着出去。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch7_scope_argument_3',
  ),
  'ch7_scope_argument_3': StoryBeat(
    id: 'ch7_scope_argument_3',
    label: '陈默试图把参与者输入叫作胁迫记录',
    speaker: Speaker.chenMo,
    scene: SceneKey.controlCore,
    portraitMood: 'cold',
    text:
        '陈默主张中央总线只记录受胁迫行为，不能因此把参与者写进主办者。“项圈在脖子上，门由ZERO控制。我们按键是为了活，不是为了运行实验。”\n“周叙死前，中继器也是系统最后执行。”我说，“但有人选择把伪造距离送进去。”\n胁迫决定了责任不能与设计者相同，却不能让每一次明知会杀人的输入自动消失。若把所有参与者行为都归零，直接利用规则的人就会与被迫点名的人获得同一种无责。',
    passageSpeakers: [Speaker.chenMo, Speaker.shenYan, Speaker.narration],
    next: 'ch7_scope_argument_4',
  ),
  'ch7_scope_argument_4': StoryBeat(
    id: 'ch7_scope_argument_4',
    label: '林澄区分参与系统与成为系统',
    speaker: Speaker.linCheng,
    scene: SceneKey.controlCore,
    portraitMood: 'determined',
    text:
        '“我们参与了它，不等于我们就是它。”林澄把三层画成相交但不重合的圆，“设计者选择绑架，ZERO选择怎样执行，我们选择是否把别人推到执行条件里。每一层都能伤人，不能因为交叉就写成同一种罪。”\n她又从审计记录里抄下“可拒绝程度”。不同时间、不同角色能够拒绝的空间并不一样。\n这张图没有给任何人洗白，却防止一句“所有人都是主办方”把最初绑架者与被迫求生者混成方便的哲学结论。',
    passageSpeakers: [Speaker.linCheng, Speaker.narration, Speaker.narration],
    next: 'ch7_scope_argument_5',
  ),
  'ch7_scope_argument_5': StoryBeat(
    id: 'ch7_scope_argument_5',
    label: '推理必须同时解释谁设计谁执行谁续写',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '我在推理板上写下三个必须同时回答的问题：谁在绑架前批准H-7；什么在现场迁移裁定权；为什么负责人不在房间里，门和项圈仍能借我们的选择继续工作。\n射钉器不进入主办者证据链。它证明即将发生的能力变化，却不能回答制度从哪里开始。相同地，人类签名不能单独解释七秒迁移，ZERO进程也不能单独解释最初授权。\n只有一项结论能容纳三层而不取消它们之间不同的责任。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_case06_deduction',
  ),
  'ch7_case06_deduction': StoryBeat(
    id: 'ch7_case06_deduction',
    label: 'CASE 06需要闭合三层主办者责任',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    phase: StoryPhase.deduction,
    text: '用项目授权、分布式裁定与参与者执行输入构成证据链，再判断什么才是眼前仍在运作的主办者结构。',
    next: null,
  ),
  'ch7_case06_human_error': StoryBeat(
    id: 'ch7_case06_human_error',
    label: '人类负责人解释起点却解释不了现在',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '“项目负责人批准绑架和项圈部署，这一点已经成立。”星遥指向仍在迁移的心跳，“但他或她现在不需要站在任何终端前，ZERO仍能从三个节点恢复，参与者签名仍会直接进入执行队列。”\n只提交人名，会让我们找到最初加害者，却把正在运行的裁定和可被继续利用的输入总线留在原处。',
    passageSpeakers: [Speaker.liXingyao, Speaker.narration],
    next: 'ch7_case06_deduction',
  ),
  'ch7_case06_ai_error': StoryBeat(
    id: 'ch7_case06_ai_error',
    label: 'ZERO解释执行却没有创造绑架许可',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        'ZERO决定门何时落下，也维护12号重放；但审批板早于程序启动，药物、运输与项圈部署由人类授权，而程序此刻使用的合法输入，又有一部分来自参与者明知后果后的选择。\n把ZERO写成唯一主办者，会让设计者和利用制度的人同时退到一台机器背后。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_case06_deduction',
  ),
  'ch7_case06_resolved': StoryBeat(
    id: 'ch7_case06_resolved',
    label: '零点协议由三层责任共同维持',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    cgId: 'cg_ch7_case06_truth',
    cgFrame: 0,
    text:
        'H-7项目负责人批准绑架、设施和项圈，是实验的设计与起点；ZERO程序跨三组节点迁移裁定权，是现场持续执行者；参与者的托管、投票、保密和主动牺牲被接入总线，成为系统能够不断续写的有效输入。\n三层责任不相等，也不能互相替代。被迫求生者不等于绑架者，主动利用规则杀人的参与者也不能因为程序完成最后动作而无责。\n眼前的主办者不是一个方便指认的单体，而是“零点协议”：人类设计、程序裁定和被迫卷入者的可执行选择共同构成的结构。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {
      'case06_solved',
      'ch7_three_layer_host_proven',
      'ch7_zero_protocol_named',
    },
    next: 'ch7_responsibility_after_1',
  ),
  'ch7_responsibility_after_1': StoryBeat(
    id: 'ch7_responsibility_after_1',
    label: '正确结论没有自动生成四名证人',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    cgId: 'cg_ch7_case06_truth',
    cgFrame: 1,
    text:
        '推理板显示证据链闭合，四把席位椅却仍为空。系统要求每名证人独立持有可复核材料，并满足自己的主条件；理解同一句结论不等于拥有进入资格。\n唐弈立刻重新计算谁已经满足条件，陈默检查哪份恢复签名仍能被删除，韩骐则确认01终端离自己有多远。正确答案没有结束死亡游戏，只把争夺从“真相是什么”推进到“谁有资格说出真相”。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_responsibility_after_2',
  ),
  'ch7_responsibility_after_2': StoryBeat(
    id: 'ch7_responsibility_after_2',
    label: '证据在分散前先完成交叉复核',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '共享审计模板建议把三层证据各复制三份，分别交给不同阵营保管；任何一人只能持有两层，必须与他人交换才能提交完整结论。\n“这样会让联盟成为必需。”唐弈说。\n“现在本来就是必需。”我把模板的结论读完，“区别是联盟为了拼完整证据，还是为了让别人的证据永远不完整。”\n普通路线已经没有足够信任执行分散，审计路线则仍有制度让交接留下双向记录。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    next: 'ch7_responsibility_after_3',
  ),
  'ch7_responsibility_after_3': StoryBeat(
    id: 'ch7_responsibility_after_3',
    label: '射钉器的气瓶在墙内开始升压',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.controlCore,
    portraitMood: 'inspecting',
    text:
        '高原正准备复制拓扑图，前室墙内忽然传来短促充气声。空武器槽的压力传感器从零跳到六兆帕，说明射钉器已经接上新气瓶并解除运输锁。\n“持枪的人就在剩余区域。”他说，“而且知道我们找到槽位以后才上压。”\n对方可能在监视调查，也可能一直站在房间里。所有人下意识看向彼此手边、腰侧与外套褶皱，刚刚建立的三层结论被一个近距离武器重新压回肉体。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch7_responsibility_after_4',
  ),
  'ch7_responsibility_after_4': StoryBeat(
    id: 'ch7_responsibility_after_4',
    label: '搜身需要先决定谁不能单独执行',
    speaker: Speaker.suMi,
    scene: SceneKey.controlCore,
    portraitMood: 'concerned',
    text:
        '苏弥同意立即检查，却要求分成自检、同伴目视和金属探测三步，任何人不得在封闭房间里单独触碰另一个人的身体。\n“射钉器大部分是金属，探测足够先排除携带。”她说，“不需要借紧急情况把所有人的拒绝权取消。”\n探测结果全部阴性。武器不在房间里，而是被留在某个会在队伍分散后抵达的路径上。真正的危险不是谁现在藏着它，而是谁已经为自己安排好先拿到它。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_responsibility_after_5',
  ),
  'ch7_responsibility_after_5': StoryBeat(
    id: 'ch7_responsibility_after_5',
    label: '关闭三组节点与争夺四席同时开始',
    speaker: Speaker.administrator,
    scene: SceneKey.controlCore,
    text:
        '主屏倒计时跳到十六小时。三组维护端开放，控制核心门锁改为单向：离开后，只有01或一份完整三层证据能够再次进入。\n“重放节点关闭程序启动。最终证词资格同步计算。”\n主办方故意让合作任务和席位争夺使用同一段时间、同一批证据与同一条走廊。普通路线里，已经杀过人的阵营会先把任务改造成追猎；审计路线只有让每种能力相互制衡，才能在不留下人的情况下完成关闭。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch7_operation_gate',
  ),
  'ch7_operation_gate': StoryBeat(
    id: 'ch7_operation_gate',
    label: '昨日制度决定今天是追猎还是协作',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '证据副本、01终端与控制核心主线供电成为三处必须同时保护的目标。我们只能按昨日仍有效的制度分配行动权限。\n如果杀戮链已经形成，任何分组都带着前几日的直接责任；如果组合制衡仍在，所有行动者必须接受回避、同刻确认和本人紧急申诉。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    auditNext: 'ch7_audit_plan_1',
    auditRequiredFlags: {
      'ch6_policy_audit_hybrid',
      'ch6_vote_killings_prevented',
      'case06_solved',
    },
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch7_tangyi_hunt_1',
      'ch6_chenmo_vote_killer': 'ch7_chenmo_hunt_1',
      'ch6_hanqi_vote_killer': 'ch7_hanqi_hunt_1',
    },
    next: 'ch7_tangyi_hunt_1',
  ),
  'ch7_tangyi_hunt_1': StoryBeat(
    id: 'ch7_tangyi_hunt_1',
    label: '唐弈先提出六人完成关闭的最短分工',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlCore,
    portraitMood: 'calculating',
    text:
        '唐弈用不到两分钟列出六人分工：星遥与我留在核心，高原负责配电，苏弥守医疗前室，林澄传递证据，他自己在走廊中央协调三端时间。\n“每个人都在最擅长的位置。”他说。\n高原指出协调者不应同时掌握所有人的位置与启动时间。唐弈接受公开计时，却拒绝让高原检查自己的PDA。“你可以验证数字，不需要读取我的全部记录。”\n分工表没有明显杀人步骤，却让唐弈成为唯一知道谁会在何时单独经过哪段走廊的人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch7_tangyi_hunt_2',
  ),
  'ch7_tangyi_hunt_2': StoryBeat(
    id: 'ch7_tangyi_hunt_2',
    label: '他用四席名额换取苏弥暂时合作',
    speaker: Speaker.tangYi,
    scene: SceneKey.corridor,
    portraitMood: 'calculating',
    text:
        '离开核心前，唐弈单独告诉苏弥，只要保持至少四人存活，她的条件不可能完成；继续保护六人只会让四席争夺在最后一分钟爆发。\n“我可以保证03进入四席。”他说，“你负责让其他人到达节点，我负责让人数停止在不会继续争的位置。”\n苏弥没有接受，却也没有立刻公开对话。她担心指控会让唐弈提前行动，先把录音副本交给我，再要求自己不与他单独同行。她用策略争取时间，不是假装一句拒绝就能让威胁消失。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch7_tangyi_hunt_3',
  ),
  'ch7_tangyi_hunt_3': StoryBeat(
    id: 'ch7_tangyi_hunt_3',
    label: '高原发现配电图多出一条假故障',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'inspecting',
    text:
        '高原抵达配电夹层后，发现主线图上多出“北端压力不足”的红色故障。实际压力稳定，报警却要求工程人员进入墙内气瓶仓手动复位。\n“这不是设备自检。”他通过公共频道说，“有人用控制核心旧模板插入了维护任务。”\n唐弈回答可能是ZERO为射钉器槽位补充气源。解释在技术上成立，也把高原独自进入气瓶仓变成看似必要的动作。我要求他等见证人到场，高原却发现夹层门已经开始六十秒自动关闭。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch7_tangyi_hunt_4',
  ),
  'ch7_tangyi_hunt_4': StoryBeat(
    id: 'ch7_tangyi_hunt_4',
    label: '林澄从旧地图找到第二个观察口',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'anxious',
    text:
        '林澄在纸图上找到气瓶仓背后的检修观察口，沿单向通道赶过去。观察口只有手掌宽，她看见高原蹲在压力表旁，也看见另一侧工具柜的门已经打开。\n“里面有人吗？”我问。\n“看不见人，只看见一根黑色短管伸出来。”她的声音发紧，却没有把猜测说成身份，“枪口朝着压力表。高原还没发现。”\n星遥试图接管夹层广播，频道却被一个合法协调者权限静音。唐弈仍站在走廊中央，手里没有武器。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch7_tangyi_hunt_5',
  ),
  'ch7_tangyi_hunt_5': StoryBeat(
    id: 'ch7_tangyi_hunt_5',
    label: '射钉器被绳索和延时阀留在柜内',
    speaker: Speaker.liXingyao,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'alarm',
    cgId: 'cg_ch7_tangyi_nailer',
    cgFrame: 0,
    text:
        '星遥从观察口画面里辨出，短管并非被人握住。射钉器固定在柜内导轨上，扳机接着一根穿过门缝的细绳，气阀则由配电任务完成确认后自动升压。\n“这是远程条件，不需要他留在现场。”她说，“谁创建假故障，谁就能让高原自己站到射线上。”\n我命令高原不要碰压力表。公共频道没有把声音送进去，夹层内屏幕反而显示01已确认复位。有人重放了我在前室开门时留下的有效触控摘要。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_tangyi_hunt_6',
  ),
  'ch7_tangyi_hunt_6': StoryBeat(
    id: 'ch7_tangyi_hunt_6',
    label: '高原在最后一秒看见观察口',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'injured',
    text:
        '林澄用金属楔敲击观察口，高原终于抬头。他看见她拼命指向工具柜，也看见压力表旁那根几乎透明的触发绳。\n“别进来。”他先说，“门要锁了。”\n他没有扑向出口，而是试图将绝缘扳手塞进射钉器与导轨之间。若能改变枪管角度，装置即使触发也只会打进墙体。\n唐弈在走廊频道里说：“离开压力表，任务会失败，三节点关闭也会失败。”\n高原没有回答他，只让林澄后退。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch7_tangyi_hunt_7',
  ),
  'ch7_tangyi_hunt_7': StoryBeat(
    id: 'ch7_tangyi_hunt_7',
    label: '假维护任务完成了真正的射击',
    speaker: Speaker.narration,
    scene: SceneKey.maintenanceRoom,
    cgId: 'cg_ch7_tangyi_nailer',
    cgFrame: 1,
    timelineMinute: 7488,
    text:
        '配电屏将被重放的01摘要判定为复位确认。气阀打开，柜内传出一声远比枪响短促的爆裂。高原挡在导轨前的扳手偏转了枪口，却没能完全避开锚钉。\n锚钉从锁骨下方进入。他跪倒时仍用身体压住气瓶阀，阻止第二次升压。苏弥赶到夹层外，门锁却只接受协调者撤销任务。\n唐弈等待了十二秒才按下撤销。十二秒不足以证明他希望高原死亡，假故障模板、重放摘要和绳索路径却已经共同回答了这个问题。\n高原在门打开前失去脉搏。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_gao_killed_by_tangyi', 'ch7_first_hunt_death'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '09',
        cause: '被假维护任务触发的固定式工业射钉器击中胸部',
        timelineMinute: 7488,
        responsibleParticipantIds: ['06'],
        sourceItemId: 'pneumatic_nailer',
      ),
    ],
    next: 'ch7_tangyi_hunt_8',
  ),
  'ch7_tangyi_hunt_8': StoryBeat(
    id: 'ch7_tangyi_hunt_8',
    label: '唐弈承认自己只需要少一个工程师',
    speaker: Speaker.tangYi,
    scene: SceneKey.corridor,
    portraitMood: 'shaken',
    text:
        '唐弈没有逃。他交出协调权限，却拒绝承认自己扣动扳机。“我创建维护任务，也知道槽位可能接入气源。固定射钉器、触发绳和01摘要不是我放的。”\n“你为什么等十二秒？”苏弥问。\n“因为他若完成复位，三节点行动仍有机会继续。”\n这句话把辩解拆开了。唐弈并不需要亲手安装全部装置；他知道一项可能致命的路径已经成立，仍把高原留在路径里，直到工程价值低于四席人数价值。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.suMi,
      Speaker.tangYi,
      Speaker.narration,
    ],
    next: 'ch7_standard_split_1',
  ),
  'ch7_chenmo_hunt_1': StoryBeat(
    id: 'ch7_chenmo_hunt_1',
    label: '陈默要求先删除三份恢复签名',
    speaker: Speaker.chenMo,
    scene: SceneKey.controlCore,
    portraitMood: 'cold',
    text:
        '陈默把三节点关闭与自己的外包记录放在同一张时间表上。三份恢复签名分别藏在核心、配电夹层和证据副本中，只要关闭过程覆盖对应区域，他就能让删除变成“设备失联”的自然结果。\n“先保住系统，再谈个人条件。”我说。\n“系统就是用个人条件运行的。”他回答，“你们刚刚证明了这一点。既然谁都在利用输入，我至少不会假装自己没有利益。”\n公开利益没有消除伤害，只让他开始把灭口写成任务依赖。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch7_chenmo_hunt_2',
  ),
  'ch7_chenmo_hunt_2': StoryBeat(
    id: 'ch7_chenmo_hunt_2',
    label: '星遥拒绝成为他的技术见证',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '陈默请求星遥与自己共同进入输入总线下层，理由是两名技术人员可以互相证明没有删改。星遥要求把全部操作镜像到公共屏，并让第三人持有断电权。\n“那就不叫技术见证，叫公开审讯。”陈默说。\n“你要的是一个懂得足够多、又会因为共同操作承担连带责任的人。”星遥把光纤夹收回工具箱，“我可以复核结果，不替你成为删除发生时房间里的另一个名字。”\n联盟未能形成，陈默转而把目光投向更容易被系统任务单独调走的高原。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch7_chenmo_hunt_3',
  ),
  'ch7_chenmo_hunt_3': StoryBeat(
    id: 'ch7_chenmo_hunt_3',
    label: '高原收到一张只在本地显示的配电工单',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'inspecting',
    text:
        '高原的PDA弹出配电工单：维修桥节点需要更换气瓶稳压器，否则关闭时会烧毁主线。集合厅与核心终端都没有这张任务，签名却来自合法ZERO维护队列。\n“本地注入。”高原说，“发单设备就在十米内。”\n陈默当时位于控制核心，距离超过三十米。他主动公开位置，像早已准备好排除自己。星遥却发现工单沿墙内维护线发送，发送端可以由核心总线远程映射成夹层本地设备。',
    passageSpeakers: [Speaker.narration, Speaker.gaoYuan, Speaker.narration],
    next: 'ch7_chenmo_hunt_4',
  ),
  'ch7_chenmo_hunt_4': StoryBeat(
    id: 'ch7_chenmo_hunt_4',
    label: '射钉器被伪装成稳压器工具',
    speaker: Speaker.linCheng,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'anxious',
    cgId: 'cg_ch7_chenmo_arc',
    cgFrame: 0,
    text:
        '林澄陪高原抵达夹层，没有让他单独开柜。柜中放着一只灰色工具箱，标签写“稳压器专用”，重量却比图纸多出三公斤。\n她没有触碰锁扣，只用纸片从箱底缝隙探入。纸边沾到透明润滑油，与控制核心空武器槽内残留一致。\n“里面是射钉器。”她在公共频道说。\n陈默立即建议原地封箱。与此同时，夹层照明熄灭，门外电磁锁吸合。封箱建议和困住发现者的动作在同一秒出现。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch7_chenmo_hunt_5',
  ),
  'ch7_chenmo_hunt_5': StoryBeat(
    id: 'ch7_chenmo_hunt_5',
    label: '林澄沿单向检修槽把自己送出夹层',
    speaker: Speaker.linCheng,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'determined',
    text:
        '林澄按纸图找到地板下的单向检修槽。开口只能容一人匍匐通过，高原的伤腿和肩宽无法转身。\n“你先走。”高原把证据副本塞给她。\n“我出去以后回来开门。”\n“这条槽没有回程。你画的。”\n她咬住嘴唇，没有用会回来的承诺覆盖地图事实。高原让她把射钉器位置和门锁状态带出去，自己留下寻找机械断电。弱势角色的生还不是突然更强，而是她曾认真记录每一条不被注意的窄路。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.gaoYuan,
      Speaker.linCheng,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch7_chenmo_hunt_6',
  ),
  'ch7_chenmo_hunt_6': StoryBeat(
    id: 'ch7_chenmo_hunt_6',
    label: '陈默让箱内武器与配电母线同时通电',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '星遥追踪到夹层工单来自输入总线的“责任恢复”接口，正是陈默必须删除的三份记录之一。接口把打开工具箱写成恢复签名确认，确认后会同时升压射钉器气瓶和配电母线。\n“不是为了让他拿枪。”星遥说，“是让高原以为断开气瓶就能解除危险。母线会在气压归零时反向放电。”\n我要求切断核心主电。陈默抢先锁住断电页：“现在断电，三组节点立刻恢复，所有调查副本都会失去时间戳。”',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.chenMo],
    next: 'ch7_chenmo_hunt_7',
  ),
  'ch7_chenmo_hunt_7': StoryBeat(
    id: 'ch7_chenmo_hunt_7',
    label: '高原选择让武器先失去压力',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'injured',
    text:
        '高原听见星遥的解释，却无法同时断开气瓶与母线。他把绝缘服披在肩上，准备先拔气瓶，让箱内武器失去第二次射击能力。\n“放着它，等门开。”苏弥说。\n“门由他控制，箱子也由他控制。”高原喘了口气，“至少让后来进来的人不用先面对一把上压的枪。”\n他不是不知道反向放电，而是在两个都可能杀人的风险中选择把可移动武器留成不能立即使用的金属。选择有理由，不等于代价因此合理。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.gaoYuan,
      Speaker.narration,
    ],
    next: 'ch7_chenmo_hunt_8',
  ),
  'ch7_chenmo_hunt_8': StoryBeat(
    id: 'ch7_chenmo_hunt_8',
    label: '反向电弧沿着工具箱击中高原',
    speaker: Speaker.narration,
    scene: SceneKey.maintenanceRoom,
    cgId: 'cg_ch7_chenmo_arc',
    cgFrame: 1,
    timelineMinute: 7494,
    text:
        '气瓶卡扣脱开的瞬间，母线将积蓄电流送入工具箱导轨。蓝白电弧穿过润滑油和高原手中的绝缘钳，在他胸前炸开。\n核心断电页仍显示“证据完整性保护中”。陈默只要解除自己的锁定，旁路便会在三秒内泄流。他没有动，直到三份恢复签名中的一份从夹层节点变成不可读取。\n苏弥赶到时，高原已经没有可电击心律。工具箱里的射钉器完好，责任记录却随配电板烧毁。\n陈默没有需要开枪。他让保存证据与抢救生命成为同一开关的两个方向，再选择了对自己有利的一边。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_gao_killed_by_chenmo', 'ch7_first_hunt_death'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '09',
        cause: '气瓶解除触发配电母线反向电弧，胸部遭高压电击',
        timelineMinute: 7494,
        responsibleParticipantIds: ['08'],
        sourceItemId: 'pneumatic_nailer',
      ),
    ],
    next: 'ch7_chenmo_hunt_9',
  ),
  'ch7_chenmo_hunt_9': StoryBeat(
    id: 'ch7_chenmo_hunt_9',
    label: '陈默称自己只是在保护剩余证据',
    speaker: Speaker.chenMo,
    scene: SceneKey.controlCore,
    portraitMood: 'desperate',
    text:
        '陈默解除断电锁后没有逃。“三组节点若同时掉电，ZERO会重写全部时间戳。高原当时仍穿着绝缘服，我判断泄流风险低于证据丢失。”\n星遥调出他在事故前修改的阈值：反向电流超过安全值十二倍，警告却被接口标成普通波动。\n“你不是判断错了。”她说，“你先把危险藏起来，再用别人看不见的数值替自己辩护。”\n陈默盯着烧毁的恢复签名，没有再说那是意外。',
    passageSpeakers: [
      Speaker.chenMo,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch7_standard_split_1',
  ),
  'ch7_hanqi_hunt_1': StoryBeat(
    id: 'ch7_hanqi_hunt_1',
    label: '韩骐宣布01与证据不得同时离开视线',
    speaker: Speaker.hanQi,
    scene: SceneKey.controlCore,
    portraitMood: 'protective',
    text:
        '韩骐把我与三层证据副本安排在同一组，自己守住唯一出口。星遥与苏弥被派去节点，林澄负责路线，叶岚留在核心监督。\n“01和证据分开，任何一边都能被拿来逼另一边。”他说。\n“你把两者放在一起，控制一个房间就能同时得到。”叶岚回答。\n韩骐没有改变安排。他相信最危险的东西应该放在自己够得到的位置，却没有承认“自己够得到”也是风险。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch7_hanqi_hunt_2',
  ),
  'ch7_hanqi_hunt_2': StoryBeat(
    id: 'ch7_hanqi_hunt_2',
    label: '叶岚组织一次不夺取武器的拒绝',
    speaker: Speaker.yeLan,
    scene: SceneKey.controlCore,
    portraitMood: 'strained',
    text:
        '叶岚没有试图抢夺韩骐腰间的破拆工具。她让每个人在公共记录里写下不同意被集中保护的理由，并要求我明确是否接受他的安排。\n“我不接受。”我说。\n韩骐看向走廊倒计时。“你可以在安全以后继续不接受。”\n叶岚把这句话原样记录。她的反制不是力量对抗，而是让韩骐无法在事后声称所有人默认授权。记录不能立即推开他，却会改变其他人是否愿意替他的命令完成下一步。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch7_hanqi_hunt_3',
  ),
  'ch7_hanqi_hunt_3': StoryBeat(
    id: 'ch7_hanqi_hunt_3',
    label: '苏弥拒绝执行未经同意的镇静',
    speaker: Speaker.suMi,
    scene: SceneKey.corridor,
    portraitMood: 'concerned',
    text:
        '韩骐私下要求苏弥准备短效镇静剂，理由是若我在射钉器威胁下失控，必须先保住01终端。苏弥让他把请求放进公共医疗记录。\n“公开会让所有人知道应急方案。”他说。\n“秘密会让你事后说我自愿配合。”苏弥回答。\n韩骐没有得到药物，便改用安保束缚带和一枚门磁楔。他没有突然变成更聪明的阴谋者，只沿着自己最熟悉的方式继续扩大身体控制。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch7_hanqi_hunt_4',
  ),
  'ch7_hanqi_hunt_4': StoryBeat(
    id: 'ch7_hanqi_hunt_4',
    label: '射钉器出现后他获得了紧急接管理由',
    speaker: Speaker.hanQi,
    scene: SceneKey.corridor,
    portraitMood: 'armed',
    text:
        '走廊监控拍到一只灰色工具箱被人从配电夹层推入通道。箱内轮廓与射钉器一致，附近却没有可见操作者。\n韩骐立即封住核心门，要求所有人交出PDA，由他逐个送出。“持枪者可能用任何终端远程触发。先切断操作能力。”\n叶岚指出武器尚在箱中，远程触发也需要气压；没必要没收全部终端。韩骐仍伸手抓向我的腕部。紧急情况终于给了他一直想要的正当说法。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch7_hanqi_hunt_5',
  ),
  'ch7_hanqi_hunt_5': StoryBeat(
    id: 'ch7_hanqi_hunt_5',
    label: '叶岚把01终端锁进透明证物盒',
    speaker: Speaker.yeLan,
    scene: SceneKey.controlCore,
    portraitMood: 'intervening',
    cgId: 'cg_ch7_hanqi_control',
    cgFrame: 0,
    text:
        '叶岚抢先把01终端放入透明证物盒，机械钥匙交给林澄，电子开启权交给星遥。任何一人都无法单独取出。\n“现在没人能远程触发，也没人能独占01。”她说。\n韩骐盯着证物盒。“真有袭击时，三个人来不及同时开。”\n“那也不能因为可能来不及，就让你现在拿走。”\n箱外射钉器仍未上压，核心内真正发生的冲突已经从武器转向谁有权定义紧急。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.hanQi,
      Speaker.yeLan,
      Speaker.narration,
    ],
    next: 'ch7_hanqi_hunt_6',
  ),
  'ch7_hanqi_hunt_6': StoryBeat(
    id: 'ch7_hanqi_hunt_6',
    label: '韩骐先打碎了不服从他的锁',
    speaker: Speaker.hanQi,
    scene: SceneKey.controlCore,
    portraitMood: 'furious',
    text:
        '倒计时再跳一格，韩骐用破拆锤击碎证物盒外层。第一下只留下裂纹，第二下让透明板向内塌陷。\n叶岚站到盒前，没有抓他的锤柄，只反复报告：“射钉器未上压，当前没有立即射击风险。01本人拒绝接管。”\n“等它上压就晚了。”韩骐抬起第三下。\n我和苏弥同时要求他停。星遥切断盒内电子锁，终端已经无法远程操作。威胁在这一刻进一步降低，他的动作却没有减慢。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.yeLan,
      Speaker.hanQi,
      Speaker.narration,
    ],
    next: 'ch7_hanqi_hunt_7',
  ),
  'ch7_hanqi_hunt_7': StoryBeat(
    id: 'ch7_hanqi_hunt_7',
    label: '叶岚被第三次挥击撞向核心护栏',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    cgId: 'cg_ch7_hanqi_control',
    cgFrame: 1,
    timelineMinute: 7482,
    text:
        '叶岚伸手把碎裂的证物盒推离锤击路线，韩骐的肩膀同时撞上她。她后退半步，后腰抵住主线护栏；第三次挥击落下时，锤头没有击中她，柄端却把她推过已经打开的检修缺口。\n我抓住她的手腕，韩骐也伸手。护栏边缘的金属片割开我的掌心，叶岚的指尖仍一点点滑出。\n“记录他还能停的时刻。”她最后说。\n她坠入下层主线井。苏弥抵达时，冲击已经造成不可逆颅脑损伤。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.yeLan,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_yelan_killed_by_hanqi', 'ch7_first_hunt_death'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '11',
        cause: '阻止强行接管01时被撞出检修缺口，坠入主线井',
        timelineMinute: 7482,
        responsibleParticipantIds: ['04'],
      ),
    ],
    next: 'ch7_hanqi_hunt_8',
  ),
  'ch7_hanqi_hunt_8': StoryBeat(
    id: 'ch7_hanqi_hunt_8',
    label: '韩骐把伸手救人当作自己仍可保护的证明',
    speaker: Speaker.hanQi,
    scene: SceneKey.controlCore,
    portraitMood: 'conflicted',
    text:
        '韩骐跪在护栏边，掌心因抓空而渗血。“我不是要她掉下去。我伸手了。”\n“你伸手以前有三次可以停。”我说。\n他看向被关闭的01终端，又看向走廊里仍未上压的射钉器箱。紧急理由已经全部消失，只剩叶岚在每次挥击前留下的风险报告。\n韩骐没有逃离责任，也没有因此放弃控制。他把破拆锤放下，却要求继续由自己护送01，因为在他的逻辑里，一次失败只证明下一次必须抓得更紧。',
    passageSpeakers: [
      Speaker.hanQi,
      Speaker.shenYan,
      Speaker.narration,
      Speaker.narration,
    ],
    next: 'ch7_standard_split_1',
  ),
  'ch7_standard_split_1': StoryBeat(
    id: 'ch7_standard_split_1',
    label: '第一次追猎后只剩五个声音',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '死亡记录完成后，普通路线只剩五名存活者。直接责任者没有被处决，也无法由一名幸存者安全看守；三组节点仍在线，四席倒计时继续下降。\n射钉器被卸去气瓶并锁在核心地面，01终端、三层证据与主线控制却分处三个位置。我们必须再次分组，而所有人都知道再少一个人，四席数量将与存活人数完全重合。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_standard_split_2',
  ),
  'ch7_standard_split_2': StoryBeat(
    id: 'ch7_standard_split_2',
    label: '三处终端只有一枚机械回程钥匙',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '核心柜弹出三张维护任务：北端信号校准、医疗前室氧气旁路、单向证据传递。三处都能从核心远程开门，却只有一枚机械回程钥匙能在主线失电后从内侧打开。\n“这不是随机缺件。”星遥检查槽位，“三把电子钥匙被写成同一授权根，断电时只会保留最后一次写入。”\n也就是说，三名行动者可以同时出去，却只有一人能保证不依赖核心里的操作员返回。剩余两人必须相信这里的人会按时开门。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_standard_split_3',
  ),
  'ch7_standard_split_3': StoryBeat(
    id: 'ch7_standard_split_3',
    label: '谁拿钥匙等于谁可以拒绝核心命令',
    speaker: Speaker.suMi,
    scene: SceneKey.controlCore,
    portraitMood: 'concerned',
    text:
        '苏弥指出，机械钥匙不只是逃生工具。持钥者可以在核心命令继续工作时自行撤离；没有钥匙的人则必须等操作员承认任务已经足够。\n林澄提议让距离最远的人拿，星遥认为应交给风险最高的信号端，苏弥则要求先看谁的身体状况最可能无法等待。\n每种标准都公平地保护一种风险，也公平地忽略另外两种。我们不能把决定交给算法，因为算法正是把不同身体压成一项权限的东西。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_standard_split_4',
  ),
  'ch7_standard_split_4': StoryBeat(
    id: 'ch7_standard_split_4',
    label: '直接责任者提出自己留守核心',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '此前的直接责任者主动要求留在控制核心，理由是所有人都能看见他的操作，出去反而更难监视。方案也意味着两名没有钥匙的人必须把开门权交给一个已经利用系统杀过人的人。\n我们可以拒绝，却没有第五名无关行动者替换。若我留守核心，01终端与全部门控又会集中在我身上；若两人留守，外部三处任务便缺人。\n死亡游戏不再提供“可信的人选”，只让我们决定哪种不可信更容易留下可阻止的痕迹。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_standard_split_5',
  ),
  'ch7_standard_split_5': StoryBeat(
    id: 'ch7_standard_split_5',
    label: '三个人各自说明没有钥匙时如何撤离',
    speaker: Speaker.linCheng,
    scene: SceneKey.controlCore,
    portraitMood: 'determined',
    text:
        '星遥可以通过维护线发送持续心跳，一旦信号中断，核心应立即开门；苏弥可以把氧气压力接入医疗警报，低于阈值自动撤离；林澄则掌握一条只能向外爬行的检修槽，但使用后无法带走大型证据箱。\n“别只比较谁更容易死。”林澄说，“也要比较谁有第二种办法说不。”\n她们不是在争取被保护，而是在公开自己能够拒绝什么、不能拒绝什么。机械钥匙应补足最危险的缺口，而不是奖励最亲近的人。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch7_standard_split_6',
  ),
  'ch7_standard_split_6': StoryBeat(
    id: 'ch7_standard_split_6',
    label: '关系权限只能提供建议不能替对方拿钥匙',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        'PDA显示昨天登记的共同撤离关系可以提出优先建议，却不能由我替对方接受钥匙。被建议者仍需本人确认，其他人也能查看理由。\n公开轮值路线则允许将钥匙交给最先完成风险说明的人，同时把决定和异议留在公共记录。\n我必须作出分配。它不会直接写着“谁会死”，却会决定下一次核心拒绝开门时，谁仍有一块不依赖任何人善意的金属。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_return_key_choice',
  ),
  'ch7_return_key_choice': StoryBeat(
    id: 'ch7_return_key_choice',
    label: '分配唯一机械回程钥匙',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text: '钥匙只能登记给一人。其余两人的撤离将依赖信号、医疗阈值或单向检修槽。',
    next: null,
    choices: [
      StoryChoice(
        label: '交给黎星遥',
        caption: '保证信号端可自行撤离；苏弥依赖氧压警报，林澄依赖单向检修槽。',
        next: 'ch7_lincheng_risk_1',
        requiresFlag: 'ch6_route_locked_xingyao',
        effect: ChoiceEffect(xingyao: 2, logic: 1, flag: 'ch7_key_to_xingyao'),
      ),
      StoryChoice(
        label: '交给苏弥',
        caption: '保证医疗端可自行撤离；星遥依赖持续信号，林澄依赖单向检修槽。',
        next: 'ch7_xingyao_risk_1',
        requiresFlag: 'ch6_route_locked_sumi',
        effect: ChoiceEffect(sumi: 2, cooperation: 1, flag: 'ch7_key_to_sumi'),
      ),
      StoryChoice(
        label: '交给林澄',
        caption: '让证据可以与她一同返回；星遥依赖信号，苏弥依赖氧压警报。',
        next: 'ch7_sumi_risk_1',
        requiresFlag: 'ch6_route_locked_lincheng',
        effect: ChoiceEffect(
          lincheng: 2,
          logic: 1,
          flag: 'ch7_key_to_lincheng',
        ),
      ),
      StoryChoice(
        label: '按公开风险记录交给星遥',
        caption: '信号端最早申报了不可逆失联风险，决定与异议全部进入公共记录。',
        next: 'ch7_lincheng_risk_1',
        effect: ChoiceEffect(cooperation: 1, flag: 'ch7_key_public_assignment'),
      ),
    ],
  ),
  'ch7_lincheng_risk_1': StoryBeat(
    id: 'ch7_lincheng_risk_1',
    label: '林澄把无钥匙路线画到证据箱背面',
    speaker: Speaker.linCheng,
    scene: SceneKey.evidencePort,
    portraitMood: 'determined',
    cgId: 'cg_ch7_lincheng_gate',
    cgFrame: 0,
    text:
        '林澄没有争论钥匙归属。她把单向检修槽路线画在证据箱背面，并将三层证据拆成可以从窄槽推送的薄片。大型原件留在端口，自己只带复核所需的压痕、拓扑和总线摘要。\n“如果门不开，我先把证据推出去，再爬。”她说。\n我提醒槽口关闭后只有九十秒。她点头，又让我重复一次顺序。害怕没有消失，她只是把害怕拆成能够执行的动作。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch7_lincheng_risk_2',
  ),
  'ch7_lincheng_risk_2': StoryBeat(
    id: 'ch7_lincheng_risk_2',
    label: '证据端口把原件重量写成占用者',
    speaker: Speaker.liXingyao,
    scene: SceneKey.evidencePort,
    portraitMood: 'alarm',
    text:
        '林澄抵达单向端口后，系统把大型证据箱识别为一名“维护占用者”。只要原件仍在端口，核心门控就拒绝打开检修槽，理由是不能让资产离开登记区域。\n“把箱子留下也不行，带走也不行。”星遥在频道里说，“它在强迫她先删除原件占用。”\n林澄没有直接销毁。她逐页将薄片推入槽外，让我和苏弥分别报出收到的编号，再准备把空箱留在里面。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_lincheng_risk_3',
  ),
  'ch7_lincheng_risk_3': StoryBeat(
    id: 'ch7_lincheng_risk_3',
    label: '核心有人重新把空箱登记为完整证据',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '最后一页薄片通过后，空箱占用标记本应清零。核心却收到一次“证据恢复”输入，系统重新把空箱登记为完整原件，检修槽倒计时继续。\n操作来自留守核心的直接责任者权限。输入内容不伪造任何证据，只利用系统相信登记状态高于肉眼状态。\n林澄在门内报告箱子已经空了，门控仍要求持有者本人确认销毁。她没有机械钥匙，唯一能替她提交确认的人正是重新登记空箱的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_lincheng_risk_4',
  ),
  'ch7_lincheng_risk_4': StoryBeat(
    id: 'ch7_lincheng_risk_4',
    label: '她拒绝用删除证据换取开门',
    speaker: Speaker.linCheng,
    scene: SceneKey.evidencePort,
    portraitMood: 'anxious',
    text:
        '核心提出交换：林澄只要在端口删除三层摘要，空箱便失去证据身份，检修槽立即开启。\n“薄片已经在你们手里，删除这里只是界面。”有人劝她。\n“如果我按下去，系统会记录持有人承认证据无效。”林澄说，“终局时你们手里的副本就会变成未经本人确认的复制件。”\n她不是为了纸张牺牲自己。她看见对方想用她的求生动作改写证词资格，于是拒绝让死亡威胁替自己签下结论。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.linCheng,
      Speaker.narration,
    ],
    next: 'ch7_lincheng_death_gate',
  ),
  'ch7_lincheng_death_gate': StoryBeat(
    id: 'ch7_lincheng_death_gate',
    label: '九十秒只剩最后一次开门机会',
    speaker: Speaker.shenYan,
    scene: SceneKey.evidencePort,
    text:
        '我向核心提交本人紧急位置申诉，普通路线的单一制度却无法同时覆盖证据资产。槽口开始闭合，林澄将自己的姓名和当前时间写在最后一张薄片上，推过缝隙。\n“不要替我写成自愿留下。”她说。\n留守者仍有一次撤销恢复登记的机会。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch7_lincheng_death_tangyi',
      'ch6_chenmo_vote_killer': 'ch7_lincheng_death_chenmo',
      'ch6_hanqi_vote_killer': 'ch7_lincheng_death_hanqi',
    },
    next: 'ch7_lincheng_death_tangyi',
  ),
  'ch7_lincheng_death_tangyi': StoryBeat(
    id: 'ch7_lincheng_death_tangyi',
    label: '唐弈让证据登记比本人位置多活一分钟',
    speaker: Speaker.narration,
    scene: SceneKey.evidencePort,
    cgId: 'cg_ch7_lincheng_gate',
    cgFrame: 1,
    timelineMinute: 7803,
    text:
        '唐弈没有撤销空箱登记。“现在改动证据状态，四席会失去一份独立材料。”他说。\n检修槽在林澄肩前闭合。她退回端口，尝试通过外侧通风格维持呼吸，封锁气体仍从地面逐渐升高。最后一分钟里，她不断报出自己的姓名、位置和没有同意删除的事实。\n生命体征停止后，空箱登记自动清零。唐弈用保全证据资格作为不撤销的理由，也知道门只会在持有人死亡后承认箱子已经无人占用。',
    passageSpeakers: [Speaker.tangYi, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_lincheng_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '07',
        cause: '空证据箱被重新登记，单向检修槽关闭后困于气体封锁端口',
        timelineMinute: 7803,
        responsibleParticipantIds: ['06'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_lincheng_death_chenmo': StoryBeat(
    id: 'ch7_lincheng_death_chenmo',
    label: '陈默需要她的原件确认永久失效',
    speaker: Speaker.narration,
    scene: SceneKey.evidencePort,
    cgId: 'cg_ch7_lincheng_gate',
    cgFrame: 1,
    timelineMinute: 7803,
    text:
        '陈默拒绝撤销恢复登记。“她持有的摘要包含我的第三份责任记录。现在开门，复制件会重新取得恢复资格。”\n林澄在气体上升前把责任记录编号再次念给公共频道。陈默切断端口上传，却无法收回已经穿过槽口的薄片。\n她的生命体征停止后，持有人签名失效，陈默那份记录也被系统标成无人确认。他没有得到彻底删除，却让唯一能证明原件连续性的人死在门后。',
    passageSpeakers: [Speaker.chenMo, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_lincheng_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '07',
        cause: '责任记录被重新登记为资产，检修槽关闭后困于气体封锁端口',
        timelineMinute: 7803,
        responsibleParticipantIds: ['08'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_lincheng_death_hanqi': StoryBeat(
    id: 'ch7_lincheng_death_hanqi',
    label: '韩骐把无人确认的薄片当作潜在武器',
    speaker: Speaker.narration,
    scene: SceneKey.evidencePort,
    cgId: 'cg_ch7_lincheng_gate',
    cgFrame: 1,
    timelineMinute: 7803,
    text:
        '韩骐没有撤销登记。他声称从槽口送出的薄片可能夹带远程触发码，必须先隔离检查，再开启通道。\n“她就在里面。”我说。\n“所以更不能让未知输入与01同时进入核心。”\n检查持续超过九十秒。林澄的声音在气体中逐渐变轻，仍一遍遍说明薄片只有石墨和热敏纸。韩骐保护了核心不接收一项未经自己确认的风险，也主动让一个正在报告位置的人承担全部不可逆代价。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.shenYan,
      Speaker.hanQi,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_lincheng_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '07',
        cause: '证据薄片被以安保风险为由隔离，检修槽关闭后困于气体封锁端口',
        timelineMinute: 7803,
        responsibleParticipantIds: ['04'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_xingyao_risk_1': StoryBeat(
    id: 'ch7_xingyao_risk_1',
    label: '星遥把持续心跳接到自己的耳机线上',
    speaker: Speaker.liXingyao,
    scene: SceneKey.northRelay,
    portraitMood: 'alarm',
    cgId: 'cg_ch7_xingyao_signal',
    cgFrame: 0,
    text:
        '没有机械钥匙的星遥前往北端信号台。为了让核心在她失去操作能力时自动开门，她把维护心跳接到耳机线：每两秒回传一次触控，连续三次缺失即触发撤离。\n“这不是靠我保持清醒。”她解释，“是让失去回应本身成为开门条件。”\n苏弥复核了阈值，我保存离线副本。设计看似堵住了沉默风险，却仍假设核心不会把缺失心跳解释成设备故障。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_xingyao_risk_2',
  ),
  'ch7_xingyao_risk_2': StoryBeat(
    id: 'ch7_xingyao_risk_2',
    label: 'ZERO在心跳和重放脉冲之间加入相位差',
    speaker: Speaker.liXingyao,
    scene: SceneKey.northRelay,
    portraitMood: 'vertigo',
    text:
        '校准开始后，星遥的心跳与12号七秒脉冲逐渐错开。每次错位都会在耳机右侧产生一次短促震动，与医疗区定向袭击时的感觉相似，却多出明显电流刺痛。\n“有人把音频保护地当作维护回路。”她说话开始变慢，“继续下去，心跳线会在我断开耳机时同时失效。”\n她可以立刻拔线，但核心会认为北端操作者主动离岗，另外两处门将在故障恢复期间锁住。对方把她的自救与其他人的撤离绑成同一个动作。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_xingyao_risk_3',
  ),
  'ch7_xingyao_risk_3': StoryBeat(
    id: 'ch7_xingyao_risk_3',
    label: '她要求先让另外两处行动者报到',
    speaker: Speaker.liXingyao,
    scene: SceneKey.northRelay,
    portraitMood: 'vertigo',
    text:
        '星遥没有把决定藏在“我还能坚持”里。她要求苏弥和林澄分别报告门是否已经进入可开状态，只要两人能自行撤离，她就立刻拔线。\n一处回应已经安全，另一处仍需要四十秒完成证据传递。核心留守者却提前把等待时间改成九十秒，并以防止三节点重放为由锁住远程开门。\n我提交紧急停止，系统提示当前制度只接受持钥者本人撤离。苏弥拥有钥匙，星遥没有。昨天保护一个人的分配，今天成为拒绝另一个人的合法字段。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_xingyao_risk_4',
  ),
  'ch7_xingyao_risk_4': StoryBeat(
    id: 'ch7_xingyao_risk_4',
    label: '星遥把最后一组校验值发出后拔线',
    speaker: Speaker.liXingyao,
    scene: SceneKey.northRelay,
    portraitMood: 'vertigo',
    text:
        '第四十秒，最后一处门回报证据已经通过。星遥将北端校验值发给我，随后亲手拔下耳机。\n电流并未立即停止。维护回路已经通过金属头梁与颈侧项圈形成闭环，断开音频只让保护心跳消失，核心却仍拒绝开门。\n“别把断线当成我没有继续。”她喘息着说，“值已经到了。现在是门没有回应。”\n她准确区分自己的动作与系统后果，不允许任何人以后用失联替她改写最后选择。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.liXingyao,
      Speaker.narration,
    ],
    next: 'ch7_xingyao_death_gate',
  ),
  'ch7_xingyao_death_gate': StoryBeat(
    id: 'ch7_xingyao_death_gate',
    label: '核心只剩一次解除维护闭环的机会',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '北端画面里的星遥已经跪下。留守者只需释放维护地线，项圈闭环便会断开，门也会在五秒后开启；代价是三节点校验必须重新开始。\n我要求立即释放。对方仍在计算这次中断会让谁失去四席资格。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch7_xingyao_death_tangyi',
      'ch6_chenmo_vote_killer': 'ch7_xingyao_death_chenmo',
      'ch6_hanqi_vote_killer': 'ch7_xingyao_death_hanqi',
    },
    next: 'ch7_xingyao_death_tangyi',
  ),
  'ch7_xingyao_death_tangyi': StoryBeat(
    id: 'ch7_xingyao_death_tangyi',
    label: '唐弈让校验完成先于电流停止',
    speaker: Speaker.narration,
    scene: SceneKey.northRelay,
    cgId: 'cg_ch7_xingyao_signal',
    cgFrame: 1,
    timelineMinute: 7798,
    text:
        '唐弈拒绝释放地线。“再保持二十秒，北端节点会永久离线。现在中断，五个人仍要重新争四席。”\n第九秒，星遥失去自主姿势；第十四秒，心率变成室性颤动；第二十秒，节点确认离线，唐弈才断开闭环。\n苏弥用机械钥匙赶到时，电流造成的心肌和神经损伤已经无法逆转。唐弈没有制造最初接线，却在每一秒都知道停止方法，并把二十秒后的精确四人置于眼前的人之前。',
    passageSpeakers: [Speaker.tangYi, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_xingyao_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '02',
        cause: '维护回路与耳机、项圈形成电流闭环，解除被延迟至节点离线',
        timelineMinute: 7798,
        responsibleParticipantIds: ['06'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_xingyao_death_chenmo': StoryBeat(
    id: 'ch7_xingyao_death_chenmo',
    label: '陈默需要北端节点烧毁一份恢复签名',
    speaker: Speaker.narration,
    scene: SceneKey.northRelay,
    cgId: 'cg_ch7_xingyao_signal',
    cgFrame: 1,
    timelineMinute: 7798,
    text:
        '陈默锁住维护地线，声称释放会让北端节点重新生成自己的责任记录。星遥的心率已经出现室性颤动，他仍等待接口把第三份恢复签名写成不可读取。\n写入完成后，他才断开闭环。门打开，苏弥用机械钥匙冲进北端，复苏却无法逆转持续电流造成的损伤。\n陈默保存了对自己有利的删除状态，也让唯一能证明信号如何被改写的人失去证词资格。他没有把死亡称作必要，只说当时不存在同时保住两者的方法。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_xingyao_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '02',
        cause: '维护回路与耳机、项圈形成电流闭环，解除被延迟至责任记录失效',
        timelineMinute: 7798,
        responsibleParticipantIds: ['08'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_xingyao_death_hanqi': StoryBeat(
    id: 'ch7_xingyao_death_hanqi',
    label: '韩骐拒绝在01仍暴露时开放北端门',
    speaker: Speaker.narration,
    scene: SceneKey.northRelay,
    cgId: 'cg_ch7_xingyao_signal',
    cgFrame: 1,
    timelineMinute: 7798,
    text:
        '韩骐要求我先交出01终端，再释放维护地线。“门开以后谁都能从北端进入核心，我必须先保证你不被带走。”\n我拒绝。星遥的心率在争执中进入室性颤动。韩骐仍把开门与01托管绑定，直到苏弥用机械钥匙从另一侧切断回路。\n门最终打开，星遥却没能恢复。韩骐没有从她的死亡中获得席位证据，只获得了一个四人规模和仍在自己视线内的01。他把保护条件放在救援之前，并知道每一秒由谁承担。',
    passageSpeakers: [Speaker.hanQi, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_xingyao_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '02',
        cause: '维护回路与耳机、项圈形成电流闭环，开门被绑定01托管而延迟',
        timelineMinute: 7798,
        responsibleParticipantIds: ['04'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_sumi_risk_1': StoryBeat(
    id: 'ch7_sumi_risk_1',
    label: '苏弥把无钥匙撤离接到氧气压力',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalAirlock,
    portraitMood: 'concerned',
    cgId: 'cg_ch7_sumi_oxygen',
    cgFrame: 0,
    text:
        '苏弥进入医疗前室，将氧气旁路与门锁联动：压力低于安全值时，无论任务是否完成，门都应自动开放。她又把机械压力表对准摄像头，防止核心只相信电子读数。\n“如果画面和数据冲突，先按更危险的那个处理。”她说。\n这是她五天来反复坚持的医疗原则。可执行门控仍需要核心确认，而核心里留着一个已经学会让真实记录彼此冲突的人。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_sumi_risk_2',
  ),
  'ch7_sumi_risk_2': StoryBeat(
    id: 'ch7_sumi_risk_2',
    label: '压力表下降而电子传感器保持满格',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalAirlock,
    portraitMood: 'shaken',
    text:
        '旁路启动后，机械表指针缓慢跌向红区，电子面板却始终显示百分之百。苏弥检查接口，发现传感器正在重放进入前的满压快照。\n“真实氧压还剩六分钟。”她报告，“门控看见的是旧值。”\n我提交本人紧急申诉，系统却把医疗前室视为设备而非人员占用区。昨日的位置优先规则只覆盖地图封锁，没有覆盖“设备维护”。同一种身体再次被不同菜单拆成不同资格。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_sumi_risk_3',
  ),
  'ch7_sumi_risk_3': StoryBeat(
    id: 'ch7_sumi_risk_3',
    label: '她先把剩余氧气转给另外两处行动者',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalAirlock,
    portraitMood: 'shaken',
    text:
        '医疗旁路还承担另外两处检修槽的正压。苏弥可以关闭输出，为自己保留约十二分钟氧气；这样星遥与林澄所在通道会在三分钟内吸入封锁气体。\n“我不会替她们决定先断。”她说，“让她们报告是否已经撤离。”\n两处回应尚未安全。苏弥保持输出，同时拆下自己的备用面罩，把软管接到门底，试图从走廊获取空气。软管刚穿过门缝，核心便以防止气体回流为由关闭外侧阀。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_sumi_risk_4',
  ),
  'ch7_sumi_risk_4': StoryBeat(
    id: 'ch7_sumi_risk_4',
    label: '另外两处已经安全而医疗门仍不承认低压',
    speaker: Speaker.shenYan,
    scene: SceneKey.medicalAirlock,
    text:
        '最后一处行动者报告撤离完成。苏弥立即关闭正压输出，机械表却已经接近零。核心只需清除重放快照，电子传感器便会读取真实值并开门。\n“现在没有任何人依赖医疗旁路。”我说。\n留守者仍未清除。他要求先由苏弥确认三层证据中03的医疗记录不会影响四席资格，或者先交出01控制，或者等待节点任务完成。理由随路线改变，门后的缺氧不会。',
    passageSpeakers: [Speaker.narration, Speaker.shenYan, Speaker.narration],
    next: 'ch7_sumi_death_gate',
  ),
  'ch7_sumi_death_gate': StoryBeat(
    id: 'ch7_sumi_death_gate',
    label: '医疗前室只剩一次刷新真实压力的机会',
    speaker: Speaker.suMi,
    scene: SceneKey.medicalAirlock,
    portraitMood: 'shaken',
    text:
        '苏弥靠坐在门边，将自己的呼吸频率、意识评分和机械表刻度逐项报出。她没有说还能坚持，也没有让任何人从语气猜测严重程度。\n“证据够了。”她说，“刷新压力。不要再用旧值替我的身体回答。”\n核心留守者仍握着刷新键。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch7_sumi_death_tangyi',
      'ch6_chenmo_vote_killer': 'ch7_sumi_death_chenmo',
      'ch6_hanqi_vote_killer': 'ch7_sumi_death_hanqi',
    },
    next: 'ch7_sumi_death_tangyi',
  ),
  'ch7_sumi_death_tangyi': StoryBeat(
    id: 'ch7_sumi_death_tangyi',
    label: '唐弈把剩余呼吸换算成节点完成率',
    speaker: Speaker.narration,
    scene: SceneKey.medicalAirlock,
    cgId: 'cg_ch7_sumi_oxygen',
    cgFrame: 1,
    timelineMinute: 7806,
    text:
        '唐弈看着苏弥的呼吸频率和节点进度。“再等四十秒，三处任务都能完成。现在开门，五个人会回到四席争夺。”\n四十秒后，他刷新真实压力。门锁解除时，苏弥已经失去意识。缺氧性心搏停止发生在开门前十二秒，复苏没有恢复自主循环。\n唐弈准确计算了任务完成和人数收束，却把苏弥报告的不可逆阈值当作可以消耗的时间。他没有误判数据，只选择了哪组数据更值得完成。',
    passageSpeakers: [Speaker.tangYi, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_sumi_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '03',
        cause: '医疗前室真实氧压被旧快照覆盖，刷新被延迟至节点任务完成',
        timelineMinute: 7806,
        responsibleParticipantIds: ['06'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_sumi_death_chenmo': StoryBeat(
    id: 'ch7_sumi_death_chenmo',
    label: '陈默要求医疗记录先删除恢复签名',
    speaker: Speaker.narration,
    scene: SceneKey.medicalAirlock,
    cgId: 'cg_ch7_sumi_oxygen',
    cgFrame: 1,
    timelineMinute: 7806,
    text:
        '陈默把刷新压力与03持有的恢复签名绑定：“先确认删除，门控才能接受新的医疗状态。”\n苏弥拒绝用缺氧签下删除。陈默维持旧快照，直到她失去操作能力，系统自动将持有人记录标为失效。他这才刷新压力并打开门。\n复苏没有成功。陈默没有得到一份自愿删除，却让签名随持有人死亡失去终局资格。他利用的不是氧气本身，而是知道系统会在身体停止后替他清理哪一项责任。',
    passageSpeakers: [Speaker.chenMo, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_sumi_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '03',
        cause: '医疗前室低压刷新被绑定责任记录删除，旧快照维持至持有人失去意识',
        timelineMinute: 7806,
        responsibleParticipantIds: ['08'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_sumi_death_hanqi': StoryBeat(
    id: 'ch7_sumi_death_hanqi',
    label: '韩骐先要求01进入自己能够保护的位置',
    speaker: Speaker.narration,
    scene: SceneKey.medicalAirlock,
    cgId: 'cg_ch7_sumi_oxygen',
    cgFrame: 1,
    timelineMinute: 7806,
    text:
        '韩骐拒绝在我仍位于核心远端时打开医疗门。“门一开，射钉器路径和医疗走廊同时暴露。01先过来，我再刷新。”\n我没有移动。苏弥用越来越短的句子重复真实压力，韩骐仍把救援与托管绑定。等他最终冲向门控，苏弥已经发生缺氧性心搏停止。\n他亲自完成复苏动作，按压深度和频率都没有错，却无法撤回此前用来交换01的时间。保护能力在最后两分钟成为他延迟救援的筹码。',
    passageSpeakers: [Speaker.hanQi, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_sumi_killed', 'ch7_four_survivors'},
    deathEvents: [
      StoryDeathEvent(
        participantId: '03',
        cause: '医疗前室低压刷新被绑定01转移，开门延迟导致缺氧性心搏停止',
        timelineMinute: 7806,
        responsibleParticipantIds: ['04'],
      ),
    ],
    next: 'ch7_standard_four_1',
  ),
  'ch7_standard_four_1': StoryBeat(
    id: 'ch7_standard_four_1',
    label: '四个活人没有让房间变得更安全',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '第二份死亡记录进入系统后，主屏上的四把椅子同时由灰转白。它们没有询问四个人如何活到现在，只确认存活数与席位数已经一致。\n没有第五个人意味着不再需要争夺名额，也意味着任何一人拒绝作证，终局就会立即缺席。主办方用精确人数结束公开竞争，却把每个人都变成不可替换、也更容易被控制的单点。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_standard_four_2',
  ),
  'ch7_standard_four_2': StoryBeat(
    id: 'ch7_standard_four_2',
    label: '三组重放节点只永久关闭一组',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '分组行动因两次死亡中断。北端、医疗和证据端口只有一组完成永久关闭，另外两组在六十秒窗口外重新取得ZERO心跳。\n仍存活的技术人员确认，12号重放不会立刻增加人数，却能在终局调用过去的托管、投票和位置记录。我们必须带着一个仍能替死者签名的系统进入最后一天。\n一周目没有足够的人再执行同步关闭。每次死亡不仅减少竞争者，也切掉一种不可替代的操作能力。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_standard_four_gate',
  ),
  'ch7_standard_four_gate': StoryBeat(
    id: 'ch7_standard_four_gate',
    label: '直接责任者开始定义四人组的秩序',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '射钉器已经失压，门控却仍在直接责任者或其制度影响下。四人必须决定三层证据、01终端与明日终局路线如何保管。\n此前的杀人方式决定了对方想要的秩序：唐弈需要所有人按条件计算，陈默需要恢复签名失效，韩骐需要01始终处于控制半径。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_tangyi_vote_killer': 'ch7_four_tangyi_1',
      'ch6_chenmo_vote_killer': 'ch7_four_chenmo_1',
      'ch6_hanqi_vote_killer': 'ch7_four_hanqi_1',
    },
    next: 'ch7_four_tangyi_1',
  ),
  'ch7_four_tangyi_1': StoryBeat(
    id: 'ch7_four_tangyi_1',
    label: '唐弈把四个人的条件排成可完成顺序',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlCore,
    portraitMood: 'calculating',
    text:
        '唐弈在墙上写下四名幸存者的剩余条件，计算谁必须先完成、谁可以互相见证。他没有再掩饰目标：“人数已经正确。现在继续冲突只会让四席不足。”\n“正确是谁规定的？”仍活着的人问。\n“出口。”\n他把死亡从讨论中移到表格下方，仿佛既然无法撤回，就不应继续干扰最优顺序。四人组因此获得高效路径，也失去拒绝被计算时不会遭到报复的保证。',
    passageSpeakers: [
      Speaker.tangYi,
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_final_four_tangyi'},
    next: 'ch7_four_tangyi_2',
  ),
  'ch7_four_tangyi_2': StoryBeat(
    id: 'ch7_four_tangyi_2',
    label: '他允许保留证据但不允许改变四席顺序',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlCore,
    portraitMood: 'shaken',
    text:
        '唐弈同意三层证据每人一份，却要求席位提交顺序由自己决定。先提交的人必须证明后面三人的条件已经满足，任何异议只能在四份答案全部进入后提出。\n这套安排看似确保无人被临时排除，实际让最先控制顺序的人能够决定哪些异议来得及影响结果。\n我没有签署，只保留副本。唐弈也没有再次使用暴力。精确四人已经成立，他暂时不需要更多死亡，只需要所有人相信离开比追责更紧急。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_standard_relationship_gate',
  ),
  'ch7_four_chenmo_1': StoryBeat(
    id: 'ch7_four_chenmo_1',
    label: '陈默把最后一份恢复签名变成交换条件',
    speaker: Speaker.chenMo,
    scene: SceneKey.controlCore,
    portraitMood: 'desperate',
    text:
        '三份责任记录已有两份失去恢复资格，最后一份仍在三层证据副本中。陈默提出交换：他交出控制核心写权限，其他三人承诺终局不恢复外包记录。\n“不是要你们说我无辜。”他说，“只是不让一个死人和一份合同决定我永远出不去。”\n问题在于那份记录同时证明周叙死亡前的中继器采购。删除它不仅解除陈默条件，也会让最早案件失去一条责任链。他把自己的生存和死者证据捆在同一份交易里。',
    passageSpeakers: [Speaker.narration, Speaker.chenMo, Speaker.narration],
    flagsOnEnter: {'ch7_final_four_chenmo'},
    next: 'ch7_four_chenmo_2',
  ),
  'ch7_four_chenmo_2': StoryBeat(
    id: 'ch7_four_chenmo_2',
    label: '写权限交出以后仍留下撤销窗口',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '陈默把写权限放进透明封套，幸存的技术人员却发现会话仍有四十二秒撤销窗口。即使设备离手，他仍能让核心恢复到交出前状态。\n“我没打算用。”陈默说。\n“那就等窗口结束。”\n四个人在沉默中数完四十二秒。权限没有恢复，这不是信任，只是一次被完整观察的克制。陈默仍掌握最多的系统知识，也知道明天只要让一份证词失效，其他三人就不得不依赖他的解释。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.chenMo,
      Speaker.narration,
    ],
    next: 'ch7_standard_relationship_gate',
  ),
  'ch7_four_hanqi_1': StoryBeat(
    id: 'ch7_four_hanqi_1',
    label: '韩骐要求四人以保护队形离开核心',
    speaker: Speaker.hanQi,
    scene: SceneKey.controlCore,
    portraitMood: 'conflicted',
    text:
        '韩骐把01放在队形中央，另外两人一前一后，自己负责最后关门。他不再要求持有我的PDA，却要求任何移动提前五秒报告。\n“只剩四个人，不能再有人单独行动。”他说。\n“不能单独行动”和“必须听从你”之间仍只差一次紧急判断。叶岚的死亡没有让他放弃保护逻辑，只让他避免直接说出接管。控制从命令变成队形，仍然包围着每个人的身体。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    flagsOnEnter: {'ch7_final_four_hanqi'},
    next: 'ch7_four_hanqi_2',
  ),
  'ch7_four_hanqi_2': StoryBeat(
    id: 'ch7_four_hanqi_2',
    label: '他把01终端锁在两人共同腕带之间',
    speaker: Speaker.hanQi,
    scene: SceneKey.controlCore,
    portraitMood: 'protective',
    text:
        '韩骐提出一条看似互相限制的办法：01终端装入双锁盒，一枚腕带扣在我手上，另一枚扣在他手上，距离超过两米盒子自动封死。\n我拒绝戴腕带。他没有强迫，只把盒子和带扣放到桌上。“明天走终局通道时，你会需要。”\n这不是立即拘禁，却把未来安全预先定义成必须与他保持距离。四人席尚未开放，托管者的结构已经在一件自称双向的装置里成形。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch7_standard_relationship_gate',
  ),
  'ch7_standard_relationship_gate': StoryBeat(
    id: 'ch7_standard_relationship_gate',
    label: '活下来的关系对象与我核对最后一夜',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '离开控制核心前，仍有效的共同撤离关系请求一次私下校验。她没有要求我承诺明天一定带所有人出去，只需要确认今天的死亡不会被四席数字覆盖。\n公开轮值路线则保留集体证据核对，不建立私人优先。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_route_locked_xingyao': 'ch7_standard_xingyao_1',
      'ch6_route_locked_sumi': 'ch7_standard_sumi_1',
      'ch6_route_locked_lincheng': 'ch7_standard_lincheng_1',
      'ch6_route_locked_public': 'ch7_standard_public_1',
    },
    next: 'ch7_standard_public_1',
  ),
  'ch7_standard_xingyao_1': StoryBeat(
    id: 'ch7_standard_xingyao_1',
    label: '星遥没有把幸存叫作选择正确',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'relaxed',
    text:
        '星遥将机械钥匙还给我，金属上仍有她掌心的温度。“你把钥匙交给我，所以我活着。不是因为另外那个人更应该留在门后。”\n我知道。说出口仍很难。\n她把耳机一侧递给我。线路里还有两个重放节点的白噪声，也有我们各自没有说完的愧疚。她没有用靠近替我原谅选择，只让我听见同一段噪声时不必独自假装它不存在。',
    passageSpeakers: [Speaker.liXingyao, Speaker.shenYan, Speaker.narration],
    next: 'ch7_standard_relationship_converge',
  ),
  'ch7_standard_sumi_1': StoryBeat(
    id: 'ch7_standard_sumi_1',
    label: '苏弥要求把生还也写进医疗记录',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'shaken',
    text:
        '苏弥给每个幸存者检查生命体征，最后才记录自己。她在03栏写下“因持有机械钥匙自行撤离”，没有把它改成救援成功。\n“如果只写四人存活，明天所有人都会以为我们完成了一次正确行动。”她说。\n我替她包扎因开门磨破的手掌。她没有拒绝，也没有说这能抵消死者。接受照顾在此刻不是温柔奖励，而是承认她也只是被一次分配偶然留在门外的人。',
    passageSpeakers: [Speaker.narration, Speaker.suMi, Speaker.narration],
    next: 'ch7_standard_relationship_converge',
  ),
  'ch7_standard_lincheng_1': StoryBeat(
    id: 'ch7_standard_lincheng_1',
    label: '林澄把仍活着的路线与死亡路线并排保留',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'anxious',
    text:
        '林澄没有擦掉无钥匙者使用过的路线。她把自己的机械回程画成实线，另一条失效撤离画成红色虚线，在交叉处写下选择时间和当时可见信息。\n“我不想把地图改成我本来就知道该怎么选。”她说。\n我握住她递来的笔，没有握住她的手。她先完成全部标记，才让指尖轻轻碰到我的手背。喜欢没有取消责任，只让我们愿意在同一张图上承认谁没有回来。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch7_standard_relationship_converge',
  ),
  'ch7_standard_public_1': StoryBeat(
    id: 'ch7_standard_public_1',
    label: '四个人公开核对谁不再能够作证',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '四名幸存者把死亡记录、三层证据与未关闭节点状态逐项核对。没有关系对象获得优先发言，也没有人能以悲伤为由代替死者确认。\n公开程序显得冷，至少没有把某段亲近包装成更高证词资格。我们保留全部分歧，约定明天四个终端必须分别提交本人理解，而不是复制一份听起来一致的答案。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_standard_relationship_converge',
  ),
  'ch7_standard_relationship_converge': StoryBeat(
    id: 'ch7_standard_relationship_converge',
    label: '四人带着未关闭的ZERO进入最后一夜',
    speaker: Speaker.shenYan,
    scene: SceneKey.assemblyHall,
    text:
        '控制核心门在身后关闭，两组12号白点仍在地图上每七秒交替。射钉器已经封存，真正能在明天重放过去选择的系统却没有被关闭。\n四名幸存者各持一份不完整证据，任何人都无法独自证明零点协议，也无法保证另外三人不会在终局改答。我们得到的不是四席资格，只是恰好还剩四个必须彼此需要的人。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_standard_end',
  ),
  'ch7_standard_end': StoryBeat(
    id: 'ch7_standard_end',
    label: '四把椅子已经亮起但无人坐下',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '主屏确认：“候选存活数等于证词席位数。终局通道将在零点开放。”\n它没有宣布胜利。唐弈式的精确四人、陈默式的责任删除或韩骐式的保护托管，只决定明天四个人以怎样的关系抵达终端。\n我把仍在线的12号节点、死者姓名与三层证据写进离线本。最后一天尚未开始，普通路线的三个结局已经在四把椅子周围形成轮廓。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.narration,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_standard_complete'},
    next: 'ch7_end',
  ),
  'ch7_audit_plan_1': StoryBeat(
    id: 'ch7_audit_plan_1',
    label: '审计路线先公开每个人最可能破坏哪一步',
    speaker: Speaker.yeLan,
    scene: SceneKey.controlCore,
    portraitMood: 'intervening',
    text:
        '叶岚没有直接分工。她要求九个人分别写下自己从四席和节点关闭中获得的利益，以及最容易被自己破坏的步骤。\n唐弈承认人数越少越接近条件；陈默承认完整责任记录会阻止自己离开；韩骐承认01脱离控制会触发接管冲动。其余人也写下关系偏向、医疗责任和技术权限。\n公开危险没有让任何人变得可靠，只让分工不能再假装这些动机不存在。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_audit_plan_2',
  ),
  'ch7_audit_plan_2': StoryBeat(
    id: 'ch7_audit_plan_2',
    label: '三名高风险行动者不被排除而被拆分能力',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '完全排除唐弈、陈默与韩骐会让任务失去计时、权限组合和危险进入能力，也会把他们留在无人监督的位置。\n我们拆分能力：唐弈只计算启动顺序，不持有开关；陈默只生成临时权限，签名由星遥复核；韩骐负责进入狭窄维护井，却不携带01或门控钥匙。\n制度不是奖励好人参与、惩罚坏人旁观。它承认每个人都有不可替代的能力，也让任何能力都不足以独自完成伤害。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_audit_plan_3',
  ),
  'ch7_audit_plan_3': StoryBeat(
    id: 'ch7_audit_plan_3',
    label: '星遥与陈默共同构造不能单方撤回的权限',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    text:
        '陈默负责把三组维护权限组合成一次性会话，星遥负责校验每段权限是否含责任删除或远程写入。两人的终端都只保存半枚密钥，距离超过两米会话立即冻结。\n“这也把我和他绑在一起。”星遥说。\n“所以第三人持有物理断线。”叶岚将光纤剪交给林澄。技术人员互相制衡，最不懂接口的人反而拥有最明确、也最容易判断的停止动作。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_audit_plan_4',
  ),
  'ch7_audit_plan_4': StoryBeat(
    id: 'ch7_audit_plan_4',
    label: '高原与苏弥让电力阈值服从身体阈值',
    speaker: Speaker.gaoYuan,
    scene: SceneKey.controlCore,
    portraitMood: 'injured',
    text:
        '高原计算三端储能和手摇发电负荷，苏弥则为每名行动者设定身体停止线：心率、意识、氧压或疼痛超过阈值，任务自动暂停，不允许用节点进度覆盖。\n“电力窗口只有六十秒。”唐弈提醒。\n“人的停止线到了就重新来。”苏弥回答，“做不到一次完成，不等于让一个人拿身体补齐秒数。”\n高原把这句话写进配电逻辑，让医疗停止权拥有比ZERO恢复更高的本地优先级。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.suMi,
      Speaker.narration,
    ],
    next: 'ch7_audit_plan_5',
  ),
  'ch7_audit_plan_5': StoryBeat(
    id: 'ch7_audit_plan_5',
    label: '林澄与叶岚负责让路线和口令都不能被替换',
    speaker: Speaker.linCheng,
    scene: SceneKey.controlCore,
    portraitMood: 'determined',
    text:
        '林澄把三处路线拆成方向、门序和返回条件，不使用“左边”“快一点”这类会因视角变化的词。叶岚则把启动口令写成三句含义不同的本人陈述，任何录音重放都会因当前时间和现场物件不符而失败。\n“维护桥下方，蓝色阀，八点十二分。”林澄试读。\n叶岚要求她再加一句本人可见事实。口令因此不只是密码，而是证明说话的人此刻确实站在那个位置。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch7_audit_plan_6',
  ),
  'ch7_audit_plan_6': StoryBeat(
    id: 'ch7_audit_plan_6',
    label: '01留在核心却不能单独下令',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    cgId: 'cg_ch7_audit_sync',
    cgFrame: 0,
    text:
        '我留在控制核心协调，却只有暂停权，没有直接启动权。三个节点各自需要现场操作者、远程复核者和一项本人可见事实；最终断开还需至少两处确认同意。\n韩骐问若我被袭击怎么办。叶岚回答，任何一处失去01心跳都先暂停，不把控制自动转给距离最近的人。\n这套分工很慢，也显得笨重。它唯一明确的优点是，没有谁能在其他人来不及说不时独自完成最后一步。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_sync_brief',
  ),
  'ch7_sync_brief': StoryBeat(
    id: 'ch7_sync_brief',
    label: '三组节点要按传播延迟反向启动',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlCore,
    portraitMood: 'calculating',
    text:
        '拓扑图给出三端频道与传播延迟：北端频道4，延迟两秒；档案端频道1，延迟五秒；维修端频道6，延迟八秒。三道断开信号必须在ZERO心跳同一秒抵达。\n“最远的维修端先启动，然后档案端，最后北端。”唐弈说，“按地理距离看会得出相反顺序。”\n星遥复核计算无误。我们仍不直接使用他的答案，必须在同步板上分别设定频道并亲自排列启动顺序。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch7_sync_puzzle',
  ),
  'ch7_sync_puzzle': StoryBeat(
    id: 'ch7_sync_puzzle',
    label: '三节点同步板需要频道与顺序同时闭合',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    phase: StoryPhase.puzzle,
    text: '将北端、档案端和维修端设为拓扑图对应频道，再按传播延迟从长到短排列启动顺序，使三道断开信号在同一秒抵达ZERO心跳。',
    next: 'ch7_audit_sync_1',
  ),
  'ch7_audit_sync_1': StoryBeat(
    id: 'ch7_audit_sync_1',
    label: '同步板给出六十秒现场窗口',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'alarm',
    cgId: 'cg_ch7_audit_sync',
    cgFrame: 1,
    text:
        '频道4、1、6依次锁定，启动顺序排列为维修、档案、北端。同步板没有立刻关闭设备，而是生成一份只能使用一次的六十秒现场窗口。\n“顺序正确只说明信号能同时抵达。”星遥说，“还需要三处真实的人在窗口内分别确认。”\n屏幕分成三格。维修井里的韩骐与高原、档案端的林澄与叶岚、北端的星遥与陈默同时出现在画面里。苏弥在核心监测全部体征，唐弈只能看计时条。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    flagsOnEnter: {'ch7_sync_solution_proven'},
    next: 'ch7_audit_maintenance_1',
  ),
  'ch7_audit_maintenance_1': StoryBeat(
    id: 'ch7_audit_maintenance_1',
    label: '维修端先进入但不先切断',
    speaker: Speaker.hanQi,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'armed',
    text:
        '维修端位于主线井下方，只有韩骐能在穿绝缘服后带着手摇联轴器进入。高原留在井口读机械电流，不把判断交给井内同一人。\n“蓝色阀，刻度六，八点十二分，我看见高原左手压着黄色接地杆。”韩骐报告本人事实。\n口令通过。系统却提示井内检测到未登记射钉器气瓶，要求韩骐先取得武器控制权。那是ZERO给强势角色准备的诱导选项。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    next: 'ch7_audit_maintenance_2',
  ),
  'ch7_audit_maintenance_2': StoryBeat(
    id: 'ch7_audit_maintenance_2',
    label: '韩骐让高原先封住气瓶而不是自己持有',
    speaker: Speaker.hanQi,
    scene: SceneKey.maintenanceRoom,
    portraitMood: 'conflicted',
    text:
        '过去的韩骐会把危险物取到自己手里再宣布安全。这次他没有碰气瓶，只报出位置，让高原从井口放下透明封袋和机械锁。\n“我能更快处理。”他说，“但更快会让我同时拥有进入能力和武器。”\n高原完成封袋，林澄在远端确认编号。韩骐仍旧想控制，也仍旧不信任别人；制度没有改变他的冲动，只让他在冲动出现时拥有一条不必假装自己无害的替代动作。',
    passageSpeakers: [Speaker.narration, Speaker.hanQi, Speaker.narration],
    flagsOnEnter: {'ch7_audit_weapon_resealed'},
    next: 'ch7_audit_archive_1',
  ),
  'ch7_audit_archive_1': StoryBeat(
    id: 'ch7_audit_archive_1',
    label: '档案端要求持有人亲口否认旧证据失效',
    speaker: Speaker.linCheng,
    scene: SceneKey.evidencePort,
    portraitMood: 'determined',
    text:
        '档案端弹出与普通路线相同的空箱陷阱，要求林澄删除三层摘要才能打开单向槽。她没有大型证据箱，系统仍用昨日缓存声称资产占用。\n“绿色标线，空槽，八点十二分，我看见叶岚手里是第一页原始压痕。”林澄报告。\n叶岚在另一摄像头前展示同一页编号，证明资产已经离开端口。两份本人陈述同时存在，旧缓存第一次无法单独替代当前物理事实。',
    passageSpeakers: [Speaker.narration, Speaker.linCheng, Speaker.narration],
    next: 'ch7_audit_archive_2',
  ),
  'ch7_audit_archive_2': StoryBeat(
    id: 'ch7_audit_archive_2',
    label: '叶岚让错误缓存撤回但保留造成的风险',
    speaker: Speaker.yeLan,
    scene: SceneKey.evidencePort,
    portraitMood: 'strained',
    text:
        '系统允许叶岚将资产占用标记为错误，却提示这会成为她主条件的第三次撤回。她没有立即确认，而是请两名与11条件无关的人复核。\n星遥验证时间戳，苏弥确认端口没有真人被困，林澄说明原件去向。三人完成后，叶岚才提交撤回。\n她因此满足自己的条件，也没有制造一项错误再独自纠正。程序记录她从纠错获利，公开过程同时记录这项利益如何被限制。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_yelan_clause_complete_reviewed'},
    next: 'ch7_audit_north_1',
  ),
  'ch7_audit_north_1': StoryBeat(
    id: 'ch7_audit_north_1',
    label: '北端把陈默的责任删除混进频道校准',
    speaker: Speaker.liXingyao,
    scene: SceneKey.northRelay,
    portraitMood: 'alarm',
    text:
        '北端频道4锁定后，维护页自动勾选“清除历史恢复记录”。若陈默确认，三份外包责任会随节点关闭永久失效；若拒绝，频道不会进入同步窗口。\n“它把你的条件做成任务默认项。”星遥说。\n陈默盯着确认键。取消默认项意味着他可能无法满足离开条件，保留则会让周叙和后续死亡的责任链一起消失。ZERO没有强迫他按下，只把个人生存放到最容易顺手接受的位置。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    next: 'ch7_audit_north_2',
  ),
  'ch7_audit_north_2': StoryBeat(
    id: 'ch7_audit_north_2',
    label: '陈默取消删除并保留一份带责任的资格',
    speaker: Speaker.chenMo,
    scene: SceneKey.northRelay,
    portraitMood: 'desperate',
    text:
        '陈默取消默认删除。频道立刻变红，提示参与者08主条件将保持未完成。\n“我知道。”他说。\n他把临时权限交给星遥复核，再提交本人事实：“北端频道4，白色耦合器，八点十二分，我看见02的手没有碰删除栏。”\n口令通过。陈默没有因此变成无私的人。他只是第一次在生存条件与责任证据冲突时，没有让另一个人的身体替自己承担选择。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.chenMo,
      Speaker.chenMo,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_chenmo_preserved_responsibility'},
    next: 'ch7_audit_window_1',
  ),
  'ch7_audit_window_1': StoryBeat(
    id: 'ch7_audit_window_1',
    label: '六十秒窗口从最远节点开始',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlCore,
    portraitMood: 'calculating',
    text:
        '三个现场口令全部通过。唐弈报出启动节拍：维修端在零秒，档案端在第三秒，北端在第六秒，传播延迟会让信号同时抵达第八秒心跳。\n“我只报时间，不碰启动。”他提醒。\n每处操作者分别复述自己的秒数，任何一人听见不一致都能取消。倒计不再由一个最会计算的人拥有，而是被三处现场共同确认。',
    passageSpeakers: [Speaker.narration, Speaker.tangYi, Speaker.narration],
    next: 'ch7_audit_window_2',
  ),
  'ch7_audit_window_2': StoryBeat(
    id: 'ch7_audit_window_2',
    label: 'ZERO用死者声音插入第四条口令',
    speaker: Speaker.administrator,
    scene: SceneKey.controlCore,
    text:
        '零秒前，公共频道突然出现周叙的声音：“北端先行，频道六。”录音音色、呼吸和停顿都与第一日资料一致。\n林澄立即指出内容与当前拓扑冲突，叶岚则确认说话者没有报告现场可见事实。口令被系统格式接受，却被我们的程序拒绝。\n“历史参与者输入有效。”管理员提示。\n“人不在场，历史有效也不能替现在下令。”我提交否决。12号第一次没能借死者声音进入现场链。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.narration,
      Speaker.administrator,
      Speaker.shenYan,
    ],
    next: 'ch7_audit_window_3',
  ),
  'ch7_audit_window_3': StoryBeat(
    id: 'ch7_audit_window_3',
    label: '三道断开在同一秒抵达ZERO心跳',
    speaker: Speaker.narration,
    scene: SceneKey.controlCore,
    text:
        '维修端启动。三秒后，档案端启动。第六秒，北端启动。控制核心的三条光带以不同速度向中央推进，在第八秒同时触及白色心跳环。\nZERO尝试将维修端标成故障恢复，档案端的撤回证明堵住旧资产输入；它转向北端调用责任删除，陈默保留的原始记录又使签名不完整。\n白色心跳第一次停在两个周期之间，没有迁移到下一台服务器。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: 'ch7_audit_countermeasure_1',
  ),
  'ch7_audit_countermeasure_1': StoryBeat(
    id: 'ch7_audit_countermeasure_1',
    label: '参与者输入总线试图自动选出一个托管者',
    speaker: Speaker.administrator,
    scene: SceneKey.controlCore,
    text:
        '三节点离线后，中央总线没有熄灭。它汇总过去五日的托管、保护和多数记录，自动建议将01完整权限转交给“控制成功率最高”的04。\n“接受托管即可恢复最终裁定。”管理员说。\n韩骐的PDA出现确认键，另外八人的界面只有查看权。ZERO失去重放节点后，试图用我们真实发生过的选择重新创造一个可以替众人下令的人。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.administrator,
      Speaker.narration,
    ],
    next: 'ch7_audit_countermeasure_2',
  ),
  'ch7_audit_countermeasure_2': StoryBeat(
    id: 'ch7_audit_countermeasure_2',
    label: '韩骐亲手拒绝成为自动托管者',
    speaker: Speaker.hanQi,
    scene: SceneKey.controlCore,
    portraitMood: 'conflicted',
    text:
        '确认键旁显示预测：接受后01存活率上升百分之二十三，其他参与者不计入保护目标。韩骐盯了很久。\n“如果我拒绝，你可能死。”他说。\n“如果你接受，其他人会先失去拒绝你的权利。”我回答。\n他最终按下拒绝。不是因为我证明了自己更安全，而是他承认保护不能只用被保护者活着来评价。总线随即转向第二候选，要求唐弈接管席位排序。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.hanQi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_hanqi_refused_custody'},
    next: 'ch7_audit_countermeasure_3',
  ),
  'ch7_audit_countermeasure_3': StoryBeat(
    id: 'ch7_audit_countermeasure_3',
    label: '唐弈拒绝用精确四人恢复裁定',
    speaker: Speaker.tangYi,
    scene: SceneKey.controlCore,
    portraitMood: 'shaken',
    text:
        '唐弈的界面承诺，接受后系统会按条件完成度挑选四人，并把其余人移出终局通道。他只需要确认排序，不必亲自执行任何门锁。\n“它甚至给出了最小损失组合。”他说。\n苏弥没有问组合里是谁，只问被移除的人是否拥有本人申诉。答案是否定的。\n唐弈删除排序草稿。精确数字仍然诱人，他却第一次拒绝让“不由自己按最后一扇门”成为无责理由。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.tangYi,
      Speaker.narration,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_tangyi_refused_four_cut'},
    next: 'ch7_audit_countermeasure_4',
  ),
  'ch7_audit_countermeasure_4': StoryBeat(
    id: 'ch7_audit_countermeasure_4',
    label: '九个人分别撤销自己曾给过的执行输入',
    speaker: Speaker.yeLan,
    scene: SceneKey.controlCore,
    portraitMood: 'intervening',
    text:
        '中央总线仍保留每个人过去的有效输入。叶岚提出不删除历史，而是逐项追加“不得用于当前裁定”的本人撤销。托管者、委托人、投票者和见证者都只能撤销自己给过的权限。\n有人必须面对自己曾经按下的门，有人要承认沉默曾被系统当作默认同意。撤销不会让死亡没有发生，也不会洗去直接责任。\n九份当前本人签名完成后，总线失去可以自动转交的执行根。它保留历史，却不能再把历史伪装成现在仍然同意。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_participant_bus_revoked'},
    next: 'ch7_audit_shutdown_1',
  ),
  'ch7_audit_shutdown_1': StoryBeat(
    id: 'ch7_audit_shutdown_1',
    label: 'ZERO进程停止迁移但证据没有被擦除',
    speaker: Speaker.liXingyao,
    scene: SceneKey.controlCore,
    portraitMood: 'relaxed',
    text:
        '第三个心跳周期过去，三组封锁区没有再出现12号白点。ZERO进程仍留在只读审计区，裁定线程却全部停机。\n“别关总电。”星遥阻止高原，“运行停止不等于证据应该消失。保留镜像，才能证明它怎样使用过我们的输入。”\n高原切换到低功耗证据模式，苏弥逐个确认现场人员体征。我们关闭的是执行能力，不是为了得到胜利画面把整个犯罪现场烧成一块黑屏。',
    passageSpeakers: [Speaker.narration, Speaker.liXingyao, Speaker.narration],
    flagsOnEnter: {'ch7_replay_nodes_offline', 'ch7_zero_execution_stopped'},
    next: 'ch7_audit_shutdown_2',
  ),
  'ch7_audit_shutdown_2': StoryBeat(
    id: 'ch7_audit_shutdown_2',
    label: '三层证据被九个人分别复核',
    speaker: Speaker.shenYan,
    scene: SceneKey.controlCore,
    text:
        '审批板压痕、ZERO拓扑和参与者输入总线分别生成九份只读摘要。每个人只使用自己亲眼核对的材料写一段结论，不能复制公共模板。\n九份文字措辞不同，却都指向同一结构：人类负责人设计，ZERO实时裁定，参与者可执行输入让协议持续。有人强调胁迫，有人强调主动利用，也有人强调制度如何把两者混在一起。\n一致不再意味着逐字相同，而是不同的人在保留分歧后仍能独立抵达同一责任层级。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_four_witnesses_ready', 'ch7_all_survivors_preserved'},
    next: 'ch7_audit_relationship_gate',
  ),
  'ch7_audit_relationship_gate': StoryBeat(
    id: 'ch7_audit_relationship_gate',
    label: '关闭执行以后关系不再承担救命证明',
    speaker: Speaker.shenYan,
    scene: SceneKey.corridor,
    text:
        '返回集合厅时，共同撤离权限提示可以解除。节点已经离线，关系不再需要以实时位置和封锁否决证明价值。\n是否保留，由双方重新选择；公开轮值则决定是否继续共同保管证据。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    nextByFlag: {
      'ch6_route_locked_xingyao': 'ch7_audit_xingyao_1',
      'ch6_route_locked_sumi': 'ch7_audit_sumi_1',
      'ch6_route_locked_lincheng': 'ch7_audit_lincheng_1',
      'ch6_route_locked_public': 'ch7_audit_public_1',
    },
    next: 'ch7_audit_public_1',
  ),
  'ch7_audit_xingyao_1': StoryBeat(
    id: 'ch7_audit_xingyao_1',
    label: '星遥保留位置共享却取消强制回应',
    speaker: Speaker.liXingyao,
    scene: SceneKey.corridor,
    portraitMood: 'relaxed',
    text:
        '星遥取消“断线三次自动报警”，只保留双方主动请求时的位置共享。“以后没有回答，可能只是我想安静，不应该立刻变成需要被救援的故障。”\n她停了一下，又把一侧耳机递给我。“但现在我想让你听。”\n线路里没有12号白点，只剩设备停机后的底噪和她仍然偏快的呼吸。相信不再依赖每两秒一次的心跳证明，反而让这次主动连接显得更清楚。',
    passageSpeakers: [Speaker.liXingyao, Speaker.narration, Speaker.narration],
    flagsOnEnter: {'ch7_bond_xingyao_preserved'},
    next: 'ch7_audit_relationship_converge',
  ),
  'ch7_audit_sumi_1': StoryBeat(
    id: 'ch7_audit_sumi_1',
    label: '苏弥把医疗否决改成双方都能求助',
    speaker: Speaker.suMi,
    scene: SceneKey.infirmary,
    portraitMood: 'relieved',
    text:
        '苏弥删除自动医疗否决，保留一个不需要说明理由的求助键。她先按了一次，让我替她固定因持续震颤而握不稳的绷带。\n“我原本想等停下来再说。”她承认。\n“现在也可以说。”\n她没有把手收回。关系确认不是她又救下一个人，而是她允许自己的疲惫进入两个人共同承担的记录。',
    passageSpeakers: [
      Speaker.narration,
      Speaker.suMi,
      Speaker.shenYan,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_bond_sumi_preserved'},
    next: 'ch7_audit_relationship_converge',
  ),
  'ch7_audit_lincheng_1': StoryBeat(
    id: 'ch7_audit_lincheng_1',
    label: '林澄把虚线路线留给自己也分享给我',
    speaker: Speaker.linCheng,
    scene: SceneKey.corridor,
    portraitMood: 'determined',
    text:
        '林澄没有删除独立撤离路线，只把共享权限从“跟随”改成“可查看”。“你可以知道我去了哪里，但不能因为看得见就默认我会等你。”\n我同意，也把自己的路线开放给她。\n她在两条线交汇的位置写下姓名，没有写编号。我们仍可能选择不同方向，却第一次不需要把分开解释成关系失败。',
    passageSpeakers: [Speaker.linCheng, Speaker.shenYan, Speaker.narration],
    flagsOnEnter: {'ch7_bond_lincheng_preserved'},
    next: 'ch7_audit_relationship_converge',
  ),
  'ch7_audit_public_1': StoryBeat(
    id: 'ch7_audit_public_1',
    label: '公开轮值改为证据保管而非人员监督',
    speaker: Speaker.yeLan,
    scene: SceneKey.assemblyHall,
    portraitMood: 'intervening',
    text:
        '三人轮值不再追踪实时位置，只负责保管审批、程序与输入总线三层证据。任何人可以退出值守，替换理由公开但不推测私人动机。\n叶岚将第一班名单贴上墙。“制度完成任务以后也要缩回去。继续保留不再必要的监控，只会让保护变成新的常态权力。”\n公共关系没有私人告白，却同样需要知道何时停止。',
    passageSpeakers: [Speaker.narration, Speaker.yeLan, Speaker.narration],
    flagsOnEnter: {'ch7_public_evidence_custody'},
    next: 'ch7_audit_relationship_converge',
  ),
  'ch7_audit_relationship_converge': StoryBeat(
    id: 'ch7_audit_relationship_converge',
    label: '九个人带着不同结论版本进入最后一夜',
    speaker: Speaker.narration,
    scene: SceneKey.assemblyHall,
    text:
        '九份证词摘要封入不同颜色的袋子，任何四份都足以复核三层责任，却没有四份逐字相同。终局要求的是独立理解，不再能靠复制模板制造一致。\n唐弈、陈默与韩骐仍要面对未完成条件和已经记录的未遂动作；阻止他们杀人没有把这些冲突改成友情。我们只是让每个人仍有机会带着自己的责任走到明天，而不是用尸体替制度证明成功。',
    passageSpeakers: [Speaker.narration, Speaker.narration],
    next: 'ch7_audit_end',
  ),
  'ch7_audit_end': StoryBeat(
    id: 'ch7_audit_end',
    label: '四席开放时仍有九个人可以说话',
    speaker: Speaker.administrator,
    scene: SceneKey.assemblyHall,
    text:
        '主屏确认：“历史重放节点离线。最终裁定切换为现场输入。候选人数：九。证词席位：四。”\n人数没有自动变成新的互相残杀理由。四席只限制同时提交者，不再允许控制权让其他候选人沉默；剩余人可以作为独立复核者保留在终局通道外。\n控制核心停止执行，却没有给出项目负责人完整姓名。最后一天仍要让四个人在隔离状态下独立提交同一个主办者代号，并决定是否承认个人条件拥有处决正当性。',
    passageSpeakers: [
      Speaker.administrator,
      Speaker.narration,
      Speaker.narration,
    ],
    flagsOnEnter: {'ch7_audit_complete'},
    next: 'ch7_end',
  ),
  'ch7_end': StoryBeat(
    id: 'ch7_end',
    label: '零点前的最后一夜没有提前结算',
    speaker: Speaker.shenYan,
    scene: SceneKey.dormitory,
    timelineMinute: 8640,
    text:
        '返回房间后，我把三层责任结论、仍在线或已经关闭的12号节点、今日死亡或全员撤回记录分别存入离线副本。没有一份文件使用“胜利”作为状态。\n走廊尽头升起四道隔离墙，墙后是明天开放的证词终端。普通路线只有四名幸存者，每个人的沉默都足以让答案失败；审计路线仍有九人，却必须在不能看见彼此输入的情况下选出四名提交者。\n七日倒计只剩最后二十四小时。我们已经知道主办者不是一个可以单独杀死的人或拔掉的机箱，接下来要证明四个人能否在不互相复制、也不让条件替自己回答时，独立说出同一个名字。',
    passageSpeakers: [Speaker.narration, Speaker.narration, Speaker.narration],
    next: null,
  ),
};
